packages/et/build.sh
packages/et/fix-includes.patch

Also migrate to Git URL due to submodules missing from release tarball.

et: Bump to 6.2.2

---

packages/apt/build.sh
packages/root-repo/build.sh
packages/x11-repo/build.sh

Referencing to
https://github.com/termux/termux-tools/commit/311ac5c9824792945bb9cefccd185d5e3a38b86d.
This should hopefully help reduce the amount of bandwidth consumed by
out Hetzner instance.
Some rough statistics (proper ones would require some scripts to be run
on the server, I just got to lazy to write something that could work):
Cloudflare cached content accounts for only about 14.9% of the total
amount of requests. This change should increase this number in the long
run

chore(main/{apt,{root,x11}-repo}): use cloudflare proxy by default

---

x11-packages/pcsx-rearmed/build.sh

Use of `PREFIX` is not standard. `TERMUX_PREFIX` should be used instead.
%ci:no-build

pcsx-rearmed: Refactor `build.sh`

---

packages/imath/build.sh

Imath 3.1.6 is known to work with OpenEXR 3.1.5.

imath: Bump to 3.1.6

---

packages/mpd/build.sh
packages/mpd/doc-mpdconf.example.patch

Since mpd depends on pulseaudio, add the possibility to use pulseaudio
output. Disabled by default.

mpd: add pulseaudio output to the default config

---

packages/ani-cli/build.sh

Due to changed dependencies, a simple bump as in #14773 is insufficient.
Greetings from upstream,
port19

ani-cli: fix 4.0 dependencies

---

packages/opengl/build.sh

to be specified as a dependency of packages that require `lib/libGL.so` and friends.
Currently `lib/libGL.so` is provided by `libglvnd` package. Depending on `libglvnd`, however, would not work, because `libglvnd` does not depend on any provider of OpenGL implementation (`mesa` is a recommendation.) At least one provider should be hard-depended on, not only recommended.
See also #14785.

new package: opengl

---

scripts/build/termux_step_massage.sh
scripts/build/termux_step_setup_variables.sh

to disable stripping binaries.
To be used by `guile` package. (#14830)

scripts: Add new variable `TERMUX_PKG_NO_STRIP`

---

packages/frp/build.sh
packages/frp/upstream-upgrade-quic-go-to-0.32.0.patch

fix(main/frp): upgrade quic-go to 0.32.0

---

packages/python-numpy/build.sh

The issue described in commit b3b1092640bcb575b14a5f2207026378e3c0fa38 is resolved upstream in version 1.24.1.
See also: https://github.com/numpy/numpy/issues/22850
%ci:no-build

python-numpy: Remove dep on libandroid-complex-math

---

packages/syncthing/build.sh
packages/syncthing/upstream-upgrade-quic-go-to-0.32.0.patch

fix(main/syncthing): upgrade quic-go to 0.32.0

---

packages/python/build.sh
packages/python/python-ensurepip-wheels.subpackage.sh
packages/python/python-tkinter.subpackage.sh

* Fix license (PythonPL was for CNRI Python)
* Adjust recommended packages (clang etc. are recommended by python-pip)
* Fix included files for python-tkinter
* Separate ensurepip wheels as subpackage (not needed by default now)
* Fix underlinking of `_crypt` extension (not just a refactoring though)
%ci:no-build

python: Refactor `build.sh` before bumping to 3.11.2

---

packages/python/build.sh

When updating python, the check does not find the python-pip package in pacman and ended up removing the pip command from the python-pip package.

fix(main/python): pip checkout fix

---

.github/workflows/command_not_found.yml
.github/workflows/package_updates.yml

instead of `GH_API_KEY`.
I'm not sure if this works.
Ref: #14993

workflows: Use `TERMUXBOT2_TOKEN`

---

scripts/build/termux_step_extract_into_massagedir.sh
scripts/build/termux_step_setup_toolchain.sh
scripts/build/termux_step_start_build.sh
scripts/build/toolchain/termux_setup_toolchain_23c.sh
scripts/build/toolchain/termux_setup_toolchain_25c.sh
scripts/setup-termux.sh

Currently we create only libutil.so in our setup_toolchain scripts. Several packages have pthread patches that should no longer be needed if we create libpthread.so.
This makes environment on device slightly more similar to docker builds also, on device we have these libraries in ndk-sysroot.
These changes allows us to simplify openjdk build script a bit. Will push that with a %ci:no-build tag after this is merged.

scripts: create lib{util,rt,pthread}.so in termux_step_start_build

---

x11-packages/deadbeef/build.sh
x11-packages/handbrake/build.sh
x11-packages/kitty/build.sh
x11-packages/raylib/build.sh
x11-packages/sfml/build.sh

after commit af18f1dac0b561d5a54cbdad4aa6c90491ef71f5.
%ci:no-build

tree-wide: Cleanup dummy `lib{rt,pthread}` hack

---

packages/pulseaudio/build.sh

as a symlink to `lib/libpulse.so`. Firefox expects it.
Fixes https://github.com/termux/termux-packages/issues/12964.

pulseaudio: Provide `lib/libpulse.so.0`

---

packages/python-pip/build.sh
packages/python-pip/install_py_preventing_pip_from_installing.patch

In short, the `pip` install blocker only works for a single `pip` value. That is, if you specify `pip` twice, then the first `pip` will be skipped and the second `pip` will be installed.

fix(main/python-pip): fix blocking on pip installation

---

packages/ghostscript/build.sh

when `libmd` package is installed.

ghostscript: Fix build

---

x11-packages/qt5-qtwebengine/build.sh

qt5-qtwebengine: mark as `not safe for on-device build`

---

packages/libllvm/build.sh
packages/libllvm/llvmgold.subpackage.sh

libllvm: Build gold plugin

---

packages/cargo-c/build.sh

Build-dependency of `librav1e` (and future version of `libimagequant`) on device.

new package: cargo-c

---

packages/ghc-libs/build.sh
packages/ghc-libs/libiserv-enable-network.patch

It will be used to build `iserv-proxy` which will be used to cross compile template-haskell.
For reference see: https://medium.com/@zw3rk/cross-compiling-template-haskell-7e38c00c2914

ghc-libs: Enable `network` support in `libiserv`

---

x11-packages/xf86-input-void/build.sh
x11-packages/xf86-video-dummy/build.sh
x11-packages/xorg-server/build.sh
x11-packages/xorg-server/xorg.conf

xorg-server with default modules (dummy and void) is needed to make termux-x11 work with existing server. Xvfb is slow, Xwayland needs compositor and does not support multiple resolutions. Xorg is enough good for this.

new packages: xf86-video-dummy and xf86-input-void. Added default config for Xorg.

---

packages/php/build.sh
packages/tidy/build.sh

tidy: Bump to 5.9.14-next

---

x11-packages/mumble-server/build.sh
x11-packages/mumble-server/scripts-mumble-server-user-wrapper.patch

an RC but significant as the first version that supports OpenSSL 3.0.

mumble-server: Bump to 1.5.517

---

packages/libduckdb/CMakeLists.txt.patch
packages/libduckdb/build.sh

Not sure if there's a way to set CMake flags instead? That would be much nicer than patching the CMakeLists.txt

libduckdb: enable various extensions

---

x11-packages/virglrenderer-android/0001-meson-add-new-option-egl_without_gbm-to-enable-build.patch.beforehostbuild
x11-packages/virglrenderer-android/0002-android-build-and-use-egl-platform-on-Android-withou.patch.beforehostbuild
x11-packages/virglrenderer-android/0003-test-angle.patch.beforehostbuild
x11-packages/virglrenderer-android/0004-Assume-no-shm-on-Host.patch.beforehostbuild
x11-packages/virglrenderer-android/0005-Enable-debug-for-EGL.patch.beforehostbuild
x11-packages/virglrenderer-android/0006-Disable-feature-feat_dual_src_blend.patch.beforehostbuild
x11-packages/virglrenderer-android/0007-Ensure-EGL-and-GLES.patch.beforehostbuild
x11-packages/virglrenderer-android/0008-Change-vtest-socket-path.patch.beforehostbuild
x11-packages/virglrenderer-android/build.sh

This package contains a virgl test server using the OpenGLES driver of Android native. This package is tested on Adreno 630 (Xiaomi MIX2s) and Adreno 650 (Xiaomi MIX4) and works fine. It doesn't work on Bluestacks because the GLES driver Bluestacks provided doesn't have some feature.
To test this package, start the server in one session and run graphic tests in another session.
For example
Session 1:
```
virgl_test_server_android
```
Session 2:
```
vncserver :1
DISPLAY=:1 GALLIUM_DRIVER=virpipe glmark2
```
Closes #14517

new package: virglrenderer-android

---

packages/zellij/build.sh
packages/zellij/prefix.patch

Zellij just released a new verions [v0.35.1](https://github.com/zellij-org/zellij/releases/tag/v0.35.1), this PR bumps the registery package version.

zellij: Bump to 0.35.1

---

scripts/build/termux_step_setup_variables.sh

`TERMUX_PYTHON_CROSSENV_PREFIX` should be architecture-specific. If we build `x86_64` pip package, then build `aarch64`, `python-crossenv` will still be `x86_64` and then error will occur.

fix(scripts): `TERMUX_PYTHON_CROSSENV_PREFIX` should be architecture-specific

---

packages/ndk-multilib/build.sh
packages/ndk-multilib/ndk-multilib-native-stubs.subpackage.sh
packages/ndk-multilib/postinst-alien.in
packages/ndk-multilib/postinst-header.in
packages/ndk-multilib/postinst-native.in

which are now installed with subpackage named ndk-multilib-native-stubs.

ndk-multilib: Exclude native stubs for shared libs

---

x11-packages/qemu-system-x86-64/build.sh
x11-packages/qemu-system-x86-64/qemu-system-aarch64.subpackage.sh
x11-packages/qemu-system-x86-64/qemu-system-arm.subpackage.sh
x11-packages/qemu-system-x86-64/qemu-system-i386.subpackage.sh
x11-packages/qemu-system-x86-64/qemu-system-m68k.subpackage.sh
x11-packages/qemu-system-x86-64/qemu-system-ppc.subpackage.sh
x11-packages/qemu-system-x86-64/qemu-system-ppc64.subpackage.sh
x11-packages/qemu-system-x86-64/qemu-system-riscv32.subpackage.sh
x11-packages/qemu-system-x86-64/qemu-system-riscv64.subpackage.sh

libslirp dep was missing from qemu-system-* subpackages.
There is a plan to further modify this package soon, so:
%ci:no-build

qemu-system-x86-64: Fix dependency

---

packages/qemu-system-x86-64-headless/build.sh
packages/qemu-system-x86-64-headless/qemu-common.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-system-aarch64-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-system-arm-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-system-i386-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-system-m68k-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-system-ppc-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-system-ppc64-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-system-riscv32-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-system-riscv64-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-aarch64.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-arm.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-i386.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-m68k.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-ppc.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-ppc64.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-riscv32.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-riscv64.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-x86-64.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-utils.subpackage.sh

* libslirp dep was missing from qemu-system-*-headless subpackages. Use TERMUX_SUBPKG_DEPEND_ON_PARENT=deps to avoid this type of bug.
* qemu-user-* subpackages do not depend on libc++.
(And more.)

qemu-system-x86-64-headless: Fix dependency

---

packages/mutt/build.sh

--enable-debug makes it easier to debug issues, and ac_cv_func_fget{c,s}_unlocked=no is necessary for compilation on device to work

mutt: configure with --enable-debug and ac_cv_func_fget{c,s}_unlocked=no 

---

packages/navidrome/build.sh

```bash
~ $ navidrome 
_   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
Version: 0.49.3-SNAPSHOT (8b93962)
INFO[0000] goose: no migrations to run. current version: 20230209181414 
INFO[0000] Starting signaler                            
INFO[0000] Setting Session Timeout                       value=24h
ERRO[0000] Agent not available. Check configuration      name=spotify
INFO[0000] Creating Image cache                          maxSize="100 MB" path=cache/images
INFO[0000] Finished initializing cache                   cache=Image elapsedTime=6.4ms maxSize=100MB
INFO[0000] …
```

add(main): new package navidrome

---

packages/coreutils/build.sh
packages/coreutils/src-hostid.c.patch

coreutils: Add workaround for undeclared `gethostid`

---

packages/libcurl/build.sh

for backward compatibility.
Reference: #15852, #15889.

curl: Set `ac_cv_func_getpwuid=yes`

---

packages/bash/build.sh
packages/bash/examples-loadables-getconf.c.patch

`confstr` is not available to Android.

bash: Fix `getconf` loadable

---

packages/netpbm/build.sh

stopgap until i figure out what should replace netpbm-security-code.patch

netpbm: disable clang 16

---

packages/libnl/build.sh
packages/libnl/getsubopt.c
packages/libnl/getsubopt.h
packages/libnl/getsubopt.patch

Reference #15852.
Actually `libnl-cli` was broken for Android API `< 26` due to this.

libnl: Fix missing `getsubopt` definition

---

packages/libbsd/__progname.patch

libbsd: Fix `configure` for detecting `__progname`

---

packages/srelay/configure.in.patch

srelay: Fix implicit int in `configure`

---

x11-packages/mtpaint/configure.patch

mtpaint: Fix `configure` for strict C99

---

packages/mariadb/configure.cmake.patch

mariadb: Fix detection of `select()`

---

x11-packages/deadbeef/build.sh

Fix build for 32-bit arches:
```
/home/builder/.termux-build/deadbeef/src/external/mp4p/src/mp4pfile.c:49:16:
error: incompatible function pointer types assigning to
'off_t (*)(struct mp4p_file_callbacks_s *)' (aka 'long (*)(struct mp4p_file_callbacks_s *)')
from
'int64_t (mp4p_file_callbacks_t *)' (aka 'long long (struct mp4p_file_callbacks_s *)')
[-Werror,-Wincompatible-function-pointer-types]
file->tell = _file_tell;
^ ~~~~~~~~~~
```

deadbeef: Set `_FILE_OFFSET_BITS=64`

---

packages/mailsync/acinclude-ac_with_md5.m4.patch

mailsync: Fix implicit int in `configure`

---

packages/python-pyarrow/build.sh

* python-pyarrow: Add workaround for `pyarrow.__version__`
Closes #16047.
* python-pyarrow: Set `PYARROW_WITH_PARQUET`
Closes #16049.

python-pyarrow:

---

x11-packages/webkit2gtk-4.1/pas_thread_local_cache.c.patch

that is not available until API 26.

webkit2gtk-4.1: Do not use `pthread_getname_np()`

---

x11-packages/qt5-qtwebengine/build.sh

Add missing dependencies libdrm for qtwebengine. But IMO this will not affect many users because libdrm will be installed if they use mesa as opengl provider. So I'd like to skip the ci.
Closes #15955

qt5-qtwebengine: fix build dependencies

---

packages/libt3key/build.sh
packages/libt3key/config.pkg.patch
packages/libt3window/build.sh
packages/libt3window/config.pkg.patch

libt3{key,window}: Fix `configure` for strict C99

---

packages/libtranscript/build.sh
packages/libtranscript/config.pkg.patch

libtranscript: Fix `configure` for strict C99

---

x11-packages/liblxqt/add_missing_wordexp.patch
x11-packages/liblxqt/build.sh
x11-packages/lxqt-runner/add_missing_wordexp.patch
x11-packages/lxqt-runner/build.sh

liblxqt, lxqt-runner: Fix missing `pipe2` declaration

---

packages/postgis/build.sh
packages/postgis/liblwgeom-ptarray.c.patch

postgis: Fix missing `bzero` declaration

---

packages/libsasl/build.sh
packages/libsasl/cyrus-sasl-2.1.28-fix-time.h-check-0001.patch
packages/libsasl/cyrus-sasl-2.1.28-fix-time.h-check-0002.patch

libsasl: Fix implicit declaration of function

---

packages/apache2/build.sh
packages/apr/build.sh

apache2: Fix missing `crypt` declaration

---

packages/lrzsz/build.sh
packages/lrzsz/lib-long-options.c.patch

lrzsz: Fix missing `exit` declaration

---

packages/liblog4c/build.sh
packages/liblog4c/src-sd-malloc.h.patch

declared in system `<malloc.h>`.

liblog4c: Fix implicit declaration of function

---

packages/anacron/build.sh
packages/anacron/log.c.patch
packages/anacron/main.c.patch

anacron: Fix missing `exit` declaration

---

packages/mruby/build.sh
packages/mruby/mrbgems-mruby-cmath-src-cmath.c.patch

mruby: Fix missing `clog` declaration

---

packages/netcat-openbsd/build.sh
packages/netcat-openbsd/debian-patches-port-to-linux-with-libbsd.patch

netcat-openbsd: Fix missing `explicit_bzero` declaration

---

packages/renameutils/add-missing-functions.patch
packages/renameutils/build.sh

renameutils: Add missing `getsubopt` declaration

---

packages/minimodem/build.sh
packages/minimodem/src-fsk.c.patch

minimodem: Fix missing `bzero` declaration

---

packages/streamripper/build.sh
packages/streamripper/lib-argv.c.patch

streamripper: Fix missing `strcpy` declaration

---

packages/exercism/build.sh

After installation I found out that `exercism` binary is not executable, so here is the fix.

exercism: make the binary executable

---

packages/whois/build.sh

whois: Fix missing `crypt` declaration

---

root-packages/wireless-tools/iwlib.c.patch

wireless-tools: Fix missing `bzero` declaration

---

packages/python-sabyenc3/build.sh
packages/sabnzbd/build.sh
packages/sabnzbd/prog_dir.patch
packages/sabnzbd/webbrowser.patch

SABnzbd is an alternative to NZBGet, which is also packaged in Termux but is now abandoned by the upstream developer.
`python-sabyenc3` is a dependency for SABnzbd, it contains native (C) code and doesn't compile without patching.
In addition to the sabyenc3 dependency, it includes various enhancements like service definition for `termux-services`, patch to support `termux-open-url`, placing of `bash-completion` file etc. Before finilizing this package, I inspected and sourced ideas from packaging of SABnzbd on Arch Linux, RHEL 8 and Ubuntu.

addpkg(main/sabnzbd): v3.7.2

---

packages/tracepath/build.sh
packages/traceroute/build.sh

which is now provided by the package of the same name.
* traceroute: Declare conflict with older tracepath
that provided `traceroute` command as an alias of `tracepath`.
Fixes #16562.

tracepath: Remove `traceroute`

---

packages/libsass/build.sh
packages/python-libsass/build.sh
packages/python-libsass/setup.py.patch

Dependency of repomaker requested in #15940.
The libsass Python module fails to install through pip without patching: https://bugs.gentoo.org/881339.

new package: libsass, python-libsass

---

packages/libmad/build.sh
packages/libmp3lame/build.sh

Do not assume TERMUX_PKG_CONFIG_LIBDIR to be a single directory.
Fixes #16610.

libmp3lame, libmad: Fix installation of pc files

---

packages/nodejs-lts/build.sh
packages/nodejs-lts/deps-uv-uv.gyp.patch
packages/nodejs-lts/node.gyp.patch
packages/nodejs-lts/test-parallel-test-child-process-uid-gid.js.patch

Also update my email address to termux.dev one
Logs of test run, as run in termux-docker. Note that for aarch64 and arm, the tests were run using QEMU and has a bunch of false-positives. The PR will be merged after running those tests on an actual arm device.
[test-result-aarch64.txt](https://github.com/termux/termux-packages/files/11458283/test-result-aarch64.txt)
[test-result-i686.txt](https://github.com/termux/termux-packages/files/11458285/test-result-i686.txt)
[test-result-x86_64.txt](https://github.com/termux/termux-packages/files/11458288/test-result-x86_64.txt)
[test-result-arm.txt](https://github.com/termux/termux-packages/files/11458289/test-result-arm.txt)

bump(main/nodejs-lts): v18.16.0

---

repo.json
scripts/properties.sh

Should have been done during the initial migration to monorepo itself, but anyways.
Requesting a review from @licy183 , one of the maintainers of TUR

chore: do not hardcode repository information in `scripts/proporties.sh`

---

packages/mdbook-cat-prep/build.sh

mdbook-cat-prep: Use Rust 1.68.2 to build

---

packages/mdbook-presentation-preprocessor/build.sh

mdbook-presentation-preprocessor: Use Rust 1.68.2 to build

---

packages/ocl-icd/build.sh

fix(main/ocl-icd): use internal headers

---

packages/starship/0001-Cargo.toml.patch
packages/starship/build.sh

0001-Cargo.toml.patch: updated patch
build.sh: `$CARGO_HOME/registry/src/github.com-*/cmake-*` -> `$CARGO_HOME/registry/src/*/cmake-*`
fixes #16853

bump(main/starship): v1.15.0

---

packages/signify/Makefile.patch
packages/signify/build.sh
packages/signify/signify.c.patch

[Homepage](https://github.com/aperezdc/signify)
[Debian package](https://packages.debian.org/sid/utils/signify-openbsd)
I'm not really sure if patches are correct. I would prefer to define `BYTE_ORDER` in included headers and not to disable compiler warning.

addpkg(main/signify): Lightweight cryptographic signing and verifying tool

---

packages/e2fsprogs/build.sh

which is provided by blk-utils, a subpackage of util-linux.
Fixes #16883.

e2fsprogs: Disable fsck

---

packages/bc-gh/build.sh

This commit/PR is a request to consider changing the bc implementation to the one by Gavin Howard. I understand if this PR is ultimately rejected.
That said, the bc/dc by Gavin Howard (me) is IMO a better option than the GNU bc/dc for these reasons:
* It is already used by the upstream Android Open Source Project. [1]
* It is permissively licensed.
* It implements the POSIX bc standard better.
* It can be made to imitate the GNU bc/dc exactly, barring differences between the GNU bc and the POSIX standard. This includes all GNU extensions and command-line options.
* It can *also* be made to imitate the BSD bc/dc exactly, barring differences between the BSD bc and the POSIX standard. This means that my bc can be a bridge for Android users used to the BSD bc/dc.
* It is being actively …

addpkg(main/bc-gh): GNU- and BSD-compatible Unix dc and POSIX bc

---

packages/ffmpeg/build.sh
packages/libandroid/build.sh

ffmpeg: enable jni and mediacodec

---

packages/libwebp/build.sh

libwebp: Revbump to rebuild

---

packages/gst-plugins-base/build.sh

gst-plugins-base: Revbump to rebuild

---

packages/graphicsmagick/build.sh

graphicsmagick: Revbump to rebuild

---

packages/imagemagick/build.sh

imagemagick: Revbump to rebuild

---

packages/gdal/build.sh

gdal: Revbump to rebuild

---

packages/mupdf/build.sh

mupdf: Revbump to rebuild

---

packages/poppler/build.sh

poppler: Revbump to rebuild

---

packages/python-pillow/build.sh

python-pillow: Revbump to rebuild

---

packages/libspice-server/build.sh

libspice-server: Revbump to rebuild

---

packages/ghostscript/build.sh

ghostscript: Revbump to rebuild

---

packages/gst-plugins-good/build.sh

gst-plugins-good: Revbump to rebuild

---

packages/imlib2/build.sh

imlib2: Revbump to rebuild

---

x11-packages/gtk4/build.sh

gtk4: Revbump to rebuild

---

x11-packages/sdl2-image/build.sh

sdl2-image: Revbump to rebuild

---

x11-packages/qt5-qtbase/build.sh

qt5-qtbase: Revbump to rebuild

---

x11-packages/tigervnc/build.sh

tigervnc: Revbump to rebuild

---

packages/links/build.sh

links: Revbump to rebuild

---

x11-packages/mpv-x/build.sh

mpv-x: Revbump to rebuild

---

x11-packages/emacs-x/build.sh

emacs-x: Revbump to rebuild

---

x11-packages/webkit2gtk-4.1/build.sh
x11-packages/webkitgtk-6.0/build.sh

webkit2gtk-4.1, webkitgtk-6.0: Revbump to rebuild

---

x11-packages/fltk/build.sh

fltk: Revbump to rebuild

---

x11-packages/wxwidgets/build.sh

wxwidgets: Revbump to rebuild

---

x11-packages/mogan/build.sh

mogan: Revbump to rebuild

---

packages/python-torchvision/build.sh

python-torchvision: Revbump to rebuild

---

x11-packages/sdl-image/build.sh

sdl-image: Revbump to rebuild

---

packages/chafa/build.sh

chafa: Revbump to rebuild

---

x11-packages/qt5-qtwebengine/build.sh

qt5-qtwebengine: Revbump to rebuild

---

x11-packages/mesa-demos/build.sh

instead of using patchelf, to keep things simple.

mesa-demos: Use LD_LIBRARY_PATH for eglinfo-system

---

packages/dcmtk/build.sh

libjpeg-turbo are not linked against, not even detected by build system.

dcmtk: Adjust dependency

---

packages/librsvg/build.sh

librsvg: Revbump to rebuild

---

packages/postgresql/build.sh

postgresql: Revbump to rebuild

---

packages/gst-plugins-bad/build.sh

gst-plugins-bad: Revbump to rebuild

---

packages/libgnustep-base/build.sh

libgnustep-base: Revbump to rebuild

---

packages/monetdb/build.sh

monetdb: Revbump to rebuild

---

x11-packages/news-flash-gtk/build.sh

news-flash-gtk: Revbump to rebuild

---

packages/mpd/build.sh

due to SONAME change in libexpat.

mpd: Revbump to rebuild

---

packages/apr-util/build.sh

due to SONAME change in libexpat.

apr-util: Revbump to rebuild

---

packages/dbus/build.sh

due to SONAME change in libexpat.

dbus: Revbump to rebuild

---

packages/suite3270/build.sh

due to SONAME change in libexpat.

suite3270: Revbump to rebuild

---

packages/mesa/build.sh

as it is not used anyways.
%ci:no-build

mesa: Remove libexpat from dependency

---

x11-packages/mate-applet-brisk-menu/build.sh

* Add libx11
* Remove libxml2 as unused
%ci:no-build

mate-applet-brisk-menu: Adjust dependency

---

x11-packages/gimp/build.sh

libxml2 and libxslt are not linked against.
%ci:no-build

gimp: Adjust dependency

---

packages/zstd/build-meson-contrib-meson.build.patch
packages/zstd/build.sh

to remove the custom post-make-install step for building pzstd.
CMake could be used instead, which however now has some subtle issue of symbol visibility which makes me prefer Meson. (See also #17335.)

zstd: Use Meson to build

---

scripts/build/termux_create_debian_subpackages.sh
scripts/build/termux_create_pacman_subpackages.sh
scripts/buildorder.py

for subpackage not to be created for specific arches.
Ref #17338

scripts: Introduce `TERMUX_SUBPKG_EXCLUDED_ARCHES`

---

packages/libllvm/lldb.subpackage.sh

libllvm: Exclude lldb from 32-bit arches

---

packages/rpm/build.sh
packages/rpm/errno.patch
packages/rpm/goto_declaration.patch

Having `rpm` in Termux should provide means to quickly inspect RPM files locally, outside RPM based distros. For example `mc` integrates with `rpm` and allows browsing RPM archives.

addpkg(main/rpm): 4.18.1

---

packages/python-torch/build.sh

Bump the package to latest version (v2.0.1) and add support for Vulkan API also.

python-torch: Bump to 2.0.1 and enable Vulkan support

---

packages/vulkan-extension-layer/build.sh
packages/vulkan-tools/build.sh

Follow up of #17297 but for Khronos packages that depends on vulkan-loader-generic (to avoid pollution from the other loader)
Drops TERMUX_PKG_RECOMMENDS and reinstate TERMUX_PKG_DEPENDS on vulkan-loader

*: fix vulkan packages deps 2

---

x11-packages/xorg-server/build.sh
x11-packages/xorg-server/xorg-server-xephyr.subpackage.sh

Resolves #17388 
License file wasn't included as it is already part of `xorg-server` package? Added this as subpackage since it only takes to just enable kdrive and xephyr.

New package: xorg-server-xephyr

---

x11-packages/angle-android/args.gn.in
x11-packages/angle-android/build.sh
x11-packages/virglrenderer-android/build.sh
x11-packages/virglrenderer-android/virgl_test_server_android.in

Running virgl straightly over Android's GL may cause error due to the lack of extensions and differences between Android's GLs. ANGLE can translate OpenGL operations to other OpenGL or vulkan, so it may solve some running issues for virglrenderer-android.
Tested on `Adreno 660` and `Mali G610`.
Related issue: #16763, #17406

new package: angle-android

---

packages/music-file-organizer/build.sh

In commit 3362326d7ed746de45ee12f9dff3d3eb135cec2e, this package was disabled because the tarball didn't have license file in it. This has been rectified upstream, so re-enable it.

music-file-organizer: re-enable now that there's a license file

---

x11-packages/firefox/build.sh

Next major version probably need to rewrite build.sh.
So bump this to address a few CVEs: https://repology.org/project/firefox/cves?version=115.0

bump(x11/firefox): 115.0.3

---

x11-packages/firefox/build.sh
x11-packages/firefox/firefox.patch
x11-packages/firefox/shared_memory_posix.cc.patch

Regenerated the patch since the old patches are manually butchered
Supposedly starting Firefox 116 no longer combines Wayland and X11 together. This package will be X11 only moving forward.
I will take a closer look if Firefox Wayland is possible or not...

bump(x11/firefox): 116.0.2

---

packages/ffmpeg/build.sh
packages/libvo-amrwbenc/build.sh

Close #17586 
ffmpeg will need to upgrade to GPLv3 properly
which previously has been GPLv2 falsely advertised as GPLv3 in the package

ffmpeg enable amr encoding support

---

packages/zlib/build.sh

minor version bump due to finally dropping K&R support!
despite this not breaking ABI (i think), i might do some revbumps anyway? just in case things see the new version number and error out on principle

bump(main/zlib): 1.3

---

packages/zig/build.sh
packages/zig/zig-lib-libc-musl-src-stat-fstatat.c.patch
packages/zig/zig-lib-libc-musl-src-unistd-access.c.patch
packages/zig/zig-lib-std-os-linux.zig.patch
scripts/build/setup/termux_setup_zig.sh

fix(main/zig): disable certain syscalls usage

---

x11-packages/qt5-qtbase/build.sh
x11-packages/qt5-qtbase/qmake.conf
x11-packages/qt5-qtbase/use_posix_ipc.patch

SysV semaphore doesn't seem to work since Android 8.0, use POSIX semaphore instead.
Closes #17780

qt5-qtbase: use posix ipc

---

packages/python-numpy/build.sh
packages/python-numpy/numpy-distutils-core.py.patch

python-numpy: bump to 1.26.0

---

scripts/build/termux_step_get_dependencies.sh
scripts/buildorder.py

This change adds two values ​​to configure how package dependencies are retrieved:
- `TERMUX_PKG_SEPARATE_SUB_DEPENDS` - this value allows to avoid adding dependencies from `*.subpackage.sh`
- `TERMUX_PKG_ONLY_INSTALLING` - if some package requests a package with this value, then this package must be installed and not compiled, otherwise it will be ignored (designed to avoid circular dependencies)
These values ​​will work in a package if this package is requested from another package as a dependency. In other cases they are ignored.

scripts/buildorder.py: improving dependency retrieval

---

x11-packages/firefox/build.sh

chore(x11/firefox): relax to 2 hours limit for CI

---

packages/neovim/build.sh
scripts/updates/api/termux_github_api_get_tag.sh

At time of commit, we have neovim 0.9.0 and haven't automatically picked
up 0.9.2. This turned out to be because neomvim has some floating tags
(`nightly`) and (`stable`) and `stable` was the latest tag offered by
the api.
Since we already have a regex for the tag, we can give it to the fetcher
and use it as a filter. I updated neovim for this usage and confirmed
that we now detect 0.9.2 as an auto-update with
`scripts/bin/update-packages`.

Give the github tag fetcher regex filter powers.

---

packages/openssh/build.sh
packages/openssh/session.c.patch

This makes things work better when ssh:ing in and directly executing some script which can have a shebang (`#!/bin/sh`) that needs `termux-exec`.
It's also necessary for the proposed changed to `termux-exec`, to avoid executing ELF files directly: https://github.com/termux/termux-exec/pull/24

openssh: Keep also the LD_PRELOAD environment variable

---

packages/libcoinor-osi/build.sh
packages/libcoinor-utils/build.sh
packages/libcoinor-utils/no-register.patch

See https://github.com/termux/termux-packages/pull/17863

libcoinor-{osi-utils}: Bump and fix c++17/ndk26 compatibility

---

packages/ttyd/build.sh

ttyd does not use xxd during the build since 2020, so this can be removed: https://github.com/tsl0922/ttyd/commit/0e728e61ce28a36072b164a43badc8830e1f0d2e

ttyd: Avoid downloading and building xxd

---

packages/freeimage/build.sh

This fixes building on Android NDK 26, which otherwise defaults to C++ 17. See https://github.com/termux/termux-packages/pull/17863.

freeimage: Build using std=c++11

---

packages/libsodium/build.sh

Flag `CFLAGS_ARMCRYPTO` is not properly set in `configure` step, so set it manually.

libsodium: fix build on ndk 26

---

scripts/Dockerfile
scripts/setup-ubuntu.sh

This change fixes building the builder docker image also on systems that does not have an existing user with id 1001.

fix(scripts/Dockerfile): Make build more portable

---

packages/amber/ambr.subpackage.sh
packages/amber/ambs.subpackage.sh
packages/amber/build.sh

Currently amber have two subpackages: ambr and ambs
There is a cyclic dependency between these: ambr depends each subpackage, and each subpackage depends on ambr.
This makes scripts/buildorder.py (used by build-all.sh) error out.
And there is also no point in this current package split, as all three packages will always be installed together due to the cyclic dependency. So let's remove the subpackage split.

fix(main/amber): Break dependency cycle by merging subpackages

---

packages/kcptun/build.sh
packages/kcptun/kcptun-client.subpackage.sh
packages/kcptun/kcptun-server.subpackage.sh

Currently kcptun have two subpackages: kcptun-client and kcptun-server
There is a cyclic dependency between these: kcptun depends on each subpackage, and each subpackage depends on kcptun.
This makes scripts/buildorder.py (used by build-all.sh) error out.
And there is also no point in this current package split, as all three packages will always be installed together due to the cyclic dependency. So let's remove the subpackage split.

fix(main/kcptun): Break dependency cycle by merging subpackages

---

packages/libtool/build.sh
packages/libtool/libltdl.subpackage.sh

The libltdl has been split out from libtool to allow packages to depend only on libltdl and not the whole libtool. But for this to work we need
TERMUX_SUBPKG_DEPEND_ON_PARENT=no
Otherwise there is a dependency cycle between libtool and libltdl, so they are always installed together

chore(libltdl): Fix package dependency cycle

---

packages/libdispatch/build.sh
packages/libdispatch/libblocksruntime.subpackage.sh

The libblocksruntime has been split out from libdispatch to allow packages to depend only on libblocksruntime and not the whole libdispatch. But for this to work we need
TERMUX_SUBPKG_DEPEND_ON_PARENT=no
Otherwise there is a dependency cycle between libdispatch and libblocksruntime, so they are always installed together

chore(libblocksruntime): Fix package dependency cycle

---

.github/workflows/docker_image.yml
scripts/Dockerfile
scripts/Dockerfile.cgct

Avoiding the cgct installation shrinks builder image size with 1.5 GB.
For cgct builds, switch from:
ghcr.io/termux/package-builder:latest
to:
ghcr.io/termux/package-builder-cgct:latest

enhance(scripts/Dockerfile): Split out cgct installation

---

.github/workflows/docker_image.yml

https://github.com/termux/termux-packages/pull/18166 dropped the publishing to docker hub by mistake - add that back.

fix(scripts/Dockerfile): Add back publishing to docker hub

---

scripts/run-docker.sh

set `"$@"` to `bash` when no arguments. This reduces duplicating long command line otherwise.

enhance(run-docker.sh): Reduce duplication

---

packages/v2ray/build.sh

This also fixes the build, as 5.7.0 cannot be built with go 1.21.

bump(main/v2ray): 5.8.0

---

x11-packages/jwm/build.sh

New package: `jwm` - Joe's Window Manager.
`jwm` is a [widely packaged](https://repology.org/project/jwm/information), lightweight window manager for X11.
All necessary dependencies are already packaged.
The `.deb`'s range between 84 to 100KB.
PR checklist:
<details><summary>Tested on-device (Android 10, Aarch64)</summary>
<p>
</p>
</details>
I am uncertain if the listed dependencies are all required at runtime.
The [documentation](http://joewing.net/projects/jwm/#:~:text=can%20use) isn't entirely clear on that point.

new package: jwm

---

packages/libmad/build.sh

`libmad` switch the building system to cmake since 0.16.0, the SOVERSION suffix is disabled at the same time. Enable this SOVERSION again to avoid revbump revdeps.
Closes #18227

libmad: enable SOVERSION suffix

---

x11-packages/spek/build.sh

Because it may damage the compilation environment of some packages.

fix(x11/spek): Change libandroid-stub to suggests

---

packages/rizin/build.sh

This pull request adds support for rizin(fork of radare2), a UNIX-like reverse engineering framework and commandline toolset, to the android termux package. Rizin aims to provide a more user-friendly and modular interface, as well as faster development and bug fixes. With this package, termux users can easily install and use rizin on their android devices, and perform various tasks such as binary analysis, debugging, forensics, and exploitation. The package has been tested on several android versions and architectures and works as expected. I hope this contribution will be useful for the termux community and the rizin project.
Co-developed-by: Joshua Kahn @TomJo2000

rizin: add package

---

scripts/build/setup/termux_setup_meson.sh

This version is needed to cross compile some packages with llvm 17.

termux_setup_meson: bump to 1.2.2

---

x11-packages/freerdp/0001-pthread_cancel.patch
x11-packages/freerdp/0002-use-cross-wayland-scanner.patch
x11-packages/freerdp/0003-posix-shm.patch
x11-packages/freerdp/0004-incompatible-function-pointer-types.patch
x11-packages/freerdp/0005-fix-hardcoded-paths.patch
x11-packages/freerdp/0006-read-timezone.patch
x11-packages/freerdp/build.sh

Add `freerdp`, a RDP client. Termux already has `xrdp` as RDP server, but no RDP client currently.
Also enable `freerdp-server` as it is the dependency of `weston` (a wayland compositor, will be added after this PR gets merged).
Tested on MIX2S with tigervnc.

new package: freerdp

---

packages/perl/build.sh

Closes #18340.
Output of `perl -V` now includes -O2:
```
Summary of my perl5 (revision 5 version 38 subversion 0) configuration:
Platform:
osname=android
osvers=current
archname=aarch64-android
uname=''
config_args='--target=aarch64-linux-android --with-cc=aarch64-linux-android-clang --with-ranlib=llvm-ranlib -Dosname=android -Dsysroot=-I/data/data/com.termux/files -Dprefix=/data/data/com.termux/files/usr -Dsh=/data/data/com.termux/files/usr/bin/sh -Dld=aarch64-linux-android-clang -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Dar=llvm-ar -Duseshrplib -Duseithreads -Dusemultiplicity -Doptimize=-O2 --keeplog --mode=target --target=aarch64-linux-android --targetarch=aarch64-unknown-linux-android'
(snip)
```
On my Quest 3, speed of an empty is loop goes down from …

perl: build with -O2

---

packages/libseat/build.sh
x11-packages/weston/0001-neatvnc-0.7.0.patch
x11-packages/weston/0002-drop-deps-libinput.patch
x11-packages/weston/0003-drop-deps-pam.patch
x11-packages/weston/0004-drop-deps-libudev.patch
x11-packages/weston/0005-use-cross-wayland-scanner.patch
x11-packages/weston/0006-progname.patch
x11-packages/weston/0007-fix-include.patch
x11-packages/weston/0008-drop-tests.patch
x11-packages/weston/build.sh

Add `weston`, a basic wayland compositor. It provides native RDP and VNC support, and can provide wayland session inside X11 or wayland.
Tested on MIX2S with both VNC backend and RDP backend.

new package: weston

---

x11-packages/firefox/build.sh
x11-packages/firefox/firefox.patch

fix(x11/firefox): no pack-relative-relocs

---

packages/nerdfix/build.sh
packages/starship/build.sh

Adds the [`nerdfix`](https://github.com/loichyan/nerdfix) utility for replacing obsolete NerdFont glyphs.
It would probably be prudent to package an interactive utility for replacing obsolete NerdFont 2.3.x glyphs, considering termux/termux-styling just updated the fonts to NerdFonts 3.0.2
- termux/termux-styling#212
`nerdfix` is [already packaged](https://repology.org/project/nerdfix/versions) on the AUR, Homebrew and Nixpkgs.
I have chosen to package the latest commit [`76bf959`](https://github.com/loichyan/nerdfix/commits/main) as of today,
as there are several improvements over the 0.3.1 release from May.
I think it would be better to put this package in the main repo rather than the TUR
as it makes sense to set it as a `TERMUX_PKG_SUGGESTS`
for packages often used in conjunction with …

new package: nerdfix

---

.github/workflows/packages.yml
scripts/big-pkgs.list

Due to the fact that we specify “large” packages in `packages.yml`, this is not added in the git repo mirror termux-pacman/termux-packages since `packages.yml` is static (that is, any changes are ignored).

packages.yml: change location indicating "large" packages

---

.github/workflows/packages.yml

The origin one will not work properly, all of the packages will build on the VM rather than our Docker image.
Tested with Github Action.
"libc++": https://github.com/termux/termux-packages/actions/runs/6953220058/job/18918023611
"libllvm": https://github.com/termux/termux-packages/actions/runs/6953227022
"libc++ libllvm": https://github.com/termux/termux-packages/actions/runs/6953255561/job/18918102357

packages.yml: fix regexp on big packages

---

packages/zsh/build.sh
packages/zsh/etc-zshrc

fix(main/zsh): zshrc double sourcing and dangling nomatch

---

packages/nushell/build.sh

The build failed for i686 at <https://github.com/termux/termux-packages/actions/runs/7186452137/job/19571862993>.
See <https://github.com/nushell/nushell/pull/9542>. This had similar issues due to `simd-json`. They just skipped it with the *Rust* flags `--exclude=nu-cmd-dataframe`.

fix(main/nushell): disable `--features=dataframe` for `i686` as it's not building on *GitHub*

---

scripts/bin/update-packages
scripts/updates/termux_pkg_auto_update.sh
scripts/updates/utils/termux_pkg_upgrade_version.sh

Making auto-updater workflow faster.
There are a few bottlenecks in current (master branch) implementation:
1. `buildorder.py` script is being invoked for every single package. It is pretty slow (500+ ms for single package). I do not know why it is so slow. It is not a problem for single package but a problem for 2400 packages. There is no need to invoke `buildorder.py` in the case if the package is up-to-date, but it is not known before invoking `_run_update`.
2. All requests to github/gitlab API are invoked one by one. Each request takes some time but does not require CPU. Better solution is to request everything concurrently. Also doing this before everything else lets us check if packages are up-to date before calling `_update_dependencies`.
About this pull:
In the case if …

scripts(update-packages): speed-up package update checks

---

packages/binutils-libs/build.sh

Saw this in #18758. llvm appears to have upgraded a warning to an error
(https://reviews.llvm.org/D135402), and while they're not wrong to do
so, this package and others
(https://github.com/rust-lang/rust/issues/105967) depended on it. This
is the simple fix, per the llvm reviews link.
Fixes #18750.

fix(main/binutils-libs): Downgrade a new llvm error so we can keep building.

---

packages/vulkan-utility-libraries/build.sh

The custom auto update is broken
https://github.com/termux/termux-packages/actions/runs/7340765805/job/19987331415#step:4:2042
```
INFO: Updating vulkan-utility-libraries [Current version: 1.3.271]
WARNING: Skipping auto-update: Not a release(1.3.274)
termux - took 806ms
```

bump(main/vulkan-utility-libraries): 1.3.274

---

packages/mesa-vulkan-icd-freedreno-dri3/build.sh
packages/mesa-vulkan-icd-freedreno-dri3/cmake-wrapper.in
packages/mesa-vulkan-icd-freedreno-dri3/fix-for-anon-file.patch
packages/mesa-vulkan-icd-freedreno-dri3/fix-for-getprogname.patch
packages/mesa-vulkan-icd-freedreno-dri3/meson.build.patch
packages/mesa-vulkan-icd-freedreno-dri3/src-gallium-drivers-llvmpipe-lp_screen.c.patch
packages/mesa-vulkan-icd-freedreno-dri3/tu_kgsl_export_dmabuf.patch
packages/mesa-vulkan-icd-freedreno-dri3/virgl-socket-path.patch
packages/mesa-vulkan-icd-freedreno-dri3/wsi-no-pthread_cancel.patch
packages/mesa-vulkan-icd-freedreno-dri3/wsi-termux-x11.patch

Only available on turnip with kgsl enabled.
Requires latest Termux:X11 build.
Thanks to twaik for the idea and implemented dri3 support for Termux:X11.

experimental dri3 support for turnip kgsl on Termux:X11

---

x11-packages/weston/0009-fix-hardcoded-paths.patch
x11-packages/weston/build.sh

Fix
```
$ XDG_RUNTIME_DIR=$TMPDIR weston --backend=vnc --xwayland
...
[06:10:33.382] failed to create lock file /tmp/.X0-lock: No such file or directory
```

fix(x11/weston): hardcoded paths

---

packages/android-tools/termux-exec.patch

Intead of checking /proc/self/exe. This allows adb to be used with termux-exec changes in https://github.com/termux/termux-exec/pull/24.

enhance(main/android-tools): use TERMUX_SELF_EXE env var if set

---

x11-packages/gtk3/build.sh
x11-packages/gtk3/gdkdisplay-wayland.c.patch
x11-packages/libxkbcommon/build.sh

This should bring most GTK3 based apps to have Wayland support. Some apps may still need to be rebuild or manually enabled in their build.sh but most don't.

enhance(x11/libxkbcommon,gtk3): enable wayland

---

packages/vulkan-loader-generic/build.sh

Fix https://github.com/termux/termux-packages/actions/runs/7428056920/job/20214798062#step:4:1714
```
INFO: Updating vulkan-loader-generic [Current version: 1.3.271]
WARNING: Skipping auto-update: Not a release(1.3.275)
```
Also changed to checking symlinks instead of making symlinks ourselves

bump(main/vulkan-loader-generic): 1.3.275

---

packages/git-delta/build.sh

Update the completions for `delta` with the new ones generated by the upcoming `--generate-completion` option,
also adds the missing Fish and Zsh completions in the process.

git-delta: update completions

---

packages/aptitude/0001-fix-ftbfs-with-gcc-10.patch
packages/aptitude/0002-apt_2.1.19_compatibility.patch
packages/aptitude/0003-fix-FTBFS-1011681.patch
packages/aptitude/0004-fix-bashism-related-issue-with-fixman-scripts.patch
packages/aptitude/0005-fix-ftbfs-with-gcc-12.patch
packages/aptitude/0100-fix-hardcoded-paths.patch
packages/aptitude/0101-do-not-link-against-stdc++fs.patch
packages/aptitude/0102-non-static-member-access-in-nested-type.patch
packages/aptitude/0103-fill-some-functions-from-libintl.h.patch
packages/aptitude/0104-fill-rpmatch.patch
packages/aptitude/0105-add-namespace-to-ptr_fun.patch
packages/aptitude/0106-cxx11-narrowing.patch
packages/aptitude/0107-char-array-initialization.patch
packages/aptitude/build.sh
packages/libcwidget/0001-pthread_cancel.patch
packages/libcwidget/0002-replace-Wterminate-with-Wexceptions.patch
packages/libcwidget/build.sh

This package was added in TUR about half year ago by [kawanakaiku](https://github.com/kawanakaiku) because this package cannot be compiled with clang (I guess). I applied some patches and now it is able to be compiled with clang. So I think it's time to add this package to main repository.
Comments about the `pthread_cancel` patch: Customized signal handler cannot be used in this package because it blocks all signals when creating a thread.
Closes #865

new package: libcwidget, aptitude

---

packages/libidn2/0000-disable-versioning-of-symbols.patch

Building `libidn2` currently fails at link:
```
make[3]: Entering directory '/home/builder/.termux-build/libidn2/build/lib'
// snip
CC       context.lo
CCLD     libidn2.la
ld.lld: error: .libs/puny_encode.o: symbol _idn2_punycode_encode@IDN2_0.0.0 has undefined version IDN2_0.0.0
ld.lld: error: .libs/puny_decode.o: symbol _idn2_punycode_decode@IDN2_0.0.0 has undefined version IDN2_0.0.0
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Makefile:1609: libidn2.la] Error 1
```
This fix is recommended here[0]. I couldn't figure out a cleaner way to
do this. It would have been a more stable patch against `config.ac`, but
`configure` is included in the source tarball and this seemed like the
lesser evil. I manually built all packages explicitly …

fix(main/libidn2): Disable symver aliases.

---

packages/rclone/build.sh

fix(main/rclone): Adds a 'v' at the beginning of the version string (#19013)

---

packages/fdupes/build.sh

`fdupes` now has a build time dependency on `libsqlite`
I also noticed the License is actually MIT, not BSD.
PR Checklist:

updpkg(main/fdupes): 2.3.0

---

packages/proxychains-ng/build.sh
packages/proxychains-ng/libproxychains.c.patch

proxychains-ng: bump to 4.17

---

packages/weechat/build.sh
packages/weechat/src-core-hook-wee-hook-url.c.patch
packages/weechat/src-core-wee-url.c.patch

The original patch for `pthread_cancel` will not work properly, because no cancellation is requested during the running process of the thread.
This patch will also not **always** work as expected. There are many cancellation points existing in `curl_easy_init` and `curl_easy_perform`, but we have no control to there functions.

weechat: fix `thread_cancel` patch

---

packages/libpopt/build.sh

We have pkgconfig scripts so should be no need for .la file.  In fact, trying to build a static library that uses libpopt becomes difficult with libpopt.la, due to it declaring that libandroid-glob.so is a dependency (seemingly for both libpopt.so and libpopt.a).

chore(main/libpopt): drop libpopt.la file

---

packages/git/build.sh

As with #19238, `git` itself should also recommend `openssh`
since it enables several features in Git, such as Pushing/Pulling over SSH,
and Commit/Tag/Push signing via SSH keys.
I believe `TERMUX_PKG_RECOMMENDS` is the right relation for the two.
Since:
> [`packages usually used with the current one`](https://github.com/termux/termux-packages/wiki/Creating-new-package#:~:text=TERMUX_PKG_RECOMMENDS)
Fits Git/OpenSSH's relation.

Git: recommend `openssh`

---

packages/util-linux/build.sh
scripts/build/toolchain/termux_setup_toolchain_26b.sh

Bump `util-linux` to make sure it works, fixes #19299.

fix,scripts(toolchain_26b): add rpath flag to avoid adding CI paths to all package binaries

---

root-packages/vnstat/build.sh
root-packages/vnstat/cfg-vnstat.conf.patch
root-packages/vnstat/src-common.h.patch
root-packages/vnstat/src-daemon.c.patch
root-packages/vnstat/vnstati.subpackage.sh

vnstatd needs to be run as root since it reads /sys/class/net. vnstat also needs root since it reads databse from vnstatd. vnstati pulls in libgd as dependency which depends on x11 libs (can be added as seperate package?)

new package: vnstat

---

x11-packages/deadbeef/build.sh
x11-packages/deadbeef/plugins_gme.patch

Patches the `gme` plugin to use `gme_set_fade_msecs` which replicates the previous behavior of the `gme_set_fade` function used by the plugin.
See upstream commit: https://github.com/libgme/game-music-emu/commit/65d238684960ac08174682eea93b4fb391cfe84c
Closes #19331
> [!NOTE]
> Checklist:
> - [x] Builds on CI
> - [x] Tested on device

fix,enhance(x11/deadbeef): enable gme plugin

---

packages/ffmpeg/build.sh
packages/ffmpeg/libavcodec-allcodecs.c.patch

Close #18023
Close #19396 
Move h264 mediacodec encoder to lower priority so that libx264 encoder is preferred

fix(main/ffmpeg): move h264 mediacodec encoder to low priority

---

x11-packages/mesa-demos/build.sh

This change fixes the following error.
~ $ teapot
Teapot V1.2
Written by David Bucciarelli (tech.hmw@plus.it)
../data/tile.rgb: No such file or directory
File not found
Error reading a texture.

fix(x11/mesa-demos): Use full path for data files

---

packages/eza/build.sh

It's been 6 months, I think we can drop the package replacement notice.

chore(main/eza): drop package replacement notice

---

scripts/build/configure/termux_step_configure_meson.sh

This commit fixes the following warning with meson newer than 0.64.0 version.
WARNING: Running the setup command as `meson [options]' instead of `meson setup [options]' is ambiguous and deprecated.

termux_step_configure_meson.sh: Add setup option with meson command

---

packages/kbd/build.sh
packages/kbd/resizecons.c.patch

I can write a proper package request for `kbd` later if wanted,
for now here's the cliff notes version.
Tools for configuring the console (keyboard, virtual terminals, etc.)
- Packaging todo list:
> - [x] Builds on GitHub CI/CD
> - [x] Works on-device (tested on: Android 10, aarch64)
I mainly just ported this for `showkey`,
most of the other commands in this package either aren't applicable or don't work on Termux.
I'll see if the ones related to VTs can be patched to work on Termux,
but I've been up 20 hours and I'm running on sugar and caffeine right now.

new package: kbd

---

packages/k9s/build.sh

Hello, the UI of k9s uses some compile-time definitions to show the version in the main panel. Without this fix it just shows `0.0.0` and it clutters the main panel with the "upgrade available" stuff.
I tested and compiled with this flag directly on my device and it looks good, but since this is my first PR any comment is welcome!
I also removed the dependencies line because 1. there was a typo so it was unused anyway and 2. I don't think "mesa" is a dependency for a TUI application.

K9S: compile using the right ldflags

---

x11-packages/firefox/0018-fix-include-dir-for-cpufeatures.patch
x11-packages/firefox/0024-fix-missing-include-for-macro-MOZ_TRY-in-TimeZone.cpp.patch
x11-packages/firefox/0025-disable-native-https-dns-resolve.patch
x11-packages/firefox/0026-partially-disable-unified-builds.patch
x11-packages/firefox/build.sh
x11-packages/firefox/mozconfig.cfg

Hope that disabling `unified build` will not make it reach the CI limit of 6 hours.
Depends on #19436 
Closes #19053

firefox: bump to 123.0.1

---

packages/perl/build.sh

To fix build errors like:
aarch64-linux-android-clang --sysroot=/home/builder/.termux-build/_cache/android-r26b-api-24-v2/sysroot -Wl,-rpath,/data/data/com.termux/files/usr/lib/perl5/5.38.2/aarch64-android/CORE -Wl,-E -o perl perlmain.o libperl.so
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: pow
>>> referenced by libperl.so

fix(main/perl): link against libm

---

packages/lazygit/build.sh

* Before:
```
$ lazygit --version
commit=, build date=, build source=unknown, version=unversioned, os=android, arch=arm64, git version=2.44.0
```
* After:
```
$ lazygit --version
commit=v0.41.0, build date=2024-03-23T12:58:13Z, build source=termux, version=0.41.0, os=android, arch=arm64, git version=2.44.0
```
Also make the binary somewhat reproducible.

chore(main/lazygit): add version number to build flags

---

packages/git-delta/build.sh

The shell completions will be generated after installing the package.

chore(main/git-delta): Remove upstream patch for generating shell completions

---

packages/llvm-mingw-w64-libcompiler-rt/build.sh
packages/llvm-mingw-w64-ucrt/build.sh
packages/llvm-mingw-w64/build.sh

Update to `20240320`, and rebuild against LLVM 18.
Also for some reason `llvm-mingw-w64-ucrt` won't build unless I manually make it remove:
- `$TERMUX_PREFIX/opt/llvm-mingw-w64` and
- `$TERMUX_PREFIX/lib/clang/18/lib/windows`
I have no idea what's going on with that.
I'm hoping that's just a local issue.

bump(main/llvm-mingw-w64{,-ucrt,-libcompiler-rt}):

---

packages/minio/build.sh

This enables CGO which is required for go 1.22
https://github.com/golang/website/commit/8cd359112ea8314a583ca0505da660e0b9831c0f
Also fixes the following error.
android/amd64 requires external (cgo) linking, but cgo is not enabled
Fixes #19624

fix(main/minio): Fix building for non-aarch64 architectures

---

packages/ca-certificates/build.sh

This was forgotten when openjdk was updated.

fix(main/ca-certificates): update openjdk path

---

packages/gopass/build.sh

Based on the results of the [last auto update CI run](https://github.com/termux/termux-packages/actions/runs/8582949378),
this package now required CGO to be enabled for all architectures except AArch64.
<details><summary>Details</summary>
<p>
```log
android/arm requires external (cgo) linking, but cgo is not enabled
make: *** [Makefile:72: gopass] Error 1
>> BUILD, version = 1.15.13/, output = gopassmake: Leaving directory '/home/builder/.termux-build/gopass/src'
Error: Process completed with exit code 2.
```
</p>
</details> 
For build consistency I have decided to just turn on CGO for all architectures to avoid future discrepancies between AArch64 and other builds of this package.

chore(main/gopass): fix arm, i686 and x86_64 build

---

packages/picolisp/build.sh

Use upstream link for source tarball. That link was reverted in e45652b2c61e39f9f0cd954aeac41e2671d55573 commit.
Fixes #19667

bump(main/picolisp): 24.3

---

packages/just/build.sh

This adds [just](https://github.com/casey/just), a tool similar to `make` but with a different approach and a bunch of other features.
However, there's a small issue. `Just` by default searches up to the root for other `Justfiles` during initialization. As non-root installations don't have read permission in `/data/data/`, just throws an I/O error.
The author suggested a workaround in [just/#1492](https://github.com/casey/just/issues/1492#issuecomment-1379876914).
Note that this doesn't hinder the program's functionality, only during initialization.

addpkg(main/just): A handy way to save and run project-specific commands

---

packages/shellcheck/build.sh

Supersedes #15410
Since the blocker for 0.9.0 was cleared upstream, we should probably get Shellcheck updated since we're now 2 versions behind.
CC: @landfillbaby

bump(main/shellcheck): 0.10.0

---

packages/valgrind/build.sh
packages/valgrind/no-statx.patch

fix(main/valgrind): x86_64 syscall patch

---

x11-packages/libdecor/build.sh

This was a mistake on my part that I did not check carefully. Move libdecor to x11-repo due to gtk3 only available in x11-repo.

libdecor: move to x11

---

x11-packages/gtk-layer-shell/build.sh
x11-packages/gtk-layer-shell/gir/GtkLayerShell-0.1.xml

<details><summary>Click here to see the list of added files in gtk-layer-shell package</summary>
```diff
--- gtk-layer-shell-old.txt
+++ gtk-layer-shell-new.txt
@@ -8,6 +8,8 @@
./data/data/com.termux/files/usr/include/gtk-layer-shell/
./data/data/com.termux/files/usr/include/gtk-layer-shell/gtk-layer-shell.h
./data/data/com.termux/files/usr/lib/
+./data/data/com.termux/files/usr/lib/girepository-1.0/
+./data/data/com.termux/files/usr/lib/girepository-1.0/GtkLayerShell-0.1.typelib
./data/data/com.termux/files/usr/lib/libgtk-layer-shell.so
./data/data/com.termux/files/usr/lib/pkgconfig/
./data/data/com.termux/files/usr/lib/pkgconfig/gtk-layer-shell-0.pc
@@ -15,3 +17,9 @@
./data/data/com.termux/files/usr/share/doc/
./data/data/com.termux/files/usr/share/doc/gtk-layer-shell/ …
```

enhance(x11/gtk-layer-shell): Enable gobject introspection data

---

packages/oh-my-posh/build.sh

feat(oh-my-posh): add package

---

packages/just/build.sh

also set a maintainer.
I noticed we were missing the `elvish` completions, and we should probably be generating these from the binary anyway.
I also set a maintainer since that wasn't done in #19712
@flipee since you are the author on that original PR, if you want to take the maintainership for `just` instead please say so, so I can adjust that line.

fix(main/just): generate completion and add elvish

---

x11-packages/pyqt5/build.sh

This prevents running pyqt5 with older version of pyqt5-sip and fixes
the following runtime error.
RuntimeError: the sip module implements API v12.0 to v12.12 but the PyQt5.QtCore module requires API v12.13
Fixes #19755

chore(x11/pyqt5): Add version requirements for runtime and build time dependencies

---

packages/delve/build.sh
packages/delve/debugger.go.patch

fixes https://github.com/termux/termux-packages/issues/18672
I still need to test it, but running `./build-package.sh delve` compiles a lot of stuff and does not reach delve.
Edit: I got it working with `./build-package.sh -s delve`

fix(main/delve): patch debugger.go to contain android

---

packages/zrok/build.sh

I also enabled autoupdates, which apparently I forgot during the initial PR.

bump(main/zrok): 0.4.27

---

packages/plutolang/build.sh
packages/plutolang/src-loslib.cpp.patch

```
$ pluto
Pluto 0.9.0 Copyright (C) 2022-2024 PlutoLang.org, Ryan Starrett, Sainan.
Based on Lua 5.4.6 Copyright (C) 1994-2023 Lua.org, PUC-Rio.
> os.tmpname()
stack corruption detected (-fstack-protector)
Aborted
```

fix(main/plutolang): Fix buffer overflow in os.tmpname

---

packages/usql/build.sh

This adds [usql](https://github.com/xo/usql), a universal command-line interface for PostgreSQL, MySQL, Oracle Database, SQLite3, Microsoft SQL Server, [and many other databases](https://github.com/xo/usql#database-support) including NoSQL and non-relational databases.

addpkg(main/usql): 0.18.1

---

packages/tmux/build.sh
packages/tmux/htonll.patch

Also enable building with `--enable-sixel` in anticipation of future Sixel support in the main app.
I'd much appreciate testing on this PR before merging.
Instructions below.
<sub>(This is a pre-written, saved reply.)</sub>
To test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux/termux-packages/pull/19736/checks).
After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instuctions, if needed.</summary>
<p>
```bash
termux-info
pkg install unzip tar
unzip debs-aarch64-*.zip
tar xf debs-aarch64-*.tar
pkg install -- ./debs/*.deb
rm -rfi debs debs-aarch64-*.zip debs-aarch64-*.tar
```
</p>
</details>

bump(main/tmux): 3.4

---

packages/gdu/Makefile.patch
packages/gdu/build.sh

* Now requires CGO for non AArch64 architectures.
* Fix version number.
* Disable static linking which does not work with liblog.
See the build failures in c4fec80f01c9a3fffae7c40dcbf6ebd9736f8b9d commit.

chore(main/gdu): fix arm, i686 and x86_64 build

---

scripts/build/termux_step_make.sh
scripts/build/termux_step_make_install.sh

ninja has removed the flag `-w dupbuild=warn` since https://github.com/ninja-build/ninja/commit/8f47d5aa33c6c303a71093be2eac02672dfb2966.
```
$ ninja --version
1.12.0
$ ninja -w dupbuild=warn
ninja: error: unknown warning flag 'dupbuild=warn'
```

fix(scripts/build): ninja: unknown warning flag 'dupbuild=warn'

---

packages/matplotlib/build.sh
packages/python-contourpy/build.sh

For #19755 with love.
I can not install matplotlib in my old phone because it can not compile python-contourpy with lower memory. If python-contourpy is provided as a package matplotlib can be installed successfully.

addpkg(main/python-contourpy): 1.2.1

---

x11-packages/vala-panel-appmenu/build.sh
x11-packages/vala-panel-appmenu/gir/AppmenuGLibTranslator-24.02.xml
x11-packages/vala-panel-appmenu/xfce4-appmenu-plugin.subpackage.sh

* Enable gobject introspection data.
* xfce4-appmenu-plugin now depends on vala-appmenu-plugin which provides libappmenu-glib-translator.so.
Fixes #17896

bump(x11/vala-panel-appmenu): 24.02

---

packages/dbus/build.sh

This fixes the following error with `dbus-daemon --system' command by
creating a PREFIX/var/run/dbus directory with a dummy file.
dbus-daemon[16282]: Failed to start message bus: Failed to bind socket
"/data/data/com.termux/files/usr/var/run/dbus/system_bus_socket": No such file or directory
The workaround is similar as openssh. If that directory is not present
dbus-daemon can not create pid and system_bus_socket files.

fix(main/dbus): Fix launching systemwide message bus with dbus-daemon

---

packages/swi-prolog/build.sh

Build fails with:
```ml
[1049/1049] -- CHR bootstrap compilation step 4
[35/36] Install the project...
-- Install configuration: "Release"
termux-elf-cleaner: Replacing unsupported DF_1_* flags 134217729 with 1 in './lib/swipl/bin/arm64-android/swipl-ld'
termux-elf-cleaner: Replacing unsupported DF_1_* flags 134217729 with 1 in './lib/swipl/bin/arm64-android/swipl'
ERROR: lib/swipl/lib/arm64-android/time.so contains undefined symbols:
72: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND backtrace
73: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND backtrace_symbols
```
Apollo suggested adding a dependency for `libandroid-execinfo`, that didn't seem to fix it.
Issue seems to be related to `libunwind` in some way.

bump(main/swi-prolog): 9.3.3

---

x11-packages/gtk3/build.sh
x11-packages/gtk3/gtk-update-icon-cache.subpackage.sh

`share/man/man1/gtk-update-icon-cache.1.gz` is moved from gtk3 to gtk-update-icon-cache since version 3.24.41, the latter should have BREAKS field to let the installation process work as intended.

gtk-update-icon-cache: add BREAKS field

---

packages/libmediainfo/build.sh
packages/mediainfo/build.sh

Fix https://github.com/termux/termux-packages/actions/runs/8841094968/job/24277612526#step:4:493
```console
INFO: Updating libmediainfo [Current version: 24.04]
WARN: Auto update failure!
api_url_r=<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta http-equiv="refresh" content="0;url='/en/MediaInfo'" />
<title>Redirecting to /en/MediaInfo</title>
</head>
<body>
Redirecting to <a href="/en/MediaInfo">/en/MediaInfo</a>.
</body>
</html>
r1=
latest_version=
termux - took 719ms
```

fix(main/mediainfo): auto update

---

scripts/build/toolchain/termux_setup_toolchain_23c.sh
scripts/build/toolchain/termux_setup_toolchain_26b.sh

Fix `go build` error: unrecognized command-line option ‘-fno-openmp-implicit-rpath’.

fix(scripts/termux_setup_toolchain_26b): fix CGO_LDFLAGS

---

scripts/build/termux_step_massage.sh
scripts/build/termux_step_setup_variables.sh
scripts/libc.map.txt
scripts/libdl.map.txt
scripts/libm.map.txt

The dummy package is not part of this PR. But it demonstrates how we can capture the issue early on.
The benefit is that we don't need to physically install packages on old devices to check the package can even be started or not.
I do not think we want to maintain libc.map.txt and a matching parser for the little effort so I pasted symbols into a function.
I have changed so that it checks all files instead of just "*.so" from lib dir only but I like to gather opinions from all first.
Old commit: https://github.com/termux/termux-packages/commit/d98409a91fbef3c22303cdd3af7490502e3d6d2d
Old CI: https://github.com/termux/termux-packages/actions/runs/6507027577/job/17673682012

termux_step_massage: enhance symbol checking 

---

packages/dbus/build.sh

Since lld 17, `-no-undefined-version` is enabled by default. It causes `ld-version-script` check fails in `dbus` and disables the versioned symbol in `libdbus-1.so`, making some binaries compile failure.
Symbol list in `1.15.6-2`:
```
123: 000000000002b314    24 FUNC    GLOBAL DEFAULT   12 _dbus_credentials_are_anonymous
124: 000000000002ba5c   120 FUNC    GLOBAL DEFAULT   12 dbus_move_error
125: 000000000003af34    36 FUNC    GLOBAL DEFAULT   12 dbus_type_is_valid
126: 00000000000339c8   160 FUNC    GLOBAL DEFAULT   12 dbus_message_set_interface
```
Symbol list in `1.15.6-1` or `1.15.6-3`:
```
123: 000000000002b384    24 FUNC    GLOBAL DEFAULT   13 _dbus_credentials_are_anonymous@@LIBDBUS_PRIVATE_1.15.6
124: 000000000002bacc   120 FUNC    GLOBAL DEFAULT   13 dbus_move_error@@LIBDBUS_1_3 …
```

dbus: enable version script

---

x11-packages/qbittorrent/build.sh
x11-packages/qbittorrent/qbittorrent-nox.subpackage.sh

closes:
- #10081
`qbittorrent` (even the headless `-nox` version) depends on `qt5-qtbase`, so it needs to be in the X11 Repo.
I'm forcing Cmake for the build.
Cmake has better [upstream build instructions](https://github.com/qbittorrent/qBittorrent/wiki/Compilation-with-CMake:-common-information).
Builds fine with `make` as well, if that's preferable.
---
If there's an easy way to just build it twice I'd actually like to build it once with GUI and once without,
and split off `qbittorrent-nox` into a subpackage.
But I couldn't figure out a good way to do that.
And the request was for the headless one.

addpkg(x11/qbittorrent{,-nox}): 4.6.4

---

packages/fselect/build.sh
packages/fselect/libmimalloc-sys-tls.diff

Add workaround for libz-ng-sys crate build failure.
Fixes #20014

bump(main/fselect): 0.8.6

---

packages/mpv/build.sh
x11-packages/mpv-x/build.sh

Also enable Wayland support for mpv-x and set maintainer

bump({main,x11}/mpv{,-x}): 0.38.0

---

packages/kakoune/Makefile.patch
packages/kakoune/build.sh

Makefile was moved from src sub-directory to main directory. https://github.com/mawww/kakoune/commit/b05295637e7dbe5239a1142a72afe8265e5d77c3
Fixes #20071

bump(main/kakoune): 2024.05.09

---

packages/fish/apt-autocompletion-sources-paths.patch
packages/fish/build.sh
packages/fish/share-functions-__fish_print_apt_packages.fish.patch

Package autocompletions works now by setting appropriate `sources.list` paths. In this case, it will use Termux prefix to find and use its `sources.list`
Compare and test:
- Install and use the latest fish, run `fish` shell, try typing `apt install cmat<TAB>` and it doesn't autocomplete.
- Testing the patch included for this packages or manually setting the appropriate paths in the fish completions file `$PREFIX/share/fish/completions/apt.fish` through editing would make package autocompletions works.
P.S: Please let me know if this is enough for now, as fish have several builtin completions for variety of apps included in its source code. I had provided the modified completion file in a patchfile format. Also, I will revbump later if it goes well.

fish: fix hardcoded paths for apt completions file

---

packages/libarrow-cpp/build.sh

Fixes #20103
```
>>> import pyarrow
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
import pyarrow.lib as _lib
ImportError: dlopen failed: cannot locate symbol "_ZN6google8protobuf2io19ZeroCopyInputStream8ReadCordEPN4absl12lts_202308024CordEi" referenced by "/data/data/com.termux/files/usr/lib/libarrow.so"...
$ c++filt "_ZN6google8protobuf2io19ZeroCopyInputStream8ReadCordEPN4absl12lts_202308024CordEi"
google::protobuf::io::ZeroCopyInputStream::ReadCord(absl::lts_20230802::Cord*, int)
```

revbump(main/libarrow-cpp): abseil-cpp update

---

scripts/lint-packages.sh

Inspired by #19990.
This adds two simple checks, making sure that:
- A.) the package directory exists in `packages`, `x11-packages` or `root-packages`
and
- B.) there is a `build.sh` file in the package directory

scripts(lint-packages):sanity check package layout

---

packages/hunspell-hu/build.sh

Fixes a build error due to checksum mismatch after an upstream dictionary update.

bump(main/hunspell-hu): 2024.03.28

---

packages/libebur128/build.sh
packages/libebur128/ebur128-CMakeLists.txt.patch

>ERROR: ./lib/libebur128.so contains undefined symbols:
>     8: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND pow
>     9: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND tan
>    12: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND log
>    15: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND sin
>    16: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cos

fix(main/libebur128): Link to libm

---

packages/libvbisam/build.sh

> [..]/ischeck.c:148:12: error: parameter 'ihandle' was not declared, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]

fix(main/libvbisam): Fix building with current clang

---

packages/tere/build.sh

Fixes the below error:
> [..]/tere/build.sh: line 15: TARGET_CFLAGS: unbound variable

fix(main/tere): Fix build error due to undefined shell variable

---

packages/go-musicfox/build.sh

new packages:
* [go-musicfox](https://github.com/go-musicfox/go-musicfox)

new package: go-musicfox

---

packages/doctest/build.sh

Suppress compiler warnings as errors until https://github.com/doctest/doctest/issues/766 is fixed.

fix(main/doctest): Fix building with current clang

---

packages/distcc/build.sh

Fixes the below error:
> error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
> void dcc_read_localslots_configuration()

fix(main/distcc): Fix building with current clang

---

packages/hexcurse/build.sh

> [..]/getopt.c:73:1: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
exchange (argv)
> [..]/getopt.c:98:1: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
getopt_set_posix_option_order (on_or_off)
> [..]/getopt.c:108:1: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
_getopt_internal (argc, argv, optstring, longopts, longind, long_only)
> [..]/getopt.c:450:1: error: a function definition without a prototype is deprecated in all versions of C and is not …

fix(main/hexcurse): Fix building with current clang

---

packages/stfl/build.sh

Fixes the below build error:
> Failed to download https://grimler.se/termux/stfl-0.24.tar.gz

fix(main/stfl): Fix to working src url

---

packages/sabnzbd/build.sh

sabnzbd: python target dependencies

---

packages/libgts/build.sh
packages/libgts/src-Makefile-in.patch

> ERROR: ./lib/libgts-0.7.so.5.0.1 contains undefined symbols:
>    32: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND atan2
>    64: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND sincos
>    67: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cos
>    77: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND log
>    78: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND exp

fix(main/libgts): Fix undefined symbols

---

packages/openfoam/build.sh
packages/openfoam/src-OpenFOAM-Make-options.patch

Fix the below build error:
> ERROR: ./opt/OpenFOAM-v2312/platforms/linuxARM64ClangDPInt32Opt/lib/libOpenFOAM.so contains undefined symbols:
>   344: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND backtrace
>   345: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND backtrace_symbols
> 56092: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND backtrace
> 56093: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND backtrace_symbols

fix(main/openfoam): Fix undefined symbols and parallel build

---

packages/ffmpeg/build.sh

Draw a text string or text from a specified file on top of a video.
This commit enables the option as suggested in the upstream docs.
https://ffmpeg.org/ffmpeg-filters.html#drawtext-1
Fixes #20220

enhance(main/ffmpeg): Enable drawtext feature

---

packages/taskwarrior/0001-timestamp.patch32
packages/taskwarrior/build.sh
packages/taskwarrior/linkme-android.diff
packages/taskwarrior/linkme-impl-android.diff

taskwarrior: bump to 3.0.2

---

packages/apt/build.sh

This fixes building apt when old tarball are removed in https://deb.debian.org/debian/pool/main/a/apt/
The same source link is used in other Linux distributions. For example,
* Alpine Linux https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/apt/APKBUILD
* Fedora Linux https://src.fedoraproject.org/rpms/apt/blob/rawhide/f/apt.spec
Fixes #20288

chore(main/apt): Use source tarball from upstream git archive

---

packages/apt/build.sh

Years ago apt used libcurl for its http(s) transport, but that is no longer the case.
See #19980 regarding the big amount of dependencies apt has.

chore(main/apt): Remove false dependency on libcurl

---

build-package.sh

Issue:
Currently, the build-package.sh script fails when trying to build a package like neovim when `git config --system log.showSignature true` is set and the latest commit is signed causing the signature to be included in the output.
Fix:
This fixes the issue by being more strict in it's search for the commit date in the git log output by only retrieving the last line of the log and then searching for a string of numbers corresponding to the expected value for SOURCE_DATE_EPOCH.
This fix has been tested to work against the main branch that is lacking a commit signature in the git log output as well.
This would allow people with commit signing to more easily contribute without needing to disable that security feature to do so.

scripts(build-package.sh): make git log more strict in it's output for SOURCE_EPOCH_DATE

---

packages/logo-ls/build.sh

Updated logo-ls to latest commit and updated `build.sh` to be more strict when searching for version string for (hopefully) easier future updates

bump(main/logo-ls): update logo-ls to latest commit(61ad1aa)

---

scripts/buildorder.py

See #20338 for context. [Current output of buildorder.py](https://github.com/termux/termux-packages/files/15462088/buildorder.err.txt) with this change. New content is at the bottom.

enhance(scripts/buildorder.py): print detected cycles

---

packages/libluajit/build.sh
packages/libluajit/src-Makefile.patch
scripts/updates/termux_pkg_auto_update.sh

Background: luajit uses rolling releases - see https://luajit.org/download.html
The recommended approach is to make frequent snapshots, which the termux package is currently taking from the 2.1 branch.
The version scheme follows what arch linux is doing: https://archlinux.org/packages/extra/x86_64/luajit/
That means that the version number "2.1.1716656478" refers to the "2.1" branch, with "1716656478" being the timestamp of the commit built (as displayed by `git show -s --format=%ct`).
The problem is that the termux package was hardcoded to build a specific commit from 2021-03-10: https://github.com/LuaJIT/LuaJIT/commit/787736990ac3b7d5ceaba2697c7d0f58f77bb782
We now instead look up the commit from the timestamp in the version string, so that what is built is correct, and auto updates …

fix(main/libluajit): Fix mismatch between version and what is built

---

packages/libsamplerate/CMakeLists.txt.patch32
packages/libsamplerate/build.sh

Fix the below build error when building for 32-bit arm:
> ERROR: ./lib/libsamplerate.so contains undefined symbols:
6: 00000000     0 NOTYPE  GLOBAL DEFAULT   UND lrintf
7: 00000000     0 NOTYPE  GLOBAL DEFAULT   UND lrint

fix(main/libsamplerate): Fix undefined symbols on 32-bit builds

---

x11-packages/qt6-qtbase/build.sh

* QT_BUILD_TOOLS_BY_DEFAULT: Build tools which are excluded for cross compilation.[1]
* QT_FORCE_BUILD_TOOLS: Forces building tools even if host tools have already been found.[2]
* Disable building in source directory due to presence of some similar files.
* Create symlinks in cross build like host build.
[1]: https://doc.qt.io/qt-6/configure-options.html
[2]: https://doc.qt.io/qt-6/cmake-variable-reference.html

enhance(x11/qt6-qtbase): Build all tools same as host cross tools packages

---

packages/apt/0000-cmake-fix.patch
packages/apt/build.sh

Add libiconv and libgcypt depdencies explicitly.
https://salsa.debian.org/apt-team/apt/-/blob/2.7.14/CMakeLists.txt?ref_type=tags#L44 https://salsa.debian.org/apt-team/apt/-/blob/2.7.14/CMakeLists.txt?ref_type=tags#L143

bump(main/apt): 2.7.14

---

packages/re2c/build.sh

Earlier maintainer hasn't participated in any of Termux's repositories
since a while now and the package seems to have been maintained by us. I
am currently working on something that requires re2c to build, so it
would make testing the package just another chore for me which I can do
easily

chore(main/re2c): adopt package

---

packages/just/build.sh

Man page and completions are no longer tracked in the source repo.
I refactored the build script to instead generate them at build time.
This also eliminates the previous "update" step in the postinstall step.
CC: Tagging @flipee as maintainer, to keep you informed of the changes.

bump(main/just): 1.28.0

---

packages/ncurses/build.sh

termux_step_post_massage() should not make changes that causes TERMUX_PREFIX and TERMUX_PKG_MASSAGEDIR to diverge. When we build packages without -i/-I this can cause build errors, as evident from discussion in https://github.com/termux/termux-packages/pull/20411.
Also update header list, tic.h and nc_tparm.h no longer exist.
This essentially reverts commit 276ebf803df7 ("ncurses: symlink headers in `post_massage` step").
CC @Maxython, thanks for reporting the issue!

ncurses: symlink headers in post_make_install step

---

packages/vis/build.sh

Yeah it was literally a 1 byte fix...
See: https://github.com/termux/termux-packages/pull/20473#issuecomment-2156640754

fix(main/vis): fix include path for `lua53-lpeg` dependency

---

packages/python/build.sh

No more needed as clang supports `-fno-openmp-implicit-rpath` after #20464
This reverts commit d2e1d4ac0a8743c8bba8035b7307d09558154340.

python: drop workaround for `-fno-openmp-implicit-rpath`

---

packages/taskwarrior/build.sh

By setting `CMAKE_ANDROID_ARM_MODE` we get the normal `armv7-linux-androideabi` target which we set:
https://github.com/termux/termux-packages/blob/master/scripts/build/setup/termux_setup_rust.sh#L5
See
https://github.com/corrosion-rs/corrosion/blob/master/cmake/FindRust.cmake#L705-L711:
```cmake
elseif (ANDROID)
if (CMAKE_ANDROID_ARCH_ABI STREQUAL armeabi-v7a)
if (CMAKE_ANDROID_ARM_MODE)
set(_Rust_ANDROID_TARGET armv7-linux-androideabi)
else ()
set(_Rust_ANDROID_TARGET thumbv7neon-linux-androideabi)
endif()
```
This avoids having to install another rust target, and actually fixes the current 32-bit arm build which before this change fails with:
```txt
cargo:warning=crypto/curve25519/asm/x25519-asm-arm.S:36:1: error: invalid instruction, any one of the following would fix this: …
```

fix(main/taskwarrior): Fix 32-bit arm build by setting CMAKE_ANDROID_ARM_MODE

---

packages/libarrow-cpp/build.sh
packages/thrift/build.sh

Otherwise it builds static thrift library from vendored dependencies.

enhance(main/libarrow-cpp): use shared thrift library from package

---

packages/ruby/build.sh
packages/ruby/fix-paths.patch
packages/ruby/yjit-src-codegen.rs.patch
packages/ruby/yjit-src-yjit.rs.patch

See https://bugs.ruby-lang.org/issues/19616 about readline.so removal.
Will rev-bump `asciidoctor` and `weechat` as follow ups.

bump(main/ruby): 3.3.2

---

scripts/bin/update-packages

See #20498 and https://github.com/termux/termux-packages/actions/runs/9465206895/job/26074224976
Partial revert of 5f1c3865995c7181a7df17fd47244d4e43445a73 to fix
Breakage (before):
Package Updates always build packages if detected new updates
Fix (after or before the breakge):
Package Updates checks existing issue before build if detected new updates
The last commit already allows PR to check auto update is working or not without closing existing issues.

fix(auto-update): check issues before building in CI

---

packages/libaom/build.sh

Source tarball link can be found in https://groups.google.com/a/aomedia.org/g/av1-discuss
This reverts commit d0221f5207d1b6896d9feda07eea967bd81cc605

chore(main/libaom): Use source tarball, enable auto-update

---

packages/imagemagick/build.sh

Getting this error when running any `magick` command.
```
CANNOT LINK EXECUTABLE "magick": cannot locate symbol "xmlNanoHTTPMethod" referenced by "/data/data/com.termux/files/usr/lib/libMagickCore-7.Q16HDRI.so"...
```
This has happened before, a revbump usually fixes that.

revbump(main/imagemagick): Rebuild after libxml2 2.13.0 update

---

root-packages/i2c-tools/build.sh

Can be used to learn more about the various hardware chips in your phone (if they communicate over i2c).

addpkg(root/i2c-tools): tools for interacting with i2c devices

---

scripts/bin/check-auto-update

Or else curl commands fails with 403 Forbidden, at least for me locally.

fix(scripts/check-auto-update): set a user-agent for repology check

---

root-packages/containerd/build.sh

Fixes the following error
android/amd64 requires external (cgo) linking, but cgo is not enabled
Fixes #20437

fix(root/containerd): Enable CGO for non AArch64 architectures

---

packages/below/build.sh

This is one of the few packages depending on host llvm 15 being installed. Soon the transition to llvm 17 is complete, and we can drop llvm 15 from the Docker image for size and maintenance reasons.

chore(main/below): Switch from clang-15 to clang-17

---

x11-packages/qt5-qtwebengine/build.sh

This is one of the few packages depending on host llvm 15 being installed. Soon the transition to llvm 17 is complete, and we can drop llvm 15 from the Docker image for size and maintenance reasons.

chore(x11/qt5-qtwebengine): Switch from clang-15 to clang-17

---

packages/libgee/build.sh

See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271485:
> Clang 16 has a new error about incompatible function types, which shows
> up when building devel/libgee:
>
> hashmap.c:4089:23: error: incompatible function pointer types assigning to 'gboolean (*)(GeeMapIterator *)' (aka 'int (*)(struct _GeeMapIterator *)') from 'gboolean (GeeHashMapNodeIterator *)' (aka 'int (struct _GeeHashMapNodeIterator *)') [-Wincompatible-function-pointer-types]
>              iface->get_read_only = gee_hash_map_map_iterator_real_get_read_only;
>                                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Since the error occurs in vala-generated code, it does not make sense to
> patch the .c file. Suppress the warning instead.

fix(main/libgee): Fix build with current toolchain

---

packages/libgcrypt/build.sh

The `-no-integrated-as` build flag was added waaay back (7 years ago) when clang was a lot newer and seems to be no longer necessary, either due to improvements in clang or with code changes to make assembly portable in libgcrypt.

chore(main/libgcrypt): Switch to the clang integrated assembler

---

packages/neovim/build.sh
packages/neovim/runtime-CMakeLists.txt.patch
packages/neovim/src-nvim-CMakeLists.txt.patch
packages/neovim/src-nvim-po-CMakeLists.txt.patch

closes #20221
Regenerated patches, build still fails with:
```styl
CMake Error at /home/builder/.termux-build/_cache/cmake-3.29.3/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find Lpeg (missing: LPEG_LIBRARY)
Call Stack (most recent call first):
/home/builder/.termux-build/_cache/cmake-3.29.3/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
cmake/FindLpeg.cmake:3 (find_package_handle_standard_args)
src/nvim/CMakeLists.txt:34 (find_package)
```
It seems like the luarocks modules `lpeg` and `mpack` are missing.
As I am unsure if there is a consensus as to how to best handle additional luarocks modules in package builds I decided to put this up as a PR, so that can be hashed out.

bump(main/neovim): 0.10.0

---

packages/libsoup/0001-Fix-build-with-libxml2-2.12.0-and-clang-17.patch
packages/libsoup/build.sh

The `_WRAPPER_BIN` section is copied from [libsoup3 build.sh](https://github.com/termux/termux-packages/blob/master/packages/libsoup3/build.sh#L25-L34) - should we do it differently? Without it the build fails with:
> OSError: [Errno 8] Exec format error: '/data/data/com.termux/files/usr/bin/glib-mkenums
The patch is (as seen in the file) taken from https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/385 - merged upstream but not released yet. It fixes the below build error:
> ../src/libsoup/soup-xmlrpc-old.c:512:8: error: call to undeclared function 'xmlParseMemory'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration] …

fix(main/libsoup): Fix build with current toolchain

---

packages/zsh/build.sh
packages/zsh/etc-zshrc

I also cleaned up the module listing and history section in build script by turning it into an array,
and set a maintainer.
---
<sup>(This is a pre-written, saved reply.)</sup>
If you want to test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux/termux-packages/pull/20604/checks).
After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instructions, if needed.</summary>
<p>
```bash
termux-info
pkg install unzip tar
unzip debs-aarch64-*.zip
tar xf debs-aarch64-*.tar
pkg install -- ./debs/*.deb
rm -rfi debs debs-aarch64-*.zip debs-aarch64-*.tar
```
</p>
</details>

enhance(main/zsh): enable zsh/newuser module.

---

x11-packages/firefox/build.sh

It seems that `-no-integrated-as` is no longer necessary.

chore(x11/firefox): Switch to the clang integrated assembler

---

x11-packages/fluxbox/build.sh

Set `-std=c++11` to fix build errors such as:
> src/FbTk/MemFun.hh:86:28: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
> src/FbTk/MenuItem.hh:158:14: error: no template named 'auto_ptr' in namespace 'std'

fix(x11/fluxbox): Fix building with current toolchain

---

packages/flang/build.sh

Currently `pkg install flang` gives the below error:
> The following packages have unmet dependencies:
> flang : Depends: libllvm (= 18.1.7) but 18.1.7-1 is to be installed
>         Depends: clang (= 18.1.7) but 18.1.7-1 is to be installed
>         Depends: lld (= 18.1.7) but 18.1.7-1 is to be installed
>         Depends: mlir (= 18.1.7) but 18.1.7-1 is to be installed
> E: Unable to correct problems, you have held broken packages.
This is due to the `(= $TERMUX_PKG_VERSION)` version qualifier on llvm dependencies, introduced in 50737838a5344f1e128f4164b90af07378945cc0 to make sure that llvm matches the flang version.
This is fine for the upstream version (version `18.1.7` of flang should depend on version `18.1.7`).
But when bumping the `TERMUX_PKG_REVISION` on llvm, which was done in …

fix(main/flang): Fix unmet dependencies problem

---

packages/qemu-system-x86-64-headless/build.sh

This uses system provided dtc package to link with fdt library.
Otherwise, dtc subproject is used which install duplicate fdt
header files - fdt.h, libfdt_env.h and libfdt.h.
Fixes #20627

fix(main/qemu): Remove duplicate fdt headers

---

packages/wasi-libc/build.sh
packages/wasm-component-ld/build.sh
scripts/build/get_source/termux_git_clone_src.sh
scripts/build/setup/termux_setup_rust.sh

Will follow up enabling `rust-std-wasm32-wasip1` and `rust-std-wasm32-wasip2` later
```
~/bin $ cc --target=wasm32-wasi hello.c -o hello.wasm --sysroot=$PREFIX/share/wasi-sysroot; file hello.wasm; wasmtime hello.wasm
hello.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
Hello world!
~/bin $ cc --target=wasm32-wasip1 hello.c -o hello.wasm --sysroot=$PREFIX/share/wasi-sysroot; file hello.wasm; wasmtime hello.wasm
hello.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
Hello world!
~/bin $ cc --target=wasm32-wasip2 hello.c -o hello.wasm --sysroot=$PREFIX/share/wasi-sysroot; file hello.wasm; wasmtime hello.wasm
hello.wasm: WebAssembly (wasm) binary module version 0x1000d
Hello world!
~/bin $ cat hello.c
#include <stdio.h>
int main(void) {
puts("Hello world!");
return 0;
}
```

bump(main/wasi-libc): 22

---

packages/mariadb/build.sh

Fixed #20647 
mysql_install_db: Deprecated program name. It will be removed in a future release, use 'mariadb-install-db' instead

mariadb: update termux_step_create_debscripts

---

build-package.sh
scripts/build/termux_step_handle_host_build.sh

The [`wiki`](https://github.com/termux/termux-packages/wiki/Building-packages) describes the function `termux_step_handle_host_build` but in the codebase it is referenced as `termux_step_handle_hostbuild`. Fixed it to be in sync with the docs.

fix: Update function name as per wiki

---

packages/alsa-lib/0001-path.patch
packages/alsa-lib/build.sh
packages/alsa-utils/build.sh
packages/jack-example-tools/build.sh
packages/jack/build.sh
packages/jack2/0001-fix-android-build.patch
packages/jack2/0002-fix-path.patch
packages/jack2/0003-opensles-driver.patch
packages/jack2/0004-remove-su-features.patch
packages/jack2/build.sh
packages/mpv/build.sh
x11-packages/mpv-x/build.sh

Few packages
* `jack2` is an audio server. On Android, it can use OpenSLES as backend. 
* The metapackage `jack` is for dependency management and will accept the upcoming `pipewire-jack` as an option. By the way, I am not interested in making `jack1` functional and be one of the `jack` option, given that we have `jack2` now and it seems Linux distros usually not packing `jack1` officially (at least for Archlinux it is in AUR). 
* `alsa-lib` as deps of `jack2`. Also, it is tested to work along with `pipewire-alsa` which will be finalized in the pipewire PR. 
* `mpv` and `mpv-x` are updated to support jack and alsa audio output
Tested working with: 
```
jackd -d opensles
```
and then use the updated mpv in this PR
```
mpv --ao=jack ./test.wav
```
By the way, since …

new packages: JACK Audio Connection Kit and `alsa-lib`

---

x11-packages/pavucontrol/build.sh
x11-packages/xfce4-pulseaudio-plugin/build.sh

patch in `termux_step_pre_configure()` needed to address `/data/data/com.termux/files/usr/bin/glib-compile-resources: not found`.

addpkg(x11/pavucontrol): 6.0

---

packages/swift/build.sh

This is one of the last few packages depending on host llvm 15 being installed.
Soon the transition to llvm 17 is complete, and we can drop llvm 15 from the Docker image for size and maintenance reasons.

chore(main/swift): Switch from clang-15 to clang-17

---

packages/libprotobuf/build.sh
packages/protobuf-static/build.sh
scripts/build/termux_step_override_config_scripts.sh

For more information for this PR, check https://github.com/termux/termux-packages/pull/19468#issuecomment-2104878325
The test rebuilt `mosh` (depending on the shared library protobuf) and `opencv` (depending on the static library protobuf) in the same PR, and the test has passed. See https://github.com/termux/termux-packages/actions/runs/9052874693.

chore: override config for protobuf

---

packages/gexiv2/build.sh

* Remove unused -D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES compiler flag which was added in 3157a78171fa755e31ed8f776f5b4ad0110c64f8 commit.
* Fix the following build error. OSError: [Errno 8] Exec format error: '/data/data/com.termux/files/usr/bin/glib-mkenums'
Fixes #20729

bump(main/gexiv2): 0.14.3

---

scripts/setup-ubuntu.sh

It is installed by `python2 get-pip.py`.

setup-ubuntu.sh: remove pip from /usr/local/bin

---

x11-packages/libxfce4ui/0001-system-info.patch
x11-packages/libxfce4ui/build.sh

See #20574
Tested on MIX4 (Snapdragon 888 Plus), MIX2S (Snapdragon 845), Xiaomi Pad 5 Pro (Snapdragon 870) and Redmi Note 12 (Snapdragon 7+ Gen 2) Turbo

libxfce4ui: add cpu-info fallback

---

scripts/build/setup/termux_setup_no_integrated_as.sh
scripts/build/termux_step_setup_toolchain.sh
scripts/build/toolchain/termux_setup_toolchain_23c.sh

Mainly to fix issues and follow up of #20312
```
clang-12: error: unsupported option '--start-no-unused-arguments'
clang-12: error: unsupported option '--end-no-unused-arguments'
```

scripts: NDK r23c clean up

---

packages/neovim/build.sh
packages/tree-sitter-markdown/build.sh

Add markdown parser.
Used by Neovim for inline "hover" documentation.
The build script is for the most part copied from `tree-sitter-vimdoc`.

addpkg(main/tree-sitter-markdown): 0.2.3

---

x11-packages/nitrogen/build.sh

Set `-std=c++14` in `CXXFLAGS` when building `nitrogen` to fix the build error:
> error: no member named bind2nd in namespace std
due to `bind2nd` being removed in C++17.

fix(x11/nitrogen): Fix build with current toolchain

---

x11-packages/synaptic/build.sh

Set `-std=c++14` in `CXXFLAGS` when building `synaptic` to fix the build error:
> error: no template named binary_function
due to `binary_function` being removed in C++17.

fix(x11/synaptic): Fix build with current toolchain

---

packages/zsh/build.sh
packages/zsh/etc-zshrc

Zsh already automatically runs `zsh-newuser-install` as part of the `newuser` module. Running it manually in the system `zshrc` caused it to run twice.
Note that `zsh-newuser-install` automatically exits if the terminal's size is less than `72x15`, so it might not run on the default Termux terminal size.

fix(main/zsh): Fix zsh-newuser-install being run twice

---

x11-packages/mkvtoolnix/build.sh

Currently the build of `mkvtoolnix` fails with:
> checking for qmake6... using supplied /data/data/com.termux/files/usr/lib/qt6/bin/qmake6
> no: not all of the required Qt6 modules were found (needed: core )
> configure: error: The Qt library version >= 6.2.0 is required for building MKVToolNix.
Don't know much about the Qt build system, is this change of `qmake6` to `host-qmake6` the correct fix here (ping @Biswa96)?

fix(x11/mkvtoolnix): Fix build by using `host-qmake6`

---

packages/nodejs/build.sh
packages/nodejs/node.gyp.patch

This PR is to just let @fornwall know that I've started working on the new release so that he doesn't duplicate the effort. I'll try to get the LTS version on track soon after

bump(main/nodejs): 22.4.0

---

x11-packages/kf6-kwindowsystem/build.sh

This fixes the following warning while running lxqt.
kf.windowsystem: Could not find any platform plugin.
The cmake options move plugin files from lib/plugins to lib/qt6/plugins
and qml files from lib/qml to lib/qt6/qml. The new paths are set by
TERMUX_PKG_EXTRA_CONFIGURE_ARGS in qt6-qtbase.

fix(x11/kf6-kwindowsystem): Fix qml and plugins directory

---

packages/fzf/build.sh

New tags will have `v` prefix.
https://github.com/junegunn/fzf/commit/9e92b6f11e0f59272de410f56493893334071e6e
Fixes #20799

bump(main/fzf): 0.54.0

---

packages/gdb/build.sh

zlib is already in the dependency list but it is not used.

enhance(main/gdb): Build with system zlib package

---

x11-packages/virglrenderer-android/build.sh

fix(x11/virglrenderer-android): Use _LIBEPOXY_VERSION [no ci]

---

scripts/updates/utils/termux_pkg_upgrade_version.sh

If we're testing, with an expectation of a value being NULL.
We clearly don't want `set -u` to end the check if the variable is unset.
That is already the behavior for `$TERMUX_PKG_UPGRADE_VERSION_DRY_RUN`.
This commit just fixes it for the `$TERMUX_PKG_UPDATE_VERSION_REGEXP`, `$TERMUX_PKG_UPDATE_VERSION_SED_REGEXP`, and `$LATEST_VERSION` checks.
https://github.com/termux/termux-packages/blob/d44e30dd91c4d801846800a0ed6cc43f5a880e4d/scripts/updates/utils/termux_pkg_upgrade_version.sh#L60
This closes #20839, where I specifically unset `TERMUX_PKG_UPDATE_VERSION_REGEXP` in `taplo`'s auto update function before calling `termux_pkg_upgrade_version` to avoid re-filtering the version.

fix(scripts/termux_pkg_upgrade_version): allow NULL in NULL checks.

---

scripts/build/termux_step_install_license.sh

Part of:
- #20858
This PR is a total refactor of `scripts/build/termux_step_install_license.sh`.
The goal was to eliminate shellcheck warnings and reduce jank.

chore(scripts/termux_step_install_license): total refactor

---

.github/workflows/packages.yml

I still think of removing this and replace with an emulator set up. Until then put this as a stopgap for Docker Pull Rate Limit error.

ci(packages): continue regardless dbhi/qus fails

---

packages/python-msgpack/build.sh

This change fixes metadata directory from UNKNOWN-0.0.0.dist-info to msgpack-1.0.8.dist-info.

fix(main/python-msgpack): Fix metadata directory by using pyproject.toml to build

---

packages/libandroid-complex-math/build.sh

Fix undefined symbols error
```
ERROR: ./lib/libandroid-complex-math.so contains undefined symbols:
4: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND csqrtl
5: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND atan2l
6: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND logl
7: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND coshl
8: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND sincosl
9: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND sinhl
11: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND expl
12: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cabsf
13: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND logf
14: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND atan2f
15: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cabsl
16: 0000000000000000 …
```

fix(main/libandroid-complex-math): link with libm

---

packages/lua-language-server/build.sh

`lua-language-server` gets the version for its `--version` option from its `changelog.md` file.
https://github.com/LuaLS/lua-language-server/blob/7d06e5573c8188e61516e987b0d796a40f718b05/script/version.lua#L3-L18
We can simplify `termux_step_make_install()` for it by including the changelog in the package so `--version` can work as intended by the upstream project.
<h1><em></em></h1> 
Similar to:
- #20929
I have also updated the maintainer field.

chore(main/lua-language-server): fix `--version` option

---

packages/graphicsmagick/build.sh
packages/graphicsmagick/coders-url.c.patch

This commit fixes the following compiler error.
url.c:209:11: error: call to undeclared function 'xmlNanoFTPInit';
ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
xmlNanoFTPInit();
^

fix(main/graphicsmagick): Fix building with latest libxml2

---

packages/bsd-finger/build.sh

Part of #20966
Switch to Debian source mirror.
Same approach as `netcat-openbsd`.
https://github.com/termux/termux-packages/blob/806b4241f24a91edbe0a0bb166d80ada69d2fbd2/packages/netcat-openbsd/build.sh#L1-L6
(Sidenote, what's going on with `netcat-openbsd`'s version?)

chore(main/bsd-finger): fix dead source and homepage links

---

packages/gpgme/build.sh

This fixes the following warning with static library build.
*** Warning: Linking the shared library libgpgmepp.la against the
*** static library /path/to/libclang_rt.builtins-aarch64-android.a is not portable!

fix(main/gpgme): Update upstream source link and fix static library build

---

packages/libhangul/build.sh

This fixes the following error.
ERROR: ./lib/libhangul.so contains undefined symbols:
25: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND glob
26: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND globfree

fix(main/libhangul): Fix undefined symbols error with glob and globfree

---

packages/rust/build.sh
packages/rust/config.toml
packages/rust/rust-docs.subpackage.sh
scripts/build/setup/termux_setup_rust.sh
scripts/build/termux_step_massage.sh
scripts/setup-termux.sh

Close #20970
* Restore rust-docs path back to `share/doc/rust` from `share/doc/docs` since rust 1.78.0.
* Running `./build-package.sh -I -f rust` on device should not break Termux installation and able to build rust on device. But I doubt there's any benefit to this. There may be unsolved linking issue building on old 32bit arm device but I will not fix it as any "real" 32bit arm device is not able to build with limited RAM and storage.

rust: restore rust-docs path and support on device build

---

packages/libfann/build.sh

This fixes the errors as following.
ERROR: ./lib/libfann.so contains undefined symbols:
13: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND exp
14: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND sin
15: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cos
22: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND pow
31: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND log

fix(main/libfann): Fix undefined symbols error with math functions

---

packages/libgnt/build.sh

This fixes the following error.
/bin/sh: 1: /data/data/com.termux/files/usr/bin/glib-genmarshal: not found

fix(main/libgnt): Fix building with glib-cross for cross compilation

---

x11-packages/pcsx-rearmed/build.sh
x11-packages/pcsx-rearmed/libpicofe_menu.c.patch
x11-packages/pcsx-rearmed/libpicofe_plat.c.patch
x11-packages/pcsx-rearmed/libpicofe_plat.h.patch
x11-packages/pcsx-rearmed/menu.c.patch

00c802bcfb139c92615c4c716cdff97d0639cfc1: `-Oz` crashes the program;
6d1c9128e49cd0f75eed56ccb546ff589e425868: minimal optimizations and parameterizations.

Revise package: pcsx-rearmed

---

packages/libhtmlcxx/build.sh

This fixes the following compiler error.
error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
and the linker warning
*** Warning: Linking the shared library libhtmlcxx.la against the
*** static library libclang_rt.builtins-x86_64-android.a is not portable!

fix(main/libhtmlcxx): Fix compiler and linker error

---

packages/eltclsh/build.sh

I'm still getting the following symbol error.
```styl
ERROR: ./lib/libeltclsh.so contains undefined symbols:
28: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND mblen
```
Should be a simple missing `-l<libname>`, just don't know what library contains `mblen`.

chore(main/eltclsh): conform to #20867 changes

---

packages/moria/build.sh

and redo postinst/prerm scripts as HEREDOCs
Part of
- #20966

fix(main/moria): specify license file

---

packages/redis/build.sh

Redis 7.4.0 introduces the new restrictively
RSALv2/SSPLv1 "source available" license model.
Until a final determination is made on it,
freeze Redis at the last BSD licensed version 7.2.5
This reverts commit f91c3b5b4a526fe585cb6407e2f4e18c4964708c.

revert(main/redis): freeze version at 7.2.5 pending replacement

---

packages/taplo/build.sh

bump(main/taplo): 0.9.3 - also don't build with `--locked`

---

scripts/build/termux_step_install_license.sh
x11-packages/gtkwave/build.sh

Move counter advance to the end of the while loop.
This fixes a logic error where the counter wouldn't advance if the first license was "generic"
and the second one was author specific.
This would cause `cp` to attempt to copy through the dangling symlink to the generic license
in `termux-licenses` which fails and dies.
I also moved the `$TERMUX_PACKAGE_LIBRARY` check into a `case` which should make it easier to follow.

fix(scripts/termux_step_install_license): fix logic error

---

packages/wasmedge/build.sh

* before: wasmedge version 0.0.0-unreleased
* after: wasmedge version 0.14.0
This uses source tarball from release assets to get VERSION file for proper version number.

fix(main/wasmedge): Fix version number output

---

root-packages/nexttrace/build.sh

`nexttrace-enhanced` was renamed to `nexttrace`, and the `enhanced` version has been removed from the original repository.

fix(root/nexttrace): version info

---

packages/cmus/build.sh

Support native audio on Android 8.1 and later.
- Better battery life.
- Configurable latency.
- Configurable capture policy.
- Configurable sharing mode.
- Configurable spatialization.
- Full multi-channel audio support.
- Supports `pause_on_output_change`.
https://github.com/cmus/cmus/pull/1346
https://github.com/cmus/cmus/commit/3880d9df1c03e8931a59a3dd22daade8457d1b43

enhance(main/cmus): Add AAudio output plugin

---

packages/pueue/build.sh

This fixes some issues with the `pueue` package I submitted in [addpkg(main/pueue): a command-line task management tool by stevenxxiu · Pull Request #20959 · termux/termux-packages](https://github.com/termux/termux-packages/pull/20959):
- Fix typo in *Bash* completions dir. I copied that from the `starship` package <https://github.com/termux/termux-packages/blob/df4b49c63779c74411395a396566b7ebc41fed36/packages/starship/build.sh#L38>. You might want to fix this up. I thought it's nicer to not fix that in the same PR, as it's a separate package.
- Run `post_install` after reinstalling or upgrading with *Pacman*, so the completions are generated. I tested that this works.

enhance(main/pueue)

---

packages/7zip/build.sh

This PR fixes the `7zip` package build by explicitly specifying the license files.
I also took the opportunity to bump 7zip to the newly released `24.08`.
- `DOC/License.txt` contains the text of the BSD 3 and 2 Clause licenses, applicable to LZFSE/ZSTD, and XXH64 respectively.
As well as the per file breakdown of which licenses apply to what parts of the source code.
- `DOC/copying.txt` is the text of the LGPL-2.1 license.
- `DOC/unRarLicense.txt` is not included, as we build 7zip with `DISABLE_RAR=1`.
- `TERMUX_PKG_SRCURL` and `TERMUX_PKG_SHA256` have been reformated in accordance with;
#20645

bump(main/7zip): 24.08

---

packages/fcp/build.sh
packages/fcp/rust-1.80-compat.patch

Apply patch from https://github.com/Svetlitski/fcp/pull/42 to fix build error noted in (#21130) (there hasn't been an fcp release in 3 years, so a wait for an upstream release might be long).

fix(main/fcp): Fix building with current rust 1.80

---

packages/magic-wormhole-rs/build.sh
packages/magic-wormhole-rs/remove-clipboard.patch

Fixes the current rust 1.80 build failure (#21130) as the time crate dependency has been updated.

bump(main/magic-wormhole-rs): 0.7.1

---

packages/ruby/build.sh

Need for this was noticed when building weechat: https://github.com/termux/termux-packages/actions/runs/10409120894/job/28828010345

revbump(main/ruby): Drop OpenMP build options

---

packages/sc-im/Makefile.patch
packages/sc-im/build.sh
packages/sc-im/src-interp.c.patch

* Use LUA_PKGNAME to select lua version instead of patching makefile.
That option for make was added in the following upstream commit
https://github.com/andmarti1424/sc-im/commit/5c2e0a19e26a99e899751f72f9715fd35f3131eb
* Update lua dependency to lua5.4.
* Fix the following compiler error with interp.c and modified langinfo.h.
langinfo.h:107:1: error: function definition is not allowed here
Fixes #21146

bump(main/sc-im): 0.8.4

---

scripts/build/termux_step_massage.sh

This PR modify the termux_step_massage script to make sure that the local variable LIBOMP_SO_SYMBOLS is set. 
This fixes https://github.com/termux/termux-packages/issues/21155 .

termux_step_massage: ensure LIBOMP_SO_SYMBOLS is set

---

ndk-patches/27/time.h.patch
packages/coreutils/build.sh
scripts/build/termux_step_setup_toolchain.sh

toolchain: add API guard for `timezone_t`

---

x11-packages/poppler-qt/build.sh

This helps to avoid heuristic exclusion of common files based on name. That logic was added in e1e2634adcf2e091b7f5706ade091dea54ddd263 commit.

chore(x11/poppler-qt): Use cmake to install files

---

packages/uv/0001-sys-info-replace-index-with-strchr.diff
packages/uv/build.sh

addpkg(main/uv): 0.3.2

---

packages/dpkg/build.sh
packages/dpkg/configure.diff

This fixes building dpkg when old tarball are removed in https://mirrors.kernel.org/debian/pool/main/d/dpkg/

chore(main/dpkg): Use upstream git repository instead of tarball from mirror

---

packages/silicon/build.sh
packages/silicon/bump-time-crate.patch

Fixes build failure noted in #21130.

fix(main/silicon): Update time crate for rust 1.80 compatibility

---

x11-packages/xcb-util-image/build.sh

chore(x11/xcb-util-image): link against `libandroid-shmem` explicitly

---

packages/boost/build.sh
packages/boost/phoenix-linking-issue.patch

I encountered linking errors with `boost` as I am bringing libreoffice deps to TUR, including a package called `libetonyek` which depends on `boost`. The error prompt is `ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg1`. After some investigation, the errors are fixed in `boost` 1.86.0 with this commit https://github.com/boostorg/phoenix/commit/665047aac26ad4d96b266d87504b3a88ad21b37e. These github build actions shows that the patch fixes the problem of building the libreoffice dep `libetonyek`: [without patch](https://github.com/knyipab/termux-packages/actions/runs/10647080259) vs [with patch](https://github.com/knyipab/termux-packages/actions/runs/10647083466). 
Please consider taking this upstream patch. Or bump the package if the dev may wish to. Thank you!

boost: apply upstream patch for  phoenix symbols

---

packages/monolith/build.sh

Build failed in dd30194ca176463e250fbb035b2daa1f75aa0274 commit with i686 arch. CI log https://github.com/termux/termux-packages/actions/runs/10677533883/job/29592861248

fix(main/monolith): Fix linker error for i686 build

---

scripts/build/setup/termux_setup_meson.sh

Tested with a few packages: glib, gstreamer, libwayland, python-numpy and kitty.
Reference: [Meson 1.5 reles notes](https://mesonbuild.com/Release-notes-for-1-5-0.html)

bump(scripts/setup-meson): Update meson from 1.4.0 to 1.5.1

---

scripts/setup-ubuntu.sh

In both ubuntu 22.04 and 24.04 the `openjdk-17` and `openjdk-21` packages can be installed without adding this ppa, so remove it to simplify things and prepare for updating to ubuntu 24.04.

scripts(setup-ubuntu.sh): Remove openjdk ppa

---

scripts/Dockerfile

Fix the following warning when building the docker image:
>  1 warning found (use docker --debug to expand):
> - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 10)

fix(scripts/Dockerfile): Avoid legacy key-value format

---

scripts/setup-ubuntu.sh

A step in cleaning up the ubuntu setup and preparing for updating to ubuntu 24.04.
Note that there is no `python3.9` package actually installed in the builder image even before this change - what was actually happening is this:
> $ sudo env DEBIAN_FRONTEND=noninteractive apt-get install python3.9
> Note, selecting 'python3.9-llfuse' for regex 'python3.9'
> Note, selecting 'python3-llfuse' instead of 'python3.9-llfuse'

scripts(setup-ubuntu.sh): Remove python3.9

---

x11-packages/qt5-qtwebengine/build.sh

Fixes two build errors noticed in #21130:
- 5.15.15 not being compatible with current clang
- Licence file not found

bump(x11/qt5-qtwebengine): 5.15.17

---

packages/yazi/Cargo.lock.patch
packages/yazi/build.sh

See https://github.com/bytecodealliance/rustix/pull/1147
Fixes #21364

fix(main/yazi): Update rustix to get TCGETS fallback

---

packages/alist/build.sh

Fixes the build as the previous version 3.37.0 seems to have been removed - https://github.com/alist-org/alist/releases.

bump(main/alist): 3.37.1

---

packages/rust/build.sh

Should be a lot smoother compared to the 1.80 problems with the time crate breakages (see
https://internals.rust-lang.org/t/type-inference-breakage-in-1-80-has-not-been-handled-well/21374 about that).
Tested building a few rust packages without problems: distant, ripgrep, fd, crowbook, tectonic, fcp, kak-lsp, magic-wormhole-rs, miniserve and typst.

bump(main/rust): 1.81.0

---

scripts/build/termux_step_massage.sh
scripts/build/termux_step_setup_variables.sh

Some package (like [codon](https://github.com/termux-user-repository/tur/pull/1166)) may ship its own `libomp.so`, so add an option to skip this check

scripts: add an option to skip the openmp check

---

packages/ncurses/build.sh
packages/ncurses/ncurses-tinfo-lib_setup.c.patch
packages/ncurses/ncurses-tinfo-tinfo_driver.c.patch

Also bump `kitty` and `alacritty` terminfo entries to latest releases.

bump(main/ncurses): 6.5.20240831

---

packages/python-msgpack/build.sh

Use source tarball from pypi because the GitHub generated tarball does not have _cmsgpack.c file. Also, upstream suggests to use sdist or manually cythoize.
https://github.com/msgpack/msgpack-python/commit/0b1c47b06b55d91c00c9f7153c4a9440ea878886
Fixes #21419

bump(main/python-msgpack): 1.1.0

---

packages/cloneit/build.sh

This updates away from the previous openssl-1.1 dependency.

bump(main/cloneit): 2024.07.28

---

disabled-packages/libart-lgpl/build.sh
disabled-packages/libglade/build.sh
disabled-packages/libglade/libglade-2.0.1-nowarning.patch
disabled-packages/libgnomecanvas/build.sh
disabled-packages/obconf/build.sh
disabled-packages/obconf/obconf-2.0.4-clang16.patch
disabled-packages/xournal/build.sh
disabled-packages/xournal/src-ttsubset-ttcr.c.patch
disabled-packages/xournal/xo-shapes.c.patch
disabled-packages/xournal/xournal-0.4.8-c99-fix.patch

Add back recently removed packages (#21409 and #21410) to `disabled-packages/`:
- libart-lgpg
- libglade
- libgnomecanvas
- obconf
- xournal

chore(disabled-packages): Add recently removed packages to disabled

---

scripts/build/setup/termux_setup_nodejs.sh

Will allow us to fix the `seanime` build error in c66a06a86917e7c5d70b7f00c12c5ee50529d93b:
> You are using Node.js 18.16.1. For Next.js, Node.js version >= v18.17.0 is required.
Will revbump `seanime` as a follow up change.
Note that node.js has two current LTS versions (see https://nodejs.org/en/download/package-manager), `20.17.0` and `18.20.4`. Might as well go for the later one (which matches what we have in our `nodejs-lts` package).

bump(scripts/setup-nodejs): Update nodejs from 18.16.1 to 20.17.0

---

packages/unicode-data/build.sh

Support for SHA-256 array was added in f6de8fd3646eee51527c9da2395f98c0bee4fc87 commit.

chore(main/unicode-data): Enable auto update

---

packages/ghostscript/build.sh

Refer:
#21130
https://github.com/llvm/llvm-project/issues/74361

revbump(main/ghostscript): NDK r27 build fix

---

packages/htslib/build.sh

Build package in source directory to mitigate the following compiler error.
htslib/src/test/test_khash.c:43:10: fatal error: 'htslib/khash.h' file not found
Fixes #21455

bump(main/htslib): 1.21

---

scripts/setup-ubuntu.sh

Removing host `python2` (which is currently pulled in as a dependency of `python-setuptools`) is a step towards updating to ubuntu 24.04, which does not have a `python2` package out of the box.
While we could always add a third-party `python2` package, it's probably best to start out with checking if we can proceed without one.
Note that this is a separate issue then removing the `python2` termux package (which should eventually be done, but until that it builds fine without a preinstalled host `python2`).
- ~~[libduktape](https://github.com/termux/termux-packages/blob/master/packages/libduktape/build.sh) uses host `python2`~~ (fixed in #21407).
- ~~[libglade](https://github.com/termux/termux-packages/blob/master/x11-packages/libglade/build.sh) requires host `python2` to build~~ (removed …

scripts(setup-ubuntu.sh): Remove host python2

---

packages/openssh/build.sh
packages/openssh/sshd.c.patch

Regenerated `sshd.c.patch` and set a maintainer.
Looks like what stopped `sshd.c.patch` from applying was the [newly added `&& !inetd_flag` on line 1351](https://github.com/openssh/openssh-portable/blob/53a80baaebda180f46e6e8571f3ff800e1f5c496/sshd.c#L1351).
Introduced in [`openssh/openssh-portable@c21c3a2`](https://github.com/openssh/openssh-portable/commit/c21c3a2419bbc1c59cb1a16ea356e703e99a90d9)

bump(main/openssh): 9.9p1

---

.github/workflows/packages.yml
scripts/Dockerfile
scripts/build/setup/termux_setup_swift.sh
scripts/setup-ubuntu.sh

Points of interest from the ubuntu `22.04` -> `24.04` update:
- System `python3` is now `3.12`, compared to `3.10` previously.
- As our `python` package is version `3.11` and requires a host python of that version, we now use the [deadsnakes ppa](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) to install python `3.11`, as upstream ubuntu no longer packages that python version.
I've pushed a [prebuilt image](https://hub.docker.com/r/fredrikfornwall/termux-package-builder-ubuntu-24.04) of this to docker hub, which can be tested out with:
```sh
CONTAINER_NAME=termux-builder-ubuntu-24.04 TERMUX_BUILDER_IMAGE_NAME=fredrikfornwall/termux-package-builder-ubuntu-24.04 ./scripts/run-docker.sh
```
To build and use the docker image locally with this branch checked out instead:
```sh
(cd …
```

chore(package-builder): Update to ubuntu 24.04

---

scripts/Dockerfile
scripts/setup-ubuntu.sh

Fixes the `Free additional disk space` CI step, which calls `setup-ubuntu.sh` without having the setup steps in the `Dockerfile` done.

fix(scripts): Move deadsnakes PPA setup to setup-ubuntu

---

.github/workflows/package_updates.yml
.github/workflows/packages.yml

Fixes the below errors when trying to build big packages after switching to ubuntu 24.04:
> E: Unable to locate package google-cloud-cli
> E: Unable to locate package powershell

fix(ci/packages): Do not try to uninstall packages no longer present

---

packages/jp2a/build.sh

* Change home page URL which is not related to the upstream project.
* Add new required dependencies.
* Fix bash completion directory.
Fixes #21547

bump(main/jp2a): 1.3.0

---

x11-packages/mlt/0001-rtaudio-soundcard.h.patch
x11-packages/mlt/0002-rtaudio-remove-pthread_testcancel.patch
x11-packages/mlt/0003-rtaudio-remove-pthread_attr_setinheritsched.patch
x11-packages/mlt/0004-fhs-path.patch
x11-packages/mlt/32-bit-symbol.diff
x11-packages/mlt/build.sh
x11-packages/shotcut/0001-lib-name.patch
x11-packages/shotcut/build.sh

Draft PR. currently the app mostly works ~well but cannot output video results, perhaps there are problems with QProcess, see #20354 .~ [fixed]
Other things to note:
* [fixed] ~32-bit arch does not build (see error log, related to `qint64` type)~
* [fixed] ~GPU mode requires  PR #20352 , related to #20351~
* [optional] rtaudio (mlt optional deps) needs ALSA and jack API, we may need a functioning pipewire, related to #20316 
* [optional: someone may try] `opencv` cannot be included as `mlt`build deps (which is done by Archlinux), prompting some compilation error related to `QPrivate` when building `shotcut`

new packages: shotcut, mlt and their deps

---

scripts/setup-android-sdk.sh

In the `ubuntu-24.04` runner image android-35 is preinstalled, not android-33. Syncing with that image makes building packages work when they are built outside of docker due to being built in the same PR as a package listed in `scripts/big-pkgs.list`.
This will be followed by a bump to reference android-35 in `aapt`.

scripts(toolchain): Update from android-33 to android-35

---

packages/aapt/build.sh

Follow up to #21561 - allows the `aapt` package to build both in Docker and when built directly on the `ubuntu-24.04` CI image, due to being touched in the same PR as a big package.

chore(main/aapt): Update from android-33 to android-35

---

packages/rsgain/build.sh

See
https://github.com/complexlogic/rsgain/blob/master/docs/BUILDING.md?plain=1#L21-L26C10:
> The features that rsgain uses from the fmt library have been integrated into the C++20 and C++23 standards, specifically the `<format>` and `<print>` headers. The standard library implementations are planned to completely replace rsgain's fmt dependency in the future. To support the transition, rsgain can use either the fmt library or standard library, depending on platform:
> - MSVC has full support in the standard library since version 19.37. The fmt library has been dropped from the Windows version in favor of the standard library implementation
> - GCC (libstdc++) has full support in the standard library since version 14. Pass `-DUSE_STD_FORMAT=ON` to `cmake` to use the standard library …

chore(main/rsgain): Use libc++ instead of the fmt library

---

x11-packages/rnote/build.sh
x11-packages/rnote/custom-gettext-rs-crate-Cargo.toml.patch
x11-packages/rnote/disable-cargo-command-meson.build.patch
x11-packages/rnote/fix-compile-gresource.patch
x11-packages/rnote/gettext-rs-crate.diff
x11-packages/rnote/no-debug-Cargo.toml.patch
x11-packages/rnote/remove-rodio-audio.patch

Fixes https://github.com/termux/termux-packages/issues/17655
Thanks @Biswa96 @TomJo2000 @Doublonmousse @romanovj @askorbinovaya-kislota and everyone else for your help

addpkg(x11/rnote): 0.11.0

---

packages/coreutils/build.sh
packages/libandroid-selinux/Makefile-android
packages/libandroid-selinux/build.sh
packages/libandroid-selinux/termux-build.patch
packages/libandroid-selinux/termux_build.h

This PR introduces a new library (libandroid-selinux) for basic SELinux functionality.
Along with that, I've also added SELinux support to coreutils.
`chcon` and `ls -Z` seems to be working.
I still haven't done a thorough testing just yet so it might still have a few catch, but that should not break existing functionalities.

libselinux and SELinux support for coreutils

---

packages/simde/build.sh

Used by newer `kitty` versions (#21595). Also seems to have some momentum and might be useful in general when building some code bases on devices:
- https://github.com/simd-everywhere/simde
- https://wiki.debian.org/SIMDEverywhere

addpkg(main/simde): Implementations of SIMD instructions for all systems

---

scripts/build/termux_step_get_dependencies_python.sh

so termux python can work with them

termux_step_get_dependencies_python.sh: adding path to python-crossenv modules

---

x11-packages/qt6-qt5compat/build.sh
x11-packages/qt6-qt5compat/qt6-qt5compat-cross-tools.subpackage.sh

Grateful for considering to merge this. 
I am trying to build krita with all deps ready, but this `qt6-qt5compat` cannot be built together in one PR, cuz other krita deps (of deps) requires `qt5-qtbase` which messes up the build process of `qt6-qt5compat`. Merging this PR is needed in order to proceed to building krita (though using krita git qt6 version. Cuz termux's qt5 doesn't support opengl and won't build). 
Deps and build deps take ref to  https://archlinux.org/packages/extra/x86_64/qt6-5compat/ and also verified to be sufficient by looking at its cmakelists.txt

new package: qt6-qt5compat

---

packages/seanime/build.sh

closes: https://github.com/termux/termux-packages/issues/21458

fix(main/seanime): web-ui issue

---

packages/grafana/build.sh
packages/grafana/go-mod.patch

Fixes a build error with the current grafana and golang version:
> github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
> ../../../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
> ../../../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
Fixes #21183.

bump(main/grafana): 11.2.0

---

x11-packages/qbittorrent/build.sh
x11-packages/qbittorrent/qbittorrent-nox.subpackage.sh

Adds `python` as a dependency.
It is used by the search plugin system.
- I updated the description to specify Qt6, since Qt5 has been deprecated by qBittorrent.
- `TERMUX_PKG_FORCE_CMAKE=true` is no longer necessary as support for the `qmake` and `autotools` build systems was also dropped.
- https://github.com/qbittorrent/qBittorrent/blob/release-5.0.0/Changelog#L83-L85
- I also sorted the `TERMUX_PKG_DEPENDS` and `TERMUX_PKG_EXTRA_CONFIGURE_ARGS`

enhance(x11/qbittorrent{,-nox}): suggest `python`

---

packages/ncurses/build.sh

Build `ncurses` with `--disable-opaque-panel` which is necessary to build at least `libgnt`.

fix(main/ncurses): Build with --disable-opaque-panel

---

packages/rust/0006-llvm-19.patch
packages/rust/build.sh

revbump(main/rust): after LLVM 19 update

---

packages/nushell/build.sh

Clipboard integration historically hasn't worked on Termux anyway, so cargo's features were chosen to explicitly opt into a feature that included all default features except clipboard support.
9f0a6bee57dd96fd608ffefb166686111d4682d8 upgraded to 0.98.0, which removed support for clipboard integration, and thus the need for that feature flag went away. Unfortunately, it removed the `default-no-clipboard` feature, but not the `no-default-features` flag, so the resulting binary is missing a lot of stuff, like plug-in support, sqlite, and others.
This fixes that by removing the `--no-default-features` flag.

fix(main/nushell): Build with default features

---

packages/python-contourpy/build.sh
packages/python-onnxruntime/build.sh
packages/python-scipy/build.sh
x11-packages/python-torchaudio/build.sh
x11-packages/python-torchvision/build.sh

Revbump some python packages after python 3.12 (#18078).
Let's await the merge to build and make some general sanity checks before starting revbumping python revdeps.

revbump(main/python-{contourpy,onnxruntime,scipy},x11/python-torch{audio,vision})

---

packages/python-skia-pathops/build.sh
scripts/build/setup/termux_setup_gn.sh

Also update `gn` version in `termux_setup_gn` (which is currently only used in `python-skia-pathops`) to latest version to fix setting it up under ubuntu 24.04.

revbump(main/python-skia-pathops): After python 3.12

---

packages/libcurl/build.sh

Enable support for options like `--dns-servers` or `--dns-ipv4-addr`
Closes #21630

libcurl: enable c-ares support

---

scripts/setup-ubuntu.sh

After switching to python 3.12 we no longer need host python 3.11.

scripts(setup-ubuntu.sh): Remove host python3.11

---

scripts/lint-packages.sh

At some point, we can't be expected to still use API level 24, 25, 26, 27, 28 indefinitely. So remove the upper limit.

scripts(lint-packages): remove TERMUX_PKG_API_LEVEL upper limit

---

packages/ncdu/build.sh
packages/ncdu2/build.sh
packages/ncdu2/fix-hardcoded-paths.patch
packages/ncdu2/fix-progname.patch

`ncdu` now depends on `zstd` as of version 2.6[^1]
I've taken the opportunity to refactor the `post_get_source` step.
A minor patch to the Makefile is also required to ensure it respected the set `${STRIP}` program.
[^1]: upstream changelog https://g.blicky.net/ncdu.git/tree/ChangeLog?h=v2.6#n6

bump(main/ncdu2): 2.6

---

packages/glib/build.sh

Fixes #20070
Fixes #20447
This PR lets us build glib without downloading prebuilt `gobject-introspection` dependency
```
./build-package.sh glib
```

chore(main/glib): completely remove gobject-introspection dependency

---

packages/zola/build.sh

A fast static site generator in a single binary with everything built-in.
https://www.getzola.org/

new package: zola

---

x11-packages/webkit2gtk-4.1/build.sh
x11-packages/webkitgtk-6.0/build.sh

webkit2gtk-4.1,webkitgtk-6.0: remove workaround for g-ir-scanner

---

x11-packages/fcitx5-configtool/build.sh
x11-packages/fcitx5-qt/build.sh

The manual copying from `$TERMUX_PREFIX/opt/qt6/cross/lib/qt6/plugins/platforminputcontexts` to `$TERMUX_PREFIX/lib/qt6/plugins/platforminputcontexts` should be fixed in a more central place (perhaps in the `qt6-qtbase` package)? Had to do the same thing in #21816.

chore(x11/fcitx5-{configtool,qt}): Switch to Qt6

---

packages/inxi/build.sh

Project has moved from GitHub to Codeberg.
Now housed at: https://codeberg.org/smxi/inxi

bump(main/inxi): 3.3.36-1

---

packages/termux-am/build.sh

Fixes gradle hanging sometimes, see:
- https://github.com/termux/termux-packages/issues/21130#issuecomment-2420689151
- https://github.com/gradle/gradle/issues/14961

fix(main/termux-am): Update gradle version to 8.10.2

---

x11-packages/xfce4-battery-plugin/build.sh
x11-packages/xfce4-battery-plugin/libacpi.c

Based on `termux-battery-status` from `termux-api`. Not perfect, with 30 sec delay by design, but at least available to users who is using DE in full screen. 
Showcase

addpkg(x11/xfce4-battery-plugin): 1.1.5

---

x11-packages/audacity/build.sh

`libsoundtouch` needs to be in the deps list of aduacity, otherwise it prompts this error on my device:   
```
CANNOT LINK EXECUTABLE "audacity": library "libSoundTouch.so" not found: needed by main executable
```

audacity: fix no libSoundTouch.so

---

x11-packages/fritzing/build.sh

A quick fix of the consequence of #21780 that making fritzing to prompt: 
```
CANNOT LINK EXECUTABLE "Fritzing": library "libquazip1-qt5.so" not found: needed by main executable
```

fritzing: fix libquazip1-qt5.so not found

---

packages/vulkan-tools/build.sh
packages/vulkan-tools/no-android.patch

Fix #21865
Partially revert 605d6a3888535cb655078debe318dc3beecf87ed, maybe it didn't happen that time 🤔
https://github.com/KhronosGroup/Vulkan-Tools/compare/v1.3.298...v1.3.299
`vkcube-wayland` is merged into `vkcube --wsi wayland`

bump(main/vulkan-tools): 1.3.299

---

.github/workflows/vagrant.yml
scripts/Vagrantfile

The lonely Vagrantfile didn't get any love and abandoned

ci(vagrant): add CI for scripts/Vagrantfile

---

x11-packages/mpv-x/build.sh
x11-packages/mpv-x/default-to-x11.patch

By default mpv chooses wrong video backend and shows this:
```
Error opening/initializing the selected video_out (--vo) device.
Video: no video
```
This patch fixes it.
I will merge it in 72 hours if no one minds.
Or anyone else can merge it earlier.

chore(x11/mpv): make X11 default backend

---

x11-packages/qt6-qtwebsockets/build.sh

Will be used for transitioning `nextcloud-client` from Qt5 to Qt6.

addpkg(x11/qt6-qtwebsockets)

---

packages/lesspipe/build.sh

Let people use `lesspipe` in Debian way (without `.sh` suffix).
Fixes #21389

enhancement(main/lesspipe): add symlink lesspipe -> lesspipe.sh

---

x11-packages/wine-stable/build.sh

Fixes #21926
Related to #21130

fix(x11/wine-stable): fix building after toolchain upgrade

---

x11-packages/ardour/build.sh

The package was auto-updated to `9.0-pre0`, but the package was never built since the build was cancelled: https://github.com/termux/termux-packages/commit/4f3395aed8f4739bbf269451f67c96385fe8ae4d
Switch version to 8.10 (so updating from 8.8 in the apt repository) and disable auto updates for now.

bump(x11/ardour): 8.10

---

x11-packages/opencv/build.sh

chore(x11/opencv): Switch to Qt6

---

packages/inetutils/build.sh
packages/inetutils/man-Makefile.am.patch
packages/inetutils/src-logger.patch

Also it fixes generating mans.
This project uses `help2man` which invokes `<prog> --help`, and this requires binaries built for host, since host can not launch bionic binaries.
I do not know why and how generating mans worked fine on CI before this commit. My attempt to invoke build with `termux-package-builder` failed.
Closes #1112.
It will be merged in 72 hours if no one minds or earlier if there will be 2+ approves.

fix(main/inetutils): make logger print to logcat instead of syslog

---

packages/python/build.sh

Mistakes were made, but it definitely makes time.tzset() available.

fix(main/python): Enable time.tzset()

---

x11-packages/alacritty/build.sh
x11-packages/kitty/build.sh

> [!IMPORTANT]
> **DO NOT MERGE THIS BEFORE #21949**
- This PR is going to follow up #21949
Since the `alacritty`, `foot` and `kitty` terminfo files shipped with `ncurses`
will no longer be pulled from hardcoded versions of their respective project.
Thus enabling safe auto-updating for them.

enhance(x11/{alacritty,kitty}): enable auto updates.

---

root-packages/runc/build.sh
root-packages/runc/fix_static_build.patch
root-packages/runc/stubs.c

After creating new namespace runc deadlocks in dlopen on android 14. Switching to static build so there is no problem with dl anymore. It include workaround for https://github.com/golang/go/issues/59942

enhance(root/runc): static build runc to avoid runtime linker deadlock

---

x11-packages/alacritty/0001-disable-clipboard.patch
x11-packages/alacritty/build.sh
x11-packages/alacritty/freetype-sys.diff
x11-packages/alacritty/glutin-treat-android-as-linux.diff
x11-packages/alacritty/winit-treat-android-as-linux.diff

Pain and patch drift.
resolves #21965

Bump alacritty: 0.14.0

---

packages/libx264/build.sh

Also revert 2b12322b66f80faeb4c31535049730d24930f9ae that causes build error on NDK r27 for i686:
```console
i686-linux-android-clang conftest.c -m32  -march=i686 -msse3 -mstackrealign -mfpmath=sse -fPIC -fstack-protector-strong -Oz -Wall -I. -I$(SRCPATH)     -m32 -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -fuse-ld=bfd -lm -o conftest
/usr/bin/ld.bfd: /home/builder/.termux-build/_cache/android-r27-api-24-v1/bin/../sysroot/usr/lib/i686-linux-android/24/libm.so: unable to initialize decompress status for section .debug_abbrev
/usr/bin/ld.bfd: /home/builder/.termux-build/_cache/android-r27-api-24-v1/bin/../sysroot/usr/lib/i686-linux-android/24/libm.so: unable to initialize decompress status …
```

bump(main/libx264): 0.164.3191

---

packages/libcurl/build.sh

For many users, enabling this feature will result in the inability to resolve DNS.
Closes #21727, Closes #21987

libcurl: disable c-ares support

---

packages/libgmp/build.sh

Fixes error 
```
checking C++ compiler aarch64-linux-android-clang++  -I/data/data/com.termux/files/usr/include  -fstack-protector-strong -Oz -L/data/data/com.termux/files/usr/lib... no, program does not run
configure: error: C++ compiler not available, see config.log for details
...
configure:10520: checking C++ compiler aarch64-linux-android-clang++  -I/data/data/com.termux/files/usr/include  -fstack-protector-strong -Oz -L/data/data/com.termux/files/usr/lib
Test compile:
configure:10534: aarch64-linux-android-clang++  -I/data/data/com.termux/files/usr/include  -fstack-protector-strong -Oz -L/data/data/com.termux/files/usr/lib conftest.cc >&5
configure:10537: $? = 0
configure:10541: ./a.out || ./b.out || ./a.exe || ./a_out.exe || ./conftest
CANNOT LINK EXECUTABLE "./a.out": library …
```

fix(main/libgmp): fix building with `build-all.sh`

---

packages/libmcrypt/build.sh

Fix for `error: call to undeclared library function 'memmove/calloc/malloc/memcpy/free/sprintf/etc.'` during running `build-all.sh` Probably it would be easier to add `-Wimplicit-function-declaration` to `CFLAGS`, but this solution feels more correct.
Related to #21130.
I will merge this in 36 hours if nobody minds or after it gets 2+ approves.

fix(main/libmcrypt): fix building with `./build-all.sh`

---

packages/libnfc/build.sh

Fixes the following error which appears during running `./build-all.sh`.
```
/home/builder/.termux-build/libnfc/src/examples/pn53x-tamashell.c:48:12: fatal error: 'readline/readline.h' file not found
48 | #  include <readline/readline.h>
|            ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
Since `libnfc.so` has only `libc.so` in `NEEDED` section I put `readline` to build dependency section.
Related to #21130.
I will merge it in 36 hours if nobody minds or after it gets 2+ approves.

fix(main/libnfc): fix building with `./build-all.sh`

---

packages/lighttpd/build.sh

Progress on https://github.com/termux/termux-packages/issues/21130
Fixes this error during build:
```
ld.lld: error: undefined symbol: posix_spawn_file_actions_init
>>> referenced by fdevent.c:495 (../src/src/fdevent.c:495)
>>>               src/test_mod.p/fdevent.c.o:(fdevent_fork_execve)
```
I tested this by using the docker container to cross-compile this package, then copying the .deb file to my aarch64 Android 10 device. I was able to successfully test the resulting program as a functioning web server at runtime after installing the .deb file by typing these commands (note: identical commands are also required for testing the previous build of the `lighttpd` package from the time of NDK revision 26 that's currently in the repositories, so I believe that my update most likely has …

fix(main/lighttpd): link with libandroid-spawn

---

packages/mesa/0000-disable-android-detection.patch
packages/mesa/0002-fix-for-getprogname.patch
packages/mesa/0004-do-not-check-xlocale.patch
packages/mesa/build.sh

Closes #20432.
I tested it with glmark2 (llvmpipe) and with vkcube (lavapipe + `-disable-dri3`) and they worked fine. 
I will merge it in 72 hours if no one minds or when it gets 2+ approves.

bump(main/mesa): 24.1.1

---

packages/macchina/build.sh

Use git repository in source URL to get ansi-to-tui and color-to-tui git submodules which were added in the following upstream commit. https://github.com/Macchina-CLI/macchina/commit/b9ea77335ed6b45734abb3371df258f521745bc1
Fixes #22021

bump(main/macchina): 6.3.1

---

packages/oleo/build.sh

Fixes error `#error "Cannot find a 32-bit data type"` from `gettext.h` while invoking `build-all.sh` in docker.
Related to #21130.
It is small fix so I will merge it in 12 hours if nobody minds or after it gets 2+ approves.

fix(main/oleo): fix building with `./build-all.sh` in docker.

---

packages/hilbish/build.sh
packages/hilbish/fix-hardcoded-path.patch

This update includes temporary fix for `golua` building (due to https://github.com/golang/go/issues/67401) and moves building rules from `Taskfile.yaml` to `build.sh`.
I installed it on device and it seems to work. I only entered hilbish shell with `hilbish` command and tried simple command `ls -la` and it worked fine.
I will merge this in 48 hours if nobody minds or after it gets 2+ approves.
Also it is related #21130 because currently building is impossible without `-checklinkname=0` (Go 1.23).

bump(main/hilbish): 2.3.2/2024.07.30

---

packages/luvi/0001-skip-script-compiling.patch
packages/luvi/build.sh

```
$ luvi . --
init.lua: cannot load incompatible bytecode
stack traceback:
[C]: at 0x61b25d8c94
[C]: in function 'require'
[string "return require('init')(...)"]:1: in main chunk
```
This PR also bumps the commit used because previously the commit it was referencing did not exist.

fix(main/luvi): fix incompatible bytecode error

---

scripts/setup-ubuntu.sh

Fixes #22060
There are also several other methods that could be used to fix this particular problem, but the way I have written this keeps it mostly similar to how fornwall originally wrote this update, without radically changing the method too much from his general idea.

scripts(setup-ubuntu.sh): Apply system libdirs and pkgconfig dirs to new pkgconf build

---

scripts/updates/utils/termux_pkg_upgrade_version.sh

* Clean before and after test build big package
* Unroll and decrease indentation for nested if else
Close #22017

enhance(termux_pkg_upgrade_version): some fixes

---

x11-packages/libqtxdg/build.sh

This fixes icon engine plugin directory.
Otherwise, it was installed in PREFIX/opt/qt6/cross/ directory.
* Fixes #20779
* After this change 👇

fix(x11/libqtxdg): Fix missing icons in lxqt

---

packages/grafana/build.sh

Build grafana with latest golang (1.23) now that the upstream issue https://github.com/grafana/grafana/pull/92055 has been released.
Fixes the last usage of TERMUX_PKG_GO_USE_OLDER=true, meaning that we are better prepared for the next future go 1.24 release.

chore(main/grafana): Build with latest golang

---

.github/workflows/packages.yml
packages/openjdk-21/build.sh

Fixes #22029.
I will merge it in 72 hours if no objections or after it gets 2+ approves.

chore(main/openjdk-21): add rule to fetch only stable tags during auto-update

---

packages/fossil/build.sh

This fixes the following runtime error with system sqlite.
Unsuitable SQLite version 3.46.1, must be at least 3.43.0
See also https://fossil-scm.org/forum/forumpost/fc348ef04f
* Fixes #22194

fix(main/fossil): Always use bundled sqlite to match required version

---

packages/gpgme/build.sh
packages/gpgme/gpgmepp.subpackage.sh

Workaround the following build error by disabling check for yat2m.
/bin/bash: line 3: /data/data/com.termux/files/usr/bin/yat2m: cannot execute binary file: Exec format error
* Fixes #22143

bump(main/gpgme): 1.24.0

---

root-packages/containerd/build.sh
root-packages/containerd/too_long_path.patch

docker fails to start containers on android 14 due to too long unix socket path. The limit is 108 characters.

[docker] fix too long path

---

packages/racket/build.sh
packages/racket/rktio_network.c.patch

racket: avoid `AI_V4MAPPED` on Android

---

packages/usql/build.sh
packages/usql/resvg-i686.diff

usql: bump to 0.19.4

---

packages/graphviz/build.sh

This replaces previous workaround in 1b126e9572100f9c2f92903c26c51bf7ef56aac8
commit because it produces the following warning.
Warning: Linking the shared library libcgraph.la against the
static library NDK/lib/clang/18/lib/linux/libclang_rt.builtins-aarch64-android.a is not portable!
The warning is explained here https://stackoverflow.com/a/8352756

chore(main/graphviz): Fix libtool warnings about linking with static library

---

packages/lit/build.sh
packages/luvit/build.sh

This PR changes the way how `lit` package and `luvit` package are built and installed.

fix(main/{lit,luvit}): don't embed luvi into {lit,luvit} bin

---

.github/workflows/package_updates.yml
scripts/bin/update-packages

on branches (except master) and forks
This should allow more people to check for potential auto update issues before submitting

ci(package_updates): allow dry run auto update check

---

.github/workflows/packages.yml

Close #21906 
Example: https://github.com/termux/termux-packages/actions?query=branch%3Adev%2Fissue-21906
I don't think there is more efficient way than this unless aptly api can query before forcefully upload which I can't make it to work...

ci(packages): get Packages.bz2 for server file check

---

packages/libimobiledevice/build.sh
packages/libusbmuxd/build.sh

Fix #21176
@Grimler91 @sylirre
Please clean up https://packages-cf.termux.dev/apt/termux-main/pool/main/u/usbmuxd/
since it was  moved to https://packages-cf.termux.dev/apt/termux-root/pool/stable/u/usbmuxd/

chore(main/libimobiledevice,libusbmuxd): drop depends usbmuxd

---

x11-packages/swaybg/0001-use-cross-wayland-scanner.patch
x11-packages/swaybg/0002-impl-shm_open.patch
x11-packages/swaybg/build.sh

Required for sway. Otherwise, the following warning is shown. [sway/config/output.c:1071] failed to execute 'swaybg' (background configuration probably not applied): No such file or directory

addpkg(x11/swaybg): 1.2.1

---

packages/vim-python/build.sh
packages/vim/build.sh
x11-packages/vim-gtk/build.sh

This PR does a couple of things:
- First and foremost, enable auto updates on every 50th patch for `vim`, `vim-python` and `vim-gtk`.
As part of some housekeeping I have also standardized the order of control variables between the three build scripts,
and done some general cleanup.
This isn't quite everything I have planned, but it's good enough for review.
I'd like to additionally:
- Split out `xxd` into a separate and independent subpackage so it can be installed as a standalone utility.
- and retire the `vim-python` package in favor of enabling `python` (vim-python), `lua` (VimL), and potentially `perl`, `ruby` and `tcl` (which are also supported) on both `vim` and `vim-gtk`.
- for `lua` I'd also like to switch over the interpreter 
But that can wait for another time.

enhance(main/vim{,-python}, x11/vim-gtk): enable auto updates

---

x11-packages/libfcft/build.sh
x11-packages/libfcft/doc-meson.build.patch

* Enable auto update and man pages.
* Remove unused dependencies.

bump(x11/libfcft): 3.1.9

---

packages/emscripten/build.sh

bump(main/emscripten): 3.1.71 -> 3.1.72

---

packages/predict/build.sh
packages/predict/disable-alsa.patch

fix(main/predict): prevent opportunistic inclusion of asoundlib.h

---

packages/ffmpeg/build.sh

Most distros have lib-rubberband compiled with ffmpeg. It will also make Key Change/Pitch Shifting work on https://github.com/vicwomg/pikaraoke where Termux support was recently added.

enhance(main/ffmpeg): Enable lib-rubberband

---

packages/ptunnel-ng/build.sh

Generate autotools files which are removed in this release.
* Fixes #22402

bump(main/ptunnel-ng): 1.43

---

scripts/setup-ubuntu.sh

As Termux has switched to Python 3.12, there is no need to install deadsnakes PPA

setup-ubuntu.sh: Remove deadsnakes PPA

---

packages/cmus/build.sh

This fixes buffer underruns on the Pixel 9 due to the default buffer capacity and burst size being much lower than other devices (e.g., 2886/962 frames at 48000 Hz on the P9 vs 6734/3367 on the P8).
I am one of the upstream maintainers and the author of the AAudio output plugin.
See cmus/cmus#1386. This PR is a cherry-pick of the first commit (the bugfix), but not the second (a feature to allow overriding the requested buffer capacity).

fix(main/cmus): ensure the AAudio buffer is at least 80ms

---

packages/rust/build.sh
scripts/build/setup/termux_setup_rust.sh
scripts/build/toolchain/termux_setup_toolchain_23c.sh
scripts/build/toolchain/termux_setup_toolchain_27c.sh

The gist of these PRs is to drop `RUSTFLAGS` that is poorly understood causing weird unexplainable build issues. We should use `CARGO_TARGET_*_RUSTFLAGS` instead. Also clean up to match other languages by init variables in setup_toolchain file. Note that `CFLAGS_{target}` is used by `cc` rust crate and not by `cargo` or `rustc`.

Rust rework 1

---

x11-packages/vim-gtk/build.sh

fix(x11/vim-gtk): correct filename of share/man/man1/xxd.1 in $TERMUX_PKG_RM_AFTER_INSTALL

---

packages/less/build.sh

This PR enables auto updates for the `less` package using a [`ncdu`-style](https://github.com/termux/termux-packages/blob/35a62d9fe0ae719ef7eaa4c82de6a0696f755c0b/packages/ncdu/build.sh#L15-L28) auto update function.

enhance(main/less): enable auto updates

---

packages/just/build.sh

The 32bit builds failed on commit https://github.com/termux/termux-packages/commit/f6b33bc6ca0d0a567ecb600caf49e6ec543e8089.
- This seems to be the same issue we encountered in https://github.com/termux/termux-packages/commit/966977f4aaacff91cf33d99d7e8acbaf937ca8ed
and #22508
Since [`just_1.38.0`](https://packages.termux.dev/apt/termux-main/pool/main/j/just/) never made it to the repos due to the failed 32 bit builds no package revision is required.

fix(main/just): fix 32bit builds

---

packages/moreutils/build.sh

This PR switches the SRCURL for `moreutils` to the upstream git source repo.
Unfortunately `git+https://git.joeyh.name/git/moreutils.git` only provides "dumb http transport".
So I've had to add a `termux_step_get_source()` that mostly reuses `termux_git_clone_src`, but leaves out the `--depth 1` flag since the dumb http transport does not support clone depth.
This change is committed with `%ci:no-build` to let the auto update cycle handle the actual package update, as a test of function.

chore(main/moreutils): use upstream source repo

---

.github/workflows/bootstrap_archives.yml
.github/workflows/command_not_found.yml
.github/workflows/docker_image.yml
.github/workflows/package_updates.yml
.github/workflows/packages.yml
.github/workflows/vagrant.yml

After recent attack through github actions against https://github.com/ultralytics I had a look at our scripts. 
Most of the fixed variables, and `persist-credentials: false` for actions/checkout@v4, was suggested by [zizmor](https://github.com/woodruffw/zizmor), which @Biswa96 showed me.

CI: move some vars to env and set persist-credentials: false for actions/checkout@v4

---

x11-packages/mangohud/build.sh
x11-packages/mangohud/meson.build.patch
x11-packages/mangohud/src-hud_elements.h.patch
x11-packages/mangohud/src-overlay.cpp.patch

addpkg(x11/mangohud): 0.7.2

---

packages/python-torchaudio/build.sh
packages/python-torchaudio/ffmpeg-configure.patch
packages/python-torchaudio/torchaudio-ffmpeg.subpackage.sh
packages/python-torchvision/build.sh
x11-packages/kdenlive/build.sh
x11-packages/shotcut/build.sh

Progress on #22502
For these, I believe the existing package verifiably calls into FFmpeg 7.1 to play videos with no obvious issues, but revision-bumping to be on the safe side.
- `firefox`
- `kdenlive`
- `shotcut`
I have found ways to enable the FFmpeg backends in these that did not previously have FFmpeg support in Termux.
I also changed these packages to use the release downloads instead of git and use checksum verification, which they previously did not. If there is a reason that these specific packages are not supposed to use checksum verification, please let me know.
- `python-torchaudio`: `torchaudio-ffmpeg` subpackage created based on some logic copied from `audacity-ffmpeg`, enabling FFmpeg 6.1.2 support in this package
- `python-torchvision`: minor adjustments to build script …

FFmpeg 7.1 transition part 3

---

x11-packages/audacity/build.sh
x11-packages/audacity/ffmpeg-configure.patch

following the directions given here: https://github.com/termux/termux-packages/issues/22502#issuecomment-2552191867
(paraphrased) "if audacity works with ffmpeg 7 we should recompile it and upgrade the ffmpeg subpackage"
<details>
<summary>Alternative implementation of this change (deleting subpackage) that I tested first</summary>
```diff
--- a/x11-packages/audacity/audacity-ffmpeg.subpackage.sh
+++ /dev/null
@@ -1,5 +0,0 @@
-TERMUX_SUBPKG_DESCRIPTION="Minimal FFmpeg libraries for Audacity"
-TERMUX_SUBPKG_INCLUDE="
-opt/audacity/lib/
-share/doc/audacity-ffmpeg/
-"
--- a/x11-packages/audacity/build.sh
+++ b/x11-packages/audacity/build.sh
@@ -3,18 +3,11 @@ TERMUX_PKG_DESCRIPTION="An easy-to-use, multi-track audio editor and recorder"
TERMUX_PKG_LICENSE="GPL-2.0" …
```

bump(x11/audacity-ffmpeg): 7.1, revbump audacity for ffmpeg-audacity 7.1

---

packages/vim/build.sh
x11-packages/vim-gtk/build.sh

This PR closes #22631.
It also reduces the diff between the vim/vim-gtk builds to a minimum.
Also standardizing some additional feature sets (like tutor files and deb scripts) between the two packages.
GitHub doesn't have a nice way to show the diff between the two build scripts, so here's a screenshot from my editor.
<sup>`vim` on the left, `vim-gtk` on the right</sup>

bump(main/vim): 9.1.0950

---

x11-packages/termux-x11-nightly/build.sh

When reinstalling termux-x11-nightly via pacman, `postinst` does not run and the package itself breaks. To fix this, you need to configure the `postupg` script, which will run `postinst` when reinstalling/updating.

fix(x11-packages/termux-x11-nightly): full debscripts setup for pacman

---

packages/tinymist/build.sh

typlite was merged in the following upstream commit. https://github.com/Myriad-Dreamin/tinymist/commit/9017e05afa51df0286bdb789995c0e0d2501fd49
* Fixes #22682

bump(main/tinymist): 0.12.14

---

packages/ctags/build.sh

This patch cleans up ctags package in several ways:
- Added TERMUX_PKG_REVISION (per @twaik suggestion) instead of playing the version tricks. This has an extra benefit of removing colon from deb file name, with which I had problems in my CI.
- Removed regcomp_works=yes hack that is no longer needed since this: https://github.com/universal-ctags/ctags/pull/3054/commits/daa1a0f9169324eb3176eda8c59414c9e0770a49#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810L607-L617
- Removed TERMUX_PKG_HOSTBUILD and the related packcc games. They are no longer needed per https://github.com/termux/termux-packages/pull/22639#issuecomment-2558116781 (@truboxl) and are making problems in my CI.
- Removed double autogen.sh invocation
The result is faster-building (no hostbuild, no double …

ctags: package clean-up

---

x11-packages/xfce4-notes-plugin/build.sh

Add gtksourceview4 dependency.
Remove unused x11 related dependencies.
* Fixes #22715

bump(x11/xfce4-notes-plugin): 1.11.1

---

x11-packages/xrdp/build.sh
x11-packages/xrdp/fix-configs.patch
x11-packages/xrdp/fix-tmpdir.patch

sesman.ini was renamed to sesman.ini.in
https://github.com/neutrinolabs/xrdp/commit/fd37805ac073170b88557aeec138e694a781d661
xrdp.ini was renamed to xrdp.ini.in
https://github.com/neutrinolabs/xrdp/commit/9ed5243de9c8cb511a38b2ee09c3f8be76c40065
* Fixes #22671

bump(x11/xrdp): 0.10.2

---

packages/squeezelite/build.sh

Fixes the build error with the current package version.

bump(main/squeezelite): 2.0.0.1517

---

x11-packages/cairo-dock-core/build.sh
x11-packages/cairo-dock-core/src-gldit-CMakeLists.txt.patch

Fix build errors such as:
> ld.lld: error: undefined reference due to --no-allow-shlib-undefined: tan referenced by gldit/libgldi.so

fix(x11/cairo-dock-core): Fix build by linking libgldi to libm

---

packages/libspdlog/276ee5f5c0eb13626bd367b006ace5eae9526d8a.patch
packages/libspdlog/build.sh

Fixes building cherrytree (and probably other libspdlog using packages).

fix(main/libspdlog): Backport fmt 11.1 compatibility patch

---

packages/pdf2djvu/build.sh

> ERROR: Found files depend on libomp.so
> ERROR: Showing result
> ERROR: ./bin/pdf2djvu: libc++_shared.so, libc.so, libdjvulibre.so, libdl.so, libiconv.so, libm.so, libomp.so, libpoppler.so

fix(main/pdf2djvu): Fix build by using --disable-openmp

---

packages/ncspot/build.sh
x11-packages/ncspot-mpris/build.sh

It is not clear to me why previous commits
67cc1b95f28e13077187736af783469f41f8f46a
7b2f9c5a3d28273848844c63d856ecfc90488bb1
worked when removing the cmake wrapper but now doesnt.
Restore the cmake wrapper from commit
61be97f1dbe93b62b591d0f02fccaca18440b602
for now instead of breaking build.

fix(main,x11): fix build ncspot and ncspot-mpris

---

packages/pipewire/IPTOS_DSCP.patch
packages/pipewire/build.sh
packages/pipewire/pthread_cancel.patch

- `src/pipewire/thread.c`: patch to support use of custom `create_function` added in https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/16f629d2245e88da317c094d1411ed83c1b41af9

bump(main/pipewire): 1.2.7

---

packages/pango/build.sh
packages/pango/gir/Pango-1.0.xml

* Enable auto-update.
* Use new source and home page url.

bump(main/pango): 1.56.0

---

x11-packages/meld/build.sh
x11-packages/meld/handle-bindtextdomain-oserror.patch

A GUI folder diff tool for X11. Packaged in [many distros](https://repology.org/project/meld/versions)
Closes #18900
(that bug was described as "with the general intention of running meld", and this is a newer way and a newer version of meld than that)

addpkg(x11/meld): 3.22.2

---

packages/libzxing-cpp/build.sh

* Update home page and source url to new repository.
* Change cmake options to new zxing prefixed ones.
* Enable auto update.

bump(main/libzxing-cpp): 2.3.0

---

x11-packages/firefox/0029-fix-tagged-pointer.patch
x11-packages/firefox/build.sh

firefox: avoid using the highest byte of pointer

---

.github/workflows/packages.yml
scripts/bin/test-buildorder-random
x11-packages/vkmark/build.sh

vkmark depends on xcb-util-wm which is only available on x11 repo.
This means vkmark is not installable without x11 repo.
It also likely broke certain package build for some time.
Move vkmark to x11 repo.
Add unit test to guard against this.
Test fail demo in https://github.com/termux/termux-packages/actions/runs/12809167538/job/35713414417

ci(packages): add randomise buildorder.py test

---

packages/gitui/build.sh

- After update of `libgit2` to `v1.9.0`. See: https://github.com/termux/termux-packages/pull/22967

pkg(main/gitui): Use `libgit2`

---

packages/ffmpeg/build.sh
packages/ffmpeg/debian-0001-avformat-mov-don-t-return-the-latest-stream-when-an-.patch
packages/ffmpeg/debian-0002-avformat-internal-Add-ff_get_frame_filename.patch
packages/ffmpeg/debian-0003-avformat-img2enc-Fix-integer-truncation-when-frame_p.patch
packages/ffmpeg/debian-0004-avcodec-mediacodecenc-Fix-access-of-uninitialized-va.patch
packages/ffmpeg/debian-0005-fftools-do-not-access-out-of-bounds-filtergraph.patch
packages/ffmpeg/debian-0006-fftools-log-unconnected-filter-output-label.patch
packages/ffmpeg/debian-0007-avcodec-libx265-unbreak-build-for-X265_BUILD-213.patch
packages/ffmpeg/debian-0008-arm-Consistently-use-proper-interworking-function-re.patch
packages/ffmpeg/debian-0009-checkasm-lls-Use-relative-tolerances-rather-than-abs.patch
packages/ffmpeg/debian-0010-libavcodec-x86-Remove-an-explicit-include-of-config..patch
packages/ffmpeg/debian-0011-avcodec-vaapi_encode-fix-compilation-without-CONFIG_.patch
packages/ffmpeg/debian-0012-avfilter-framesync-fix-forward-EOF-pts.patch
packages/ffmpeg/debian-0013-lavc-avcodec-fix-global-private-option-precendence.patch
packages/ffmpeg/debian-0014-fftools-ffmpeg_filter-treat-apad-filter-as-a-source.patch
packages/ffmpeg/debian-0015-Skip-tests-using-non-existing-mpegts-pmtchange.ts.patch
packages/ffmpeg/sync-debian-patches.sh

ffmpeg is a large and complex code base that has occasional security and functionality issues, while being not that frequently released.
This PR proposes syncing patches from debian, replacing our single handpicked backported commit.
Run `./packages/ffmpeg/sync-debian-patches.sh` to regenerate the patchset from debian.

enhance(main/ffmpeg): Use debian patches

---

packages/python2/build.sh
x11-packages/tuxpaint/build.sh
x11-packages/wine-stable/build.sh

Fix empty lines with only tabs to make `./scripts/lint-packages.sh` pass.
%ci:no-build

chore(scripts/lint-packages): Fix minor styling nits lint

---

x11-packages/gw/build.sh

Uses OLD_SKIA=1 variable for compatibility with skia m93

Updated GW to v1.1.2

---

packages/cfengine/build.sh

bump(main/cfengine): 3.25.0

---

packages/sftpgo/0001-conf.patch
packages/sftpgo/build.sh

* Fixes https://github.com/termux/termux-packages/discussions/23036

fix(main/sftpgo): Relocate data path to fix running server

---

x11-packages/fcitx5/build.sh

fix(x11/fcitx5): libdl.a is a stub --- use libdl.so instead

---

packages/nim/build.sh

Bump Nim to version [2.2.0](https://nim-lang.org/blog/2024/10/02/nim-220-2010.html)

bump(main/nim): v2.2.0

---

.github/workflows/packages.yml
scripts/bin/test-buildorder-random

Add more coverage with lesser CI init cost
Otherwise have to wait until build finished which could take hours
Example test failure: https://github.com/termux/termux-packages/actions/runs/12851323881/job/35831928225?pr=22977

ci(packages): add more buildorder tests

---

packages/libwavpack/build.sh

Fixes the build as 5.8.0 was removed: https://github.com/dbry/WavPack/releases/tag/5.8.1

bump(main/libwavpack): 5.8.1

---

packages/phpmyadmin/build.sh
packages/phpmyadmin/phpmyadmin.conf

The `php-apache` is incomplete, I had to use https://github.com/termux/termux-packages/issues/7964#issuecomment-2608382401 to make it work.
I decided to ban the vendor folder. And I had to add a line to grant access to the folder or the page is 403
I added a php flag to avoid showing the deprecations:
- https://github.com/termux/termux-packages/issues/22735#issuecomment-2568497301
- https://github.com/phpmyadmin/phpmyadmin/issues/19404#issuecomment-2608396879
The package displays and connects to my database server 🎉

bump(phpmyadmin): 5.2.2

---

scripts/setup-ubuntu.sh

chore(scripts/setup-ubuntu): retarget symbolic link to prepare for aosp-libs package

---

packages/electrum/build.sh

Dependencies synced with https://github.com/spesmilo/electrum/blob/4.5.8/contrib/requirements/requirements.txt.
Electrum was broken after an auto-update due to missing dependencies until @DarkJoker360 fixed it in https://github.com/termux/termux-packages/pull/22979. Let's disable auto updates so that we do not get the same issues again.
Also add an `electrum daemon` termux-services script. To use, install `termux-services` and then run `sv up electrum`, or `sv-enable electrum`.

electrum: sync python dependencies, disable auto updates and add electrum daemon service script 

---

packages/openssh/build.sh
packages/openssh/sv/ssh-agent.run.in
packages/openssh/sv/sshd.run.in

Install `termux-services`, and then run `sv-enable ssh-agent` to enable the service, and add `export SSH_AUTH_SOCK="$PREFIX"/var/run/ssh-agent.socket` to your .bashrc to make all terminal sessions use the same agent.
The ssh-agent run script has been put in a subdirectory sv in the builder dir, and the sshd service script moved there as well. This is hopefully clearer than trying to put a multiline script in the TERMUX_PKG_SERVICE_SCRIPT variable. I am considering if we should move away from TERMUX_PKG_SERVICE_SCRIPT and instead use a subdirectory as here.. (and make our build scripts autofind the service scripts)

enhance(main/openssh): add ssh-agent service script

---

packages/codon/0001-custom-openmp.patch
packages/codon/0002-do-not-pass-no-pie-to-c-compiler.patch
packages/codon/0003-do-not-copy-libs-for-android.patch
packages/codon/0004-openblas-disable-dynamic-arch.patch
packages/codon/0005-hwy-use-cmp-function-rather-than-operator.patch
packages/codon/5001-llvm-include-llvm-ADT-SmallVector.h.patch
packages/codon/5002-llvm-tools-llvm-rtdyld-llvm-rtdyld.cpp.patch
packages/codon/5003-llvm-openmp.patch
packages/codon/build.sh
packages/codon/host-peg2cpp-CMakeLists.txt
packages/codon/openmp.diff

new package: codon

---

scripts/big-pkgs.list
x11-packages/carbonyl/0001-use-prebuilt-snapshot.patch
x11-packages/carbonyl/0002-use-prebuilt-cross-tools.patch
x11-packages/carbonyl/0003-v8-use-prebuilt-cross-tools.patch
x11-packages/carbonyl/build.sh
x11-packages/carbonyl/toolchain-template/host-toolchain.gn.in
x11-packages/carbonyl/toolchain-template/v8-toolchain.gn.in

new package: carbonyl

---

packages/cronie/build.sh

To avoid this error message, if '~/.cache' does not exist already:
crontab -e
crontab: installing new crontab
/data/data/com.termux/files/home/.cache/crontab: mkdir: No such file or directory

fix(main/cronie): ensure `~/.cache` exists

---

packages/screen/build.sh
packages/screen/issue-22688.patch

screen: fix GBK chars' rendering

---

packages/libsndfile/build.sh

- Fixes #23114
Before:
```
External MPEG Lame/MPG123 : ........... no
```
`libsndfile` reverse dependency example: **`rubberband`**:
```
~ $ rubberband -t 2 example.mp3 example_out.mp3
Using R2 (faster) engine
Using crispness level: 5 (Crisp monophonic instrumental)
ERROR: Failed to open input file "example.mp3": File contains data in an unimplemented format.
```
After:
```
External MPEG Lame/MPG123 : ........... yes
```
`libsndfile` reverse dependency example: **`rubberband`**:
```
~ $ rubberband -t 2 example.mp3 example_out.mp3
Using R2 (faster) engine
Using crispness level: 5 (Crisp monophonic instrumental)
Using time ratio 2 and frequency ratio 1
Pass 1: Studying...
Calculating profile...
Pass 2: Processing...
in: 2557062, out: 5114124, ratio: 2, ideal output: 5114124, error: 0
[...] …
```

fix(main/libsndfile): link to libmp3lame

---

packages/hidapi/build.sh
packages/hidapi/libusb-iconv-CMakeLists.txt.patch
packages/hidapi/termux-iconv-hid.c.patch

hidapi can be used with libusb, or the kernel driver "hidraw" (likely only relevant for rooted devices), to access HID devices. Goal is to patch it further and use it together with termux-usb.
Add it now for testing and development purposes.

addpkg(main/hidapi): package for accessing HID usb devices (with libusb)

---

packages/libmp3lame/build.sh

Audacity attempts to `dlopen()` `libmp3lame.so.0` by default on all linux distros, not `libmp3lame.so`
https://github.com/audacity/audacity/blob/d1f7b507a0d919dcd9d58588ac85ce6dbea527e5/au3/modules/import-export/mod-mp3/ExportMP3.cpp#L1485
This solution is based on the example seen in the `pulseaudio` package:
https://github.com/termux/termux-packages/blob/aec99dd11b9b8e50bf6260348d82385e819558c5/packages/pulseaudio/build.sh#L64-L70
- Fixes #23100

fix(main/libmp3lame): provide libmp3lame.so.0

---

packages/at/build.sh

The termux-services daemons should be run in foreground for it to work correctly. Atd's -f arg stands for foreground.
Reported-by: @qithron
Fixes: termux/termux-packages#23125

fix(main/at): use -f in atd service script

---

packages/diff-so-fancy/build.sh
packages/lazygit/build.sh

3f36bc80c new package: diff-so-fancy
-----
d8c7334da Suggest `diff-so-fancy` for `lazygit` as [it can integrate with it](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md#diff-so-fancy).
Perhaps `git` should suggest either `git-delta` or `diff-so-fancy` if Termux's infrastructure allows for building packages which suggest one of a few packages.
-----
Review note: I could not locally build and test the package as the build environment required to install all possible build dependencies even if completely unused.

new package: diff-so-fancy

---

packages/vim/build.sh
x11-packages/vim-gtk/build.sh

Routine update of the `vim` packages and minor cleanup of the auto-update function comments.

bump(main/vim, x11/vim-gtk): 9.1.1100

---

packages/ffmpeg/build.sh
packages/ffmpeg/postinst.sh.in

closes #23189
CC: @licy183
This should only show the note if `ffmpeg -version` (which should exit 0) fails to run.
Which should trigger a segfault if the symbol conflict is present on the device.
We can also just show it unconditionally if that doesn't work.

enhance(main/ffmpeg): suggest installing `libandroid-stub` if ffmpeg segfaults

---

x11-packages/tint2/build.sh

Fix build error `ld.lld: error: undefined symbol: log10`

revbump(x11/tint2): link with libm

---

scripts/bin/update-packages
scripts/updates/internal/termux_github_graphql.sh

This PR aims to make the auto-update workflow rate-limit aware in order to avoid future shadowbans of @termuxbot2 for just doing its job.
In this current state it only implements basic debugging functionality by printing out the `.resources.core` table of the rate limit query API response which contains the `limit`<sub>(int)</sub>, `used`<sub>(int)</sub>, `remaining`<sub>(int)</sub> and `reset`<sub>(unix_epoch)</sub> keys.
For local testing I have generated a fine grained access token for GitHub, which I am sourcing from `gh.env` inside the root directory of the git repo.
(This token only has read permissions to the rate-limit API endpoint, I may need to replace it for further testing)
```bash
export GITHUB_TOKEN='<your_github_token_here>'
```
The token is obviously passed in as part of …

Make auto updates rate-limit aware

---

packages/tree-sitter/build.sh

Fixes a regression introduced in https://github.com/termux/termux-packages/commit/3d26ef1d9bb8dac0b84c67e199a3e81a99a8ee84

fix(main/tree-sitter): fix typo is SOGUARD function name

---

scripts/updates/utils/termux_pkg_upgrade_version.sh

closes #22816
Should stop long running autoupdates from getting bounced because a faster autoupdate jumped the queue.

enhance(scripts/termux_pkg_upgrade_version): Fetch before attempting to push.

---

x11-packages/luanti/build.sh

- This is a potential alternative solution to #23148
- compared to #23149
- **Potential advantages**: does not require editing the `openal-soft` package
- **Potential disadvantages**: would require editing any other reverse dependency of `openal-soft` that could in the future be found to be affected by the same issue, by copying and pasting these `LDFLAGS` to its `build.sh`.

fix(x11/luanti): force-link to libOpenSLES.so

---

scripts/updates/utils/termux_pkg_upgrade_version.sh

Auto-updater complains about unstashed changing and being unable to pull with rebase in the case if it does not commit changes.
This PR should fix it.
Since this seems to be harmless I will merge it in 24 hours if nobody minds.

fix(ci): fix auto-updater running with GIT_COMMIT_PACKAGES=false

---

packages/rizin/build.sh

Add libandroid-execinfo dependency which fixes linking error.
ld.lld: error: undefined symbol: backtrace
ld.lld: error: undefined symbol: backtrace_symbols_fd
* See #23422

rebuild(main/rizin): Rebuild for tree-sitter 0.25

---

packages/which/build.sh

Change srcurl and homepage to the GNU upstream since the Github.io page for `which` has not been updated with the new version yet.
Also enables auto updates and fixes the license specifier.

bump(main/which): 2.23

---

scripts/updates/api/termux_github_api_get_tag.sh
scripts/updates/internal/termux_github_graphql.sh

And avoid shadowbanning of our dear @termuxbot2. They suffer when they can not work.
Fixes #23511, fixes #23510, fixes #23509, fixes #23507, fixes #23506, fixes #23505, fixes #23504, fixes #23503, fixes #23502, fixes #23501, fixes #23500, fixes #23498, fixes #23497
I'd like to merge this before the next auto-update cycle.
Since it is harmless and affects only auto-updater script execution time I will merge it in 6 hours if nobody minds.

fix(ci): slowdown graphql requests to avoid being ratelimited

---

x11-packages/inkscape/build.sh

- After #21944, `inkscape` is forced to statically link to `graphicsmagick`, but that PR did not also change the marked dependency from `graphicsmagick` to `graphicsmagick-static`, causing the static library to not be present in `$TERMUX_PREFIX/lib` if the package is compiled with `./build-package -I` and without also recompiling `graphicsmagick` in the same docker container first.
@twaik does this look like it is an appropriate completion of what you set up in that PR?

fix(x11/inkscape): fix build as a single package after dependency switch to graphicsmagick-static

---

packages/manim/build.sh

(`mapbox_earcut` has been downgraded to v0.1.2)

Update Python dependencies to match 0.19.0 requirements

---

x11-packages/firefox/0030-fix-headless-mode.patch
x11-packages/firefox/build.sh

- Fixes #22286
Fixes a crash in the command `firefox -headless` when run with no X11 server present
in all distros when firefox was built with the edge case intersection of:
with `MOZ_HAS_REMOTE`, with `MOZ_X11`, without `MOZ_ENABLE_DBUS` and without `MOZ_WAYLAND`
I have submitted this patch for feedback upstream here: https://bugzilla.mozilla.org/show_bug.cgi?id=1946405
This patch is a dependency of my project, "[How To Run Node.js Puppeteer On Android](https://gist.github.com/robertkirkman/0c2f3426024069546ed9b7bb2f26cb99)", which is a fully functional example of a Javascript program that invokes the system call `firefox -headless` through the Puppeteer library.
I am hoping to possibly upstream the patch part of the necessary code for the headless mode on Termux of the Firefox backend …

fix(x11/firefox): fix Segmentation fault in the command "firefox -headless"

---

packages/bgrep/build.sh

this software's build system, by default, clones the newest possible commit of gnulib, and then uses that during the build process. https://github.com/rsharo/bgrep/blob/440164692a52bac654eb75de7d16087d87649520/bootstrap#L638
that had been working up until recently, when the package began failing to build because of some changes entering the gnulib repository related to the `strcasecmp()` function. https://github.com/coreutils/gnulib/commit/b2927d1b1fa3fb09a2210a3df5691f7d48d6151b
That is not handled by the current version of `termux_step_configure_autotools()`, so an error began appearing, `configure: error: cannot run test program while cross compiling`. https://github.com/termux/termux-packages/blob/c2f2312c0894c85b68b671563a333205e0871f3d/scripts/build/configure/termux_step_configure_au …

fix(main/bgrep): fix build in 2025 (gnulib master branch)

---

packages/texinfo/build.sh

https://deb.debian.org/debian/pool/main/t/texinfo/texinfo_7.2-1.debian.tar.xz currently has 404, so this replaces it with https://deb.debian.org/debian/pool/main/t/texinfo/texinfo_7.2-2.debian.tar.xz which is not 404.

fix(main/texinfo): bump debian tar revision to 7.2-2

---

packages/swi-prolog/build.sh
packages/swi-prolog/continue-on-abi-check-failure.patch

By default `swipl` will terminate if `$PREFIX/lib/swipl/ABI` does not contain the exact same string that `swipl --abi-version` prints. The error appears to be spurious, so this bypasses it, while printing a warning about what is happening if the check failed.
Fixes #22737

fix(main/swi-prolog): continue even if ABI check fails

---

x11-packages/lxqt-wayland-session/0001-fix-hardcoded-paths.patch
x11-packages/lxqt-wayland-session/build.sh

* Screenshot of qterminal in lxqt wayland session
xfce4 already works in wayland session in termux-x11. This would allow to do so with lxqt now. Also, this help to test basic features in labwc and sway compositors in termux-x11.

addpkg(x11/lxqt-wayland-session): 0.1.1

---

packages/pass-otp/build.sh

When `$PREFIX` (an internal `pass` variable, not to be confused with Termux's `$PREFIX`) was renamed to `$PASS_PREFIX` in ddf79220de5650775849b294c6f02f304d0d83bc, `pass-otp` was not modified to reflect that, which caused all `pass otp` commands to look for the password file in Termux's `$PREFIX` instead of `$PASS_PREFIX`, resulting in `passfile not found` errors.
I have also updated the license as the source code says that using a later version is permitted.
See also: #23569

fix(main/pass-otp): Rename `$PREFIX` variable to `$PASS_PREFIX`

---

packages/libprotobuf/build.sh
packages/libprotobuf/libutf8-range.subpackage.sh
x11-packages/opencv/build.sh

- Fixes #23668
Testing locally confirms that when `scripts/run-docker.sh ./build-package.sh -I -f libprotobuf` is run in a clean docker container, the resulting `libprotobuf.so` is linked to the `libutf8_validity.so`.

rmpkg(main/libutf8-range): merge back into libprotobuf

---

packages/fish/build.sh

https://fishshell.com/blog/new-in-40/ mentions this bug and a few users have also reported this
could be reverted once https://github.com/termux/termux-app/pull/4417 is merged and released
Fixes: https://github.com/termux/termux-packages/issues/23685

fix(main/fish): disable keyboard protocols that print extra characters

---

packages/libncnn/build.sh
x11-packages/opencv/build.sh

Fixes #23681
Closes #23684
Alternative to moving dynamic library back and forth.

fix(main/libncnn,x11/opencv): static linking workaround avoiding `mv`

---

packages/fish/build.sh

previously the command was appending to the variable, this can cause the $fish_feature variable to get very long
now it first checks if the feature is enabled and then overwrites it if necessary

fix(main/fish): set feature only once instead of appending

---

CODEOWNERS
packages/coreutils/backport-915004f.patch
packages/coreutils/build.sh
packages/coreutils/selinux.patch

- Add maintainer so we hopefully get this done in a more timely manner next time.
- Ported `selinux.patch`.
Having it as a `git diff` patch should hopefully make porting it easier in the future since it allows `git apply -3` to create a merge conflict out of the conflicting hunks.
> [!IMPORTANT]
> Essential package update checklist 
> - [x] Builds on CI
> - [x] Tested on device (AArch64, Android 14, Fairphone 5)

bump(main/coreutils): 9.6

---

packages/htop/build.sh

- Update `htop` to 3.4.0
- Enable auto updates
- Minor build script cleanup.

bump(main/htop): 3.4.0

---

packages/termux-exec/build.sh

the repository name being changed from github.com/termux/termux-exec to github.com/termux/termux-exec-package causes the source archive checksum to change, because previously the archive contained a folder named "termux-exec-1.0" and now it contains a folder named "termux-exec-package-1.0" instead.

fix(main/termux-exec): the checksum has changed because the repository was renamed

---

packages/poke/build.sh

Enable strcasecmp explicitly to fix the following configure error.
checking for strcasecmp... yes
checking whether strcasecmp works...
configure: error: in '/home/builder/.termux-build/poke/src/jitter':
configure: error: cannot run test program while cross compiling
* Fixes #23740

bump(main/poke): 4.3

---

packages/dufs/build.sh
packages/pup/build.sh

The builtin `--help/-h ` screen doesn't contain full documentation, hence installing README files (for offline/intranet scenario)

pup, dufs: install documentation (README)

---

packages/doge/build.sh

- Progress on #23492
The GitHub repository name has been changed by its author from "doge" to "dog_community", which is an action that changes the checksum of the already-released archives retroactively.

fix(main/doge): update checksum after repository name changed

---

packages/mc/build.sh

Hello,
I'm preparing the migration to a new website. As part of this, we will be dropping the `www` prefix. Also, I have updated the package source to use HTTPS with our official OSU OSL mirror.
Thank you!

fix(main/mc): update project links

---

packages/ruby/build.sh
packages/ruby/process.c.patch

fix(main/ruby): fix `fork` panicking

---

x11-packages/kitty/build.sh
x11-packages/kitty/prepend-prefix-to-etc-and-share-paths.patch

fix(x11/kitty): prepend $TERMUX_PREFIX to some absolute paths that were not previously patched

---

packages/python-brotli/build.sh
packages/python-pycryptodomex/build.sh
packages/python-yt-dlp/build.sh

This PR migrates `python-yt-dlp` from the TUR.
Additionally:
- Sets a maintainer
- Makes it provide `yt-dlp` to aid package discoverability
- Changes `ffmpeg` from a `TERMUX_PKG_SUGGESTS`[^1] to `TERMUX_PKG_RECOMMENDS`[^2]
- Clean up a few shellcheck warnings
- Corresponding TUR PR: https://github.com/termux-user-repository/tur/pull/1593
[^1]: Comma-separated list of packages that are related to or enhance the current one.
[^2]: Comma-separated list of non-absolute dependencies - packages usually used with the current one.
https://github.com/termux/termux-packages/wiki/Creating-new-package#package-build-script-variables

addpkg(main/python-yt-dlp): 2025.02.19 - Migrate from TUR.

---

packages/imlib2/build.sh

Link with math library explicitly to fix the following error. ERROR: ./lib/imlib2/filters/colormod.so contains undefined symbols: pow
* Fixes #23838

bump(main/imlib2): 1.12.4

---

root-packages/thin-provisioning-tools/build.patch
root-packages/thin-provisioning-tools/build.sh
root-packages/thin-provisioning-tools/file_utils.patch

It requires following changes to work:
- https://github.com/kivy/pyjnius/pull/732
- https://github.com/hbldh/bleak/pull/1642
- https://github.com/kivy/pyjnius/pull/733
- https://github.com/hbldh/bleak/pull/1644
- termux-api also needs to be patched

[wip ]adds bleak

---

root-packages/thin-provisioning-tools/build.patch
root-packages/thin-provisioning-tools/build.sh
root-packages/thin-provisioning-tools/file_utils.patch

add thin-provisioning-tools to allow lvm2 use thin pools on 4.19 kernel

addpkg(root/thin-provisioning-tools): add v0.9.0

---

.github/ISSUE_TEMPLATE/01-bug-report.yml

Alternative to #23713.
[Preview link.](https://github.com/termux/termux-packages/blob/links-in-bug-report-template/.github/ISSUE_TEMPLATE/01-bug-report.yml)
badges are generated with https://shields.io/badges.

enhancement(github): add contact badges with links to bug report template

---

packages/coreutils/backport-d89387b.patch
packages/coreutils/build.sh

- Fixes https://github.com/termux/termux-packages/issues/23752
Patch created and shared by pixelb
This restores the `ls -Z` command to its pre-coreutils-9.6 behavior,
and passes these test cases on Samsung Galaxy A70 SM-A705FN with Android 13:
(should not crash)
```bash
cd && ls -Z ..
```
(should not crash)
```bash
cd && ls -Z . > out
```
(should not crash)
```bash
ls -Z /storage/emulated/0/
```
(should show correct output, like `u:object_r:fuse:s0`)
```bash
cd /storage/emulated/0 && ls -Z $(pwd)
```
(should print both directories without crashing)
```bash
ls -l /storage/emulated/0 /storage/emulated/0/Download
```
(should print both directories without crashing)
```bash
ls -Z /storage/emulated/0 /storage/emulated/0/Download
```
(should print both directories without crashing)
```bash
ls …
```

fix(main/coreutils): fix undefined behavior in coreutils built with selinux enabled and xattrs disabled

---

scripts/build/termux_download.sh

This PR should hopefully cut down on the time spent by `termux_download` when retrying an unresponsive URL, by putting a 300 second cumulative limit on retries.
- See: #23841
- This PR partly follows up on: #21251

Termux download retry timeout

---

packages/knockd/build.sh

Original project is unmaintained so we switch to fork which supports IPv6 (and it is used in Alpine Linux).

bump(main/knockd): 0.8.2

---

x11-packages/xfce4-session/build.sh

Fix the following error for cross-compiling.
/bin/bash: line 1: /data/data/com.termux/files/usr/bin/glib-compile-resources:
cannot execute binary file: Exec format error
* Fixes #23948

bump(x11/xfce4-session): 4.20.2

---

scripts/build/termux_step_setup_variables.sh

- Fixes https://github.com/termux/termux-packages/issues/23951
After `termux-exec` 2+ https://github.com/termux/termux-packages/commit/eaf26b3,
`LD_PRELOAD` might not end with exactly "`libtermux-exec.so`". It might end with something else like for example, "`libtermux-exec-ld-preload.so`". Therefore, the `grep` check should be replaced with a check that allows a wider range of filenames in `LD_PRELOAD`.
Relevant changes within `termux-exec`:
- https://github.com/termux/termux-exec-package/commit/1fac1073
- https://github.com/termux/termux-exec-package/commit/db738a11

fix(scripts/build/termux_step_setup_variables): update for termux-exec 2+

---

build-package.sh
scripts/build/setup/termux_setup_proot.sh
scripts/build/termux_step_setup_variables.sh

- Inspired by @licy183 implementation in https://github.com/termux/termux-packages/commit/5278c839dbded789e0b6992c90024f6e4a4d412c#diff-96e86e41ad7faf61d20b787ee4808183614387e8d49810c78d579259e89fe3ffR37 
- Will we used to run `ghc-iserv` to cross compile haskell template.

scripts(build-packages.sh,build): Add support to run target binaries

---

packages/vulkan-icd/build.sh
packages/vulkan-loader-generic/build.sh

Add a metapackage to provide Vulkan ICDs, ane make `vulkan-loader-generic` recommend `vulkan-icd`.
This PR makes it technically difficult to have no available ICD on device, thus avoiding things like #23969
Closes #23969

new package: vulkan-icd

---

packages/dbus/build.sh
packages/dbus/disable-pidfd-open.patch

- Fixes https://github.com/termux/termux-packages/issues/23981
- In a way, reverts https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/398 (introduced in dbus version 1.15.8)

fix(main/dbus): disable pidfd_open syscall

---

packages/restic/build.sh
packages/restic/failsafe-chmod.patch

* Fixes #24007 
Rebase patch file after https://github.com/restic/restic/commit/6d3a5260d358cd89e8727fd279a94dd8d553ff35 commit.

bump(main/restic): 0.18.0

---

packages/aptitude/build.sh

fix(main/aptitude): depend on googletest for libgmock.so

---

packages/libvips/build.sh

Most FFI-based libvips bindings expect version-suffixed SONAMEs.
Context: https://github.com/libvips/php-vips/pull/260.

libvips: enable SOVERSION suffix

---

packages/marksman/build.sh

Marksman is a LSP language server for Markdown.
https://repology.org/project/marksman
<h1><em></em></h1> 
<h1><em></em></h1> 
This package build is based in part on the package build for [`jackett`](https://github.com/termux/termux-packages/blob/master/packages/jackett/build.sh).

addpkg(main/marksman): 2024.12.18

---

.github/workflows/package_updates.yml
scripts/free-space.sh

- **scripts(free-space): Add switch to disable docker cleaning**
- **ci(package_updates): Do not remove docker and it's images**
Closes: #24086
Closes: #24085
Closes: #24084
Closes: #24083
Closes: #24082
Closes: #24080
Closes: #24079
Closes: #24078
Closes: #24077
Closes: #24074
Closes: #24073
Closes: #24072
Closes: #24071
Closes: #24132 
Closes: #24133 
Closes: #24134 
Closes: #24135 
Closes: #24136
Closes: #24137 
Closes: #24138 
Closes: #24139 
Closes: #24140

Do not remove docker while cleaning space for `package_updates` workflow 

---

scripts/build/termux_step_start_build.sh

In a continued build, `TERMUX_ELF_CLEANER` is set to `$PREFIX/bin/termux-elf-cleaner` after the early-return check of `TERMUX_CONTINUE_BUILD`.

scripts(start_build): set `TERMUX_ELF_CLEANER` for on-device continued build

---

packages/gdal/build.sh
packages/libsqlite/build.sh

This fixes the following error with gdal build.
CMake Error at cmake/helpers/CheckDependentLibraries.cmake:276 (message):
/data/data/com.termux/files/usr/lib/libsqlite3.so lacks the RTree
extension! Spatialite will not behave properly.  Define the
ACCEPT_MISSING_SQLITE3_RTREE:BOOL=ON CMake variable if you want to build
despite this limitation.
* Fixes #24187

enhance(main/libsqlite): Enable rtree extension for gdal

---

scripts/build/termux_create_debian_subpackages.sh

Fixes a regression in 97a63bdb78dcd042750708253ed4fcdf09fac3f2.
One quick-building test case is the `dpkg` package with the `dpkg-perl` subpackage: `dpkg-perl` should depend on `dpkg`, its parent package (since `dpkg` does not depend on `dpkg-perl`).

fix(subpackages): Fix check for if subpackage should depend on parent

---

x11-packages/termux-x11-nightly/build.sh
x11-packages/termux-x11-nightly/sv/tx11-xfce4.run.in
x11-packages/termux-x11-nightly/sv/tx11.run.in

Install termux-services and then run `sv up termux-x11` to start the service, or sv-enable termux-x11 to run it by default.
Requested in termux/termux-x11#800.
As @twaik noted it would be more useful/user-friendly to have a service script to start an entire desktop environment. That can be added separately to for example xfce4, I think there is some benefit to having being able to run just termux-x11 though, since that allows up run single gui applications without all the desktop environment overhead.

enhance(x11/termux-x11): add service script

---

packages/python-pillow/build.sh
packages/python-pip/build.sh
packages/python-torchvision/build.sh
scripts/build/setup/termux_setup_python_pip.sh

- `wheel` version 0.46+ now requires `setuptools` version 70 or newer
- discussed upstream here: https://github.com/pypa/wheel/issues/660
- discovered in termux-packages here: https://github.com/termux/termux-packages/pull/24062#issuecomment-2788106897
- Lock `wheel` version at 0.46.1 so that if a future `wheel` update causes a similar problem in the future, it doesn't immediately propagate into termux-packages without us explicitly bumping it. Recommended by Tomjo2000 here: https://github.com/termux/termux-packages/pull/24062#issuecomment-2798403944
- I have confirmed that this change works to fix the build of `python-lxml` **both**
- **in `TERMUX_ON_DEVICE_BUILD=false` mode (temporarily broken for 1 week)**,
- fixes `error: invalid command 'bdist_wheel'`
- **and also in …

bump(scripts/build/setup/termux_setup_python_pip): setuptools 78.1.0, wheel 0.46.1

---

packages/libxml2/build.sh

Will follow up with rebuilds in separate PRs shortly.
Libxml 2.14.0 raised the SOVERSION from 2 to 16 (`2 + 14`)
<sup>Upstream commit: https://gitlab.gnome.org/GNOME/libxml2/-/commit/137466aeb7d51472f418ef61dd53a27e54a4a39b</sup>
I've adjusted the SOVERSION guard to make the mismatch clearer accordingly.
Here's the full revdep list for rebuilds.
I'll split these into ~5 to 7 batches.
```console
packages/appstream
packages/aria2
packages/at-spi2-core
packages/cfengine
packages/clamav
packages/codon
packages/crystal
packages/ctags
packages/dcmtk
packages/dnsutils
packages/dvdauthor
packages/ebook-tools
packages/emacs
packages/ffmpeg
packages/finch
packages/gdal
packages/gettext
packages/gnucobol
packages/graphicsmagick
packages/gst-plugins-bad
packages/gst-plugins-good
packages/icecast …
```

bump(main/libxml2): 2.14.1

---

packages/xmlsec/build.sh

Forgot to change this before merging #24211 but we should switch `xmlsec`'s source url over to the github repo since the upstream website has been unreliable.
See: https://github.com/termux/termux-packages/actions/runs/14434349180/job/40473123158

chore(main/xmlsec): replace unreliable source URL

---

x11-packages/webkitgtk-6.0/build.sh

- Part of #24059
As mentioned this should take around 200 minutes on the CI and thus will need its own run.

Libxml2 rebuilds webkit2gtk 6.0

---

x11-packages/webkit2gtk-4.1/build.sh

- Part of #24059
As mentioned this should take around 200 minutes on the CI and thus will need its own run.

Libxml2 rebuilds webkit2gtk 4.1

---

.github/workflows/packages.yml

According to https://github.com/termux/termux-packages/actions/runs/14457475291 it works. 
`git fetch` is required because it seems like checkout action does not fetch master branch (see https://github.com/termux/termux-packages/actions/runs/14457414103)

ci(packages.yml): fix building on non-master branches.

---

.github/workflows/packages.yml
scripts/utils/termux_reuse_pr_build_artifacts.sh

This PR lets us reuse PR build artifacts in the case if none of buildsystem or build dependencies files were updated after PR diverged.
Also this PR lets us reuse CI artifacts of previous CI runs after pushes and force-pushes if they are relevant.
I intentionally made it NOT fail in any case because I want to monitor how it goes for different PRs and make sure all checks work fine.
When we know everything works fine I will implement downloading PR build artifacts and reusing them instead of running package building.

ci(packages.yml): implement draft CI fast path for reusing PR build artifacts

---

.github/workflows/packages.yml

First time contributors often sync their branches with master using merge commits.
Even though these PRs can not be merged due to our merging policy it still triggers CI rebuilding recently changed packages and wastes a lot of CI time.
I am going to merge this in 12 hours if nobody minds.

ci(packages.yml): ban merge commits in PRs to avoid wasting CI time

---

packages/libandroid-stub/build.sh
packages/libandroid-stub/libOpenSLES-wrapper.c
packages/libandroid-stub/libandroid-wrapper.c
packages/libandroid-stub/libmediandk-wrapper.c

Fixes #23695, fixes #21660, fixes #19623, fixes #21881
Unfortunately I can not reproduce ffmpeg crash on my device, but spek works fine.
It should be tested with other system-lib-pulling projects to make sure it does not break anything else.
Also I removed a comment about the package not-to-be-dependent on because it does not ship NDK libraries anymore and fallbacks to functions in system libraries.
I am not intending to merge this until it is well tested. 
CC @licy183 @truboxl because you commited changes to this package.

chore(main/libandroid-stub): turn libandroid-stub into library-wrapper

---

x11-packages/xfce4-pulseaudio-plugin/build.sh

It is used as default mixer command.
https://gitlab.xfce.org/panel-plugins/xfce4-pulseaudio-plugin/-/blob/xfce4-pulseaudio-plugin-0.5.0/meson_options.txt?ref_type=tags#L39
* Fixes #24434

fix(x11/xfce4-pulseaudio-plugin): Add pavucontrol dependency

---

scripts/build/setup/termux_setup_golang.sh

This change makes `./clean.sh` cleanup go caches as well

scripts(termux_setup_golang): move go caches to $TERMUX_TOPDIR

---

scripts/bin/revbump

* always check revision then fallback
Fix a bug where `build.sh` has `TERMUX_PKG_REVISION` but not
`^TERMUX_PKG_REVISION` causing revbump script to fail.
```
Bumping 1 packages
-1 -> 0 packages/libllvm/build.sh
```
* detect multiline `TERMUX_PKG_VERSION`
* detect `TERMUX_PKG_VERSION+=()`

fix(scripts/revbump): handle more edgecases

---

.github/workflows/packages.yml

When new commits are pushed to a pull request, previous CI workflow runs for that PR continue consuming runner time even though their results are no longer relevant. This change uses GitHub Actions’ built-in concurrency feature with a conditional group name so that:
- For pull_request events, group is set to `pr-<PR number>` and cancel-in-progress is true, ensuring only the latest run for a PR completes; earlier in-progress runs are automatically cancelled.
- For all other events (push/workflow_dispatch/schedule), group falls back to the unique run_id and cancel-in-progress is false, so non-PR builds do not interfere with each other.
This reduces wasted runner time and keeps the CI queue clean without affecting non-PR workflows.

ci(packages): cancel outdated PR workflow runs via concurrency

---

packages/openssh/build.sh
packages/openssh/scp-with-agent.sh
packages/openssh/sftp-with-agent.sh
packages/openssh/source-ssh-agent.sh
packages/openssh/ssh-with-agent.sh

- This reverts their removal in https://github.com/termux/termux-packages/commit/7b5bd568c27b1d2d08d349e6431c95b1e6195e28
We shouldn't revisit this until we've put in place a seamless replacement with the `ssh-agent` `sv` service and have properly discussed and documented the deprecation of the non-standard wrappers.

fix(main/openssh): re-add ssh-agent wrapper scripts

---

packages/openssh/build.sh
packages/openssh/sftp-with-agent.sh
packages/openssh/source-ssh-agent.sh
packages/openssh/ssh-with-agent.sh
packages/openssh/wrap-ssh-agent.sh

This makes it easy to have a single wrapper script with
symbolic links pointing at it for each wrapped command.

Use a common wrapper pattern for s{sh,cp,ftp}a scripts

---

packages/sbcl/build.sh

Unfortunately, I didn't understand how to make the auto update work correctly for this type of `TERMUX_PKG_SRCURL`, I need to find a package that has an exactly matching `TERMUX_PKG_SRCURL` format that has already been auto updated successfully, and copy the logic that it uses.
`sbcl` has this `TERMUX_PKG_SRCURL` format:
`https://github.com/(account name)/(package name)/archive/refs/tags/(package name)-${TERMUX_PKG_VERSION}.tar.gz`
I noticed that `jql` has exactly that format, and that it also has `TERMUX_PKG_AUTO_UPDATE=true`, and that the only addtional difference it has from `sbcl` is that it has `TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+.\d+.\d+"`, so I hope that this change makes the auto updater run correctly on `sbcl`.
https://github.com/termux/termux-packages/commit/1055def368cc4ca5bde …

fix(main/sbcl): add correct `TERMUX_PKG_UPDATE_VERSION_REGEXP`

---

x11-packages/qemu-system-x86-64/build.sh

Align dependencies with headless, see e6c23b338e2e319bd883ba1f99ef13087d52ac93
Closes #24499

qemu-system-x86-64: depend on alsa-lib, jack2, libdw

---

scripts/updates/utils/termux_pkg_is_update_needed.sh

It is needed to explicitly catch situations where auto-update is not possible due to wrong regexp.
Related to #24496.

chore: copy dpkg --compare-version warnings to job annotation

---

scripts/build/termux_step_copy_into_massagedir.sh

After experimenting with the massaging step, I realized that my previous changes - while avoiding tar compression - introduced extra execution overhead (due to `find|xargs` spawning) on packages with many files, and risked altering file attributes  in (unexpected) ways that could (possibly) break package behaviour. This pull request restores the original `extract_into_massagedir` logic while still eliminating any storage or compression overhead. Effectively only three binary executions and copying over pipe (without compression) are used to achieve the minimal possible overhead without changing old behaviour.

chore: old copy_into_massagedir compatible behaviour

---

packages/vitetris/build.sh

- `TERMUX_PKG_REMOVE_AFTER_INSTALL` -> `TERMUX_PKG_RM_AFTER_INSTALL`
- CLI packages dating to the same time period usually also remove the `share/pixmaps` folder because it is only used by the `.desktop` file. Example:
https://github.com/termux/termux-packages/blob/55445555fffdd0ab801eeb2f95eb410b9a97e31a/packages/mathomatic/build.sh#L12

fix(main/vitetris): remove `.desktop` file from package as intended

---

packages/ffmpeg/build.sh
packages/ffmpeg/postinst.sh.in
packages/libncnn/build.sh
packages/libncnn/use-cross-protoc.patch
packages/libprotobuf/build.sh
packages/libprotobuf/protobuf.subpackage.sh
packages/protobuf-static/build.sh
packages/termux-gui-c/build.sh
x11-packages/opencv/build.sh
x11-packages/opencv/fix-build-with-qt-6.9.patch
x11-packages/spek/build.sh
x11-packages/telegram-desktop/build.sh

- This is fixing multiple problems with:
- `libprotobuf`
- `protobuf-static`
- `glslang`
- `libncnn`
- `opencv`
- `termux-gui-c`
- `ffmpeg`
- `spek`
- `telegram-desktop`
- reverts https://github.com/termux/termux-packages/commit/335b1c1bd185d9be65b1aa62f28d8df1de456238
- partially reverts https://github.com/termux/termux-packages/commit/27db768920497a230bc68e52b3c5cc5e83a61c63
- partially reverts https://github.com/termux/termux-packages/commit/aff43fd305b6c88d390502077c922ae8262239c9
- important related code: https://github.com/termux/termux-packages/commit/f8feaa907b0bee27dd4151431f52a226c0a448aa
- important related code: https://github.com/Kitware/CMake/blob/a2530fd9559023afdbbeaa26748f1edbfa7e22dd/Modules/FindProtobuf.cmake#L821
- `ffmpeg`: depend on new `libandroid-stub`
- `spek`: …

tree-wide: migrate all reverse dependencies of `protobuf-static` to `libprotobuf`

---

packages/libprotobuf/build.sh
packages/protobuf-static/build.sh

- Fixes https://github.com/termux/termux-packages/issues/24598
- This should have **no observable effect on termux-apt**, only on termux-pacman

fix(main/protobuf-static): for termux-pacman, remove `TERMUX_PKG_REPLACES="libprotobuf"` to prevent unintended prompt during every upgrade

---

x11-packages/glfw/build.sh

I am working on porting [vkdt](https://github.com/hanatos/vkdt) and it needs this version. Originally this was using a specific commit from between the 3.3.8 and 3.3.9 releases, now it uses the 3.4 release.
I tested that kitty and glslviewer which depend on this library can launch after updating to 3.4.

Update glfw to 3.4

---

packages/sbcl/build.sh
packages/sbcl/disable-failing-tests-that-were-only-enabled-on-x86.patch
packages/sbcl/pass-testsuite-on-device.patch

- Fixes https://github.com/termux/termux-packages/issues/24526
- The auto update failed to proceed because I put the host SBCL download in `termux_download` instead of `TERMUX_PKG_SRCURL` and I forgot I did that,
- However, there are some changes near areas patched by patch files, so the patches have to be rebased anyway
- `disable-failing-tests-that-were-only-enabled-on-x86.patch`: In https://github.com/sbcl/sbcl/commit/b219fb32f534cb29eba74e3e1bb1195d1556b917, upstream disabled the failing x86-only test by commenting it out, but in rebasing, I have preserved the hunk to disable it on Android should it ever be enabled again upstream, as a reminder for the future that this test was failing on Android-x86 and might need to remain disabled even if upstream enables it again in the future.
- …

bump(main/sbcl): 2.5.4

---

packages/libtool/build.sh

**robertkirkman commit message**:
- Fixes https://github.com/termux/termux-packages/issues/24165
- https://github.com/termux/termux-packages/commit/3a19b11880a7734a414f6c4f572426fedbc5d591, but applied to `/usr/bin` as well instead of only `/bin`.
**john-peterson original message**:
a recent update that used more local host files from /usr turned into a pancake
$SED was hard coded into host path /usr/bin/sed etc in the resulting
files libtool and libtoolize
/data/.../bin/libtoolize
${EGREP="/usr/bin/grep -E"}
: ${FGREP="/usr/bin/grep -F"}
: ${GREP="/usr/bin/grep"}
: ${LN_S="ln -s"}
: ${SED="/usr/bin/sed"}

fix(main/libtool): Correct more absolute paths to some binaries for `termux-exec`-less fallback support

---

build-package.sh
scripts/build/termux_extract_dep_info.sh
scripts/build/termux_step_create_timestamp_file.sh
scripts/build/termux_step_get_dependencies.sh
scripts/utils/termux/package/termux_package.sh

Removed external commands invocations where possible.
United some conditions under single test invocation
Refactored termux_extract_dep_info to avoid re-sourcing build.sh.
Modified package extraction sequence to avoid storage hit and avoid spawning two more commands for checking if in-tar files are prefixed with `./` or not.
With these changes `termux_step_dependencies` execution time drops from `12s` to `7s` during `kf6-breeze-icons` rebuilding.
Also it reduces `~0.1s`-`~2.0s` per package during archive extracting step (depends on package size), which is good for packages with lots of dependencies (like `kf6-breeze-icons`).

chore: optimize termux_step_get_dependencies

---

scripts/build/termux_get_repo_files.sh

Removed duplicating code and got rid of external commands (seq and sed) invocations during the preparation phase.
This change reduces latency of `termux_get_repo_files`.
It does not matter much, but it also serves as PoC and training for parallel dependency downloading which will be implemented later.
Parallelizing is pretty much naive and here we do not track which file downloading failed, we simply bail on any downloading failure.

scripts(termux_get_repo_files): parallelize fetching files and refactor

---

scripts/build/termux_extract_dep_info.sh

Near zero-cost optimization which slightly reduces `termux_step_get_dependencies` execution by second (drop from ~7s to ~6s for `kf6-breeze-icons`) which is good when you debug some package's configure step and re-run `./build-package.sh` after each small change.

scripts(termux_extract_dep_info): optimize by using bash builtins

---

scripts/bin/update-packages
scripts/build/termux_get_repo_files.sh
scripts/run-docker.sh
scripts/updates/utils/termux_pkg_is_update_needed.sh
scripts/utils/termux_reuse_pr_build_artifacts.sh

Small change to let image detect CI and perform folding of some long and usually not so important listings, like log of `termux_step_get_dependencies` which becomes irrelevant immediately after the step is finished.

scripts(run-docker): let docker image detect CI and fold some long logs

---

packages/screen/build.sh

This commit makes screen's output consistent with tmux, allowing for more colors to be displayed.

screen: enable truecolor display by default

---

scripts/build/termux_extract_dep_info.sh
scripts/build/termux_step_get_dependencies.sh
scripts/build/termux_step_setup_cgct_environment.sh

Deduplicated some code.
Reduced one sourcing bash script per package for speed by extracting `TERMUX_PKG_ON_DEVICE_BUILD_NOT_SUPPORTED` during `termux_extract_dep_info`.
Enquotted previously not quotted strings for consistency with other similar places in scripts.
Removed treating variable as a command, replaced with explicit comparing with `true` literal.
Condensed/compacted some conditional blocks by applying short-circuit evaluation to reduce excessive code verbosity.
That is the last change before implementing parallel dependency download (to make CI build packages faster).

scripts(termux_step_get_dependencies): refactor and consistency

---

x11-packages/firefox/0029-prepend-prefix-to-nsXREDirProvider-absolute-paths.patch
x11-packages/firefox/build.sh

- This is a dependency of https://github.com/termux/termux-packages/pull/24708

fix(x11/firefox): prepend `$TERMUX_PREFIX` to some absolute paths found in `nsXREDirProvider.cpp`

---

packages/erlang/auto-download-ex_doc-noninteractively.patch.beforehostbuild
packages/erlang/build.sh
packages/erlang/disable-docs-of-disabled-features.patch.beforehostbuild
packages/erlang/do-not-set-manpath.patch
packages/erlang/erlang-doc.subpackage.sh

- Fixes https://github.com/termux/termux-packages/issues/24624
- This is able to make the commands `man erl` and `erl -man erl` both work, and also, several others
like `man run_erl`, `erl -man run_erl`, and more. Unfortunately,
it is **not** possible to get the `erl -man io` to fully work, but the erlang command
`h(io).` inside the interactive `erl` shell already provides a help page for `io`,
and also, **both Arch Linux and Debian also cannot currently run the command `erl -man io`**
**successfully, even while all their erlang packages are installed**.
The reason this happened is because Erlang version 27 upstream no
longer supports the `erl -man io` command, so all implementations of
it will be at best stuck at the manpage content from Erlang version
26.
- building docs requires using …

fix(main/erlang): enable building manpages and HTML docs

---

packages/libde265/build.sh
packages/libde265/only_export_decoder_api.patch

Import updated patch from debian.
https://salsa.debian.org/multimedia-team/libde265/-/blob/f1eb80470340756d3a0de6bf13c48fc2d1e435b2/debian/patches/only_export_decoder_api.patch
Fix the following warning with proper LDFLAGS.
llvm-readelf: warning: './lib/libde265.a':
libclang_rt.builtins-aarch64-android.a has an unsupported file type
* Fixes #24603

bump(main/libde265): 1.0.16

---

x11-packages/xfce4-cpugraph-plugin/build.sh

bump(x11/xfce4-cpugraph-plugin): 1.3.0

---

x11-packages/xfce4-battery-plugin/build.sh

bump(x11/xfce4-battery-plugin): 1.2.0

---

x11-packages/xfce4-genmon-plugin/build.sh

bump(x11/xfce4-genmon-plugin): 4.3.0

---

x11-packages/xfce4-timer-plugin/build.sh

bump(x11/xfce4-timer-plugin): 1.8.0

---

x11-packages/xfce4-calculator-plugin/build.sh

bump(x11/xfce4-calculator-plugin): 0.8.0

---

x11-packages/xfce4-eyes-plugin/build.sh

bump(x11/xfce4-eyes-plugin): 4.7.0

---

x11-packages/xfce4-docklike-plugin/build.sh

bump(x11/xfce4-docklike-plugin): 0.5.0

---

x11-packages/xfce4-netload-plugin/build.sh

bump(x11/xfce4-netload-plugin): 1.5.0

---

packages/bitlbee/build.sh
packages/bitlbee/configure.patch

This fixes the following compiler error.
ld.lld: error: --fix-cortex-a53-843419 is only supported on AArch64 targets
The configure.patch is modified to replace libgcrypt-config with equivalent pkg-config command. Otherwise, libgcrypt-config is picked up from host system and -L/usr/lib/x86_64-linux-gnu is added to LDFLAGS.
* Fixes #24870

fix(main/bitlbee): Fix building due to conflict with host library path

---

scripts/build/termux_create_debian_subpackages.sh
scripts/build/termux_create_pacman_subpackages.sh

The checking algorithm is under the algorithm where subpackage files are included. That is, the algorithm for including subpackage files is not regulated by the algorithm of the supported architecture, which in turn can create unplanned inclusions of subpackage files that should be in the main package according to the plan.

termux_create_{debian,pacman}_subpackages.sh: fix the checking scheme for excluded archs

---

packages/pass-otp/build.sh
packages/pass-otp/otp.bash.patch
packages/pass-otp/support-passage.patch
packages/passage/build.sh

Add patch with passage support.
This also removes pass from dependencies.
There is also a second commit that fixes passage so it works with pass-otp.

bump(main/pass-otp): 1.2.0-p20221228

---

x11-packages/qt6-qtbase/build.sh

```shell
CMake Error at /data/data/com.termux/files/usr/lib/cmake/Qt6ExampleIconsPrivate/Qt6ExampleIconsPrivateTargets.cmake:110 (message):
The imported target "Qt6::ExampleIconsPrivate_resources_1" references the
file
"/data/data/com.termux/files/usr/lib/objects-Release/ExampleIconsPrivate_resources_1/.qt/rcc/qrc_example_icons_init.cpp.o"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
"/data/data/com.termux/files/usr/lib/cmake/Qt6ExampleIconsPrivate/Qt6ExampleIconsPrivateTargets.cmake"
but not all the files it references.
Call Stack (most recent call first): …
```

fix(x11/qt6-qtbase): Don't remove files needed for PySide6 build

---

packages/ncftp/build.sh

autoreconf was added in d3fbf84d472a183c8fd1e8c20109f073886247ec commit it is no longer required after e850aab8fd517ac4f93c7de2b89839eab30c0e95
* Fixes #23963

bump(main/ncftp): 3.3.0

---

x11-packages/gimp/build.sh

- Fixes https://github.com/termux/termux-packages/issues/24779
- With the current set of features in termux-packages, it does not seem possible to have `TERMUX_PKG_SHA256`, `TERMUX_PKG_SRCURL=git+`, and `TERMUX_PKG_AUTO_UPDATE=true` simultaneously - this combination does not work because the auto update system does not have a codepath to calculate the `TERMUX_PKG_SHA256` for `TERMUX_PKG_SRCURL=git+` packages, so one of the three things has to be removed.
- There are many instances of `find . -type f ! -path '*/.git/*' -print0 | xargs -0 sha256sum | LC_ALL=C sort | sha256sum` for `TERMUX_PKG_SRCURL=git+` packages in the repository, but this is not completely consistent and does not seem absolutely required either. It is also not used with `TERMUX_PKG_AUTO_UPDATE=true` packages. Maybe in a …

bump(x11/gimp): 3.0.4

---

packages/sbcl/build.sh
packages/sbcl/disable-failing-tests-that-were-only-enabled-on-x86.patch

- Fixes https://github.com/termux/termux-packages/issues/24907
- Rebase `disable-failing-tests-that-were-only-enabled-on-x86.patch` - upstream re-enabled this test, but it is still failing on Android-x86, just like with SBCL 2.5.3

bump(main/sbcl): 2.5.5

---

packages/rust/0006-suppress-hard-linking-failed-warning.patch
packages/rust/build.sh

Well Android does not support hard linking. but rust does not know that and keeps filling the terminal with this useless warning.
This pr patches only one line from the upstream to suppress it.
Please refer to https://github.com/termux/termux-packages/issues/4921.
See this image ![hard-linking](https://github.com/user-attachments/assets/4d7f0aca-4d41-4831-8656-185fa0a638cc)
Note: this issue was reported to the upstream for almost 5 years. But unfortunately it seems that no one really cares about it. https://github.com/rust-lang/rust/issues/75997
@TomJo2000 I followed the commit message guidelines this time ;)

enhance(main/rust): Suppress hard linking failed warning.

---

packages/nodejs/build.sh
packages/nodejs/common.gypi.patch
packages/nodejs/deps-v8-src-trap-handler-trap-handler.h.patch
packages/nodejs/node.gyp.patch
packages/nodejs/tools-v8_gypfiles-v8.gyp.patch

A lot of tests are failing in comparision to v23.x releases. In v23.x I had managed to squash down the number of tests failing to less than 20, with most of them being due to permissions, and would pass on rooted devices. Let's hope to do the same once again. And since this is the latest release, I don't plan to fix all the tests in one go, may go ahead with keeping the tests broke for time and incrementally fix them. Users who want stable and highly test version of node are requested to use the LTS package (nodejs-lts) instead to install the latest LTS release
List of failing tests:
~~TODO, the tests are still running on my device, so it's going to take some time to list them :)~~ The tests were failing because I was running v24.0.1 tests with v22 nodejs binary, there are no significant …

bump(main/nodejs): 24.1.0

---

packages/plantuml/build.sh

- Fixes https://github.com/termux/termux-packages/issues/24917
- Increase gradle JVM memory to avoid `the JVM garbage collector is thrashing`

bump(main/plantuml): 1.2025.3

---

x11-packages/musescore/build.sh
x11-packages/musescore/musescore-soundfonts.subpackage.sh

- Packaging a commit of master branch after the merge of: https://github.com/musescore/MuseScore/pull/25016
- Fixes https://github.com/termux/termux-packages/issues/24301 on Samsung Galaxy A70 SM-A705FN

bump(x11/musescore): 4.5.2-p20250602

---

scripts/build/configure/termux_step_configure_cabal.sh
scripts/build/setup/termux_setup_cabal.sh
scripts/build/termux_step_make.sh

- Moved project level configuration to global. They are applied to
dependencies too (which wasn't the case with former).
See: https://github.com/termux/termux-packages/issues/24930

scripts(build): Fix cabal configuration

---

x11-packages/xeyes/build.sh

- Closes #24967
This is basically a one to one port of the Arch build script for `xeyes`.
https://gitlab.archlinux.org/archlinux/packaging/packages/xorg-xeyes/-/blob/1.3.0-2/PKGBUILD

addpkg(x11/xeyes): 1.3.0

---

packages/libusbmuxd/build.sh

Revert to tagged release from git commits which was added in fdfec333a311212389e948d28c32e6a2796baca4
* Fixes #24957

bump(main/libusbmuxd): 2.1.1

---

packages/libwebp/build.sh
packages/libwebp/disable-check-cpufeatures.patch

- Context: similar to https://github.com/termux/termux-packages/pull/24956. This is needed as a deeply-nested dependency of a potential improved Blender package.
- Enable manpages
- New files provided after this change:
```diff
/data/data/com.termux/files/usr/lib/pkgconfig/libwebpdemux.pc
/data/data/com.termux/files/usr/lib/pkgconfig/libwebpmux.pc
/data/data/com.termux/files/usr/share
+/data/data/com.termux/files/usr/share/WebP
+/data/data/com.termux/files/usr/share/WebP/cmake
+/data/data/com.termux/files/usr/share/WebP/cmake/WebPConfig.cmake
+/data/data/com.termux/files/usr/share/WebP/cmake/WebPConfigVersion.cmake
+/data/data/com.termux/files/usr/share/WebP/cmake/WebPTargets-release.cmake
+/data/data/com.termux/files/usr/share/WebP/cmake/WebPTargets.cmake …
```

fix(main/libwebp): migrate to CMake to provide `WebPConfig.cmake`

---

packages/tree-sitter-lua/build.sh
packages/tree-sitter/build.sh
packages/tree-sitter/tree-sitter-cross-tools.subpackage.sh
scripts/setup-ubuntu.sh

fix(main/tree-sitter): Use same tree-sitter version for host

---

x11-packages/libfm-qt/build.sh
x11-packages/lximage-qt/build.sh
x11-packages/lxqt-about/build.sh
x11-packages/lxqt-archiver/build.sh
x11-packages/lxqt-config/build.sh
x11-packages/lxqt-globalkeys/build.sh
x11-packages/lxqt-notificationd/build.sh
x11-packages/lxqt-panel/build.sh
x11-packages/lxqt-runner/build.sh
x11-packages/lxqt-session/build.sh
x11-packages/obconf-qt/build.sh
x11-packages/pcmanfm-qt/build.sh
x11-packages/qt6-qtbase/build.sh
x11-packages/qt6-qtbase/do-not-use-cross-tools-paths-ondevice-for-reverse-deps.patch
x11-packages/qterminal/build.sh
x11-packages/qtermwidget/build.sh
x11-packages/qtutilities/build.sh
x11-packages/tageditor/build.sh

- Fixes https://github.com/termux/termux-packages/issues/24975
Fixes the build in `TERMUX_ON_DEVICE_BUILD=true` mode of reverse dependencies of qt6 like `tageditor`, where `CMAKE_HOST_SYSTEM_NAME` is "`Android`" and the path `$TERMUX_PREFIX/opt/qt6/cross` should never be used because it contains GNU/Linux binaries that are sent there by the automatic installation of `qt6-*-cross-tools packages` during `termux_step_get_dependencies()` by `scripts/buildorder.py` installing the `qt6-*-cross-tools` subpackages of `qt6-*` packages during the builds of reverse dependencies of qt6,
https://github.com/termux/termux-packages/blob/da3717f43930c480bd8dfcf1c002430e43e49013/scripts/buildorder.py#L159
without breaking the builds of anything in `TERMUX_ON_DEVICE_BUILD=false` mode, where …

fix(x11/qt6-qtbase): only send the `opt/qt6/cross` `QT_HOST_PATH` to cross-compilations of revdeps, not on-device builds

---

packages/vapoursynth/build.sh

- closes #24826
I've got it building, but I haven't confirmed if the `vapoursynth` package is complete and/or working yet.
I'd appreciate some help in that regard.
<h1><em></em></h1>  
<sup>(This is a pre-written, saved reply.)</sup>
If you want to test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux/termux-packages/actions/runs/15556056585).
After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instructions, if needed.</summary>
<p>
```bash
termux-info
pkg install unzip tar
unzip debs-aarch64-*.zip
tar xf debs-aarch64-*.tar
pkg install -- ./debs/*.deb
rm -rfi debs debs-aarch64-*.zip debs-aarch64-*.tar
```
</p>
</details>

addpkg(main/vapoursynth): 72

---

scripts/lint-packages.sh

- Found while reviewing #25042
This fixes an edgecase where `git merge-base` is unable to find a base commit with `origin/master` if the PR is opened from the `master` branch of the fork.

fix(scripts/lint-packages): don't fail if branch name is `master`

---

packages/git/build.sh
packages/git/compat-posix.h.patch
packages/git/config.mak.uname.patch

This PR:
- closes #25075
- Moves the old `git.patch` from `git-compat-util.h` to the newly split out `compat/posix.h`,
and renames the patch accordingly.
- Regenerates `config.mak.uname.patch`, which had stopped applying properly.
- Specifies that `openssl` should be used for Git's pRNG function,
it now defaults to trying to use `getrandom()`, which causes a build error.
Git *probably* fell back to its `/dev/urandom` pRNG function before 2.50.0 on Termux.
But I don't know of a way to easily test this.
OpenSSL's pRNG should work just fine without introducing changes noticeable to the user.
- Cleans up some slop in the build script.

bump(main/git): 2.50.0

---

packages/gawk/build.sh

- For consistency with `bash`: https://github.com/termux/termux-packages/pull/25113#issuecomment-2993204795
https://github.com/termux/termux-packages/blob/6d9084fcd742271e7c3eab852f0a34a6ed167d7e/packages/bash/build.sh#L37
- This kind of command prompts to autosend bug reports to gnu.org.
- This is not desirable because the gnu.org bug tracker should not be overwhelmed by bugs from an esoteric platform that might not be convenient for upstream developers.
- It is more efficient for bugs in Termux packages to be reported here, then forwarded to upstream issue trackers if reproducible on a mainstream desktop platform familiar to desktop developers.
- It is assumed that is why the choice was made for `bash`, and that the same removal should be applied to `gawkbug`.
```
Send bug report to …
```

chore(main/gawk): remove `gawkbug`

---

packages/nmap/build.sh

- Fixes https://github.com/termux/termux-packages/issues/25111
- Also, reformat the `TERMUX_PKG_EXTRA_CONFIGURE_ARGS` for readability

fix(main/nmap): only use `llvm-strip` when not a debug build

---

packages/await/build.sh

- Supersedes #25042
<sup>Apparently I didn't remember to specify the correct remote when pushing to the branch

fix(main/await): replace dead homepage

---

packages/mplayer/build.sh

- Fixes https://github.com/termux/termux-packages/issues/25137
- Prevents `scripts/run-docker.sh ./build-package.sh -I -f libmpeg2 aalib libcaca mplayer` from creating a malformed `mplayer` package
- Confirmed to prevent that with testing and this command: `ldd $(which mplayer) | grep -e caca -e mpeg2 -e aa`

fix(main/mplayer): explicitly disable some video playback dependencies

---

.github/workflows/codeql.yml
.github/workflows/golang_validation.yml

Potential fix for [https://github.com/termux/termux-packages/security/code-scanning/1](https://github.com/termux/termux-packages/security/code-scanning/1)
To fix the issue, add a `permissions` block at the root of the workflow file. This block will define the minimal permissions required for the workflow. Based on the provided workflow, it primarily performs repository cloning, environment setup, and artifact uploading. These tasks only require `contents: read` and `actions: write` permissions. Adding this block ensures that the workflow adheres to the principle of least privilege.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

packages/dpkg/build.sh
packages/dpkg/mandoc_hook.patch

- Fixes https://github.com/termux/termux-packages/issues/25217
- Moves the call to `update_mandoc()` to a codepath that is simultaneously:
- more likely to run when necessary (such as during `--config` subcommands)
- and less likely to run when unnecessary (such as during `--install` and `--remove` subcommands)
- I would be interested in test results from others' devices if possible, because unfortunately, when I tested the original version of this patch it initially worked, but then stopped working after a few days.

fix(main/dpkg): fixes for the `update-alternatives` -> `mandoc` hook

---

packages/command-not-found/build.sh

This new version of command-not-found comes with support for
'.alternatives' file
Closes termux/command-not-found#20

bump(main/command-not-found): 3.1

---

packages/clvk/build.sh

clang-18 was removed from host in af650801dbf953f11ac8c7b3a7d71e067ecd95cf commit.
* Fixes #25245

fix(main/clvk): Use llvm-19 after the migration from llvm-18

---

packages/gh/build.sh

Remove unnecessary documentation related to developing `gh` which is not related to general usage of `gh`. See this readme https://github.com/cli/cli/blob/v2.75.0/docs/README.md
* Fixes #25304

bump(main/gh): 2.75.0

---

scripts/build/setup/termux_setup_cabal.sh

- Executable stripping does not work while cross-compiling

scripts(build): Fix regressions introduced in #24952

---

packages/hledger/build.sh
packages/hledger/splitmix-patches/0001-add-conditionals-to-support-Android.patch
scripts/build/configure/termux_step_configure.sh
scripts/build/termux_step_make.sh
scripts/build/termux_step_make_install.sh

Greetings,
This is a PR in an attempt to package [`hledger`](https://github.com/simonmichael/hledger) for Termux. I'm not very accustomed with the way that Haskell programs are built, and even less so with Termux-specific process. I've tried to follow the general steps where I could - added dependencies and other small tweaks.
I've decided to adjust common build steps `make` and `make_install` to also detect other naming convention for Cabal projects.
But the build fails now on compiling `exe:alex` and I'm out of luck. Any help or pointers are very welcome.
Here I also attach the full build log when running `./scripts/run-docker.sh ./build-package.sh -f -I hledger`.
Ideally this closes https://github.com/termux/termux-packages/issues/3803 and …

addpkg(main/hledger-cli): 1.43.2

---

packages/lux-cli/build.sh

- Fixes https://github.com/termux/termux-packages/issues/24927
- This highly-requested package is described by upstream as not supporting cross-compilation, but attempting to cross-compile it appears to be working anyway, if performed as shown in this `build.sh`
https://github.com/nvim-neorocks/lux/blob/c794f476cb459df5bcb6e971c0c6f76e6a2a4dd4/lux-lib/src/lua_rockspec/platform.rs#L72
- Bash completions have been tested and are working

addpkg(main/lux-cli): 0.8.3

---

packages/yosys/Makefile.patch
packages/yosys/build.sh

- Fixes https://github.com/termux/termux-packages/issues/25349
- Adds `ncurses` to `TERMUX_PKG_DEPENDS`, because `yosys` is linked to `libncursesw.so.6`.

fix(main/yosys): enable `abc`

---

packages/helix/build.sh
packages/helix/helix.alternatives
packages/helix/libc++_shared-not-found.patch

- Fixes https://github.com/termux/termux-packages/issues/25363
- Add `.alternatives` file for `editor` for `helix`
- Remove `$TERMUX_PREFIX/opt/helix` at the start of `termux_step_make_install()` in order to prevent errors during repeated builds

bump(main/helix): 25.07

---

packages/libcommons-lang3-java/build.sh

- Unfortunately, during the development of https://github.com/termux/termux-packages/pull/25127, `libcommons-lang3-java` was auto-updated to the same version as in my branch, and when I rebased and merged my branch, the automerge automerged the two bumps into the same version, but this has unfortunately prevented the change of dependency of `libcommons-lang3-java` from `openjdk-17` to `openjdk-21` from deploying into the mirror.

revbump(main/libcommons-lang3-java): 3.18.0-1

---

packages/ncurses/build.sh

The original `fossies.org` source now requires human verification and refuses to connect in CI. [Context](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/24944#note_2633682997).
Updated to another source that provides the same file with exact checksum.
```
$ shasum -a 256 rxvt-unicode-9.31-2.tar.bz2  # from fossies.org
aaa13fcbc149fe0f3f391f933279580f74a96fd312d6ed06b8ff03c2d46672e8  rxvt-unicode-9.31-2.tar.bz2
$ shasum -a 256 rxvt-unicode-9.31.tar.bz2    # from dist.schmorp.de
aaa13fcbc149fe0f3f391f933279580f74a96fd312d6ed06b8ff03c2d46672e8  rxvt-unicode-9.31.tar.bz2
```

fix(ncurses): connection error with package source

---

packages/vim/build.sh
x11-packages/vim-gtk/build.sh

Vim's tutor files are now only provided in UTF-8 and the encoding suffixes have been dropped.
- Upstream PRs/commit
https://github.com/vim/vim/pull/17582
https://github.com/vim/vim/pull/17586
https://github.com/vim/vim/commit/8d9d2b222dbd09e091ac2bfce5ab105990e85b78
<h1><em></em></h1>  
- closes #25232
- closes #25233

bump(main/vim, x11/vim-gtk): 9.1.1550

---

x11-packages/icewm/build.sh
x11-packages/icewm/cross-compiling.patch
x11-packages/icewm/fix-mailbox-port-datatype.patch
x11-packages/icewm/genpref.diff
x11-packages/icewm/mblen.patch
x11-packages/icewm/suppress-network-permission-warning.patch
x11-packages/xdg-menu/build.sh
x11-packages/xdg-menu/termux.patch

- Fixes https://github.com/termux/termux-packages/issues/25426
```bash
pkg upgrade
pkg install x11-repo
pkg install termux-x11-nightly icewm xdg-menu
mkdir -p ~/.icewm/
xdg_menu --format icewm \
--fullmenu \
--root-menu \
$PREFIX/etc/xdg/menus/termux-applications.menu \
> ~/.icewm/programs
export DISPLAY=:0 TERMUX_X11_XSTARTUP=icewm-session
termux-x11 &
```
I was on the fence about whether or not to add `xdg_menu` commands to `postinst` scripts of window managers that don't generate their own menus by default, but I decided not to,
because originally, the idea was that users of IceWM, Openbox, Fluxbox and others are supposed to have control over their own configuration files and choose their own way to set up their menu, and learn how to manually run a menu autogenerator,
I just …

addpkg(x11/icewm): 3.8.1

---

packages/emacs/build.sh
packages/emacs/site-start.el

Scrolling on the touch screen is now registered as wheel-up and wheel-down instead of mouse-4 and mouse-5. Adjust our site-start.el to fix it.

fix(main/emacs): make touch scroll work

---

scripts/build/setup/termux_setup_rust.sh

Missed from ff64c17fbb15f4a2c547b6dc971cfbd0d1a3464c
Fix https://github.com/termux/termux-packages/pull/25458#issuecomment-3129243458

scripts(termux_setup_rust): handle rust-toolchain.toml edge case

---

packages/apr/apr-config-do-not-use-upstream-cross-compiler-detection.patch
packages/apr/build.sh

- Fixes https://github.com/termux/termux-packages/issues/25495

fix(main/apr): do not apply upstream's cross-compiling changes to `apr-config`'s includes path when cross-compiling reverse dependencies of `apr`

---

packages/mailutils/build.sh

Enable gdbm option for libmu_dbm and uidnew binaries. See changelog https://cgit.git.savannah.gnu.org/cgit/mailutils.git/tree/NEWS?h=v3.20
* Fixes #25551

bump(main/mailutils): 3.20

---

x11-packages/icewm/build.sh

- `termux-exec` should handle the path replacement for most of these, but patch all of them just in case
- I checked, and there is no string `/usr` or `/etc` in the code of IceWM that is not representing a UNIX-like system resources folder path or et cetera path respectively that can be safely and correctly replaced with `$TERMUX_PREFIX`, therefore this global replacement is safe
- (**Note: this software does attempt to use some features/files that do not exist in Termux/Android, like `(PREFIX)/etc/shells` and `(PREFIX)/etc/passwd`**. I tried for a little while to implement those features over `termux-tools` [shells implementation] / `termux-auth` [passwd implementation], but I wasn't able to do that yet. As far as I can tell, if these features are not available, they just don't do …

fix(x11/icewm): set `$TERMUX_PREFIX` throughout the software

---

packages/git-extras/build.sh

I had a typo that nobody noticed during review process

fix(main/git-extras): typo in recommended dependencies

---

packages/util-linux/build.sh
packages/util-linux/schedutils-sched_attr.h.patch

Alternative approach to https://github.com/termux/termux-packages/pull/25606, see information and discussion there.
This change currently makes a `#ifndef __ANDROID__` to avoid redefining `struct sched_attr` - a more proper approach (before e.g. considering upstreaming) is to check for the existence of the struct instead.

fix(main/util-linux): Fix building with NDK r28

---

x11-packages/vsix-package-codelldb/CMakeLists.txt.patch
x11-packages/vsix-package-codelldb/adapter-CMakeLists.txt.patch
x11-packages/vsix-package-codelldb/build.sh
x11-packages/vsix-package-codelldb/code-oss-extension-codelldb.subpackage.sh
x11-packages/vsix-package-codelldb/disable-sbapi.patch
x11-packages/vsix-package-codelldb/fix-tsconfig-cmake-builddir-path.diff
x11-packages/vsix-package-codelldb/lldb-paths.patch
x11-packages/vsix-package-codelldb/main.rs.patch
x11-packages/vsix-package-codelldb/weaklink-android.diff

- Fixes https://github.com/termux/termux-packages/issues/24715
- This single build works with both `code-oss` and also with another editor that exists somewhere else, but for the time being, only `code-oss` can be found in this Termux repository, so for now this package only references `code-oss` and could be expanded to have a subpackage that depends on the other editor if it happens to come here in the future

addpkg(x11/code-oss-extension-codelldb): 1.11.5

---

packages/pypy3/0012-do-not-use-wno-discarded-qualifiers.patch
packages/pypy3/build.sh
packages/pypy3/pypy3-tests.subpackage.sh
packages/pypy3/pypy3-tkinter.subpackage.sh
packages/pypy3/termux.py.in

- After https://github.com/termux/termux-packages/pull/25487, which was built with NDK r27c
- This is like https://github.com/termux/termux-packages/pull/25627, but for the package `pypy3` instead of the package `libllvm`
- Also prevent the repetitive warning `warning: unknown warning option '-Wno-discarded-qualifiers'`
- Also refactor the `$TERMUX_PACKAGE_FORMAT` check
- Also add `postinst` script to clean up runtime-generated files of previous `pypy3` versions that do not match the current `$_MAJOR_VERSION`

fix(main/pypy3): fix build with NDK r28c

---

packages/sendme/build.sh

- Fixes https://github.com/termux/termux-packages/issues/25293
- It is true that the package is very easy to compile, however, the problem explained in the issue is that it takes an extremely long time to compile on a slow device.

addpkg(main/sendme): 0.27.0

---

packages/discordo/build.sh

- Fix build with NDK r28c by properly porting the Go modules https://github.com/golang/mobile and https://github.com/golang-design/clipboard to Termux (X11 for Android) to fix the error `android.c:171:52: error: incompatible pointer to integer conversion passing 'ANativeWindow *' (aka 'struct ANativeWindow *') to parameter of type 'EGLNativeWindowType' (aka 'unsigned long') [-Wint-conversion]` in this line of the "mobile" module, and other errors.
- https://github.com/golang/mobile/blob/395d808d53cdcc50f14b84fcb8049ba2c6427a69/app/android.c#L171
- This does not seem to make `libx11` a required runtime dependency, because the TUI interface still works after this and the binary is not linked to `libx11` - it does become a build dependency, otherwise another error would happen.
- Add …

bump(main/discordo): 2025.08.06

---

packages/povray/build.sh

- Progress on https://github.com/termux/termux-packages/issues/23492 by fixing build with the `libc++` of NDK r28c
- change associated with this fix: **copy and paste a solution written as additional `CPPFLAGS` from one of the other major `libc++`-based distros, FreeBSD**: https://github.com/freebsd/freebsd-ports/commit/59a81f5dcbaa52d4fdcfcd42199dfe923c1a041f
- Fixes https://github.com/termux/termux-packages/issues/25752
- change associated with this fix: **removal of explicit `-Ofast` overoptimization**
- Switch from building with `-std=c++11` to `-std=c++14` like FreeBSD does, because c++14 is newer than c++11 but it still does not have the error with this software that c++17 does.
- Expand `$TERMUX_PREFIX` in `postinst` at build-time, not run-time

fix(main/povray): Fix build with NDK r28c and other fixes

---

packages/libtirpc/build.sh

Use autoreconf instead of multiple autotools command to fix the error.
Makefile.am: error: required file './INSTALL' not found
Makefile.am:   'automake --add-missing' can install 'INSTALL'
* Fixes #25819

bump(main/libtirpc): 1.3.7

---

packages/task-spooler/build.sh
packages/task-spooler/tsp.patch

This is an addendum to an earlier fix for #5662. Task-spooler provides `ts` and `ts.1`, which is already provided by moreutils, but is an entirely different tool (for prefixing input with a timestamp). Since moreutils is a very common utility package and task-spooler is much less commonly used, it should be renamed. This PR addresses this by renaming `ts` to `tsp` and patching the man page accordingly. This way both moreutils and task-spooler can be installed simultaneously.
This actually brings the package in line with Debian which has long since done the same.
https://sources.debian.org/patches/task-spooler/1.0.3%2Bdfsg1-1/tsp.patch/
The same is true in Ubuntu:
https://manpages.ubuntu.com/manpages/jammy/man1/tsp.1.html
And ArchLinux: …

enhance(main/task-spooler): Rename to tsp to avoid conflict with moreutils

---

packages/boost/build.sh
packages/boost/prepend-prefix-to-tmp-paths.patch

- Fixes a problem explained here (that `boost` lacks needed `/tmp` path patches) https://github.com/termux/termux-packages/pull/25025
- Methodology to find paths to prepend:
- Ignore all folders named `doc`
- Ignore all folders named `test`
- Find them using `grep -rn $TERMUX_PKG_SRCDIR -e '"/tmp' -e 'data/local/tmp'`
- Ignore codepaths that don't compile for Android (`#ifndef __ANDROID__`)
- Try to calculate the code behavior to make sure every patched instance is a true absolute path (and not a path subcomponent that could be appended to a longer path)
- Dependency of https://github.com/termux/termux-packages/pull/25826
- Enable on-device building because it does not modify any files owned by any packages that are not `boost` or one of its subpackages

fix(main/boost): prepend `$TERMUX_PREFIX` to all absolute `/tmp` paths

---

packages/aspell/android-14-support.patch
packages/aspell/build.sh

- Fixes https://github.com/termux/termux-packages/issues/25825 (The command `aspell dump modes` on Android 14+)
- NetBSD uses this patch in its present-day releases, https://github.com/NetBSD/pkgsrc/commit/72ca05d074a5d4a271f71fd92a6370965674007d
- and it is necessary for Android 14+ because part of Android 14's source code is copied and pasted from that newer NetBSD. https://android-review.googlesource.com/c/platform/bionic/+/2290937

fix(main/aspell): apply patch from NetBSD that avoids use of GNU regex extensions

---

packages/libtsduck/build.sh
packages/libtsduck/rename-tsp-to-tsp-tsduck.patch.beforehostbuild

- Fixes https://github.com/termux/termux-packages/issues/25848
- The build system of `libtsduck` automatically calculates the executable name from the name of the source code file, so renaming the file seems to entirely rename the executable.

fix(main/tsduck-tools): rename `tsp` to `tsp-tsduck` to avoid conflict with `task-spooler`

---

x11-packages/kcalc/build.sh

This pull request adds the `kcalc` package to the Termux repository.  
• **KCalc is a scientific calculator from KDE.**

addpkg(x11/kcalc): 25.08.0

---

packages/libx265/1-b354c009a60bcd6d7fc04014e200a1ee9c45c167.patch
packages/libx265/2-51ae8e922bcc4586ad4710812072289af91492a8.patch
packages/libx265/build.sh

Fix building with cmake 4 by backporting two commits:
- https://bitbucket.org/multicoreware/x265_git/commits/b354c009a60bcd6d7fc04014e200a1ee9c45c167
- https://bitbucket.org/multicoreware/x265_git/commits/51ae8e922bcc4586ad4710812072289af91492a8

fix(main/libx265): Fix building with cmake 4 by backporting commits

---

packages/asciinema/build.sh
scripts/updates/utils/termux_pkg_upgrade_version.sh

- Forgot to add a `TERMUX_PKG_UPDATE_VERSION_SED_REGEXP` in #25894.
I'll look into making this a general fix in `scripts/updates/utils/termux_pkg_upgrade_version.sh`.
Should be able to do something similar to the `//_/.` substitution we have already.
https://github.com/termux/termux-packages/blob/e39ee5b950e154eeeb97f6e55a8089e4549be240/scripts/updates/utils/termux_pkg_upgrade_version.sh#L64-L66

fix(scripts/termux_pkg_upgrade_version): handle -suffix versions

---

scripts/lint-packages.sh
scripts/updates/utils/termux_pkg_is_update_needed.sh

Follow up to #25950.
This should catch situations like https://github.com/termux/termux-packages/commit/2798b0f8c59bd2c54c87bb5f696fbb6e33a59069 going forward.
In this case despite being invalid the version did compare as greater than the previous version and produce exit code 0.
```console
dpkg --compare-versions "2025.09.05" lt "2025.09.05a(2)"; echo $?
dpkg: warning: version '2025.09.05a(2)' has bad syntax: invalid character in version number
0
```
To avoid false negatives like this in the future we should use `dpkg --validate-version` in both the auto-updater and the package linter.

enhance(scripts): use `dpkg --validate-version` to check version numbers

---

packages/cmake/build.sh
scripts/build/setup/termux_setup_cmake.sh
scripts/updates/utils/termux_pkg_upgrade_version.sh

We keep forgetting update `termux_setup_*` scripts. This should finally allow custom auto update to do the job.

scripts(auto-update): allow update termux_setup_* scripts, termux_setup_cmake 4.1.1

---

packages/libxls/build.sh
packages/libxls/libxls2csv.subpackage.sh

- Fixes https://github.com/termux/termux-packages/issues/26046
- Just like Arch Linux AUR package `libxls`, except that Arch Linux does not subpackage `libxls2csv`, so it seems appropriate to rename the subpackage https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libxls#n29

fix(main/xls2csv): rename to `libxls2csv`

---

packages/gdb/build.sh
packages/gdb/gdb-nat-linux-btrace.c.patch
packages/gdb/gdbsupport-eintr.h.patch

Also patch `linux-btrace.c` currently fails due to `PAGE_SIZE` being undefined.

bump(main/gdb): 16.3

---

scripts/build/toolchain/termux_setup_toolchain_28c.sh

Currently source.properties is renamed to $_TERMUX_TOOLHAIN_TMPDIR instead of being copying into the directory $_TERMUX_TOOLCAIN_TMPDIR. The directory $_TERMUX_TOOLCAIN_TMPDIR is created from the directory linux-x86_64, move the copying of source.properties to after the folder has been created.

fix(scripts/setup_toolchain_28c): cp source.properties after setting up toolchain tmpdir

---

packages/gnunet/0001-workaround-incomplete-const-changes.patch
packages/gnunet/build.sh

Fix compiler error based on this patch
https://github.com/Homebrew/homebrew-core/commit/6baabc2ed63e31ff2bd43108fd9cad496ed0f74d
* Fixes #26517

bump(main/gnunet): 0.25.0

---

packages/libelf/build.sh

Also adjust build recipe to not build inside source folder due to clang bug
https://github.com/llvm/llvm-project/issues/71925#issuecomment-1987141438
Supersedes #26538

revbump(main/libelf): rebuild for 16KB page size

---

packages/rust/build.sh
scripts/build/setup/termux_setup_rust.sh

Until a fix for rust 1.90.0 runtime issue
Refer #26682

chore(main/rust): temporary pin to 1.89.0

---

packages/leptonica/build.sh

SOVERSION was not changed in the leptonica 1.86.0 but the `set_target_properties()` format was changed in https://github.com/DanBloomberg/leptonica/commit/5dae0e5f9d63c7213004cadd4987869058b85c4d
* Fixes #26662

bump(main/leptonica): 1.86.0

---

packages/just/build.sh
packages/just/just-shim.sh

- This PR is a follow-up to https://github.com/casey/just/issues/1492#issuecomment-3239135217
`just` 1.43.0 introduces the concept of a "ceiling" to `just` which is the top directory that will not be searched past when looking for `justfile`s.
In Termux's case it makes sense to set a global default of `$HOME` for this, while allowing it to be overwritten via the `$JUST_CEILING` environment variable or `--ceiling` flag.
Since there is not currently a way to compile in a default ceiling the most straightforward way to achieve this is to turn `$PREFIX/bin/just` into a shim, akin to what we're doing for `nvim`.
https://github.com/termux/termux-packages/blob/2860bc8eba9c24ed1c064f5c591e621deed09670/packages/neovim/nvim-shim.sh#L12-L13

enhance(main/just): set a default `JUST_CEILING`

---

x11-packages/gspell/build.sh

Since October 2025, only a git tag is created for releasing gspell, and tarballs are no longer uploaded to `download.gnome.org`.
https://gitlab.gnome.org/GNOME/gspell/-/commit/de7091cf01ad6b8a7c55cb6c3eaa6bd2eda5403f
* Fixes #26743

bump(x11/gspell): 1.14.1
