termux/termux-packages

packages/mutt/smime_keys_path.patch

Small patch for smime_keys.pl to call correct openssl binary.

Patch setting termux path to mutt smime_keys.pl

---

disabled-packages/groff/build.sh
disabled-packages/man-db/build.sh

What this pull request contains:
* man-db 2.7.4
* groff 1.22.3
This is my first time contributing to an open source project of any kind, so there's most likely a lot of mistakes that need to be fixed. Here are a few that I've found:
1. `GROFF_TMAC_PATH` is hard coded to the defaults mentioned in the groff(1) man page (with the termux prefix).
2. I've added `$PREFIX/lib/man-db` to `LD_LIBRARY_PATH` in my `~/.profile`.
3. I've aliased `man` to be `man -E UTF-8` to bypass the iconv translation. Since libandroid-support has limited libiconv support, it doesn't handle translating to `en_US.UTF-8//TRANSLIT`.
Let me know what you think!
Some other details:
My .termuxrc:
```bash
#!/usr/bin/bash
export CC_FOR_BUILD="gcc -fdiagnostics-color=always"
export TERMUX_MAKE_PROCESSES="$(nproc)"
export …
```

Add man-db and groff packages

---

packages/mathomatic/build.sh

- Enable readline.
- Remove .desktop files and icon not used in Termux.
- Compile with -DUSE_TGAMMA to remove warning and improve speed.
- Compile with -DBOLD_COLOR to improve color visibility.

mathomatic: Minor changes

---

packages/p7zip/build.sh
packages/p7zip/makefile.patch

I put almost 3 hours on this!
It ships with a lot of makefiles for various platforms, notably
one for android_arm. I patched it a bit because Termux already gives
many of the goodies. Probably it could be simplified.
Most of the time went on tinkering with flags and waiting for the
Docker container to reload the new files...there must be a better way!
p7zip doesn't seem to honor $prefix, instead it uses $DEST_HOME.

p7zip: add package

---

buildorder.py

I spent some time rewriting `buildorder.py` :)
The check for `BROKEN.txt` was removed (since we're now dealing with broken pkgs by putting them into `disabled-packages`).
The buildorder is now slightly different because of the way that the script processes/sort the lists, but **it's deterministic!** If you run the script many times (with the same pkgs/deps) you'll get always the same order!
And last, but not least: you can ask it the order for certain packages only. Let's say you want to hacking on `imagemagick`... hmm... what deps do you need to use `./build-packages.sh` with, before compiling it?
```
% python buildorder.py imagemagick 
fftw
libffi
pcre
glib
libbz2
libjpeg-turbo
liblzma
libpng
libtiff
libxml2
littlecms
openjpeg
freetype
fontconfig
libpixman
libcairo
harfbuzz
pango …
```

Huge refactor of buildorder.py!

---

build-all.sh

Enhanced build-all.sh to:
- Print the messages logged to ALL.out, to keep track of progress
- Print an error message when it fails, with a hint to what failed
- Keep track of packaged that build successfully, and if build-all failed:
- Skip packages that were build successfully in the previous run.

build-all.sh status messages and ability to resume previous run.

---

packages/elinks/build.sh
packages/wol/build.sh

I use [ELinks](http://elinks.or.cz) instead of Lynx, so I missed it on Termux:
> ELinks is an advanced and well-established feature-rich text mode web (HTTP/FTP/..) browser. ELinks can render both frames and tables, is highly customizable and can be extended via Lua or Guile scripts. It is quite portable and runs on a variety of platforms. Check the about page for a more complete description.
Package is compiled with OpenSSL, libidn and expat support and with 256 colors.
I also added [wol](http://sourceforge.net/projects/wake-on-lan/), a small wake-on-lan utility:
> wol implements Wake On LAN functionality in a small program. It wakes up hardware that is Magic Packet compliant.

New packages: elinks and wol

---

packages/php/ext-standard-proc_open.c.patch

Make PHP function [proc_open()](https://secure.php.net/proc_open) work in termux, previously there was hardcoded `/bin/sh`, now it's updated to use `@TERMUX_PREFIX@/bin/sh`

php: Update path to /bin/sh for proc_open()

---

packages/php/build.sh

Make function [glob()](https://secure.php.net/glob) available in PHP, this required linking with available in Termux `libandroid-glob`

php: Enable glob() function

---

Dockerfile
packages/hunspell-en-us/build.sh

this is the correct fix as discussed here https://github.com/termux/termux-packages/pull/160
furthermore: build-all.sh was broken, because hunspell-en-us and hunspell depended on eachother, so I changed that also

*.py scripts are in scripts/, now Dockerfile knows that too

---

Dockerfile

as requested, I checked the new Dockerfile, it misses the instruction to unpack the android-sdk, otherwise it seems to be fine and I was able to build a couple of packages with it

unpack android-sdk before moving unpacked data

---

disabled-packages/libtalloc/build.sh
disabled-packages/proot/src-execve-enter.c.patch
disabled-packages/proot/src-tracee-mem.c.patch

* Don't fail `libtalloc` build if we couldn't `rm` previous version
* Clear `errno` before `ptrace(PTRACE_PEEKDATA)`
* Handle relocated embedded loader
* Don't reject binaries with linker having it's own `DT_INTERP` section
Appears to work now, through I did only simple tests, such as:
```
proot -0 id
proot -b /sdcard:/sys ls /sys
```
I think it's now might ready to be moved out of `disabled-packages`
Also, possibly I should upstream some of these changes, not sure about that.

Make PRoot work

---

packages/php/build.sh

Enable zlib extension in PHP (for [gzinflate](https://secure.php.net/gzinflate) and compressed PHAR support, php is linked with libz.so anyway)

php: Enable zlib extension

---

packages/byobu/build.sh

I added the great [Byobu](byobu.co):
> Byobu is a GPLv3 open source text-based window manager and terminal multiplexer. It was originally designed to provide elegant enhancements to the otherwise functional, plain, practical GNU Screen, for the Ubuntu server distribution. Byobu now includes an enhanced profiles, convenient keybindings, configuration utilities, and toggle-able system status notifications for both the GNU Screen window manager and the more modern Tmux terminal multiplexer, and works on most Linux, BSD, and Mac distributions.
There are some *dependencies* that can't be satisfied easy (like *locale* or *hostname* commands), but are used for [status notifications](http://manpages.ubuntu.com/manpages/xenial/en/man1/byobu.1.html), so there's no need to add them.

Added byobu package

---

packages/zbar/build.sh

Another interesting package is [ZBar](http://zbar.sourceforge.net):
> ZBar is an open source software suite for reading bar codes from various sources, such as video streams, image files and raw intensity sensors. It supports many popular symbologies (types of bar codes) including EAN-13/UPC-A, UPC-E, EAN-8, Code 128, Code 39, Interleaved 2 of 5 and QR Code.
Is compiled without obvious dependencies (QT, GTK, X11) and without Python. Depends on ImageMagick and uses iconv, so don't know if I must add libandroid-support as dependency (feel free to add it).
I tested with QR and EAN codes:

Added zbar package

---

packages/libid3tag/build.sh
packages/libmad/build.sh
packages/libmp3splt/build.sh
packages/mp3splt/build.sh

I added mp3splt and its dependencies:
> Mp3Splt-project is a utility to split mp3, ogg vorbis and native FLAC files selecting a begin and an end time position, without decoding. It's very useful to split large mp3/ogg vorbis/FLAC to make smaller files or to split entire albums to obtain original tracks. If you want to split an album, you can select split points and filenames manually or you can get them automatically from CDDB (internet or a local file) or from .cue files. Supports also automatic silence split, that can be used also to adjust cddb/cue splitpoints. Trimming using silence detection is also available. You can extract tracks from Mp3Wrap or AlbumWrap files in few seconds. For mp3 files, both ID3v1 & ID3v2 tags are supported. 
This tool, used together with _youtube-dl_ (pip …

Added mp3splt, libmp3splt, libmad and libid3tag packages

---

packages/gnupg/src-mpi-Makefile.in.patch

GnuPG has x86-specific assembly files that don't have text relocations only if they are preprocessed with PIC macro defined
These assembly files are src/mpi/i386/mpih-{add,sub}1.S
It appears that linker in N developer preview enforces requirement to not have text relocations in executables, so this is necessary for `apt` to work on x86 with Android N developer preview.
This change should affect only x86 and have no effect on other archs.
(The other thing not working on N is `bash`, but tested few other things on emulator and rest appears to be fine)

gnupg: Don't have text relocations on x86

---

packages/libgd/build.sh
packages/libmcrypt/build.sh
packages/php/build.sh

I'm a PHP developer and I missed some extensions on Termux's PHP build. I added support for cURL with existing libcurl package and added new libraries to build libgd (for creating images) and libmcrypt (required by modern frameworks like Laravel/Lumen).
I compiled libgd with wide format support (PNG, JPEG, TIFF) and also added FreeType and Fontconfig dependencies.
I tested each extension with examples from PHP.net, and here is screenshot with the enabled modules after compile:

PHP package enhanced with curl, gd and mcrypt extensions

---

disabled-packages/ltrace/build.sh
disabled-packages/ltrace/ltrace-elf.c.patch

- Use version from git, current release has problems with ARM
- Replace rindex with strrchr using C preprocessor
- Don't exit on ltelf_destroy on library that failed to load
Not included in pull request:
- I've used my host `libelf.h` header, the one from NDK has few definitions missing (Not included because I've altered my in `/data`, not sure how to package it to `ndk_patches` or somewhere else)
- Removed `termux_step_post_massage` in `elfutils` (Not included here because I think that there is a reason why it was put there)
It's mostly working for me, but showing a few warnings at beginning, trying to open libraries at wrong directories or main executable as library and doesn't load config from `[...]/share/ltrace/[...].so` (Probably due to wrongly recognized libraries, this means that …

ltrace: Step towards working version

---

ndk_patches/stdio.h.patch

This was required for building debug elfutils and when this argument is not provided then some previous value from stack/register is used.

ndk_patches: Add missing argument to open(, O_CREAT) in tmpfile()

---

packages/openssh/build.sh

The default directory used for privilege separation is not inside the Termux filesystem.

openssh: Wrong _PATH_PRIVSEP_CHROOT_DIR: "/var/empty"

---

disabled-packages/ltrace/ltrace-elf.c.patch
disabled-packages/ltrace/sysdeps-linux-gnu-proc.c.patch

- Find libraries in `LD_LIBRARY_PATH` if relative path is found in `link_map`
- Skip main executable
- Skip `/system/bin/linker` and `[vdso]`
- Only set `proc->e_machine` once, as it might be set wrongly if we later try to load library that we couldn't find
Appears to work correctly without custom conf, at least on programs I tested. Maybe can be moved out of disabled-packages now..
Since android/platform_bionic@aae859cc3ca127d890e853cbf12b731e05624a22 first one is not necessary, but it is still needed for older Android versions (5.x)

ltrace: Fix incompatibilities with Android linker

---

packages/python/fileutils.c.patch

As SELinux policy disallows `ioctl` on sockets we have to fall back
to `fcntl` on EACCES
Fixes [issue with Flask reported by Irvel N on Google+ community](https://plus.google.com/+IrvelN/posts/SC7T8Qj7xFy), however now Flask can be only run with debug mode disabled, as in debug mode it calls `ip link list` shell command which hangs waiting for netlink response after having failed sending request to kernel (also due to SELinux). That can be fixed with `rm /data/data/com.termux/files/usr/bin/ip` but that doesn't seem to be right solution.

python: Make os.set_inheritable work on sockets

---

scripts/setup-fedora.sh

Just the Ubuntu setup script modified to use Fedora package names and dnf instead of apt-get.
Tested on Fedora 23.

Added Fedora setup script

---

ndk_patches/sys-select.h.patch

Native code compiled when installing the Ruby gem nio4r (used by Rails 5) needs unsigned int fd_mask.

Add fd_mask for Rails 5 support

---

packages/abook/build.sh

This adds the "abook" program, which is a relatively simple curses address book manager.  This is often paired with mutt, which is already in the termux repos.
Nothing fancy needed here.  Termux's build system figures everything out own its own, no patches needed, and the dependencies are already available.
Tested on a Nexus 5X with Android 6.0.

Add abook package

---

packages/proot/src-arch.h.patch
packages/proot/workaround-NT_ARM_SYSTEM_CALL.patch

My attempt to fix #378 (aka. #258)
I'm working around inability to change syscall number by changing arguments of syscall to invalid ones and then starting the syscall again
This required changes are in multiple files but I'm putting them in single `.patch`, because I don't think there will be need to backport/revert them separately and they depend on each other.
Tested only on emulator where there's no crash while using `termux-chroot`, though `brk` was called with arguments meant for `mmap`, so I think this could be cause of crash on real devices.
Also, there's change in `chain_next_syscall` which I think fixes bug in proot if I understand correctly, however it may uncover some other ones; this change affects builds for all architectures, it could be good idea to restrict this patch to …

proot: Work around inability to use change syscall

---

packages/php/build.sh

I enabled more extensions that are usually bundled with PHP in Linux distros: bcmath, bz2, calendar, exi and opcache
I also added Freetype support to GD, allowing to use TTF fonts to generate images.

Added more extensions to PHP build

---

packages/opus-tools/build.sh

libopus is already there, it will more useful if we can
encode/decode opus file directly using opus-tools

Add opus-tools package

---

packages/stag/Makefile.patch
packages/stag/build.sh
packages/stag/stag.c.patch

[Stag](https://github.com/seenaburns/stag) is a small programm that generates updating bar graphs for integer data piped into it.
Here's a basic usage example:
while true; do echo $RANDOM;sleep 0.3;done| stag -t "Random data over time"
I've tested it on both arm and aarch64 devices and I have used this tool ([compiled natively](https://oliverse.ch/tech/2016/01/16/compiling-stag-on-termux.html)) on Termux or a long time now.
I've compiled this program to learn how to do cross-compiling. Please let me know if I did something wrong.

Add stag package

---

packages/termux-api/termux-tts-speak

This patch adds 2 parameters to termux-tts-speak which makes choosing of voice region and variant possible. E.g. by using "-l en -n GB" the UK voice can be chosen if installed.

Added optional region and variant params to termux-tts-speak

---

packages/fwknop/build.sh

An [interesting package](http://www.cipherdyne.org/fwknop/) to connect to machines with fwknopd server:
> fwknop stands for the "FireWall KNock OPerator", and implements an authorization scheme called Single Packet Authorization (SPA). This method of authorization is based around a default-drop packet filter (fwknop supports iptables and firewalld on Linux, ipfw on FreeBSD and Mac OS X, and PF on OpenBSD) and libpcap. SPA is essentially next generation port knocking.
Is only the client and has no dependencies.

Added fwknop package

---

packages/libsodium/build.sh
packages/libzmq/build.sh

Adapted version of PR https://github.com/termux/termux-packages/pull/270
- Update to libzmq 4.1.5
- Usage of libsodium added
This solves issue https://github.com/termux/termux-packages/issues/85 and makes PR https://github.com/termux/termux-packages/pull/270 and https://github.com/termux/termux-packages/pull/271 obsolete

Added packages libzmq and libsodium

---

packages/libcln/build.sh
packages/qalc/Calculator.cc.patch
packages/qalc/Number.cc.patch
packages/qalc/build.sh
packages/qalc/qalc.cc.patch

I added this great calculator with a huge list of [features](https://qalculate.github.io/features.html):
> Qalculate! is a multi-purpose calculator for GNU/Linux (and Mac OS). It is small and simple to use but with much power and versatility underneath. Features include customizable 
functions, units, arbitrary precision, plotting, and a user-friendly interface
There are 2 packages: [libcln](www.ginac.de/CLN) and [qalc](https://qalculate.github.io) (I named it like Debian does, because command name is qalc, qalculate is used for desktop version).
I tested it as usual:

Added Qalculate package

---

packages/ffmpeg/build.sh

Modify ffmpeg build script to include opus codec.
Information about the codec can be found at:
- https://en.wikipedia.org/wiki/Opus_(audio_format)
- https://www.opus-codec.org/

ffmpeg: Enable opus codec (fixes #452)

---

build-package.sh

Message displayed when file download fails, shows wrong information about
maximum number of attempts. Hard-coded value of '3' is shown, but in reality
there is up to six attempts (when subsequent downloads keep failing).
Fix it by using correct value.

build script: Fix message on failed download (fixes #456)

---

packages/tty-clock/build.sh

tty-clock is a popular terminal clock in the ricing community.

Add tty-clock package

---

packages/libmesode/build.sh
packages/profanity/build.sh

[libmesode ](https://github.com/boothj5/libmesode) is a fork of libstrophe providing additional functionality to profanity. It's made by the author of profanity. 
Libstrophe is now no longer needed by profanity. I am unsure if I should remove it or not. Libstrophe could still be used for developing jabber bots or clients.

Build Profanity with libmesode instead of libstrophe

---

packages/par2/build.sh

Parity Archives are very usefull for working with long term storage,
which may have degraded over time. It allows to restore the files, even
if chunks of it are corrupted. https://en.wikipedia.org/wiki/Parchive
I tested it by creating a par2 archive, corrupting the original data and
restoring it.
This program is named par2cmdline, but I named the package par2 because
that's what it is called in the Ubuntu Repo,

Add par2 package

---

build-package.sh

Found this while building a package. Scripts may have something like
```
export LDFLAGS="-some-flag\ 
-some-other-flag\
$LDFLAGS"
```
In this case the final `LDFLAGS` would be 
`-some-flag -some-other-flag-specs=$TERMUX_SCRIPTDIR/termux.spec`

fix _SPECSFLAG to prevent fail on certain occasions

---

build-package.sh
ndk_patches/paths.h.patch

Replace `MOUNTED` macro with `/proc/mounts` for a future package which uses mntent.
Added debug and disabled package switches to build-package.sh.

Builder script and ndk patch improvements

---

packages/ne/build.sh
packages/ne/makefile.patch

ne, the nice editor:
> ne is a free (GPL'd) text editor based on the POSIX standard that runs (we hope) on almost any UN*X machine. ne is easy to use for the beginner, but powerful and fully configurable for the wizard, and most sparing in its resource usage. If you have the resources and the patience to use emacs or the right mental twist to use vi then probably ne is not for you.
Fixes #521

Added ne package

---

packages/mpv/build.sh

If libcaca support isn't specified (either enable or disable) the
buildorder script decides about this feature, because it is
autodetected. If mpv is built after libcaca it will be compiled in.
So if, at any point you rebuild it, without removing libcaca first, it
will be compiled in and throw an error on termux if libcaca isn't
installed.

Enable libcaca support in mpv

---

packages/elinks/build.sh

Now that termux supports true color, elinks can display websites using
more colors. Note that enabling this option has a slight performance
hit.

Elinks: enable true color support

---

packages/neovim/runtime-autoload-provider-clipboard.vim.patch

The clipboard.vim script needs to return an arbitrary string with the
name of the clipboard it will use. Run `:CheckHealth` to see that in
action.

neovim: fix clipboard patch

---

packages/json-c/001-unused-var.patch
packages/json-c/build.sh
packages/newsbeuter/001_drop_ncurses_check.patch
packages/newsbeuter/002_langinfo.patch
packages/newsbeuter/003_lockf.patch
packages/newsbeuter/004_wordexp-stub.patch
packages/newsbeuter/005_getpass.patch
packages/newsbeuter/006_makefile.patch
packages/newsbeuter/007_translit.patch
packages/newsbeuter/008_cleanup-cache.patch
packages/newsbeuter/build.sh
packages/stfl/001-makefile.patch
packages/stfl/build.sh

> Newsbeuter is an open-source RSS/Atom feed reader for text terminals.
This PR adds [Newsbeuter](http://www.newsbeuter.org/) and its two dependencies - json-c and stfl.
It successfully starts on a Nexus 7, can list, view and fetch feeds.

Add newsbeuter

---

packages/command-not-found/command-not-found.c

command-not-found: Always return an error

---

packages/mutt/build.sh

This enables the popular sidebar feature in mutt. It will still be [disabled by default](http://www.mutt.org/doc/manual/#sidebar) and has to be [enabled in the .muttrc](https://wiki.archlinux.org/index.php/Mutt#Mutt-Sidebar).

Enable sidebar support in mutt

---

ndk_patches/sys-stat.h.patch
ndk_patches/syscall.h.patch

glibc has I_SREAD, I_SWRITE and I_SEXEC which are aliases to I_SRUSR, I_SWUSR and I_SXUSR.
Also added dummy syscall.h to include sys/syscall.h

more ndk_patches to mimic standard glibc headers

---

packages/newsbeuter/009_podbeuter_crash.patch
packages/newsbeuter/010_podbeuter_redownload.patch

Add two newsbeuter upstream fixes - makes podbeuter sucessfully start and not crash on download.
Plays podcasts successfully with `player "mpv --no-video"` in ~/.newsbeuter/config

Podbeuter download fix

---

packages/erlang/0003-erts-emulator-reorder-inclued-headers-paths.patch
packages/erlang/build.sh

Tested build using docker.  I am not sure about the way the openssl dependency is handled in the build script but it works when you first build openssl.
Erlang runs fine on a Nexus 5 with stock Android 6.  I've tested [a small example webserver](http://stackoverflow.com/questions/2206933/how-to-write-a-simple-webserver-in-erlang#2219330) and even got elixir to compile and install, after some fiddling (shebang stuff) on the target and successfully ran some scripts I wrote.

Add erlang package

---

ndk_patches/syscall.h.patch

For some reason the syscall patch was malformed.

fixed reverse patch

---

packages/libsqlite/build.sh

Is the bump in tcl package still required? If no, please, remove the note from here

sqlite: update from 3.15.2 to 3.16.0

---

packages/golang/build.sh
packages/golang/src-runtime-os_linux.patch

Android on ChromeOS uses a restrictive seccomp filter that blocks
sched_getaffinity. Simply assume 1 CPU on any error.
Fixes https://github.com/termux/termux-packages/issues/496

golang: fix runtime init on chromeos

---

packages/fossil/build.sh

Fossil is a source code manager. Docker build tested on aarch64 and arm. Binary file `fossil` works fine on my device (arm).
I can successfully clone the sqlite source repo with this.
Fixes #640

fossil: add package

---

packages/valac/build.sh

Built and tested on arm.
Successfully compiled sample vala code.
This is a big package (comes in around 28 mb), most of which are vapi files, which I'm not sure should be kept in termux.
Closes #644

valac: add package

---

build-package.sh
scripts/clang-pie-wrapper

The move to clang wrapper broke cmake builds for !aarch64. This fixes that.

fix clang cmake build left broken for arches other than aarch64

---

packages/tty-clock/Makefile.patch
packages/tty-clock/build.sh

When the debian developers come ringing for a tagged release, suddenly
everything goes really fast.
In the build environment `ncurses5-config --libs` also returns
-ltinfo, which is unavailable to the linker. That's why the patch was
needed. Is this something that could be fixed in the build environment
or is this simply a badly written makefile, unsuitable for cross
compiling?

Update tty-clock to version 2.3

---

packages/torsocks/0001-syscall-Add-clone.patch
packages/torsocks/build.sh

This fixes `cannot fork` errors on nougat devices.

torsocks: fix nougat (add clone syscall)

---

packages/bs1770gain/build.sh

BS1770GAIN is a tool to analyse audio files and apply Replaygain Tags. It can be used together with http://beets.io

add bs1770gain package

---

packages/darkhttpd/Makefile.patch
packages/darkhttpd/build.sh

Add the simple and lightweight [darkhttpd](https://unix4lyfe.org/darkhttpd/) webserver. As it has no dependencies other than the C stdlib it should be very easy to maintain.

Add darkhttpd

---

packages/jupp/build.sh

jupp is a fork of joe 3.1 by The MirOS Project, containing some bugfixes
and additional features.

Add a new package for jupp.

---

README.md
build-package.sh
ndk_patches/sys-sem.h.patch
ndk_patches/sys-shm.h.patch
packages/ndk-sysroot/build.sh

These patches add macros for sem and shm libc wrappers missing from bionic.
They replace the function calls to syscalls and as such do not perform any parameter checks. Also, these will not set errno. This limits their functionality but they help compile many more programs.

ndk_patches: add patches for sem and shm

---

disabled-packages/mariadb/build.sh
disabled-packages/mariadb/extra-readline-complete.c.patch
disabled-packages/mariadb/m_ctype.h.patch
disabled-packages/mariadb/my_global.h.patch32
disabled-packages/postgresql/build.sh
disabled-packages/postgresql/tempdir-fix-old.patch.old
disabled-packages/postgresql/tempdir-fix.patch.old

*postgresql* fails because shm region creation fails with EACCESS (permission denied). I compiled util-linux with shm support and you can create shm regions as root but not as standard users. This is strange because the first time I ran this it ran flawlessly.
*mariadb* works if you can tolerate skip-grant-tables. `mysql_install_db` fails to install system tables. I have attached some debug logs.
[mariadb.txt](https://github.com/termux/termux-packages/files/752405/mariadb.txt)

add postgresql and mariadb as disabled packages

---

disabled-packages/alsa-lib/build.sh
disabled-packages/alsa-lib/pcm_direct.c.patch
disabled-packages/alsa-lib/pcm_mmap.c.patch.old
disabled-packages/alsa-lib/versionsort.patch
disabled-packages/alsa-utils/build.sh
disabled-packages/alsa-utils/configure.patch
disabled-packages/alsa-utils/volume_mapping.c.patch
disabled-packages/easy-rsa/build.sh
disabled-packages/llvm/CMakeLists.txt.patch
disabled-packages/llvm/LLDB.cmake.patch
disabled-packages/llvm/build.sh
disabled-packages/llvm/clang-dev.subpackage.sh
disabled-packages/llvm/clang.subpackage.sh
disabled-packages/llvm/lldb-dev.subpackage.sh
disabled-packages/llvm/lldb.subpackage.sh
disabled-packages/llvm/tools-clang-lib-Driver-ToolChain.cpp.patch
disabled-packages/llvm/tools-clang-lib-Driver-Tools.cpp.patch
disabled-packages/llvm/tools-sancov-sancov.cc.patch
disabled-packages/openjdk-9-headless/build.sh
disabled-packages/openjdk-9-headless/libpthread.diff
disabled-packages/openjdk-9-headless/os_linux.cpp.diff
disabled-packages/openvpn/build.sh
disabled-packages/openvpn/configure.ac.patch.old
disabled-packages/openvpn/netbsd_getpass.c
disabled-packages/openvpn/src-openvpn-console_builtin.c.patch
disabled-packages/openvpn/src-openvpn-tun.c.patch
disabled-packages/openvpn/termux-openvpn
disabled-packages/squid/CpuAffinitySet.cc.patch
disabled-packages/squid/build.sh

- easy-rsa: works perfectly. no faults here. No one needs it so its disabled.
- openvpn: Requires root for standard operation (just like any other distro). To implement it without root,
heavy support from termux-api is required. Specifically, we'll need to use the management
engine in openvpn to replace commands requiring root with VpnService calls
- squid: works, too. isn't enabled because nobody requested it. also I wanted to disable building localized
error pages, which I was unsuccessful in doing.
- llvm: works. segregated packages need to be refined. main build.sh has function to generate file list for
subpackages. subpackages can then have `cat file_list.txt` in subpkg_include.
- alsa-lib and alsa-utils: compiles successfully. But, the Android kernel seems to be lacking kernel space …

add more disabled packages

---

packages/privoxy/GNUmakefile.in.patch
packages/privoxy/build.sh
packages/privoxy/jcc.c.patch

Another interesting package: 
> [Privoxy](https://www.privoxy.org/) is a non-caching web proxy with advanced filtering capabilities for enhancing privacy, modifying web page data and HTTP headers, controlling access, and removing ads and other obnoxious Internet junk. Privoxy has a flexible configuration and can be customized to suit individual needs and tastes. It has application for both stand-alone systems and multi-user networks. 
Why is interesting? You can proxy all device traffic through this proxy, making a [system-wide ad blocker](http://blog.vanutsteen.nl/2014/01/05/installing-privoxy-with-adblock-filters-on-openwrt/) or you can use the hotspot and filter the traffic of connected devices...
Daemon needs to be launched with user detected with `whoami`. Example running from …

Add privoxy package

---

packages/bmon/build.sh
packages/bmon/config.h.patch
packages/libconfuse/build.sh
packages/libnl3/build.sh
packages/libnl3/nf-log.c.patch
packages/libnl3/nf-monitor.c.patch
packages/libnl3/nf-queue.c.patch
packages/libnl3/nl-monitor.c.patch

I created a builder for bmon and its dependencies:
> bmon is a monitoring and debugging tool to capture networking related statistics and prepare them visually in a human friendly way. It features various output methods including an interactive curses user interface and a programmable text output for scripting.
Is very interesting for monitoring wireless traffic using it as hotspot (choose rmnetX interfaces). Interesting too if you download things in background or if you use a proxy like #406 (choose wlan0 interface)

bmon: added package and its dependencies (libconfuse and libnl3)

---

packages/pure-ftpd/build.sh
packages/pure-ftpd/pure-pwconvert.c.patch

A small ftp server:
>  Pure-FTPd is a free (BSD), secure, production-quality and standard-conformant FTP server. It doesn't provide useless bells and whistles, but focuses on efficiency and ease of use. It provides simple answers to common needs, plus unique useful features for personal users as well as hosting providers. 
Is compiled without modules and doesn't require root (more on [README](https://download.pureftpd.org/pub/pure-ftpd/doc/README)). When compiling using `--with-nonroot` option, default port is 2121 so works without many tweaks .Works with virtual users and anonymous access.
Tested as usual:

Add Pure-FTPd package

---

packages/redis/bio.c.patch
packages/redis/build.sh
packages/redis/config.h.patch

Widely used cache server:
> [Redis](https://redis.io) is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries. Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.
Has both server and client... It can be tested with `redis-benchmark` command included in package (my OnePlus 3 reaches 11.000 requests/second).

Add Redis package

---

disabled-packages/libusb/build.sh

initial try to get libusb to build for termux
In docker image, had to apt-get install libudev-dev
so libudev is probably a dependency

Created nonworking (yet) build.sh for libusb

---

packages/blogc/build.sh
packages/blogc/termux-prefix.patch

blogc is a blogging tool written in C, without any external
dependencies. It is released under BSD license, and targeted to
developers.
The package is based on a snapshot version. Version 0.13.0 should
be release soon, but the snapshot is stable and useful enough.
For more info, see: https://blogc.rgm.io/

blogc: initial packaging

---

packages/dpkg/build.sh

1.18.22 isn't available anymore on https://mirrors.kernel.org/debian/pool/main/d/dpkg/

update dpkg to 1.18.23

---

packages/apt/build.sh

this allows something like
`deb [trusted=yes] ssh://user@server:/home/user/repo termux extras`
in the sources.list.

add ssh to the apt transports

---

disabled-packages/openjdk-9-headless/build.sh

Nothing worth noting.
I tried building with clang. Rejects clang outright. We may have a problem in the future.

openjdk-9-headless: update to newest changeset, tag 160

---

packages/texlive/termux-install-tl.sh

I asked about the install-tl script at the [texlive mailing list](http://tug.org/pipermail/tex-live/2017-March/039796.html) and learned that we should this version of install-tl-unx.tar.gz instead. 
This removes the need for one of the patches to the install-tl script.
TeXLive works very well, I'm looking forward to seeing it on the termux repository .

texlive: Changed install-tl-unx.tar.gz to a historic version 

---

packages/texlive/termux-install-tl.sh

Busybox version of wget doesn't support -N so wget shouldn't use -N (or be added to package dependencies).

texlive: remove -N option from wget command in termux-install-tl.

---

.gitattributes

I don't know if this was expected but using * text=auto on windows will simply break all the builds inside docker because scripts like config.guess, *.py will be crlf and inside docker shebang won't work.

Update .gitattributes to force lf

---

packages/hunspell-ru/build.sh

Russian dictionary for Hunspell, a trivial copy-paste job based on `hunspell-en-us` with correct checksums.
The package name is `hunspell-ru` because that's what the Ubuntu equivalent is named.
Tested in Emacs, works. :)

New package: hunspell-ru

---

build-package.sh
packages/php/build.sh
packages/php/php-fpm.patch
packages/php/php-fpm.subpackage.sh
packages/php/php-pgsql.subpackage.sh

I had to enable `TERMUX_SUBPKG_CONFFILES` as php-fpm is 11 MB and it makes sense to have it as a subpackage.
Also, changed `EXTENSION_DIR` to `$TERMUX_PREFIX/lib/php`, so, now the opcache shared module resides there.

add php-pgsql and php-fpm

---

packages/termux-tools/termux-fix-shebang

Original script 'termux-fix-shebang' from termux-tools package is not working with multiple files or files with a whitespace character in name. I have made some changes that fixes this.

termux-tools: fix termux-fix-shebang script

---

packages/krb5/build.sh
packages/krb5/include-osconf.hin.patch

Some more polish to prevent end user from having to set these in configs.

krb5: specify conffiles, default cache locations and ports

---

packages/fossil/build.sh

This is a critical update because sqlite's official repo has denied access from fossil 1.x clients since March 12, 2017.
see http://www.sqlite.org/getthecode.html#clone
"As of 2017-03-12, you must use Fossil version 2.0 or later for the following instructions to work..."

fossil: Update from 1.37 to 2.1

---

packages/fish/build.sh

See https://github.com/fish-shell/fish-shell/issues/2974
This will only fail at runtime in some autocomplete commands, if the dependency is not installed.

Add bc dependency to fish shell

---

packages/boost/build.sh
packages/boost/python.jam.patch

a few things the python lib won't compile unless you add a symlink so -lpthread works as it is on device. I haven't really tested all the libs yet.

Boost libs

---

packages/pass/build.sh

Since Pass 1.7 it doesn't need pwgen anymore

Pass: remove pwgen as requirement

---

packages/jupp/build.sh

Change jupp URL to more stable one.

---

packages/httping/build.sh

Hello,
Here is a new package for [httping](http://www.vanheusden.com/httping/).
I had to remove all calls to gettext because we don't have it in Termux yet (#504).

New package: httping

---

packages/php/build.sh

yeah its a clang compile error. Use gcc instead and its fine.

fix aarch64 build giving double instead of integer

---

packages/libgpg-error/atexit.patch
packages/libgpg-error/build.sh

To workaround for #933 
The problem is if `atexit(do_deinit)` is called from a function decorated with `__attribute__ ((__constructor__))`, then while `do_deinit` is executed, no standard fd will be presented prior to Android N.
However with `atexit(do_deinit)` called in a initial function (i.e. `gpgrt_init()`) is OK.
Thus, the sample code in #933 should look like this:
```
#define GPGRT_ENABLE_ES_MACROS
#include <gpg-error.h>
int main() { gpgrt_init(); es_putc('A', es_stdout); }
```
BTW `gpgrt_init()` is called in `init_comman_systems()` of gpgconf.c
So this workaround is just register `atexit` again, and the first `do_deinit()` is able to print message out to stdout.

libgpg-error: workaround no stdout atexit with constructor prior to N

---

build-package.sh

There is no need to `basename` one by one, using internal bash functions would be enough!

No need to select one by one.

---

scripts/setup-ubuntu.sh

ed is a build dependency of bc now. The build would fail if ed is not present as shown here: 
https://gitlab.com/Wetitpig/termux-packages/pipelines/8369999

Add ed package for bc

---

packages/ncmpcpp/settings.cpp.patch

this makes default ncmpcpp settings open up the socket because it was moved to ~/../usr/tmp not ~/.mpd/.

ncmpcpp default settings to work with mpd default

---

packages/debootstrap/Makefile.patch
packages/debootstrap/build.sh
packages/debootstrap/debootstrap.patch
packages/debootstrap/functions.patch
packages/debootstrap/scripts.patch

Hello,
Here is a port of debootstrap to Termux.
It allows to easily install a complete Debian system in a folder.
We can then use `proot` to run it inside a chroot.
Here is what I had to patch:
* Use proot instead of chroot.
* Avoid using utilities that are not permitted on Android (chown, groupadd, etc.).
* Replace Debian's version of these utilities with a stub (so packages that use them in their postinstall script don't fail).
* Fix some hardcoded paths to `/usr/`.
Note that I only patched/tested the installation of Debian stable. The installation of other Debian-based distributions will probably require more work.

debootstrap: Add package

---

packages/apache2/Termux.layout
packages/apache2/build.sh

Somehow the error decided to fix itself to give us apache2 on Termux.
Fixes #855 
I have not tested it with php, yet.
As you can see, I've enabled a generous number of modules. I just took this list from Arch's PKGBUILD. If you think that a module should be or shouldn't be here, do tell.

apache2: add package

---

packages/texlive/build.sh
packages/texlive/termux-install-tl.sh

Also various improvements: split package into texlive and texlive-dev, remove most of the files in the texlive tree on uninstall.

Texlive: fix #1068, #1069 by upgrading to texlive 2017

---

packages/proot/termux-chroot

proot: /data & /property_contexts in termux-chroot

---

packages/libpulseaudio/build.sh

Fixes issue discussed in #821 and at https://github.com/cmus/cmus/issues/688.

libpulseaudio: link against libandroid-glob.

---

scripts/setup-archlinux.sh

The other day when tinkering with pulseaudio as per the #821 I wanted to build it my-self. I am not very much into docker, and I am running arch linux rather than ubuntu so partially just for fun and partially because I wanted to build pulseaudio I have taken setup-ubuntu.sh and turned it into setup-archlinux.sh .
Perhaps there are more crazy guys out there who might find this usefull.
I took building more packages for a test drive not just pulseaudio, for example openssl and mariadb build fine on arch linux as host OS after running both the setup scripts setup-archlinux.sh followed by the setup-android-sdk.sh .
I might hopefully revisit #104 in the foreseeable future.

Add scripts/setup-archlinux.sh similar to setup-ubuntu.sh

---

packages/ldc/build.sh
packages/ldc/ldc-config-stdlib.patch.beforehostbuild.in
packages/ldc/ldc-disable-idgen.patch
packages/ldc/ldc-druntime.patch.beforehostbuild
packages/ldc/ldc-linker-flags.patch.in
packages/ldc/ldc-llvm-config.patch.in
packages/ldc/ldc-phobos.patch.beforehostbuild
packages/ldc/ldc-readme.patch
packages/ldc/ldc-tools-utils-bugs.patch
packages/ldc/llvm-android_tls.patch.beforehostbuild

Finally got around to figuring out your build scripts on Arch and writing this up, fixes #71.  Only works for ARM and I had to hard-code the options that ldc normally gets from `llvm-config`, because llvm's `CMAKE_CROSSCOMPILING` support, that's supposed to build a native host `llvm-config`, is completely broken.  Once @vishalbiswas gets his script version of `llvm-config` in, #917, I'll look at using that instead.
Ldc currently depends on a lightly patched llvm for emulated TLS, because it's easy to pass this data to the D garbage-collector.  Eventually, we'll move to llvm's built-in emulated TLS.
~~I simply take the source and pre-built libraries for the D runtime and standard library, Phobos, from my cross-compiler tarfile, rather than go to the trouble of downloading and building …

ldc: add package

---

disabled-packages/ldc/build.sh
disabled-packages/ldc/ldc-llvm-config.patch.in

There was an ARM regression in 4.0.0 that kept me stuck at 3.9.1, but they disabled the constant pool optimization that triggered it in 4.0.1, so I upgraded.

ldc: update to llvm 4.0.1

---

disabled-packages/ghostscript/arch-aarch64.h
disabled-packages/ghostscript/build.sh

Hi there,
this fix makes ghostscript run on aarch64. Please merge it! I think that the ghostscript package can be enabled now...
Bye,
Richard  
```
-bash-4.4$ gs
GPL Ghostscript 9.21 (2017-03-16)
Copyright (C) 2017 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
GS>
```

Fix ghostscript for aarch64.

---

build-package.sh
ndk-patches/cstddef.cpppatch
packages/ndk-stl/build.sh

Allows cstddef include  so g++ with libc++_shared works.

fixes building cstddef include for g++

---

scripts/run-docker.sh

And don't {chmod,chown} if run as root. Running with sudo otherwise produces debs that normal users don't have permission to access.
There might still be a small change needed related to the group id of the builder. Currently, all files are given group id 1000, which my system isn't an existing group. 
I'm using 
`docker exec --interactive --tty --user $USER:100 $CONTAINER_NAME bash` 
instead of 
`docker exec --interactive --tty --user $USER $CONTAINER_NAME bash` 
but I guess group 100 doesn't exist on all systems either?

Docker: login as "builder" even if run-docker.sh is run as root.

---

packages/mpv/build.sh
packages/mpv/mpv.conf

1. I changed the way we add settings to the default mpv config.
2. Increase the audio-buffer, to prevent stuttering with bluetooth devices (#1127)
3. Added setting to disable video output of mpv, as mpv would fail if any video information is found in a file (even just album art in an mp3). It can still be overridden with `--vo=tct` (or another vo, should one become available).
I didn't bump the version number of mpv, because as of yet. 0.26.0 isn't in the repository yet.

MPV. Fix for #1127 and disable video output.

---

packages/libpng/build.sh

1.6.29 is no longer available at the previously used sourceforge url.

libpng: update to 1.6.31

---

build-package.sh

Needed for properly splitting texlive into two packages. 
Probably helpful for replacing gnupg with gnupg2.

Add more control fields (Recommends, Breaks and termux_subpkg_replaces)

---

packages/ncmpcpp/build.sh
packages/ncmpcpp/ncmpcpp.cpp.patch

It makes ncmpcpp resize itself when the window size has changed.
Not sure why this was ever added, but according to @its-pointless it can
be removed

 Don't disable SIGWINCH in ncmpcpp

---

packages/libmpdclient/build.sh

This is the first package to be built using [the meson build system](http://mesonbuild.com/) (using new support for it in `build-package.sh`), which makes it interesting, as it seems that this build system is being adopted in multiple projects.
Any `ncmpcpp`, `mpc` or `mpd` users wanting to try out this libmpdclient and see if it works? @mklein994 or @Neo-Oli perhaps?
```
wget http://fornwall.net/libmpdclient_2.13_aarch64.deb
apt install ./libmpdclient_2.13_aarch64.deb
wget http://fornwall.net/libmpdclient_2.13_arm.deb
apt install ./libmpdclient_2.13_arm.deb
```

libmpdclient: Update from 2.11 to 2.13

---

packages/oathtool/build.sh
packages/xmlsec/build.sh

I added [OATH Toolkit](http://www.nongnu.org/oath-toolkit/index.html), to generate OTPs via CLI:
> The OATH Toolkit provide components for building one-time password authentication systems. It contains shared libraries, command line tools. Supported technologies include the event-based HOTP algorithm (RFC4226) and the time-based TOTP algorithm (RFC6238). OATH stands for Open AuTHentication, which is the organization that specify the algorithms. For managing secret key files, the Portable Symmetric Key Container (PSKC) format described in RFC6030 is supported.
You can now forget Google Authenticator...
I named it like Debian does (they split in several packages, but I think here is not necessary), and is tested as usual:

oathtool: add package and its dependencies (xmlsec)

---

packages/icecast/build.sh
packages/icecast/thread.c.patch
packages/mime-support/build.sh

Small streaming server:
> Icecast is a streaming media (audio/video) server which currently supports Ogg (Vorbis and Theora), Opus, WebM and MP3 streams.
It can be used to create an Internet radio station or a privately running jukebox and many things in between. It is very versatile in that new formats can be added relatively easily and supports open standards for communication and interaction.
It requires /etc/mime.types file so I added a package called 'mime-support' based on Debian's one.

Icecast package

---

packages/openssh/build.sh

Since password auth is disabled by default, we depend on keys in our home dir but they're not created for us and the perms are wrong by default. This commit sets it up correctly for the user to simply add their key to the empty authorized_keys file

Set up home structure for authorized_keys

---

packages/ecj/build.sh

I don't know if this will actually work without you choosing to download this API's jarfile from the SDK GUI first, just copy-pasted the bit above and I haven't used the SDK in years.  This should finally close #63, if we can build Android apps for most devices.  I'll rework my Android app build instructions from that issue to use ecj and add it to your new Termux wiki once this is in.

ecj: Add android-16 API jar too

---

packages/proot/build.sh
packages/proot/termux-chroot

Allow a command to be specified when running termux-chroot.
Example:
```
$ termux-chroot ls /
bin  data  dev  etc  home  lib  proc  property_contexts  share  storage  system  tmp  usr  var  vendor
```
This makes it possible to run scripts that include a part that needs to
be run in a chrooted environment, like a compile script.
```
./configure
make
termux-chroot make install
```
Previously it had to be done like this:
```
./configure
make
termux-chroot
cd program
make install
exit

termux-chroot: Specify command to execute

---

packages/libsqlite/build.sh

fixes issues that arose from building tcl with #1169 and avoids a circular dependency

add tclsqlite3.c to libsqlite dev package

---

packages/vim-python/vterm_internal.h.patch
packages/vim/vterm_internal.h.patch

after you add --enable-terminal to building vim if you had already built the package libvterm the internal vim libvterm fails. This fixes it so it uses local vim provided vterm.h

fix building vim after libvterm

---

packages/cava/build.sh
packages/cava/cava.c.patch
packages/cava/configure.ac.patch

Cava is an Audio Visualizer that can work together with MPD. It works
out of the box if you enable "visulizer output" in MPD by either running
`mpc enable 3` or by enabling it in [7] in ncmpcpp.

Add package: Cava

---

packages/qalc/build.sh
packages/qalc/util.cc.patch

[Version 2.0.0](https://github.com/Qalculate/libqalculate/releases/tag/v2.0.0) comes with dependency changes: forget glib and libcln to use libgmp and libmpfr instead, as well as libcurl and libiconv.

qalc: update from 1.0.0 to 2.0.0

---

packages/cpio/build.sh

Busybox cpio is limited to just few of cpio variants. GNU cpio has wider
cpio support.

cpio: New package (GNU cpio)

---

packages/libllvm/gcc_loop.patch

Clang calls into gcc if it tries to compile a language it doesn't understand.
On termux gcc is a symlink to clang, so this leads into fork loop until
the whole system runs out of memory.

clang: Disable calling into gcc from clang.

---

packages/fossil/fossil-2.3-termux-sh.patch

Currently Fossil uses /bin/sh for calling out, change this to a Termux-ified path.

Add patch for Fossil to use correct shell when emulating popen()

---

packages/ldc/build.sh
packages/ldc/rdmd-tempDir.patch

rdmd, a scripting wrapper that makes it easy to use D for scripting, and dub, the D package manager, normally ship with the D compiler.  I ran their tests and they mostly work fine on Android/ARM, so I'm including them in the ldc package.  I had to make a small modification to rdmd so that it found the temporary directory in Termux.  Also bumped dmd, the host D compiler used to bootstrap ldc, to the latest version that just came out.

ldc: add dub and rdmd, plus bump host dmd to latest version 2.076.0

---

packages/pass/build.sh

Because busybox's tr doest support the [:graph:] modifier, all passwords generated
contain only the characters [:graph].

pass requires coreutils. fixes #1427

---

packages/libyaml/build.sh

We need [LibYAML](http://pyyaml.org/wiki/LibYAML) to compile [php-yml](http://bd808.com/pecl-file_formats-yaml/) and can be added as dependency for Ruby.

libyaml: add package

---

packages/ldc/build.sh
packages/ldc/ldc-config-stdlib.patch.beforehostbuild.in
packages/ldc/ldc-disable-idgen.patch
packages/ldc/ldc-llvm-config.patch.in

Simply pulled in my changes from #1323, which is now obsolete, will update that PR to the upcoming 1.5 beta instead.

ldc: update to 1.4 release

---

packages/w3m/build.sh

The default browser and editor in w3m where /usr/bin/firefox and
/usr/bin/vi respectively. I change that to termux-open-url and vi.
If you now press "M" on a link in w3m it will open it with Androids
default browser. If you press "E" while viewing a local file it will
open vi. Previously this has just printed error messages. Obviously
these settings can still be overwritten in the options of w3m to set it
to whatever you want.

Set some settings in w3m to be termux-friendly

---

packages/lftp/build.sh

#1169 
could also be made a normal depends since it shows a missing header file and obviously uses the library during the compilation phase, even before linking

add ncurses-dev to lftp build dependencies

---

build-package.sh
packages/ninja/build.sh
packages/ninja/configure.py.patch
packages/ninja/src-posix_spawn.c.patch
packages/ninja/src-posix_spawn.h.patch
packages/ninja/src-subprocess-posix.cc.patch
packages/ninja/src-util.cc.patch

Update the host version to latest and use it to cross-compile.
Ninja uses `posix_spawn` which isn't in bionic, but a google search found [this BSD-licensed `fork` wrapper in dhcpcd from the Android source repo](https://android.googlesource.com/platform/external/dhcpcd-6.8.2/+/master/compat/posix_spawn.c), so I copied it over.  However, it doesn't support `posix_spawn_file_actions*`, so I simply commented those out.  Ninja fails some of those subprocess tests on Android as a result, but in actual use to build a project like ldc, I haven't noticed a problem.
Also, bionic doesn't have `getloadavg`, so use `sysinfo` instead.

ninja: add package

---

packages/procps/z01_eaccess.patch

On some Androids many of proc files can't actually be opened. So ignore
when opening fails and go on.

procps: Ignore Permission denied in several places.

---

scripts/buildorder.py

* A package may have 'TERMUX_PKG_DEPENDS=', 'TERMUX_PKG_BUILD_DEPENDS='
and 'TERMUX_SUBPKG_DEPENDS=' at the same time.
* Currently only one of these was interpreted by the script, and all
others ignored.
Signed-off-by: Vladimir Oltean <olteanv@gmail.com>

buildorder.py: handle the case when more than one dependency type is set

---

packages/htop/build.sh
packages/htop/fix-sigsegv.patch

In some configurations of htop we may receive the following error:
```
htop 2.0.2 aborting. Please report bug at http://hisham.hm/htop
zsh: abort      htop
```
This bug already fixed in htop's repo at commit [cceab15b9dbdc2f0914c8d479cefa429d1c0daaf](https://github.com/hishamhm/htop/commit/cceab15b9dbdc2f0914c8d479cefa429d1c0daaf).

htop: fix segfault which may occur in some cases

---

packages/tmux/tmux.conf

an escape time of zero breaks tmux core functionality... you cannot have an escape time of 0, then it's impossible to use most custom key bindings, or to do things like resize panes effectively, etc...

remove zeroed escape time

---

build-package.sh

need to find ways to reduce length of log output
```
$ ./scripts/run-docker.sh ./build-package.sh iconv | wc
2836   15651  197322
$ ./scripts/run-docker.sh ./build-package.sh -q iconv | wc
2177   13021  162608
```

add quiet build option for ci builds

---

packages/texlive-bin/build.sh
packages/texlive/build.sh

This seem to work for all test cases I can think of (fresh install, update, install/update when TMPDIR isn't set...). 
Should solve #1639, finally. 
Sorry for the mess.

texlive: fix postinst, prerm, preinst scripts

---

packages/yarn/build.sh

Hello,
Here is a package for Yarn.
Yarn can currently be installed with npm but it is not recommended by the Yarn team (see *Install via npm* [here](https://yarnpkg.com/en/docs/install#alternatives-tab)) so I think it is better to have a package.

yarn: Add package

---

disabled-packages/mtr/build.sh
disabled-packages/mtr/hsearch.patch
disabled-packages/mtr/hsearch/README.md
disabled-packages/mtr/hsearch/hcreate.c
disabled-packages/mtr/hsearch/hcreate_r.c
disabled-packages/mtr/hsearch/hdestroy_r.c
disabled-packages/mtr/hsearch/hsearch.h
disabled-packages/mtr/hsearch/hsearch_r.c
disabled-packages/mtr/hsearch/search.h
disabled-packages/mtr/index_to_strchr.patch

The `hsearch(3)` implementation is based (with minor edits) on the one present in FreeBSD 11.1. A patch to change some `index()` calls to instead use `strchr()` was also needed.
This PR makes mtr able to compile and function correctly. Sadly, it doesn't appear to work out-of-the-box, without root. With root though, everything seems to operate as intended. I don't know if that qualifies it to be moved out of `disabled-packages/`, so I left it as it is.
Fixes #305

mtr: Fix #305 by implementing hsearch(3)

---

build-package.sh

avoids having to manually determine package name, needed for #1743

use tar strip-components to extract src

---

packages/libpulseaudio/build.sh

Occured on arm when trying to play music through cmus. 
Rebuilding the package wasn't enough. 
pulseaudio worked a couple of weeks ago, I'm not sure what changed between then and now. 
This fixes it anyways.

libpulseaudio: fix "shared memfd open() failed: Function not implemented"

---

packages/tor/fix-hardcoded-paths.patch

Should fix warnings like this:
```
[warn] Unable to stat resolver configuration in '/etc/resolv.conf': No such file or directory
```

tor: fix paths to /etc/hosts and /etc/resolv.conf

---

packages/tsu/build.sh

https://github.com/termux/termux-packages/commit/db817da647bfea31e7965ca99fb35c64046eab99
updated the url of tsu download but didnt bump the package version
Which I guess caused apt to skip updating this package

Bump tsu version so it actually gets installed.

---

packages/texlive-bin/texk-web2c-luatexdir-luaffi-ffi.h.patch

Fixes build error: 
```
libluaffi.a(libluaffi_a-ffi.o):/home/builder/.termux-build/texlive-bin/src/texk/web2c/luatexdir/luaffi/ffi.c:function cdata_pow: error: undefined reference to 'cpow'
clang50++: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:4995: recipe for target 'luatex' failed
```
Bumping the revision shouldn't be necessary in this case I guess.

texlive-bin: fix build failure for i686 and x86_64 (due to NDK r16?)

---

packages/poppler/CMakeLists.txt.patch
packages/poppler/build.sh

Valgrind still complains about invalid read & writes of size 4 but this also happens when building texlive on x86_64 desktop linux with the texlive-poppler-0.59.patch so it's not a problem isolated to us. 
There's probably a small error in the patch, I can try to contact the upstream author of the patch.

poppler: disable multithreading. Fixes #1657.

---

packages/tsu/build.sh

tsu shell script didn't had the copyright header.
hence  installations wouldnt preserve the license of tsu
i've fixed the issue in upstream tsu
and bumped the version to 1.1 as it is much stable now.

Update tsu to v1.1 fixes copyright derp

---

packages/proot/build.sh

termux/proot#5
Also includes fix termux/termux-packages#1679

proot: Upgrade to skip syscalls blocked by seccomp

---

build-package.sh
packages/espeak/build.sh
packages/ruby/build.sh

Fixes #1680. 
Also move similar fix for ruby from build-package.sh to build.sh. 
Let me know if you disagree about this movement.

espeak: fix floating point exception on arm

---

packages/global/build.sh
packages/global/echo-path.patch

Fixes error 'globash: line 47: /bin/echo: No such file or directory' which may occur when running `globash`.

global: fix path to 'echo' in globash

---

packages/lftp/build.sh
packages/lftp/lftp_ssl.cc.patch
packages/lftp/src-commands.cc.patch

Fix error 'no such file or directory: /bin/sh' when doing `bookmark edit` and add correct path to CA cert bundle.

lftp: fix hardcoded paths

---

build-package.sh
packages/espeak/build.sh
packages/ruby/build.sh
packages/texlive-bin/build.sh

What do you think about this?
@Grimler91 The problems in #1680 and #1765 were for 32-bit arm only, and -Os should work there, right?
@its-pointless You mentioned a problem with libgc on 32-bit arm with -Oz (so we should revision-bump that package after this change)?

Use -Os instead of -Oz for 32-bit arm

---

packages/gst-plugins-base/build.sh

covered by libvorbis dependencies

remove libogg from gst-plugins-base

---

disabled-packages/apt-updated/build.sh
packages/apt/build.sh

apt-mark is missing from Termux and I find it quite useful to figure out which packages are manually installed, it's even detailed as the only method which is listed to do so in ```man apt```.
On my Debian buster machine with apt 1.6~alpha5 apt-mark is 43168 bytes large.
Resolves #1635

apt: restores apt-mark

---

packages/tar/build.sh
packages/tar/mkfifoat.patch

Should fix #1971.
Archive for testing: [devices.tar.gz](https://github.com/termux/termux-packages/files/1584815/devices.tar.gz)

tar: fix segfault when extracting archive that contains device files

---

packages/coreutils/build.sh

I assume this was supposed to be removed with https://github.com/termux/termux-packages/commit/f05fb116ee07850beac57ad9017f7f92e8e605ad.
Package tries to cd to host-build dir currently which fails since it doesn't exist.

coreutils: remove leftovers from f05fb1

---

packages/boost/build.sh
packages/boost/python.jam.patch

not being linked against libpython3.6 prevents loading module from python. This makes it work.

libboost_python not linked to python fix

---

packages/gbt/build.sh

I have created a new package for application called [GBT](https://github.com/jtyr/gbt/). It's a highly configurable prompt builder for Bash and ZSH written in Go. When run in Termux, it looks like this:
I'm going to present GBT on the [DevOps Exchange meetup](https://www.meetup.com/DevOps-Exchange-London/events/246447551/) in London next week and it would be really great if I could show people how they can install it on their Android device via Termux without the need to download the package manually.

Adding gbt package

---

packages/readline/build.sh
packages/readline/inputrc

This makes Home/End keys working over SSH when connected from some clients like PuTTY on Windows.
Basically all Linux distributions provide some default /etc/inputrc configuration:
- Debian based distros in package readline-common (both Debian 9 and Ubuntu 17.10 share same config)
- Red Hat based distros in package setup (both CentOS 7 and Fedora 27 share same config)
- Arch Linux in package readline
- openSUSE in package aaa_base
- OpenWRT etc.
The proposed inputrc configuration is a intersection of default mappings used in Debian 9, CentOS 7 and Arch Linux. That should provide safe and expected mappings.

readline: Add inputrc

---

scripts/Vagrantfile

Existing Vagrantfile lead to some problems here during provisioning:
1. setup-ubuntu.sh would fail
and after:
2. build-all.sh would run out of disk space
3. build-all.sh would exit due to permission issues
Issue 1 can be addressed by running sudo apt-get update before setup-ubuntu.sh in the Vagrantfile.
One way to address issue 2 is to use the vagrant-disksize plugin:
https://github.com/sprotheroe/vagrant-disksize
It can be installed by:
vagrant plugin install vagrant-disksize
Then modifying Vagrantfile to contain a line like:
config.disksize.size = '50GB'
causes the first partition to be enlarged to 50GB during provisioning.  Combined with an appropriate invocation of resize2fs:
sudo resize2fs /dev/sda1
so that the filesystem in the partition is resized, the disk space issue seems …

Vagrantfile tweaks

---

packages/cadaver/build.sh

I realized, cadaver already had a dependency on gnutls, but was not build with --with-ssl=gnutls. I tried to compile it with gnutls, but it failed, so I just tried openssl without a lot of debugging.
The package compiled (aarch64) and works on my phone with https now.

cadaver: fixed SSL by replacing gnutls with openssl

---

packages/termux-am/build.sh
packages/termux-tools/build.sh

`am` command reimplementation that works on Android Oreo
This pull request moves default `am` from `$PREFIX/bin/am` to `$PREFIX/bin/applets/am` and adds `$PERFIX/bin/am` reimplementation in separate package, so `am` refers to reimplementation if new package is installed and system `am` from `termux-tools` if it's not.
Mostly based on AOSP code
termux/termux-api#105

Android Oreo-compatible am command reimplementation

---

packages/alpine/env_unix.c.patch

I imagine people are using termux-exec, now, but this is for those who don't...

alpine: use termux tmp dir for locks

---

packages/proot/build.sh

* Consider EACCES as permission denied in fake_id0 (instead of just EPERM)
* Add warning about termux-exec if first process fails to start

proot: Update package

---

packages/valgrind/build.sh

Can't use `-fstack-protector`, as discussed in https://github.com/termux/termux-packages/issues/2148.

valgrind: build without -fstack-protector if debug

---

build-package.sh

`make` echos all commands, which makes logs like [this](https://api.travis-ci.org/v3/job/343233352/log.txt) less readable. Therefore, echoing of commands should also be suppressed.
( It is not tested because my Travis CI account has been suspended. )

Silent make too

---

packages/readline/build.sh

The old site seems to be down.
See also: https://en.wikipedia.org/w/index.php?title=GNU_Readline&type=revision&diff=815079915&oldid=815079783

fix readline homepage

---

build-all.sh
build-package.sh

Quite some packages require additional patching to build with debug symbols, I'm looking into that.

debug packages: rename package to package-dbg and add debug option to build-all.sh

---

packages/gzip/build.sh
packages/gzip/fix-gzexe.patch

Fixes errors like `/bin/sh: bad interpreter: No such file or directory` or `gzip: stdin: not in gzip format` when using executables compressed with gzexe.
It also seems that gzexe is a good alternative for upx (which was requested in https://github.com/termux/termux-packages/issues/2192).

gzip: fix errors in gzexe script

---

packages/proot/build.sh
packages/proot/termux-chroot

Update proot:
* MagiskSU support in `termux-chroot` (termux/termux-packages#2229, pull request by @ShadowEO)
* `accept(2)` seccomp workaround (termux/proot#11, pull request by @marksteward)

proot: Update for accept and MagiskSU support

---

packages/emacs/build.sh

Solves https://github.com/termux/termux-app/issues/608. @michalbednarski found the solution.
Not sure if this will have any other side effects.
I also tried patching src/emacs.c by adding `&& !defined __ANDROID__` to [this line](https://github.com/emacs-mirror/emacs/blob/0965d94ca426765382f366bf48f88ba5f9500afd/src/emacs.c#L830) and it worked as well, adding this configure option felt cleaner though.

emacs: ac_cv_func_setrlimit=no to make termux-am work within emacs

---

packages/binutils/build.sh

The --enable-new-dtags option to ld causes it to emit a RUNPATH rather than RPATH entry in the elf header. Because the Android linker supports RUNPATH but not RPATH, this means many things can now Just Work. This should (eventually) eliminate the need to set LD_LIBRARY_PATH.
Prior art:
This [became the default for Linux in 2013](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commitdiff;h=822b8bf) but I think termux isn't getting it because it reports "Android" instead of "Linux"? Or maybe the way it works changed since then. Regardless, [Debian has been using RUNPATH by default since December 2016.](https://sources.debian.org/src/binutils/2.27.90.20161231-1/debian/patches/ld-new-dtags-by-default.diff/?hl=27#L27) Their [newest …

ld: set --enable-new-dtags by default

---

packages/ecj/build.sh
packages/ecj/ecj-21
scripts/setup-android-sdk.sh

Also add executable that compiles with the older android classes

ecj: provide android-21.jar instead of android-16.jar

---

packages/rclone/build.sh

Closes #704
I use GitHub archives (https://github.com/ncw/rclone/archive/v1.40.tar.gz) instead of the tarball with signed checksum (https://github.com/ncw/rclone/releases/download/v1.40/rclone-v1.40.tar.gz) as the latter is [broken](https://github.com/ncw/rclone/pull/2197). It will be fixed in the next rclone version.

rclone: new package, version 1.40

---

packages/postgresql/build.sh
packages/postgresql/postgresql-contrib.subpackage.sh

Three reasons:
1. build-package.sh doesn't have the facility to do this:
```
$ tar -xf /sdcard/Download/postgresql-9.6_9.6.7-0+deb9u1.debian.tar.xz
$ cd debian/
$ grep extension postgresql-9.6.install postgresql-contrib-9.6.install
postgresql-9.6.install:usr/share/postgresql/*/extension/plpgsql*
postgresql-contrib-9.6.install:usr/share/postgresql/*/extension/*
$
```
while `initdb` requires `extension/plpgsql*`.
2. postgresql-contrib takes up only 492kB out of 17.3MB
```
$ pkg unins postgresql
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
libandroid-shmem
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
postgresql postgresql-contrib
0 upgraded, 0 …
```

postgresql: do not split postgresql-contrib

---

packages/syncthing/build.sh
packages/syncthing/no_ioprioSet.patch

Disable use of syscall sys_ioprio_set() which is blocked
by seccomp.

syncthing: fix crash on Android 8 (#2391)

---

packages/htop/fix-missing-macros.patch

htop: Don't exit if /proc/stat cannot be opened

---

packages/imagemagick/build.sh

I was checking if it might fix the segfault problems, as the changelog
indicated that several memory overflows have been fixed, but they still
happen for me.
But at least it fixes the compliance bug present in version .29, that has been annoying me.

Update imagemagick to version 7.0.7.32

---

packages/freetype/build.sh

these files are missing but are included in build.sh for dev packages specifically... so i added them back.

install freetype-config and freetype-config.1

---

packages/libunistring/build.sh

Make locale_charset() use nl_langinfo() so that it would work
properly. For example:
$ idn2 --debug ''
Charset: en_US.UTF-8
idn2: toAscii: could not convert string to UTF-8
$ LD_PRELOAD=$PREFIX/local/lib/libunistring.so idn2 --debug ''
Charset: UTF-8
$

libunistring: fix locale_charset()

---

packages/libcln/build.sh

using no-integrated-as fails on this build.

libcln: using integrated as fix

---

packages/picolisp/build.sh

flow.c:663:37: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
So build with gcc

fails building 32bit using clang

---

packages/proot/build.sh

Fixes termux/termux-packages#2307 (aka. termux/proot#18); note however that while this fix prevents creation of broken hardlinks by `dpkg`, existing broken links needs to be removed manually (while running outside `proot`)

proot: Update to skip link2symlink rmdir handling

---

build-package.sh
packages/libqrencode/build.sh
packages/pass-otp/build.sh
packages/pass/build.sh

Useful package now that more companies/services implement two factor authorization following GDPR. 
Also add libqrencode to be able to generate qr codes. 
Add a TERMUX_PKG_SUGGESTS field to build-package.sh and suggest pass-otp for pass as well as libqrencode for pass-otp. 
Maybe pass-otp should be RECOMMENDS rather than SUGGESTS, any thoughts on the matter?

pass-otp: add package

---

packages/busybox/build.sh
packages/busybox/svlogd.c.patch

Busybox builds "busybox" and "busybox_unstripped", where the latter contains
debug symbols.
(I see that I made a typo in the commit message issue number)

busybox: fix #2488 and fix debug build

---

packages/apt/build.sh

Apt works correctly without specifying `[arch=all,${TERMUX_ARCH}]]`. So, I guess we can simplify sources.list.

apt: don't explicitly specify arch in sources.list

---

packages/termux-tools/pkg

This prevents users from using "su pkg ..." which breaks permissions. This prevents things like https://github.com/termux/termux-app/issues/542.

Add root check to pkg

---

packages/ncurses/build.sh

Symlinks of 6.0 has remained as we had been using `ln -sf` but not `rm -f` + `ln -s`:
```
$ dpkg -L ncurses ncurses-ui-libs | grep .so | sort
/data/data/com.termux/files/usr/lib/libcurses.so
/data/data/com.termux/files/usr/lib/libform.so
/data/data/com.termux/files/usr/lib/libform.so.6
/data/data/com.termux/files/usr/lib/libform.so.6.0
/data/data/com.termux/files/usr/lib/libform.so.6.1
/data/data/com.termux/files/usr/lib/libformw.so
/data/data/com.termux/files/usr/lib/libformw.so.6
/data/data/com.termux/files/usr/lib/libformw.so.6.1
/data/data/com.termux/files/usr/lib/libmenu.so
/data/data/com.termux/files/usr/lib/libmenu.so.6
/data/data/com.termux/files/usr/lib/libmenu.so.6.0
/data/data/com.termux/files/usr/lib/libmenu.so.6.1
/data/data/com.termux/files/usr/lib/libmenuw.so …
```

ncurses: fix versioned library symlinking

---

build-package.sh
packages/bash/build.sh
packages/ecj/build.sh
packages/elfutils/build.sh
packages/ldc/build.sh
packages/libgc/build.sh
packages/libllvm/build.sh
packages/linux-man-pages/build.sh
packages/ncurses/build.sh
packages/perl/build.sh
packages/pngquant/build.sh

Packages that require several source archives can then specify these in the same variables instead of downloading them in termux_step_post_extract. 
I've verified that all the packages with changes here generate the same file tree by comparing massage folders with `diff -q -r`.

Allow TERMUX_PKG_SRCURL and TERMUX_PKG_SHA256 to be arrays

---

build-package.sh

It was introduced in c18051e78118966e4a4d77cb1638d767822eca66. It didn't work as expected.

build-package.sh: don't set TERMUX_PKG_REPLACES for debug builds

---

packages/libcairo/build.sh

If libxcb is present (when building X-enabled packages), I'm getting errors:
```
/home/builder/.termux-build/libcairo/build/src/.libs/libcairo.so: error: undefined reference to 'shmat'
/home/builder/.termux-build/libcairo/build/src/.libs/libcairo.so: error: undefined reference to 'shmctl'
/home/builder/.termux-build/libcairo/build/src/.libs/libcairo.so: error: undefined reference to 'shmdt'
/home/builder/.termux-build/libcairo/build/src/.libs/libcairo.so: error: undefined reference to 'shmget'
```
because of XCB-SHM feature being enabled.
This patch disables all XCB-related stuff, it is not needed for official build anyway.

libcairo: don't use XCB if present

---

packages/nzbget/build.sh
packages/nzbget/nzbget.cpp.patch
packages/nzbget/nzbget.h.patch
packages/nzbget/options.cpp.patch
packages/nzbget/thread.cpp.patch
packages/nzbget/tlssocket.cpp.patch

Also fixes overwriting of config file during package upgrade. Use config in etc
as default instead (leaves config in users home to allow overriding).

nzbget: Update from 19.1 to 20.0

---

packages/libcurl/build.sh

Currently libcurl.so have ntlm-wb enabled without setting correct path to 'ntlm_auth' binary.

libcurl: use correct path for 'ntlm_auth'

---

packages/bash/etc-bash.bashrc
packages/openssh/session.c.patch
packages/zsh/etc-zshrc

PS1 is not supposed to be an environment variable (i.e. will not
be listed in `printenv` but only in `set`). Its value should also
be shell-specific.
With this commit we can stop exporting a static PS1 as env var on
the java side.
The prompt would now indicate whether the current user is root.

make PS1 dynamic and shell-specific

---

build-package.sh

The field 'Provides:' makes possible creation of virtual packages.
Info: https://www.debian.org/doc/debian-policy/#virtual-packages-provides

build-package.sh: introduce TERMUX_PKG_PROVIDES

---

packages/proot/termux-chroot

The check for a changed shell (e.g. by chsh) was correctly using $HOME/.termux/shell, but $HOME was being hardcoded to "/home" prior to the check.
Since most likely, $HOME is not yet "/home" (since the user is invoking termux-chroot) this test was failing to recognize changed shells (e.g. this failed with zsh).
Moving the assignment of HOME to /home after the shell has been read fixes this.

Changed shells were not being recognized

---

packages/libpulseaudio/build.sh

Pulseaudio doesn't work since upgrade to 12.0. This fixes that and ensures it doesn't happen again.

libpulseaudio: use TERMUX_PKG_VERSION in LD_PRELOAD

---

packages/openssh/build.sh

many distributions use "AcceptEnv LANG LC_*" by default for sshd. this
fixes UTF-8 output from such servers that do not happen to set LANG or
LC_CTYPE to UTF-8 by default server-side (termux env already sets
LANG=en_US.UTF-8)
I did not actually build-test this (sorry), but it's quite a trivial change.

openssh: SendEnv LANG by default

---

packages/debootstrap/Makefile.patch
packages/debootstrap/build.sh
packages/debootstrap/debootstrap.patch
packages/debootstrap/functions.patch
packages/debootstrap/scripts-debian-common.patch

Update to v1.0.106 and fix these errors:
```
grep: /proc/1/environ: No such file or directory
/data/data/com.termux/files/usr/bin/debootstrap: 1: eval: proot: Permission denied
/data/data/com.termux/files/usr/bin/debootstrap: 1027: /data/data/com.termux/files/usr/bin/debootstrap: grep: Permission denied
/data/data/com.termux/files/usr/bin/debootstrap: 1027: /data/data/com.termux/files/usr/bin/debootstrap: head: Permission denied
/data/data/com.termux/files/usr/bin/debootstrap: 1027: /data/data/com.termux/files/usr/bin/debootstrap: sed: Permission denied
/data/data/com.termux/files/usr/bin/debootstrap: 1027: /data/data/com.termux/files/usr/bin/debootstrap: cut: Permission denied
```

debootstrap: update to 1.0.106

---

packages/libmnl/build.sh

LIBDIR defaults to $PREFIX/lib64 for x86_64 these days. Maybe something that started at r17 upgrade?
Maybe other packages have the same issue.

libmnl: change to https url

---

packages/emacs/build.sh

This man page conflicts with the one included with Universal Ctags (just
like the ungziped one), so exclude it as well.

emacs: remove ctags.1.gz after building

---

packages/proot/build.sh

termux/proot#26 by @tomty89: For fake_id0 emulated `setgid` check if `euid==0`.

proot: Update for setgid() checking euid==0

---

packages/libpulseaudio/module-sles-sink.c

This should work way better than the old code, as it makes use of
the buffer queue callback to do Enqueue(), which might be the only
nice/right way to use OpenSLES on Android. CPU usage is low and
RAM usage seems reasonable. No memory leak noticed. Tested with
mpv on my Oreo phone (wired and Bluetooth).
The latency was chosen base on Bluetooth audio requirement on Oreo.
~Shouldn't be hard to make it configurable as a module param in the
future.~
~The new code has a known downside though, that is it doesn't really
support sink suspension, as in, silence will kept being written
to the audio device even when the sink is suspended, which may have
certain impact to battery time.~
~It's probably possible to catch the state change of the sink and
notify the buffer queue about it. It's just I …

libpulseaudio: rewrite sles sink

---

packages/texlive-bin/build.sh
scripts/setup-ubuntu.sh

Saves about 300 mb from docker image.

texlive-bin: host-build tools and rm texlive-binaries from setup-ubuntu.sh

---

packages/proot/build.sh

* Fix `utime` not available on Chromebook (termux/proot#28)
* Fix for running on Oreo on i386 and x86_64
* Fix `sendmsg` `SCM_CREDENTAILS` message when `getuid` was faked and application couldn't send message with own uid (termux/proot#30)

proot: update package (with fix for utime and sendmsg)

---

packages/libpulseaudio/build.sh
packages/libpulseaudio/module-sles-sink.c
packages/mpv/build.sh
packages/mpv/sles_numbuffers.patch

Apparently some Android builds/forks need it for Bluetooth audio.
It's a hardcoded default in the upstream AAudio implementation
anyway.
See the following for reference:
https://android.googlesource.com/platform/frameworks/av/+/android-8.0.0_r1/media/libaaudio/src/legacy/AudioStreamTrack.cpp#109
https://android.googlesource.com/platform/frameworks/wilhelm/+/android-8.0.0_r1/src/android/AudioPlayer_to_android.cpp#1680
https://android.googlesource.com/platform/frameworks/av/+/android-8.0.0_r1/media/libaudioclient/AudioTrack.cpp#488
Fixes #2703.

libpulseaudio/mpv: set numBuffers to 8 for SLES

---

packages/poppler/build.sh

Ran into errors when building outside the docker container.

poppler: avoid trying to use qt5 stuff

---

packages/bs1770gain/build.sh

Regrettably, I no longer wish to associate myself with this software. I do not want to have to read [changelogs](http://bs1770gain.sourceforge.net/#0.5.0-beta-4) where the author of a software chooses to inject his own political ideology, conspiracy theories and hate.

Remove @Neo-Oli (myself) as maintainer of bs1770gain

---

build-package.sh

Allows building debs outside of the Termux source directory.

Make $TERMUX_DEBDIR configurable

---

packages/mpv/build.sh

I don't think we want a rebuild just for this.

mpv: use `exec` in wrapper

---

packages/redis/no-tcsaflush.patch

Fix for https://github.com/termux/termux-packages/issues/2783

redis: use TCSANOW instead of TCSAFLUSH

---

packages/binutils/dirsearch.cc.patch

when using ld.gold this breaks stuff when something adds a searchdir /lib and android is denying root directory read permission.

ld.gold warning instead of error if dir doesn't exist

---

packages/binutils/build.sh

Disable warning for now:
```
/home/builder/.termux-build/binutils/src/gold/x86_64.cc:1592:10: error: case value evaluates to 3221225474, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
case elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND:
```

binutils: build with -Wno-c++11-narrowing

---

packages/hashdeep/PRIu_PRId.patch

Similar patch as used for [texlive](https://github.com/termux/termux-packages/blob/d946e67c5b86dd990ffa0e5654b2a514b787aeb9/packages/texlive/c%2B%2B11.patch).

hashdeep: fix c++11 build error

---

packages/par2/build.sh

par2: configure with ac_cv_c_bigendian=no

---

packages/p7zip/build.sh

Otherwise we get the same error as for binutils.

p7zip: build with -Wno-c++11-narrowing for ndk r18

---

packages/libpulseaudio/build.sh
packages/libpulseaudio/module-aaudio-sink.c

The "core" alternate sample rate must not kick in with our sink.
The sample rate of the sink must be locked onto that of the AAudio
stream.

libpulseaudio: set alternate sample rate in aaudio sink data

---

packages/ruby/build.sh

This changes it for i686 as well, even though we haven't gotten any bug reports from that arch, AFAIK.
Solves #2845.

ruby: use -O3 instead of -Os for 32 bit arches

---

packages/proot/build.sh

* Canonicalize tmp dir (termux/proot#40 by @tomty89)
* Merge changes from UserLAnd (althrough most are off by default, termux/proot#39 by @corbinlc)
* Puting loader in libexec instead of extracting it on every run

proot: Update with tmpdir canonicalization

---

packages/python/build.sh
packages/python2/build.sh

Header file 'Python.h' requires 'crypt.h' from libcrypto-dev.

python(2): dev package requires libcrypto-dev

---

packages/fakeroot/build.sh
packages/fakeroot/fakeroot-1.23_faked.c.patch
packages/fakeroot/fakeroot-1.23_libfakeroot.c.patch
packages/fakeroot/fakeroot-1.23_scripts_fakeroot.in.patch

Uses tcp ipc since SysV ipc is not available on most devices.
Requested in: https://github.com/termux/termux-packages/issues/2915

new package: fakeroot

---

packages/fontconfig/build.sh
packages/fontconfig/fcatomic.c.patch

By default, fontconfig tries to use link(2) when performing locking, but it fails due to SELinux. So it is better to disable it and directly use provided fallback.
```
<36>[13150.308510] type=1400 audit(1538522946.183:206): avc: denied { link } for pid=13109 comm="fluxbox" name="3336a65c52528c9c368e942d3dd307f8-le32d4.cache-7.TMP-b0gZma" dev="dm-0" ino=133296 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=file permissive=0
```

fontconfig: don't use link(2) for locking

---

packages/fakeroot/build.sh

Symlink libfakeroot.so is not getting installed for some reason, so it should be created manually.

fakeroot: fix missing libfakeroot.so

---

packages/strace/build.sh
packages/strace/ipc_msgctl.c.patch
packages/strace/ipc_shmctl.c.patch
packages/strace/strace.c.patch

Fixes error `Unexpected wait status 0x1f` and makes strace working on Android Pie.

strace: fix crash on Android 9 (Pie)

---

packages/ldc/build.sh
packages/ldc/ldc-druntime-tls.patch
packages/ldc/llvm-config.in

`i686` is also working with one more small patch, but I need to clean it up. `x86_64` has problems when trying to link ldc, apparently because D doesn't expect the 128-bit `long double` type used. I'll work on both and submit another pull for those arches later.

ldc: Update from 1.11 to 1.12

---

packages/bash/build.sh

This PR turns bash into essential package and prevents potential failures for bash scripts in case if bash is uninstalled.

mark bash as essential package

---

packages/termux-api/build.sh

Fixes https://github.com/termux/termux-packages/issues/2967.

termux-api: depend on 'bash'

---

packages/binutils/build.sh

In Termux, we need prioritize `$PREFIX/lib` over `/system/lib` for ld.
This patch changes search dir order to:
```
SEARCH_DIR("/data/data/com.termux/files/usr/aarch64-linux-android/lib64");
SEARCH_DIR("/data/data/com.termux/files/usr/lib");
SEARCH_DIR("/system/lib64");
SEARCH_DIR("/data/data/com.termux/files/usr/aarch64-linux-android/lib");
```
Fixes https://github.com/termux/termux-packages/issues/2992.

binutils: fix search dir order

---

packages/binutils/build.sh

Linking against libm.so libdl.so and so on currently fails on 32 bit arches
(see https://github.com/termux/termux-packages/issues/3005#issuecomment-435034306)

binutils: set correct /system/lib dir for 32bit arches

---

packages/libexpat/build.sh

Fixes https://github.com/termux/termux-packages/issues/3018

libexpat: build without docbook

---

packages/openssl/build.sh

Fix for https://github.com/termux/termux-packages/issues/2847 and other things that require OpenSSL with engine support.

openssl: build with 'engine support'

---

packages/grep/build.sh

Attempt to fix https://github.com/termux/termux-packages/issues/3010. It seems that grep is not properly linked with libandroid-support if it is not added to dependencies.
Before:
After:

grep: depends on libandroid-support

---

packages/dropbear/build.sh
packages/dropbear/default_options.h.patch
packages/dropbear/svr-authpasswd.c.patch
packages/dropbear/sysoptions.h.patch
packages/openssh/auth2-passwd.c.patch
packages/openssh/build.sh
packages/termux-auth/build.sh

Password authentication for OpenSSH and Dropbear.
This PR provides:
* libtermux-auth.so - library with password hashing & authentication method
* Password is hashed by using PBKDF from OpenSSL
* Password can be set by `passwd` command (like in normal Linux distributions)
* Necessary patches for OpenSSH & Dropbear

Dropbear & OpenSSH password authentication

---

packages/openjpeg/OpenJPEGConfig.cmake.patch
packages/openjpeg/build.sh

openjpeg: fix OpenJPEGConfig.cmake after relocation

---

packages/screen/build.sh
packages/screen/no-setuid.patch

Fix for https://github.com/termux/termux-packages/issues/3156.

screen: remove all calls that trigger seccomp on Android 9

---

packages/ledger/0001-Fix-garbled-dates-when-using-date-format.patch

ledger: Fix garbled dates when using --date-format

---

packages/mpd/build.sh

Fixes #3189.
Speedbuilding through #1169 shows that gcrypt.h is needed so I've added libgcrypt as BUILD_DEPENDS (should perhaps be DEPENDS?)

mpd: disable hybrid dsd decoder and add missing dependency libgcrypt

---

packages/unzip/bugfix-crc32.patch
packages/unzip/bugfix-csiz-underflow.patch
packages/unzip/bugfix-cve20149636.patch
packages/unzip/bugfix-empty-input.patch
packages/unzip/bugfix-getZip64Data.patch
packages/unzip/bugfix-nextbyte-overflow.patch
packages/unzip/bugfix-overflow-fsize.patch
packages/unzip/bugfix-test_compr_eb.patch
packages/unzip/build.sh

Unzip was not updated from on 20 April 2009 but contain serious issues already fixed in Linux distributions.
Termux should implement these fixes as well.
This will fix:
* CVE-2014-8139
* CVE-2014-8140
* CVE-2014-8141
* CVE-2014-9636
* CVE-2015-7696
* CVE-2015-7697
Patches were obtained from https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/unzip.

unzip: apply patches to fix some CVEs

---

packages/libgrpc/build.sh

libgrpc: update to 1.17.2 and avoid using libprotobuf's host-build

---

packages/socat/build.sh
packages/socat/no-o_append.patch

Now socat can open PTYs on Android 8 or newer.

socat: don't use O_APPEND

---

packages/debootstrap/build.sh
packages/debootstrap/fix-keyring-paths.patch

Fix for https://github.com/termux/termux-packages/issues/3105.

debootstrap: update to 1.0.114 and fix keyring paths

---

packages/hugo/build.sh

Hugo is a fast and flexible static site generator.
Requested in https://github.com/termux/termux-packages/issues/1666.

new package: hugo

---

packages/hugo/build.sh

Comple package "hugo" with feature requested in https://github.com/termux/termux-packages/issues/3236.
Generate manpages and bash completion.

hugo: build extended version

---

scripts/setup-android-sdk.sh

The licenses were not automatically accepted, and therefore running non-interactively would lead to a failure.
Using the `yes` command would solve these problems.

Accept licenses for Android SDK

---

packages/apr/build.sh

Needed for building some packages that use apr (when downloading dependencies)

apr: fix $NM path in share/apr-1/build/libtool

---

.travis.yml
Rakefile

This script can trigger builds for all architectures in parallel.
I am not very sure if this works as I am banned from Travis CI. Thanks.

Travis CI for all architectures

---

build-package.sh

Makes it possible to change default maintainer for another repo

build-package: make TERMUX_PKG_MAINTAINER overridable

---

packages/dash/build.sh

There is no need to separate `rm` and `ln -s`, right? Only `ln -sf` will already remove the original files, so that the code is less clumsy. How do you think?

Use ln -sf in dash rather than rm

---

packages/pass/build.sh
packages/pass/src-password-store.sh.patch

Since https://github.com/termux/termux-api/commit/5b3f31bf14d8588b2f0fee02b5b70f9dc46be17d fixes the newline being added to termux-clipboard-get, this workaround is no longer required here and actually breaks the comparission.

pass: don't add newline to output. Fixes #3310

---

packages/bash/build.sh
packages/nano/build.sh
packages/resolv-conf/build.sh
packages/tmux/build.sh

Some packages have configuration files not specified in TERMUX_PKG_CONFFILES. This makes user's configuration overwritten on package upgrade.

specify CONFFILES for bash, nano, resolv-conf, tmux

---

build-package.sh

Ensures -i builds are run in fresh environments

build-package.sh: set TERMUX_NO_CLEAN to false per default

---

ndk-patches/ifaddrs.h
ndk-patches/stdio.h.patch

Fixes some problems in NDK headers found in https://github.com/termux/termux-packages/pull/3321.

ndk-patches: fix stdio.h and ifaddrs.h

---

packages/proot/build.sh

- termux/proot#54 (Fix fstat() in processes which sets themselves
undumpable (SUID_DUMP_DISABLE))
- termux/proot#52 (Partial fix for issue, handle setuid on Android Pie)

proot: Update with fixes for sudo's fstat

---

.gitlab-ci.yml
scripts/Dockerfile
scripts/run-docker.sh

The `USER` instruction can replace the need to copy directories in `.gitlab-ci.yml`, and it is better as the containers need not specify username.

Dockerfile USER instruction

---

build-package.sh

[This commit](876a1e77d) assumes that there must be subpackage(s) for each package. As a result, [builds](https://cirrus-ci.com/build/5763728675962880) for `libandroid-support` or packages with no subpackages fail.
`find *.subpackage.sh` could [prevent](https://cirrus-ci.com/build/5714783631310848) such errors.

Avoid no subpackage error

---

build-package.sh
packages/termux-elf-cleaner/build.sh

I released new version of `termux-elf-cleaner`. It can be targeted at specific API level, for example if `__ANDROID_API__` is set to 24, it will keep DT_RUNPATH.
More information about changes can be found in https://github.com/termux/termux-elf-cleaner/commit/623f314cee94e5344588c40b7eb72a492f4e9b02.

termux-elf-cleaner: update to v1.3

---

scripts/build/termux_step_compare_debs.sh

Fixes the attempts at downloading everything in the repo root

termux_step_compare_debs: fix subpackage comparison

---

packages/ca-certificates/build.sh

ca-certificates at termux.net is still version 20181205

ca-certificates: fix version typo

---

build-package.sh
scripts/build/termux_download_deb.sh
scripts/build/termux_get_repo_files.sh
scripts/build/termux_step_start_build.sh

- Stop build if buildorder.py script throws an error
- Fix typo that prevented some arch=all packages to be downloaded
- Call termux_get_repo_files in termux_step_start_build instead to prevent re-downloading repo files

Fast build bug fix

---

packages/termux-elf-cleaner/build.sh
scripts/build/termux_step_start_build.sh

Provides fix for Android 5.
Closes https://github.com/termux/termux-packages/issues/2846.

termux-elf-cleaner: update to v1.4

---

build-package.sh
scripts/build/termux_step_handle_arguments.sh
scripts/build/termux_step_start_build.sh

Avoid corruption of the build environment if build-package.sh was executed in 2 parallel sessions.

build-package.sh: prevent parallel runs in the same environment

---

scripts/setup-ubuntu.sh

jq is needed by [bintray upload script](https://github.com/termux/termux-packages/blob/3f16a41efac3f364e00313ec7842a275606d08ad/scripts/package_uploader.sh#L103) and termux_step_compare_debs has been removed so debdiff is no longer needed in docker image

setup-ubuntu.sh: add jq and remove debdiff

---

packages/libc++/build.sh
scripts/build/termux_step_extract_into_massagedir.sh
scripts/build/termux_step_setup_toolchain.sh
scripts/buildorder.py

As clang++ in the NDK defaults to libc++ since r17, we no longer
need to fake a libstdc++.so at build time (and omit it from the
libc++ package we ship).

Simplify libc++ setup (android-5)

---

packages/libc++/build.sh
scripts/build/termux_step_extract_into_massagedir.sh
scripts/build/termux_step_setup_toolchain.sh
scripts/buildorder.py

As clang++ in the NDK defaults to libc++ since r17, we no longer
need to fake a libstdc++.so at build time (and omit it from the
libc++ package we ship).

Simplify libc++ setup

---

packages/fossil/build.sh

it appears to be working without api level 23 on android 5 anyway ?

fossil: working without api 23?

---

packages/nodejs/build.sh
packages/nodejs/deps-uv-src-unix-linux-syscalls.c.patch

See https://github.com/termux/termux-packages/issues/3608
Depending on how soon we want to switch to the bintray repo it might or might not make sense to merge this PR.

nodejs: avoid using __NR_statx

---

packages/libllvm/openmp-config-ix-m32.patch

Currently builds 32 bit libomp for x86_64.

libomp x86_64 fix

---

packages/finch/build.sh
packages/notmuch/build.sh

* notmuch: should be rebuilt after manpage gzipping fix in 3832f16c0fd092aa443ec293c37315e143283d5b.
* finch: remove unneeded symlink which is broken anyway.

[android-5] some packages should be rebuilt due to fixes

---

packages/termux-tools/motd

What is added:
* hints for enabling additional repositories. For now only root, unstable and x11 repos mentioned as science and game repositories enabled by default.
* links to issue tracker for application and termux-packages.

termux-tools: improve default motd

---

packages/texlive-bin/build.sh

@Grimler91 Is it will be acceptable to use Lua 5.2 for texlive-bin package ?
With liblua 5.3.5 it fails at build time:
```
aarch64-linux-android-clang -DHAVE_CONFIG_H -I. -I/home/builder/.termux-build/texlive-bin/src/texk/web2c -I./w2c  -I/home/builder/.termux-build/texlive-bin/build/texk -I/home/builder/.termux-build/texlive-bin/src/texk  -I/data/data/com.termux/files/usr/include/libpng16 -I/data/data/com.termux/files/usr/include -DPOPPLER_VERSION=\"0.75.0\" -I/data/data/com.termux/files/usr/include/poppler -I/home/builder/.termux-build/texlive-bin/src/texk/web2c/libmd5 -DpdfTeX -I/home/builder/.termux-build/texlive-bin/src/texk/web2c/luatexdir -I/home/builder/.termux-build/texlive-bin/src/texk/web2c/luatexdir/unilib -I/home/builder/.termux-build/texlive-bin/src/texk/web2c/luatexdir/luafo …
```

texlive-bin: fix compilation errors

---

.gitlab-ci.yml
scripts/build/termux_get_repo_files.sh
scripts/build/termux_step_start_build.sh

* Do not re=download release files.
* Efficiently handle dependencies: do not try to download \*.deb files when they already downloaded, do not try to extract them more than one time.
These 2 changes can significantly speed up fast-builds, especially when packages have large amount of dependencies.

Fast build fixes

---

packages/tsu/build.sh

Minor release since Magisk fixed 64bit support.

Update tsu to v2.1. Use git clone to checkout tags.

---

packages/wireguard-tools/android.c.patch

Not needed for ANDROID_API >= 24

wireguard-tools: remove part of patch

---

scripts/buildorder.py

as libiconv is no longer a symlink of it

buildorder.py: remove libandroid-support from always_deps

---

packages/cmus/build.sh

The cue sheet input plugin, which provides support for `.cue` files in cmus, makes use of the `lround` function found in the mathematical library `libm`. The linker doesn't link against `libm` by default, rendering the resulting `cue.so` library unloadable by cmus. This PR fixes this issue by appending ` -lm` to the linker flags.
Build log:
```
unprivileged@ubuntu-termux:~/gdr/termux-packages$ ./build-package.sh cmus
Building dependency libc++ if necessary...
libc++@19b built - skipping (rm /data/data/.built-packages/libc++ to force rebuild)
Building dependency libbz2 if necessary...
libbz2@1.0.6-3 built - skipping (rm /data/data/.built-packages/libbz2 to force rebuild)
Building dependency zlib if necessary...
zlib@1.2.11-3 built - skipping (rm /data/data/.built-packages/zlib to force …
```

cmus: fix cue sheet input plugin

---

packages/ffmpeg/build.sh

This PR enables the Libavfilter virtual input device. It allows for the usage of filterchains as input streams.
For example, `ffmpeg -f lavfi -i color=green -t 5.0 out.mkv` will generate a 5 seconds long video consisting solely of green pixels.
Build log: https://gist.github.com/gdrbyKo1/3e7343b66b85e0fc61d5277f3647f3bd

ffmpeg: enable lavfi virtual input device

---

packages/hfsutils/build.sh

mandir is set to $TERMUX_PREFIX/share/man in TERMUX_PKG_EXTRA_CONFIGURE_ARGS yet mkdir location does not match, causing build-all.sh to fail.

hfsutils: Correct termux_step_post_configure mandir location

---

packages/binutils/build.sh
packages/datamash/build.sh
packages/diffutils/build.sh
packages/exiv2/exiv2json.cpp.patch
packages/grep/build.sh
packages/indent/code_io.c.patch
packages/libllvm/build.sh

With this `./build-all -d -i` succeeds for all packages.
Several builds fail with `error: use of undeclared identifier '__USE_FORTIFY_LEVEL'`, maybe it's possible to solve this in some other way (rather than not using `__FORTIFY_SOURCE=2`).
The binutils error might be trivial to fix as well, but I've disabled the debug build for now. 
libllvm builds but the make install step fails so it's still disabled.

debug build fixes

---

packages/tergent/build.sh

> An ssh-agent implementation for Termux that uses Android Keystore as its backend.
The author of tergent provides [AArch64 deb](https://github.com/aeolwyr/tergent/releases). I'd like to make the installation even easier by including it in official Termux packages.

Add tergent

---

packages/keybase/build.sh

Hi,
I'm on the Keybase team and we made a bugfix release that affects Termux. This updates the build file to 4.2.1.

Update Keybase to 4.2.1

---

packages/ncurses-termcap/build.sh
packages/ncurses-termcap/fix-paths.patch
packages/ncurses-termcap/ncurses-tinfo-lib_setup.c.patch
packages/ncurses-termcap/ncurses-tinfo-tinfo_driver.c.patch

Ncurses with termcap support and libtinfo. Implements https://github.com/termux/termux-packages/pull/4101.
Seems to be compatible with already installed ncurses-based applications, but should not be used for compiling official Termux packages.

new package: ncurses-termcap

---

packages/mpdscribble/build.sh
packages/mpdscribble/file.c.patch
packages/mpdscribble/mpdscribble.conf.patch

Default config paths for log and other stuff is ~/.mpdscribble/ so users probably want to `mkdir ~/.mpdscribble` and `cp $PREFIX/etc/mpdcribble.conf ~/.mpdscribble/` and then edit `~/.mpdscribble/mpdscribble.conf` with their settings

mpdscribble: add package

---

packages/stow/build.sh

Fix #4114 by bumping stow to the version that removes unnecessary dependency

stow: update from 2.3.0 to 2.3.1

---

scripts/build/termux_step_setup_toolchain.sh

Enable stack-protector and `relro` by default. Shouldn't cause any issues, some packages even set those flags on theirs own. But still need testing.
Also adds `--as-needed` to linker flags which should prevent large lists of `DT_NEEDED` dependencies when they are not necessary.
***
https://github.com/termux/termux-packages/issues/4107

build-package.sh: basic hardening via cflags/ldflags + avoiding linking with extra libs

---

packages/hugo/build.sh

Update hugo package from 0.55.6 to 0.57.2.
This is my first contribution to termux-packages so please tell me if I am forgetting something in the contribution guidelines.
TODO

hugo: Update from 0.55.6 to 0.57.2

---

packages/cmake/Source-cmExecProgramCommand.cxx.patch
packages/cmake/build.sh

CMake modules that ran uname and other programs broke a couple days ago.

cmake: fix typo that broke exec_program

---

packages/llbuild/CMakeLists.txt.patch
packages/llbuild/build.sh
packages/llbuild/include-llbuild-BuildSystem-BuildSystemFrontend.h.patch
packages/llbuild/include-llvm-Config-config.h.patch
packages/llbuild/lib-Basic-PlatformUtility.cpp.patch
packages/llbuild/lib-llvm-Support-CmakeLists.txt.patch
packages/llbuild/products-llbuild-CMakeLists.txt.patch

llbuild is an interesting new build system and library that is now at the core of XCode and the Swift package manager. It includes a workalike to ninja, so you can replace the command `ninja test` with `llbuild ninja build test` (or more likely a shortcut).
I've been trying it out a bit lately and it seems to work well: all but one test in this package pass after adding the Termux prefix path to some tests. It also includes a swift-build-tool, which is useless right now, but won't be once I finally get the Swift compiler submitted here.
Strangely, this would be [the first llbuild package for a linux "distro"](https://pkgs.org/download/llbuild), as that site reports only a single outdated BSD package and my google searches turn up nothing else.

llbuild: add package

---

ndk-patches/bits-ioctl.h.patch
ndk-patches/langinfo.h
ndk-patches/pwd.h.patch
ndk-patches/string.h.patch
ndk-patches/sys-cdefs.h.patch

This patch hopefully makes it so that GCC can use the system headers,
and fixes a few C++ compiler issues.
Fixes made:
- __has_xxx wrappers
- Disable __overload__ attribute
- Disable _FORTIFY_SOURCE, it relies on Clangisms.
- Missing string literal cast
Hopefully, at least the main headers should work now.
Not tested. Based on my fiddling on-device.

NDK fixes for GCC and C++

---

packages/libdispatch/build.sh
packages/libdispatch/src-CMakeLists.txt.patch

Need this for the Swift stdlib but realized it can be its own library, for those who just want to use it alone. Everything else is mostly written in Swift, so it will come packaged with the compiler.  This package sticks a couple headers in $PREFIX/include/os, can change that if wanted.
Currently built off a recent snapshot, will update to the next official release whenever that's out.

libdispatch: add package

---

packages/libsignal-protocol-c/build.sh
packages/profanity/build.sh

Omemo is the hot new end-to-end encryption scheme that is now available in the latest profanity version

Enable Omemo support in Profanity

---

packages/libdispatch/build.sh
packages/libdispatch/src-CMakeLists.txt.patch
packages/llbuild/build.sh
packages/llbuild/include-llvm-Config-config.h.patch

These are the latest tags that correspond to the just-announced Swift 5.1 release. I'm looking into building a Swift 5.1 package also, but I've been using Swift master so far so I'm checking if 5.1 will work, since 5.1 was branched in March and doesn't have some Android patches that were since merged to Swift master.

Update llbuild and libdispatch packages to latest 5.1 release

---

packages/libllvm/build.sh

Fixes https://github.com/termux/termux-packages/issues/3686.

libllvm: use armv7a-linux-androideabi as default target triple

---

packages/nodejs-lts/build.sh
packages/nodejs-lts/deps-uv-src-unix-process.c.patch
packages/nodejs/build.sh
packages/nodejs/deps-uv-src-unix-process.c.patch

Should fix https://github.com/termux/termux-packages/issues/4065.
```
17829 close(22)                         = 0
17829 close(24)                         = 0
17829 close(26)                         = 0
17829 chdir("/data/data/com.termux/files/home/.npm/_cacache/tmp/git-clone-12251ed6") = 0
17829 setgroups(0, NULL)                = -1 EPERM (Operation not permitted)
17829 setgid(10088)                     = 0
17829 setuid(10088)                     = 0
17829 rt_sigaction(SIGHUP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTART}, {sa_handler=0x7b5cb3c744, sa_mask=~[KILL STOP RTMIN RT_1 RT_2 RT_3], sa_flags=SA_RESTART}, 8) = 0
```

nodejs: prevent calling setgroups(), setuid(), setgid()

---

packages/rust/build.sh
packages/rust/config.toml

Due to https://github.com/rust-lang/rust/issues/62558, the tools: rls,
clippy, and rustfmt cannot be built.
We also remove src which cuts the resulting size of the dep from about
330MB to 180MB.
The build is further broken into two steps:
1. `x.py dist`
2. `x.py install`
This change is because `x.py install` now fails due to an issue where
bootstrap tries to install  rustc-aarch64-linux-android before the
installation script is generated.
I am currently having an issue building x86_64. We should probably wait to merge until it is successful.
https://axius.s3-us-west-2.amazonaws.com/rust_1.38.0_aarch64.deb
https://axius.s3-us-west-2.amazonaws.com/rust_1.38.0_arm.deb
https://axius.s3-us-west-2.amazonaws.com/rust_1.38.0_i686.deb
https://axius.s3-us-west-2.amazonaws.com/rust-std-wasm32_1.38.0_ …

Bump Rust to 1.38.0

---

packages/starship/build.sh

Neither 0.18.0 or 0.20.2 is possible to build at the moment, it fails when trying to compile `libgit2-sys v0.9.1`
Edit: nevermind, I guess I haven't cleaned my build environment

starship: upgrade to 0.20.2

---

packages/libusb/build.sh

Since termux/termux-api#294 was merged, we can move libusb to the standard repo as per prior discussion in #2175.

libusb: Move from termux-root-packages

---

packages/libusb/build.sh

Same as #4397, this time for the android-5 branch.

libusb: Move from termux-root-packages (android-5)

---

packages/apt/build.sh

Makes possible to redirect traffic to mirror in case if main repository is down (like in https://github.com/termux/termux-packages/issues/4358).
Rule for redirecting `https://termux.org/packages/` is already configured on [CF](https://cloudflare.com).
Will add small overhead due to http redirect:
```
Hyperfine benchmark
No redirect:
Benchmark #1: apt update
Time (mean ± σ):      4.072 s ±  0.206 s    [User: 1.912 s, System: 1.463 s]
Range (min … max):    3.725 s …  4.574 s    10 runs
With redirect:
Benchmark #1: apt update
Time (mean ± σ):      4.494 s ±  0.674 s    [User: 2.075 s, System: 1.455 s]
Range (min … max):    4.032 s …  5.678 s    10 runs
```

apt: use redirectable url for main repository

---

packages/apt/build.sh

~~*Reworked variant of https://github.com/termux/termux-packages/pull/4426.*~~
* Makes possible to redirect traffic to mirror in case if main repository is down (like in https://github.com/termux/termux-packages/issues/4358).

apt: use redirectable (termux.org) url for main repository

---

packages/imagemagick/build.sh

libbz2 is listed as a dependency but it's compiled without it
apparently it's been this way since the 1st ever commit!

build ImageMagick with bzip2

---

scripts/Dockerfile
scripts/docker-cleanup.sh

As seen from [test builds](https://cirrus-ci.com/task/5661580147556352), the current uncompressed docker image size is 3.25GB...
Actually, there is a lot of work we can do that can cut down the size of the image.
1. Remove the NDK support for Android 16-19. Currently, the minimum Termux API Level is already Level 21, as seen in the `build.gradle` file of the [termux-app repository](https://github.com/termux/termux-app/blob/master/app/build.gradle). The Android NDK, however, also contains platforms for Android 16-19. These are totally unnecessary and can be removed. This yields a reduction of [80MB](https://cirrus-ci.com/task/6203545897402368). Although not significant, I think it is totally unnecessary to include it in Docker image.
2. Remove the [Vulkan …

Shrink docker image

---

packages/apt/0000-cmake-fix.patch
packages/apt/apt-ftparchive.subpackage.sh
packages/apt/build.sh
packages/apt/libapt-pkg.subpackage.sh

`libapt-pkg` is required for https://github.com/termux/termux-packages/issues/4568

apt: add apt-ftparchive and libapt-pkg subpackages

---

packages/tcl/build.sh

Both perl and tcl have Thread.3.gz this moves tcl version

fix file conflict with perl

---

scripts/build/termux_step_setup_toolchain.sh

https://github.com/termux/termux-packages/issues/4287 can be fixed by reverting https://github.com/termux/termux-elf-cleaner/commit/334efd1923c563e19d00e655dfbfb2f9f7031bb1 (I confirmed it), but that breaks libc++_shared as reported in https://github.com/termux/termux-packages/issues/3990. [@xeffyr looked into it and found](https://github.com/termux/termux-packages/issues/3990#issuecomment-507618608) that libc++_shared only breaks if termux-elf-cleaner is run before the binaries are stripped. 
So, do we need to strip the ndk libraries in termux_step_setup_toolchain? I don't get any problems for libandroid-support or libc++ during build or when linking against them on device.
Do we suspect that other packages will behave differently when building with un-cleaned android-ndk?

termux_step_setup_toolchain: skip running termux-elf-cleaner

---

packages/profanity/build.sh

Since libxss is now available in the main repository profanity started
to link against it. Since it isn't a dependency it may fail link the
executable. This removes xscreensaver support therefore this
link. I don't think there would be any use for that feature on Termux,
but if someone disagrees, we can just set libxss as a dependency
instead.

Profanity: Don't link against libXss

---

packages/chromaprint/build.sh

Chromaprint is an audio fingerprint library developed for the AcoustID project. It's designed to identify near-identical audio and the fingerprints it generates are as compact as possible to achieve that. It's not a general purpose audio fingerprinting solution. It trades precision and robustness for search performance. The target use cases are full audio file identifcation, duplicate audio file detection and long audio stream monitoring.
https://github.com/acoustid/chromaprint

New package: chromaprint

---

packages/libmediainfo/01_remove_libpthread.patch
packages/libmediainfo/build.sh
packages/libzen/01_remove_libpthread.patch
packages/libzen/02_add_libandroid_glob.patch
packages/libzen/build.sh
packages/mediainfo/build.sh

MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
https://mediaarea.net/en/MediaInfo
These build scripts are the product of trial and error. There may be a more elegant way to implement them. The challenge here is that the build files are in a subfolder (Project/GNU/Library or Project/GNU/CLI) and have relative references to the parent directories, so the build process must take place in the Project/GNU/Library directory.
Setting only TERMUX_PKG_SRCDIR to $TERMUX_PKG_SRCDIR/Project/GNU/Library and using TERMUX_PKG_BUILD_IN_SRC=true does not work because then TERMUX_PKG_BUILDDIR still points to $TERMUX_PKG_SRCDIR instead of $TERMUX_PKG_SRCDIR/Project/GNU/Library.
Versioned libraries are linked after install because other …

New packages: mediainfo, libmediainfo, libzen

---

packages/boost/build.sh

gives option to build with static libs so we don't have to update each boost revision

enable boost static libs

---

packages/bitcoin/build.sh

openssl hasn't really been used when compiling without GUI for a long time. See https://github.com/bitcoin/bitcoin/issues/16751#issuecomment-537416760

remove openssl dependency

---

packages/irssi/build.sh
packages/irssi/perl_config_support.patch.txt
packages/irssi/perlfix.patch

Enables some more features for Irssi.
Modules are static only (due to https://github.com/android/ndk/issues/201).
***
Related issues:
- https://github.com/termux/termux-packages/issues/4036
- https://github.com/termux/termux-packages/issues/2989

irssi: add support for perl and otr

---

build-package.sh
packages/busybox/build.sh
packages/emacs/build.sh
packages/mpd/build.sh
packages/openssh/build.sh
packages/tor/build.sh
packages/transmission/build.sh
scripts/build/termux_step_install_service_scripts.sh
scripts/build/termux_step_setup_variables.sh
scripts/lint-packages.sh

Makes it easier to add termux-services script. 
termux_step_install_service_scripts is run after
termux_step_post_make_install and loops over the new array
TERMUX_PKG_SERVICE_SCRIPT to add service scripts for termux-services.
The service scripts are usually only a one-liner so we might just as
well define it in a variable like TERMUX_PKG_SERVICE_SCRIPT.
TERMUX_PKG_SERVICE_SCRIPT should be an array on the format
("daemon-name" 'script to execute' "another daemon" 'multi\n line\n script'),
i.e. it should be of even length with name + script where the script
part preferably is within single quotes (to avoid accidental expansion
of for example $HOME).

Add termux_step_install_service_scripts and TERMUX_PKG_SERVICE_SCRIPT

---

packages/nodejs/avoid-ficlone-ioctl.patch
packages/nodejs/build.sh

FICLONE ioctl may trigger EACCES when executing copyfile().

nodejs: avoid FICLONE ioctl

---

packages/libluajit/build.sh

Currently, luajit header files are placed improperly.
As stated at luajit.pc file, package version is 2.1 and pkg-config
guides the header location to $TERMUX_PREFIX/include/luajit-2.1/.
This commit fixes the build script of wrong header path.
#4814

libluajit: fix unmatched header path and package version

---

.github/workflows/packages.yml

Necessary to handle cases where setup scripts were changed during push or pull request.

CI: allow to use customized Docker image

---

scripts/build/termux_step_setup_toolchain.sh

Unlike the NDK clang, the on-device clang has already been patched to add an rpath to the Termux-prefixed library path, so only have the build script add the rpath flag for NDK builds.
I noticed binaries built on-device had this path listed twice. I don't think this order change of LDFLAGS matters.

termux_step_setup_toolchain.sh: don't add duplicate rpath for on-device builds

---

packages/ndk-sysroot/build.sh
packages/ndk-sysroot/gcc_fixes.diff

This upstream commit is reverted:
github.com/aosp-mirror/platform_bionic/commit/b7b2884a2130c32b3ca7228891a0a9aa934a9be7
And some of the changes in this commit are included:
github.com/termux/termux-packages/commit/3da018dde122ae90ff82e9733c096e3c75331fe1.

ndk-sysroot: add patch for better compatibility with gcc.

---

scripts/build/termux_step_extract_into_massagedir.sh

I've been running into problems with this for on-device builds from the beginning, where it will try to stick files from `$PREFIX/tmp` into packages and fail for various reasons. Finally looked into how new packages are generated, this seems to fix it.

termux_step_extract_into_massagedir.sh: don't add tmp/ files to packages, particularly on-device

---

scripts/build/termux_step_create_datatar.sh
scripts/build/termux_step_create_debfile.sh

PAX aka POSIX is not supported in termux deb
Some (as openSUSE) distro tars take already the future default tar format PAX instead of gnu. But termux deb fails to install anything but "gnu" format so far.
Fixes install errors with
corrupted filesystem tarfile in package archive: unsupported PAX tar header type 'x'

enforce gnu format for deb tar archives

---

packages/emacs/build.sh

I have not been able to crash emacs all day so this might fix #2599. Ready to be tested by more people. Just having 
`TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" emacs_cv_func_sigsetjmp=no` 
does not work, but I have not tested only 
~~`TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" emacs_cv_func__setjmp=no"`, I should probably test that before merging~~, only having `emacs_cv_func__setjmp=no`, or only `emacs_cv_func_sigsetjmp=no` still segfaults

emacs: potential fix for segfaults on arm

---

packages/squid/build.sh

Enable certificate generator required for SslBump.

Squid: Configure with --enable-ssl-crtd

---

packages/recutils/build.sh
packages/recutils/getpass.patch
packages/recutils/vasnprintf.patch

* Patched getpass by wrapping in if statement thanks to https://github.com/termux/termux-packages/blob/master/packages/rsync/rsync-3.1.3_lib_getpass.c.patch
* Patched %n printf failing on android 10 thanks to https://github.com/termux/termux-packages/commit/759ad3f217e8e35338b488837aa27c9a007cc739
Closes #4892

Added recutils package.

---

packages/libandroid-spawn/build.sh

fixes linking with c since it won't find cpp symbols

libandroid-spawn: use CXX so it links c++ lib

---

packages/libllvm/build.sh
scripts/build/termux_step_patch_package.sh
scripts/build/termux_step_setup_variables.sh
scripts/build/termux_step_start_build.sh

This new variable is extremely useful when iterating on creating a large package, as otherwise you have to wipe the source and rebuild each time you make a mistake with the patches or build.sh script.
Simply set TERMUX_PKG_QUICK_REBUILD=true in build.sh if a build fails and then the TERMUX_PKG_SRCDIR and TERMUX_PKG_BUILDDIR will not be touched when you rebuild, including that the patches will not be applied again. When you're done iterating, diff for any new patches, save them, and remove this variable before rebuilding from scratch, hopefully for the last time. ;)
An example is shown for the giant libllvm package, where other modifications are also excluded if this variable is set.
This pull was tested by building some of the long-running libllvm package, stopping it after a while, …

Introduce TERMUX_PKG_QUICK_REBUILD

---

packages/swift/build.sh
packages/swift/llbuild-cmake-modules-Utility.cmake.patch
packages/swift/llbuild-products-llbuildSwift-BuildSystemBindings.swift.patch
packages/swift/llvm-project-clang-lib-Driver-ToolChain.cpp.patch
packages/swift/llvm-project-clang-lib-Driver-ToolChains-Linux.cpp.patch
packages/swift/llvm-project-clang-tools-IndexStore-CMakeLists.txt.patch
packages/swift/swift-build-script.patch
packages/swift/swift-cmake.patch
packages/swift/swift-corelibs-foundation-CMakeLists.txt.patch
packages/swift/swift-corelibs-libdispatch-src-CMakeLists.txt.patch
packages/swift/swift-corelibs-xctest-CMakeLists.txt.patch
packages/swift/swift-lib-Driver-ToolChains.cpp.patch
packages/swift/swift-lib-Driver-UnixToolChains.cpp.patch
packages/swift/swift-stdlib-private-SwiftPrivateLibcExtras-Subprocess.swift.patch
packages/swift/swift-stdlib-public-Platform-glibc.modulemap.gyb.patch
packages/swift/swift-tools-SourceKit-cmake-modules-AddSwiftSourceKit.cmake.patch
packages/swift/swiftpm-android.patch
packages/swift/swiftpm-chmod.patch
packages/swift/swiftpm-rpath.patch

This is for anyone who wants to try building the Swift 5.1.4 toolchain on an Android AArch64 device using the scripts in this repository. The following commands should do, you will need 5 GBs of free space and I estimate about an hour and a half with a Snapdragon 855:
```
pkg install clang binutils-gold file patch python cmake ninja python2 perl rsync libandroid-spawn libcurl libicu libsqlite libuuid libxml2 llbuild pkg-config
TERMUX_MAKE_PROCESSES=7 ./build-package.sh swift
```
Maybe one of the maintainers can build it and add the package to bintray.com. Getting all this cross-compiling from linux x86_64 like all the other Termux packages will require more work, since the Swift build scripts don't fully support building all this, other than cross-compiling the compiler and stdlib.
[Most …

swift: add script for on-device build

---

build-package.sh
scripts/build/termux_create_subpackages.sh

Makes it possible to create postinst scripts and similar or subpackages as well

build-package: add new function termux_step_create_subpkg_debscripts

---

packages/emacs/build.sh

--with-modules solves https://github.com/termux/termux-packages/issues/5011,
--without-selinux is needed for on device builds.

emacs: configure with --with-modules and --without-selinux

---

packages/muchsync/build.sh

Hi,
I'm trying to solve #5020 myself, but I'm getting
```
Downloading www.muchsync.org/src/muchsync-5.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
Dload  Upload   Total   Spent    Left  Speed
100  130k  100  130k    0     0   118k      0  0:00:01  0:00:01 --:--:--  118k                      
configure: WARNING: unrecognized options: --without-api-docs, --without-desktop, --without-emacs, --witho
ut-ruby                                             
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes          
checking whether make supports nested variables... yes …
```

Add muchsync build definition

---

packages/fselect/build.sh

[https://github.com/jhspetersson/fselect](https://github.com/jhspetersson/fselect)
Find files with SQL-like queries
While it doesn't tend to fully replace traditional `find` and `ls`, **fselect** has these nice features:
* SQL-like (not real SQL, but highly relaxed!) grammar easily understandable by humans
* complex queries
* aggregate, date, and other functions
* search within archives
* `.gitignore` and `.hgignore` support (experimental)
* search by width and height of images, EXIF metadata
* search by MP3 info
* search by extended file attributes
* search by file hashes
* search by MIME type
* shortcuts to common file types
* various output formatting (CSV, JSON, and others)

New package: fselect

---

build-package.sh
scripts/build/termux_get_repo_files.sh
scripts/setup-ubuntu.sh

When using mirrors, it is necessary to verify downloaded stuff with our PGP keys.

build-package.sh: verify release files with gpg when doing autobuilds

---

packages/libllvm/tools-clang-lib-Driver-ToolChains-Linux.cpp.patch

I recently found [this change to be useful when building the Swift package](https://github.com/buttaface/termux-packages/commit/a02f6856d2f37f91438f2acef69a92aeb22dea00#diff-f1dd144618494a04e2f3015e3a53fbaaL68), makes sense to use it here too. I also removed the last change for Android older than API 16, as nobody is likely dealing with that anymore.
Also, has anybody tried setting the `SysRoot` variable here to `@TERMUX_PREFIX@` by default, rather than appending to the current default value of `/`? I ask because sometimes Swift will pass a different sysroot to clang, and then all the prior appended paths don't work at all.

libllvm: check usr/include instead of usr/local/include for headers

---

packages/libllvm/build.sh
packages/libllvm/include-llvm-ADT-Triple.h.patch

I think this should fix #5076 and allow [other places where this `isAndroidVersionLT()` function is called](https://github.com/llvm/llvm-project/blob/7802be4a3d86743242273593d43a78df84ece8c1/llvm/lib/CodeGen/TargetLoweringBase.cpp#L202) to work properly.
The problem was that if an Android version isn't specified in the triple, it sets it to 0. That required the previous hack to ignore the version when figuring out whether to build PIE or not, but this is a better way to do it, ie set a default API level of `__ANDROID_API__` (24) if none is given in the triple.

libllvm: fix Android versioning regression that broke setting PIE on ARM

---

packages/libtool/build.sh

libltdl.la is needed by the accompanying ltdl.m4 script:
https://git.savannah.gnu.org/cgit/libtool.git/tree/m4/ltdl.m4?h=v2.4.6#n285
so it does not really make sense to split the package.

libtool: don't create libtool-static

---

packages/openssh/openbsd-compat-explicit_bzero.c.patch

The original comment indicates that using `bzero()` directly may result in dead store elimination, so they explicitly avoided calling `bzero()` as you do now. `explicit_bzero` is used in cryptographic software to clear keys from process memory after use, even if that memory is not read any more afterwards.
Maybe it would be safer like this? (I copied the approach from https://android.googlesource.com/platform/external/openssh/+/refs/tags/android-6.0.1_r70/openbsd-compat/explicit_bzero.c, so that should work on Android.)
Caveat, I was hand-editing the diff and did not find time to set up the toolchain to build this; but the general approach should work?

Indirect explicit_bzero through memset pointer.

---

scripts/build/termux_step_handle_hostbuild.sh
scripts/build/termux_step_patch_package.sh
scripts/build/termux_step_start_build.sh

Just realized I missed this in #4911 after trying to use this flag with a host build package.

TERMUX_PKG_QUICK_REBUILD: disable reapplying the host build patches too

---

scripts/build/termux_step_start_build.sh

This is useful so the host build can use the standalone toolchain if wanted. I'm currently working on a package that builds a couple needed bits for the host and cross-compiles some code for Android, using its builtin NDK support that doesn't need all the cross-compilation flags that these scripts initialize later on in `termux_step_setup_toolchain()`.
However, the `TERMUX_STANDALONE_TOOLCHAIN` variable wasn't defined before the package build script was sourced, so I move it up in this pull.
Now, there's always a chance that the standalone toolchain won't be setup before the host build for my package, so it might make sense to move that also before the host build, but it shouldn't be a problem most of the time. If you want me to move the standalone toolchain setup also before the host …

termux_step_start_build: define TERMUX_STANDALONE_TOOLCHAIN before sourcing build script

---

packages/libllvm/tools-clang-lib-Driver-ToolChains-Linux.cpp.patch

This seems to fix #5155, tested locally with the given testcase and for armv7.

libllvm: fix multilib regression that added host linker path

---

packages/proot/build.sh

proot: Update to fix brk() before execve()

---

packages/pulseaudio/module-sles-source.c

The current SL_ANDROID_RECORDING_PRESET_CAMCORDER value forced to use the internal mic.
By using SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION, instead, the pulseaudio module will follow the general behavior of the operating system ( if external headset is plugged in, audio source will be the headset, otherwise it will be the internal mic. ) 
(The value names are not really indicative, this behavior has been found out by trial  and error following OpenSLES_AndroidConfiguration.h)

modification of pulseaudio's module-opensles-source to allow headset in

---

packages/kibi/build.sh
packages/kibi/fsh-path-replacement.patch

Add [`kibi`](https://github.com/ilai-deutel/kibi), a text editor written in Rust.
I had to patch [`src/unix.rs`](https://github.com/ilai-deutel/kibi/blob/0.2.0/src/unix.rs) to replace FSH paths.

kibi: add package

---

packages/nushell/Cargo.toml.patch
packages/nushell/build.sh
packages/nushell/crates-nu-cli-Cargo.toml.patch
packages/nushell/crates-nu-cli-src-commands-from_bson.rs.patch
scripts/build/setup/termux_setup_rust.sh

I had to disable the core `sys` and `ps` builtins, because they depend on the `heim` and `battery` packages, which haven't been ported to Android. Everything else likely works, in my limited testing.

nushell: add package

---

packages/tsu/build.sh

The build.sh script is also refactored.
I have used TERMUX_PKG conventions and added sha256sums.
It now also includes a link for`sudo` that isnt advanced but works for general use of the command.
LMK if you have any questions/concerns.

tsu: Update to v8 release of v8.2.0

---

packages/jftui/build.sh
packages/mpv/build.sh

This PR adds buildscripts for [jftui](https://github.com/Aanok/jftui), and configures mpv to also build the shared library. Unfortunately, there are still some build issues: running it after installation results in `CANNOT LINK EXECUTABLE "jftui": library "libyajl.so" not found` (also applies to all other dependencies).
Interestingly, when running it with `env LD_PRELOAD="$PREFIX/lib/libyajl.so $PREFIX/lib/libmpv.so $PREFIX/lib/libcurl.so" jftui`, it works fine, so there seems to be some linker issue in my buildscript. However, I couldn't figure out what to change yet, so I'm hoping anyone seeing this has some ideas.

jftui: add package

---

packages/libflac/build.sh

using cmake makes broken and misplaced pkg-config files flac.pc and flac++.pc so using autogen.sh instead.

fix pkg-config issues

---

scripts/build/termux_step_patch_package.sh

Resolves #5326 
Logs patches that are applied during build.
**Current behaviour:**
```
$ ./scripts/run-docker.sh ./build-package.sh bitcoin
Running container 'termux-package-builder' from image 'termux/package-builder'...
termux - building bitcoin for arch aarch64...
Downloading https://github.com/bitcoin/bitcoin/archive/v0.19.1.tar.gz
Fetching boost_1_70_0.tar.bz2 from https://dl.bintray.com/boostorg/release/1.70.0/source/
```
**New behaviour:**
```
$ ./scripts/run-docker.sh ./build-package.sh bitcoin
Running container 'termux-package-builder' from image 'termux/package-builder'...
termux - building bitcoin for arch aarch64...
Downloading https://github.com/bitcoin/bitcoin/archive/v0.19.1.tar.gz
Applying patch: 0001-android-patches.patch
Applying patch: …
```

Log applied patches during build

---

packages/swift/build.sh
scripts/setup-ubuntu.sh

Also, update to prebuilt Swift compiler for Ubuntu 20.04, ~and see if it works in the updated Docker~ works fine.

swift: update from 5.2.3 to 5.2.4

---

packages/rclone/build.sh

Note: [1.52.1 might drop soon](https://github.com/rclone/rclone/pull/4287#issuecomment-636928176), if you want to hold of until then.

rclone: update to 1.52.0

---

packages/termux-tools/build.sh
packages/termux-tools/termux-reset

Provides a script which will:
* Tell user about things which will happen when $PREFIX will be erased.
* Prompt user for confirmation.
* Terminate all sessions after finish.
instead of simple `rm -rf $PREFIX` which is suggested on Wiki currently.

termux-tools: add script for resetting Termux installation

---

packages/swift/build.sh
packages/swift/swift-build-script.patch
packages/swift/swift-utils-build-script-impl
packages/swift/swiftpm-Utilities-bootstrap
packages/swift/swiftpm-rpath.patch

~Testing this WIP pull out by disabling the compiler build in the second commit for now, and only building the core libraries like Foundation and XCTest on Ubuntu to make sure they work.~
~I'm going to try cross-compiling the Swift package manager locally next, and once that's done, I'll remove the second commit and~ built the full Swift toolchain on the CI, ready to merge.

swift: build the corelibs and package manager

---

packages/megatools/build.sh

Fixes current incompatibility with Mega's new URL syntax

megatools: update to 1.10.3

---

packages/libdispatch/build.sh
packages/libdispatch/libblocksruntime.subpackage.sh

Splitting it off as suggested in #5409 and needed by #5411.

libblocksruntime: split off sub-package

---

scripts/setup-ubuntu.sh

I'm ready to submit samba to unstable-packages, but more packages need to be installed on the host. 
heimdal-multidev provides asn1_compile;  comerr-dev provides compile_et
If these aren't present, they get built during the build process by Samba, but with the cross-compiler... However, these programs need to run on the host at build time.

docker image: install heimdal-multidev and comerr-dev

---

packages/libelf/0002-Replace-libdwfl-nested-functions-with-macros-part-1.patch
packages/libelf/0003-For-clang-use-Blocks-instead-of-nested-functions.patch
packages/libelf/asm_align.c.patch
packages/libelf/build.sh
packages/libelf/gelf_st_visibility.patch
packages/libelf/libasm-static.subpackage.sh
packages/libelf/libasm.subpackage.sh
packages/libelf/libdw-static.subpackage.sh
packages/libelf/libdw.subpackage.sh

This adds two patches Chih-Hung Hsieh posted on the elfutils-devel mailing list a long while ago to allow building more of elfutils with Clang. He did patch more than what I've included here, but I wanted to include the bare minimum needed to get libdw and libasm to build. 
The patch to get libdw to build requires libdw to link against libBlocksRuntime, provided by the libdispatch package. So as to not introduce a dependency on libdispatch by the libelf package itself, I've split libasm (links to libdw) and libdw into subpackages - libelf.so continues to only link against zlib and libc.so.
libelf and its -static package remain mostly the same as before, with the exceptions of elfutils/elf-knowledge.h and elfutils/version.h now being included, along with libelf's pkg-config file. …

libelf: build libasm, libdw

---

packages/ctypes-sh/001-ctypes-android.patch
packages/ctypes-sh/002-array-element-fix-from-pahole.patch
packages/ctypes-sh/build.sh
packages/ctypes-sh/compile-obstack-c.patch
packages/ctypes-sh/configure_ac.patch
packages/ctypes-sh/fix_callback.patch

[Homepage](https://github.com/taviso/ctypes.sh)
struct support will work (well, the best it can do in the absence of debug symbols) once/if libdw gets added. In the meantime, it's fine as it is.

new package: ctypes-sh

---

packages/ctypes-sh/build.sh

Thanks for merging my other PRs, xeffyr. And thanks to buttaface for putting libblocksruntime into its own package.
Sorry if this causes any inconvenience, but this is a small bump to ctypes-sh to enable struct support now that libdw is present.

ctypes-sh: enable struct support

---

packages/swift/build.sh
packages/swift/swift-build-script.patch

`which` is no longer there by default. No need for a revision bump since this doesn't affect the official package built in the CI.

swift: tweaks to get on-device build working again

---

packages/moreutils/build.sh

parallel isn't built so why include its manpage?

moreutils: exclude parallel(1) manpage

---

packages/apksigner/Asn1BerParser.java.patch
packages/apksigner/build.sh

The current version of `apksigner` by fornwall only supports signing but not verifying `apk`.
On the other hand, this new version extracted directly from `build-tools` of Android SDK contains all the functions of the original `apksigner`. Therefore, it seems to be a much better alternative.

Full version of apksigner from Android SDK

---

packages/fdupes/build.sh

fixes #5575
turns out it was just because 287d37c53e874744ac10e7491ccc677158a677b0 changed it from the release tarball in to the development one without reconfiguring

fix fdupes

---

packages/music-file-organizer/build.sh

Old but incredibly useful program, especially on Android for Linux users pushing MP3s over manually or aggregating from multiple sources, who want some saner on-disk organization.

new package: music-file-organizer

---

.github/workflows/packages.yml

Caching of downloaded dependencies should reduce bandwidth usage.
https://github.com/termux/termux-packages/issues/5620

CI: setup caching of the dependency deb files

---

packages/apt/0012-keep-downloaded-packages.patch
packages/apt/build.sh

Tested this out locally and it works fine. I wanted something like this, as I uninstall the official Swift package all the time when I build locally updated or patched versions, and when I'd go back to installing the official package, it would need to download that 50 MB file again each time. It got to the point where I keep that package stored locally and reinstall it with `dpkg`, rather than have `apt` download it each time. With this change, `apt` will do this for me, for any packages that I uninstall, until `apt clean` is run. This new default can always be overriden on the commandline or [by adding a config file](https://salsa.debian.org/apt-team/apt/-/blob/1.4.y/debian/NEWS#L39).
I'll make some changes to add `clean` commands to the `pkg` install script and surface some cache info …

apt: update from 1.4.9 to 1.4.10, use Termux cache directory, and keep downloaded packages by default

---

packages/entr/build.sh
packages/entr/max_users_watch.patch
packages/entr/path.patch

entr v4.6 - run arbitrary commands when files change
The included patch is a backport from the upcoming 4.7 release, allows the tool to work when access to /proc is restricted.
http://eradman.com/entrproject/
https://github.com/eradman/entr

new package: entr

---

packages/apt/0000-cmake-fix.patch
packages/apt/build.sh

faster when updating by not having to call external bzip2
noticed when looking through yesterday's apt changes that the repo and its mirrors offer uncompressed, gz, or bz2, and apt chooses bz2, despite having its built-in bz2 support patched out

apt: allow bz2

---

packages/tmux/build.sh
packages/tmux/socket-path.patch

The socket path was changed from /tmp to @TERMUX_PREFIX@/var/run. Update the manual accordingly.

tmux: fix socket path in manual page

---

packages/libmediainfo/build.sh
packages/mediainfo/build.sh

Updated the packages mediainfo and libmediainfo from version 20.03 to 20.08
Also removed the extra configure arg "--with-dll" in mediainfo to switch from dynamic loading to dynamic linking to libmediainfo.

mediainfo: update from 20.03 to 20.08

---

packages/lf/build.sh

Add package for lf, a light-weight terminal file manager, version r15.
The config file, man page, docs, desktop entry, and integration scripts
(for bash, csh, fish, vim, and zsh) are also installed.

lf: add package

---

packages/rclone/build.sh

Edit: Sorry, I already forgot about https://github.com/rclone/rclone/commit/d1617ce7ceb0525019075254ecff0658fe4ed403. I'll re-enable modules.

Update rclone to 1.53.0

---

packages/croc/build.sh

This PR adds package for [croc](https://github.com/schollz/croc), a tool that allows any two computers to simply and securely transfer files and folders, similar to [magic-wormhole](https://github.com/warner/magic-wormhole).

New package: croc

---

packages/apt/0013-verify-prefix.patch.txt
packages/apt/build.sh
packages/bash/build.sh
packages/bash/verify-prefix.patch.txt
packages/coreutils/build.sh
packages/coreutils/verify-prefix.patch.txt
packages/dash/build.sh
packages/dash/verify-prefix.patch.txt
packages/dpkg/build.sh
packages/dpkg/verify-prefix.patch.txt

Few core packages like Bash or Apt will now do check whether Termux prefix is readable. That will prevent use of our prebuilt packages (and thus stop wasting Bintray bandwidth).
~~WIP for now as I need to check whether this doesn't have side effects and checks are added into `main()` function of these packages:~~
Also:

Add patches for prefix verification - prevent use of our prebuilt packages by third parties

---

packages/termux-tools/build.sh
packages/termux-tools/motd
packages/termux-tools/termux.1.md

Offline compilation of important information from the Termux Wiki.
Closes https://github.com/termux/termux-app/issues/938.
Closes https://github.com/termux/termux-app/issues/184.
Closes https://github.com/termux/termux-packages/issues/476.
~~WIP currently as following things I have not added yet~~:
Maybe will need information about add-ons.

termux-tools: add manual page for Termux app

---

packages/aspell-de/build.sh
packages/aspell-en/build.sh
packages/aspell-es/build.sh
packages/aspell-fr/build.sh

Added aspell dictionaries for English, French, German and Spanish.
Build script is fairly easy to adapt for other languages.
Dictionaries are under a custom license, so licence file is specified in build.
Build script is modelled off pull #1216.

Added some aspell dictionaries

---

packages/links/build.sh

Brotli is widely used compression for http web servers (RFC7932).
Debian has already enabled brotli decompression for links package, so
brotli decompression has been sufficiently tried and tested.
With this addition, links will add br as Accept-Encoding so that web
servers can serve brotli compressed contents for this text-mode web
browser.

links: add brotli as runtime dependency

---

packages/zoxide/build.sh

[zoxide](https://github.com/ajeetdsouza/zoxide) is a cross-shell directory autojumper.

new package: zoxide

---

packages/gitea/build.sh

Change the output of `gitea --version` to official, currntly the command outputs the termux-packages commit hash as version (I think) so it is not compatible with `gitnex`. This change makes it compatible with gitnex.

Change gitea version info to official versioning

---

packages/clash/build.sh

This adds a package for clash, GPL-3 licensed tunnel manager.
Upstream project: https://github.com/Dreamacro/clash
They do provide arm/aarch64 packages, but these obviously don't work on Termux.

Add clash tunnel manager

---

packages/sops/build.sh

Here's another new package: sops!
Upstream: https://github.com/mozilla/sops
In case you are wondering what the `make install` does: it essentially just execs `go install go.mozilla.org/sops/v3/cmd/sops` ([See Makefile](https://github.com/mozilla/sops/blob/38b25bd449619e1d6da20e637702f7c73203aa44/Makefile#L12-L13))

new package: sops

---

packages/tmux/build.sh
packages/tmux/socket-path.patch

I don't know if I should have touched the patch file (to update the dir name) - it still applies fine anyway.
Upstream: https://github.com/tmux/tmux/releases/tag/3.1c

Update tmux to 3.1c

---

packages/dictd/build.sh
packages/dictd/dict.conf

Added a basic configuration file for the dict client so that it is usable from install.
Default configuration uses servers on localhost and dict.org.

added conf to dictd client to use dict.org default server

---

packages/bash/etc-bash.bashrc

it's effectively the same but easier to read

default bashrc: less needless escapes

---

packages/rgbds/build.sh

Since rgbds is currently outdated and many repos which require it are updating to the latest version... have an update's pull request from a representative of the GBZ80 Assembly Termux community.

rgbds: update rgbds version from 0.4.1 to 0.4.2

---

packages/ca-certificates/build.sh

- Update pakage version to cacert.pem of 20201208.
- It prevented other packages from being upgraded.

[ca-certificates] Update to new uptream cacert.pem

---

scripts/build/configure/termux_step_configure_autotools.sh

Some packages install binaries to sbin folder. Since termux doesn't use sbin, just map it to bin folder. This eliminates the need of using this flag with TERMUX_PKG_EXTRA_CONFIGURE_ARGS in the build.sh script.
Also, libdir already maps to `prefix/lib` by default, so the `--libdir=$TERMUX_PREFIX/lib` flag is not necessary.

Add sbindir flag to configure script

---

packages/cfengine/build.sh

Needed to export `EXPLICIT_VERSION` otherwise the version in the binaries gets a commit hash :(

Fix version reported by cfengine for 3.17.0

---

packages/bat/build.sh

Reference: https://github.com/rust-lang/git2-rs/issues/180#issuecomment-678740147
[The build runs successfully](https://github.com/kidonng/termux-packages/actions/runs/467770672).

bat: remove unnecessary LIBGIT2_SYS_USE_PKG_CONFIG

---

packages/nodejs/build.sh

[Builds successfully](https://github.com/kidonng/termux-packages/runs/1660104936), I can try to compile locally if needed.

nodejs: update to 14.15.4

---

packages/rust/build.sh

I was not sure if just bumping the version number is enough, turns out [it builds successfully](https://github.com/kidonng/termux-packages/runs/1654945511).

rust: update to 1.49.0

---

packages/zsh/build.sh
packages/zsh/src-glob.c.patch

Backport of a patch submitted upstream.
Finally fixes #1894.

[zsh] Fix case insensitive globbing

---

packages/cmus/build.sh

Also use `v${TERMUX_PKG_VERSION}` instead of commit bash for `TERMUX_PKG_SRCURL`.

cmus: Update to 2.9.0

---

build-all.sh

- quote bash vars
- handle unknown flags in `getopts`
- add `-r` flag in `read` to avoid mangling `\`
- remove `$` in arithmetic which gives it PEMDAS characteristic
- single quote trap to expand when signaled vs. when defined

(maint) update build-all.sh

---

packages/gogs/app.ini
packages/gogs/build.sh

A lightweight self-hosted Git service
- It uses very low memory, memory usage around 30MB.
- Its performance is great in low-end mobile devices.
- It's available in most Linux distros.
- Licensed under MIT
- [Gogs](https://gogs.io/)

New Package: gogs v0.12.3

---

packages/nnn/build.sh

`nnn` requires `which` to function properly in some workflows.

Add dependency debianutils (which provides `which`)

---

.github/workflows/packages.yml

@Grimler91 I'm changing the name of `debs` tarball so it will also have a commit hash in name for tracking the corresponding commits. Making a PR so you can review your setup on grimler.se whether these changes are applicable.

github actions: append commit hash to artifacts archive name

---

.github/workflows/packages.yml

But only (try to) build the main packages. For each modified package we check if there are subpackages and in that case save them in built_packages.txt as well, so that the repository server does not have to parse the git repo to find out if there are subpackages.
@xeffyr is this fine to merge or do you need to do modifications on your box?

github actions: print subpackages to built_packages.txt as well

---

packages/direnv/build.sh

direnv has these variable set by default:
PREFIX   = /usr/local
BINDIR   = ${PREFIX}/bin
SHAREDIR = ${PREFIX}/share
MANDIR   = ${SHAREDIR}/man
We are overriding $DESTDIR while leaving $PREFIX unchanged which installs the binary to $DESTDIR/$BINDIR (i.e, $TERMUX_PREFIX/usr/local/bin instead of $TERMUX/bin).
P.S: Assuming we don't want to install direnv in $TERMUX_PREFIX/local/bin (which is what it should be installed to by default , judging from direnv's GNUmakefile) as most termux packages goes to $TERMUX/bin.

direnv: Fix installation location and update to 2.28.0

---

packages/libstrophe/build.sh

The package was changed in #6518, but I forgot a bump to reflect the
changes and so it does not get updated

Bump libstrophe revision

---

scripts/setup-termux.sh

Gnupg is required by a couple of things, including `build-package.sh`.

Ensure gnupg is installed in setup-termux.sh

---

packages/tmux/build.sh
packages/tmux/configure.ac.patch
packages/tmux/socket-path.patch

tmux 3.2 has been released [a few hours ago](https://github.com/tmux/tmux/releases/tag/3.2)
I'm by no means an autotools expert, so I really don't know how sane my patch for `configure.ac` is.
The resulting package builds and runs fine on my Android 11 devices.

Update tmux to 3.2

---

packages/rsync/build.sh
packages/rsync/configure.ac.patch
packages/rsync/configure.sh.patch

Should work, but if anyone could test if it compiles with termux tooling, cheers. It compiled on my side but it was with the hack @alexzhang describes, this way its nicer.
Basically GLIBC is not defined when using the aarm64 compiler because it uses clang (part of issue #5826), we can check if we're compiling for android and enable IPv6 support that way.
If anyone has a better fix feel free to submit that, but this should be a working solution. (Tested on actual phone, and rsync has IPv6 support this way)

rsync: configure.ac patch for IPv6 support

---

packages/croc/build.sh

Croc 8.x no longer works out of the box as there was a vulnerability in the public relay, so an upgrade to the latest version is required to get things back up and running
Edit: issue comment explaining the situation https://github.com/schollz/croc/issues/371#issuecomment-822721592

croc: update to 9.1.0

---

packages/clash/build.sh

Upstream release:
https://github.com/Dreamacro/clash/releases/tag/v1.5.0

Update clash to 1.5.0

---

packages/rclone/build.sh

Updates rclone to 1.55.1 with two new build flags:
1. Disable the inbuilt updater (`tags noselfupdate`)
2. Set the version to indicate that it is built by termux

rclone: update to 1.55.1 (+ tagged release, +noselfupdate)

---

scripts/setup-archlinux.sh

I have added the --needed option to pacman to prevent reinstalling packages that are already installed and updated.

Do not reinstall packages in setup-archlinux.sh

---

packages/ruby/build.sh

Optimization level `-O2` is insufficient for avoiding overoptimization, because it enables `-fstrict-aliasing`.
Upstream: https://bugs.ruby-lang.org/issues/17540

Force `-fno-strict-aliasing` for Ruby

---

packages/ttyd/build.sh

bump TERMUX_PKG_REVISION for ttyd 1.6.3 to 1
fix for #6845 
tested - works ok
```
~ $ ttyd -p 8080 bash
[2021/05/21 12:19:04:2233] N: ttyd 1.6.3 (libwebsockets 4.2.0-no_hash)
[2021/05/21 12:19:04:2244] N: tty configuration:
[2021/05/21 12:19:04:2245] N:   start command: bash
[2021/05/21 12:19:04:2245] N:   close signal: SIGHUP (1)
[2021/05/21 12:19:04:2246] N:   terminal type: xterm-256color
[2021/05/21 12:19:04:2246] N: LWS: 4.2.0-no_hash, loglevel 7
[2021/05/21 12:19:04:2246] N: NET CLI SRV H1 H2 WS ConMon IPv6-absent
[2021/05/21 12:19:04:2284] N:    /data/data/pl.sviete.dom/files/usr/lib/libwebsockets-evlib_uv.so
[2021/05/21 12:19:04:2330] N:  Using foreign event loop...
[2021/05/21 12:19:04:2332] N:  ++ [wsi|0|pipe] (1)
[2021/05/21 12:19:04:2333] N:  ++ [vh|0|default||8080] (1) …
```

recompile ttyd for libwebsockets 4.2.0

---

packages/pulseaudio/build.sh
packages/pulseaudio/pulseaudio-glib-static.subpackage.sh
packages/pulseaudio/pulseaudio-glib.subpackage.sh

The GLIB mainloop component is widely used (e.g. `pavucontrol-qt`)
To avoid introducing extra runtime dependencies for most current users, they're packaged as subpackages if for some reason `glib` is not wanted

Enable PulseAudio's GLIB component and put it in subpackages

---

.github/workflows/packages.yml

See https://github.com/actions/virtual-environments/issues/1187
Maybe a potential fix for the curl timeouts in GitHub Actions

Fix for curl timeout in GitHub Actions

---

packages/proot/build.sh
packages/proot/termux-chroot

I added `--kill-on-exit` option to `termux-chroot` script to terminate all processes on `exit`
this should avoid `exit` hanging when a user ran a daemon inside the `termux-chroot` session

termux-chroot: specify --kill-on-exit option

---

packages/ledger/CMakeLists.patch
packages/ledger/build.sh

This adds a compile-time configuration option to compile ledger with Python 3 support and adds Python to the list of dependencies. Not sure if the dependency should be written as `python` or `python3`. Any corrections welcome. This is related to issue #7006 and #4348. Closes #7006

compile ledger with Python support

---

packages/php-redis/build.sh

It would also need to be rebuilt anyway as it is currently broken. This
fixes that too
```
NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /data/data/com.termux/files/usr/lib/php/redis.so (dlopen failed: cannot locate symbol &quot;_call_user_function_ex&quot; referenced by
&quot;/data/data/com.termux/files/usr/lib/php/redis.so&quot;...), /data/data/com.termux/files/usr/lib/php/redis.so.so (dlopen failed: library &quot;/data/data/com.termux/files/usr/lib/php/redis.so.so&quot; not found)) in Unknown on
line 0
```

Update php-redis to 5.3.4

---

.github/workflows/packages.yml

This can be helpful while building large packages which often fail to
compile on some archs but compile well on other

CI: Do not stop all tests on failure of one

---

packages/apksigner/build.sh

Any argument with an IFS char in it used to get resplit when passed to apksigner.
Adding quotes around `$@` preserves the intended arguments.
@Grimler91 apologies for the duplicate request, github doesn't seem to allow pushing to a pull request linked to a dead branch. Made the changes and closed the older PR.

apksigner: fix word splitting in script

---

packages/ttyd/build.sh

Fix a missing library for ttyd. Adding libcap as dependencies would fix the issue (tested)

Fix missing library for ttyd: libcap

---

packages/pass/build.sh
packages/pass/src-password-store.sh.patch

With the current patch, pass will try to use `xclip` when `$DISPLAY` is
set. Termux (most of the time) doesn't have `xclip` even if `$DISPLAY`
is set, so this change will check for `xclip` specifically (and
`wl-copy`/`wl-paste` in case of `$WAYLAND_DISPLAY`).
So, if a user has `xclip` and `$DISPLAY` set, it will still use `xclip`,
otherwise it will use `termux-clipboard-set`.
```
~ $ echo $DISPLAY
localhost:10.0
~ $ pass -c Steam
/data/data/com.termux/files/usr/bin/pass: line 182: xclip: command not found
Error: Could not copy data to the clipboard
~ 1 $ dpkg -i pass_1.7.4-1_all.deb
(Reading database ... 145411 files and directories currently installed.)
Preparing to unpack pass_1.7.4-1_all.deb ...
Unpacking pass (1.7.4-1) over (1.7.4) ...
Setting up pass (1.7.4-1) ...
Processing triggers …
```

Pass: termux-clipboard-set even if DISPLAY is set

---

packages/cfengine/build.sh
packages/cfengine/cfe-3721.patch

patch file represents a fix needed for no errors on bootstrap, resolved here: https://github.com/cfengine/masterfiles/pull/2042

cfengine: update to 3.18.0

---

packages/exa/build.sh

The completions files have been moved since the latest release, so I wasn't sure what I should do. To be safe, I future-proofed the script by checking the location of one of the files. Ideally, on the next release of exa, the script would be edited and only the `else` part would be kept.

exa: install shell completions

---

packages/miniserve/build.sh

Adding miniserve (https://github.com/svenstaro/miniserve/). 
This program could be used as a faster and more feature-rich alternative of `python3 -m http.server port`
Compile and test was successful on the docker image. However, I did not test the actual `.deb` file on my local android device. (My Termux is from Google Play and $TERMUX_PREFX is not set. )  
Would be great if someone could test independently.

new package: miniserve

---

packages/fzf/build.sh

These two were missing from the build script.
Still missing: key-bindings.bash and key-bindings.zsh which I guess should be sourced in their respective .rcs.
Previous discussion: 
@xeffyr xeffyr 28 minutes ago Member
Shell completion files are already copied into prefix. Why not to just symlink (ln -sfr src dest) them?
@pvonmoradi pvonmoradi 22 minutes ago Author Contributor
I tried to replicated aur script:
https://github.com/archlinux/svntogit-community/blob/packages/fzf/trunk/PKGBUILD

fzf: Add zsh completions and fish keybindings

---

packages/helix/build.sh

@xeffyr  tar could not be used as it uses git submodules, and hence not added to automatic updated projects.

Helix: bump to version 0.4.1

---

scripts/build/termux_step_create_datatar.sh
scripts/build/termux_step_start_build.sh
scripts/generate-bootstraps.sh

All, or at least most, of our debs contain "./" as a folder. This causes problems when extracting on some systems, as ./ then is the system root directory /, and tar cannot change the permissions of this folder.  Trying to build on arch for example gives:
tar: .: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
The issue appeared on arch somewhat recently, maybe with tar 1.33. With this we switch to creating data.tar.xz's with `data/data/com.termux/` instead of `./data/data/com.termux/`
Need to test and think about this a bit more to see how many other things this might break (bootstrap and command-not-found generation for example).

Create data.tar.xz's without prefixed ./

---

packages/helix/build.sh

- `deb` has not been uploaded to Termux repo.

Helix: bump revision

---

build-package.sh
packages/libllvm/build.sh
packages/swift/build.sh
scripts/build/configure/termux_step_configure.sh
scripts/build/configure/termux_step_configure_cmake.sh
scripts/build/termux_step_handle_hostbuild.sh
scripts/build/termux_step_patch_package.sh
scripts/build/termux_step_setup_build_folders.sh
scripts/build/termux_step_setup_variables.sh
scripts/build/termux_step_start_build.sh

Replaces the `TERMUX_PKG_QUICK_REBUILD` flag that we currently have. Instead of setting that temporarily we can now run `./build-package.sh -c <package>`, and it skips source extraction and configure and starts directly from `termux_step_make`.
Works well with libllvm, but need to be tested with rust and swift and other large packages.

build-package: add option to continue builds

---

packages/jcal/build.sh

This package provides Jalali (Iranian/Persian) calendar to show date in that system and convert to/from Gregorian dates.
Note that I had to remove `test_kit` from `Makefile.am` for a successful build.
https://repology.org/project/jcal/versions

new package: jcal

---

packages/emscripten/build.sh

Getting build issues for x86 and x86_64
LLVM introduce CET that broke the build
https://github.com/llvm/llvm-project/commit/21b25a1fb32ecd2e1f336123c2715f8ef1a49f97
```
/home/builder/.termux-build/emscripten/cache/llvm-project-8e284be04f2cd43a821289133a759afa2844f935/libunwind/src/cet_unwind.h:21:10: fatal error: 'cet.h' file not found
#include <cet.h>
^~~~~~~
1 error generated.
```
Looks like this need to be patched
I can't seem to control it using cmake build options
I will let it slide until next release, hopefully upstream will resolve it by then
I highly doubt people is using x86_64 emscripten since x86_64 node does not even exist in Termux repo

emscripten: update to 2.0.29

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh
scripts/build/termux_step_setup_variables.sh

I decided to add several ways to compress the package.  This can be done via `PKG_COMPRESS` (example: `PKG_COMPRESS="gzip"`).  If this value is not in `build.sh`, then compression will be through `xz`.

Adding PKG_COMPRESS function.

---

packages/libseccomp/build.sh

This exists in the root repo, but packages from main repo may require it also.

libseccomp: add to main repo

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh

A bug was noticed because the value in the `backup` was not displayed until the end.  
In addition to this, the `TERMUX_PREFIX` value is specified with the rood directory, and in the `backup` you need to rewrite the directory without the root directory.

Fixed bug with value backup.

---

build-package.sh
packages/gn/build-gen.py.patch
packages/gn/build.sh
scripts/build/setup/termux_setup_gn.sh

TODOs:
Sample project compile well on aarch64 Android 11
~~- [ ] Add a package that requires gn to build to test `termux_setup_gn`~~
~~- [ ] Add package `v8`~~
~~- [ ] `nodejs` link to shared `v8`~~

Add package: gn

---

scripts/build/termux_create_subpackages.sh
scripts/build/termux_step_create_debfile.sh

All packages that have conffiles, and a gz compressed control.tar.gz, currently fails to install on arm if the deb is built locally or downloaded and then installed with `apt install ./foo_1.0_arm.deb`. The error looks like:
$ apt install ./tmp/foo.deb
Reading package lists... Error!
E: Tar checksum failed, archive corrupted
E: Could not read meta data from /data/data/com.termux/files/home/tmp/foo.deb
E: The package lists or status file could not be parsed or opened.
If the package does not have conffiles, or if xz compression is used, everything works. Let's change back to xz compression for all new and updated packages for now to workaround this issue.
Even if `apt install ./foo.deb` fails the deb can still be installed with `dpkg -i ./foo.deb` (seems dpkg does not do the same  checksum …

build-package: use xz compression for control archives (again)

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh
scripts/build/termux_step_start_build.sh

The compiler adds an extra "-" separator.  Because of this, an error occurs from the database from the service.  
Can experiment and add a function that will add the `epoch` value, but this is quite risky.  
https://wiki.archlinux.org/title/PKGBUILD#epoch

Fix bug with db

---

packages/lychee/build.sh

The source URL changed. So autoupdates broke. This PR bumps lychee to latest version

lychee: Bump to latest version

---

packages/nodejs/build.sh
packages/nodejs/src-debug_utils.cc.patch

I reached home and tried the deb, but it still logged to Android logcat. This patch stolen from nodejs-lts should really really fix it.
Sorry for the inconvenience caused 😔
PS, don't merge this until, I check if it's really fixed

Really fix nodejs log

---

packages/libx265/build.sh
packages/libx265/source-CMakeLists.txt.patch

Build hacks necessary for aarch64 (`-fno-integrated-as` + ` --target=${CCTERMUX_HOST_PLATFORM}`) credit goes to @jeevatattva (#7548).
EDIT: Turns out the reason that `CROSS_COMPILE_ARM` is problematic for arm is that `ARM_ALIASES` has `armv7l` instead of `armv7-a` (and it appears that `armv7l` is not accepted by cmake as the value for `CMAKE_SYSTEM_PROCESSOR`). While `CROSS_COMPILE_ARM` is not necessary / does not seem to cause any actual effect, I included the fix in the patch so that `CROSS_COMPILE_ARM` won't cause any problem. (Though the fix seems to have made `-fno-integrated-as` necessary for arm additionally.)

libx265: Update from 3.3 to 3.5

---

packages/nodejs/build.sh

Bump nodejs to 16.10.0
Additional changes made:-
- Removed comment about out of memory while building on CI, since it is not reproducible since a while now

node v16.10

---

packages/libdvbcsa/build.sh
packages/tvheadend/build.sh
packages/tvheadend/disable-mmx-sse2
packages/tvheadend/time_64.patch64

- closes #3066
- moved from #7563 
TODO:

Add package tvheadend

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh

The reason is described [here](https://github.com/termux/termux-packages/discussions/7596).

Improving the look of the version

---

packages/libx265/build.sh
packages/libx265/source-common-primitives.cpp.patch

To avoid text relocations.
Fixes #7586.

libx265: Disable assembly for arm

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh

This is necessary for the service to work stably.  The service has a bot that updates the db.  One of the required values ​​is the filename, but there is a problem.  If you take the name from the file name, then the file name is not stable for this.  And if with PKGINFO, it will not work with remote packages.

Correction of the version view in the file name (add pkgrel)

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh
scripts/build/termux_step_setup_variables.sh

Thanks to this value, can set the group that the package will belong to.  
```
TERMUX_PKG_GROUPS="base-devel"
```
or
```
TERMUX_PKG_GROUPS="base-devel, base"
```
If anything is there in more detail: https://wiki.archlinux.org/title/Pacman#Installing_package_groups

Adding TERMUX_PKG_GROUPS value for pacman packages.

---

packages/ant/build.sh

I forgot to do this earlier but I believe we should remove the manual folder. They are HTML files and is also available online. Main issue being storage as that manual folder alone is taking 40 MB.

Remove manual pages from ant

---

packages/watchexec/build.sh

1- Had to override `termux_step_make_install` to change `--path`. The [cargo.toml](https://github.com/watchexec/watchexec/blob/main/Cargo.toml) is a workspace manifest. Is there a cleaner way of doing it?  
2- I assumed https://github.com/watchexec/watchexec/blob/e21a3a99f6b66b8472abc55c6837eb5e66a412fa/cli/Cargo.toml#L53-L65 are only applicable to debian package creation and we have to manually do them in `termux_step_post_make_install`

new package: watchexec

---

packages/libass/build.sh

To avoid text relocations.
Fixes #7648.

libass: Disable nasm

---

packages/qemu-system-x86-64-headless/0017-fix-i386-mmu.patch

QEMU has bug in i386 MMU which is described in [this issue](https://gitlab.com/qemu-project/qemu/-/issues/676)
It causes Windows to BSOD with PAGE_FAULT_IN_NONPAGED_AREA error (see [this issue](https://gitlab.com/qemu-project/qemu/-/issues/394))
This patch was posted one day ago by @bonzini and it fixes this bug
[https://patchew.org/QEMU/20211104140958.445304-2-pbonzini@redhat.com/](https://patchew.org/QEMU/20211104140958.445304-2-pbonzini@redhat.com/)

qemu-system-x86_64-headless: add patch to fix MMU bug

---

packages/wasmer/build.sh
packages/wasmer/lib_vm_src_trap_traphandlers.rs.patch

Closes #7516
Replaces #7972, sorry @leapofazzam123, should have pushed this a long time ago
I had to fix an issue that broke with NDK r23 and naively using their own provided Makefile will only generate x86_64 Linux binaries, not Android binaries
`wasmer` will not be available for Android ARM and i686
as there are missing support at upstream (upstream don't even support Linux ARM yet)
Others are welcome to fix at upstream then add support here

new package: wasmer

---

packages/innoextract/build.sh

Useful for extracting Windows GOG Installers that are in `.exe` extension, may aid in porting games in the future
The sad part is the small `innoextract` depends on the huge `boost` library so download size will be big

new package: innoextract

---

packages/nim/build.sh

added -d:tempDir: when compiling nimble and koch because host nim compiler is using /data/local/tmp as temporary directory. 
fixes #8096

fixing nimble

---

packages/nodejs/build.sh
packages/nodejs/deps-v8-src-trap-handler-trap-handler.h.patch

Additional changes made:
~~- The patch `deps-v8-src-trap-handler-trap-handler.h.patch` should no longer be needed needed. This should also have been fixed https://github.com/nodejs/node/issues/36287. If this PR succeeds to build, I will report that this has been fixed by https://github.com/nodejs/node/commit/e3f89881183c70c02797ba096c50765b5bdc2433#diff-f350b1b5e53caf9ecde4240ba8f544b3be4f278e4f8efa86b54c30ea625b8b1d~~ Mistaken
- The libatomic hack has been removed since https://github.com/termux/termux-packages/issues/3092 has been reported to have been fixed with newer NDK

nodejs: Bump to 17.2.0

---

scripts/build/termux_step_setup_toolchain.sh
scripts/build/termux_step_start_build.sh

termux_step_setup_toolchain: `-fPIC` should be in `CFLAGS`

---

packages/mediainfo/build.sh

mediainfo: libandroid-support must be `DT_NEEDED` by main executable

---

packages/gdb/build.sh

gdb: Explicitly link against compiler-rt builtins

---

packages/gnunet/build.sh
packages/gnunet/no-__bswap.patch

#8080 failed when updating gnunet to 0.15.3, let's investigate and fix this

gnunet: update to 0.15.3

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh

Pacman does not have an "or" operator in package dependencies.  To avoid future errors, will need to add the `TERMUX_PKG_PROVIDES` value to one of the conflicting packages.

Bug fix - remove "or" operator in dependencies for pacman format

---

packages/mlocate/build.sh
packages/mlocate/src-locate.c.patch

mlocate: Add message for absence of `mlocate.db`

---

packages/sqlcipher/build.sh

Also, sqlcipher does not depend on sqlite (unless there's something Termux-specific I'm not aware of), so this commit removes that dependency as well.

sqlcipher: update to 4.5.0

---

packages/libcap-ng/build.sh
packages/util-linux/build.sh

Added `setpriv` in `util-linux`.
Android `7` and some Android devices `8` do not support ambient capabilities and will return `activate capabilities: Invalid argument` when running `setpriv`.
strace shows `"prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_IS_SET, CAP_CHOWN, 0, 0) = -1 EINVAL (Invalid argument)"`
This was an issue with `libcap-ng` where support for `PR_CAP_AMBIENT` was checked at compile time, so `setpriv` only worked on Android > `7`/`8` when `capng_apply()` was called.
`4.3    kernel   PR_CAP_AMBIENT`
https://github.com/util-linux/util-linux/blob/v2.37.1/sys-utils/setpriv.c#L1010
https://github.com/stevegrubb/libcap-ng/blob/v0.8.2/src/cap-ng.c#L59
https://github.com/stevegrubb/libcap-ng/blob/v0.8.2/src/cap-ng.c#L716
https://source.android.com/devices/architecture/kernel/android-commo …

Add setpriv

---

packages/gauche/build.sh
packages/gauche/configure.ac.patch
packages/gauche/ext-Makefile.ext.in.patch
packages/gauche/ext-dbm-Makefile.in.patch
packages/gauche/ext-text-gettext.scm.patch
packages/gauche/ext-tls-gauche-tls.h.patch
packages/gauche/fake-ndbm-makedb.c
packages/gauche/gc-os_dep.c.patch
packages/gauche/lib-gauche-configure.scm.patch
packages/gauche/lib-gauche-interactive-toplevel.scm.patch
packages/gauche/lib-gauche-package-util.scm.patch
packages/gauche/libsrc-gauche-process.scm.patch
packages/gauche/src-libsys.c.patch
packages/gauche/src-libsys.scm.patch
packages/gauche/src-system.c.patch

new package: gauche

---

packages/apktool/AndrolibResources.java.patch
packages/apktool/build.sh

that does not have `--forced-package-id` option.
Fixes #8295.

apktool: Always assume custom `aapt`

---

packages/aapt/build.sh

as a follow-up of https://github.com/termux/termux-packages/commit/653a110ddba96a1b6b8e8421d53e25169cc2302c.
Fixes #8385.

aapt: Add necessary `-fPIC`

---

packages/gauche/build.sh
packages/gauche/src-gauche-priv-pairP.h.patch

Effectively reverts commit 3aca178a070cbc6baa0f26a0a894704565066886.
Follow-up of #8329.

gauche: Fix assertion failure on arm

---

packages/libatomic-ops/build.sh

Intended to be used for the `gauche` package but it turns out to be unnecessary.

new package: libatomic-ops

---

packages/emscripten/build.sh
packages/nodejs-lts/build.sh
packages/nodejs/build.sh

Temporary fix for #3188 and #8387
Closes #3188 
Closes #8387
As noted in https://github.com/npm/statusboard/issues/395#issuecomment-1003256492, this seems to be a problem with how npm handles postinstall, preinstall and other package hooks. Adding `--foreground-scripts` is a temporary hack until itis fixed.

nodejs,nodejs-lts: npm: set `foreground-scripts` to true on postinstall

---

packages/cmark/build.sh

Other repos are using cmark-gfm for github's fork of cmark. In case enough people are interested for cmark-gfm, we can package it too

cmark: update to 0.32.0 and get source from upstream

---

packages/shairport-sync/build.sh
packages/shairport-sync/configure.ac.patch
packages/shairport-sync/shairport.c.patch

Using the last version that does not use `pthread_cancel`.
Closes #3552.

new package: shairport-sync

---

packages/lua-language-server/build.sh
packages/lua-language-server/make.lua.diff

- remove arm from TERMUX_PKG_BLACKLISTED_ARCHES
#8491 should be closed. That's a wrong patch.

Chore(lua-language-server): update to 2.5.6

---

packages/nodejs/build.sh

New version contains fix for security vulnerability. See https://github.com/nodejs/node/releases/tag/v17.3.1

nodejs: update to 17.3.1

---

packages/nodejs-lts/build.sh

New version has security fixes. See https://github.com/nodejs/node/releases/tag/v16.13.2

nodejs-lts: update to 16.13.2

---

packages/dart/build.sh

when flutter app loading libapp.so it will check a feature string 'compressed-pointers', the arch build without  'c', gen_snapshot will output libapp.so include 'no-compressed-pointers' not 'compressed-pointers'.

dart: support flutter and enable x86_64

---

packages/libgnutls/build.sh

When i was building `glib-networking` then i got undefined reference errors like `undefined reference to gnutls_pkcs11_init` and we have **p11-kit** already so..

build gnutls with p11-kit

---

packages/librusty-v8/build.sh

Dependency of `deno` (#5306). Needs to build separately due to disk space.

new package: librusty-v8

---

packages/strace/build.sh
packages/strace/configure-find-armv7-cc.patch
packages/strace/mpers-use-host-readelf-for-debug-dump.patch
packages/strace/sigreturn.c.patch

The mpers support doesn't appear to break anything: I was able to `strace` an obfuscated 32-bit ARM binary on my 64-bit ARM phone without problems. There's no point in enabling it for `arm` and `i686`. Sadly, `x86_64` builds fail with mpers support enabled, so it's excluded from build there. The Ubuntu host's `readelf` binary is used, because it's the only one with support for the `--debug-dump` argument.

strace: update to 5.16 + enable mpers for aarch64

---

packages/chromaprint/build.sh

as `fpcalc` does not build with ffmpeg 5.0.

chromaprint: Build without tools

---

packages/gegl/build.sh

which currently does not build against ffmpeg 5.0:
https://gitlab.gnome.org/GNOME/gegl/-/issues/301

gegl: Disable ffmpeg support

---

packages/unar/build.sh
packages/unar/sys_time.c
packages/uwsgi/build.sh
packages/uwsgi/sys_time.c

The first argument of `timespec_from_timeval()` must be a pointer.
Fixes #8647.

unar, uwsgi: Fix bug in `sys_time.c`

---

packages/openssl/build.sh

Might be helpful for anyone working with openssl
If the manpages increase the package size by a huge amount, I'll split the manpages into openssl-manpages subpackage

openssl: Also install manpages

---

packages/avahi/build.sh
packages/avahi/libdns-sd-static.subpackage.sh
packages/avahi/libdns-sd.subpackage.sh

Closes #8687.
Also enables compatibility layer for libdns_sd, closes #182.

avahi: Enable use of D-Bus / Enable libdns_sd compat

---

packages/ncurses/build.sh

The packages need to be built locally instead of on CI cause the number of them is huge. I'll try to get them all building and store the debs, so that we don't burn the CI like anything

ncurses: update to 6.3

---

packages/ncurses/build.sh

due to timeout issue for invisible-mirror.net.

ncurses: Use alternative source url

---

packages/gsl/build.sh

gsl: Do not remove `bin/gsl-config`

---

packages/chezmoi/build.sh
packages/exa/build.sh
packages/fish/build.sh
packages/lastpass-cli/build.sh
packages/lastpass-cli/process.c.patch
packages/lastpass-cli/process.h.patch
packages/nnn/build.sh
packages/pastel/build.sh
packages/ripgrep/build.sh
packages/yadm/build.sh

Currently we are installing package specific completions for fisg shell
in `$PREFIX/share/fish/completions` which is incorrect. This also fixes
completions from fish ahell conflicting with other packages'
completions.
TODO:
(No need. A quick `apt-file search` seems to say that there are no packages in these two repos which are messing this around)

Install external completions for fish in `$PREFIX/share/fish/vendor_competions.d`

---

packages/libcdk/build.sh

Dependency of `cuse` (https://github.com/termux/x11-packages/issues/591).

new package: libcdk

---

.github/workflows/packages.yml

Previously we were outputting built debs into ./debs instead of standard folder ./output.  We were also sorting built_packages.txt so that $(cat ./built_packages.txt) returned an alphabetically sorted list.
This caused issues for pushes that updated both a package and one or more of its dependencies, if the dependencies start with a letter that is later in the alphabet.
Latest example was libforestdb and libsnappy.  Libforestdb depends on libsnappy, but the buildorder as given to build-package.sh was "libforestdb libsnappy".  During the libforestdb build libsnappy was built first, but the deb put into the standard ./output folder (that's how our build system currently handles built dependency debs).  When build-package.sh then later tries building libsnappy it skips it since it has …

 CI: fix occasional dependency upload issue

---

packages/aapt/aidl.subpackage.sh
packages/aapt/build.sh
packages/libgtest/build.sh

Fixes #8961 
`libgtest` and `googletest` are exactly the same package. and we can only have one, resulting a conflict error in dpkg

aapt, aidl: depend on googletest package

---

packages/libandroid-posix-semaphore/LICENSE
packages/libandroid-posix-semaphore/build.sh
packages/libandroid-posix-semaphore/semaphore.c

Bionic libc doesn't support `sem_open`, `sem_close` and `sem_unlink`. This package contains a port of posix named semaphore from musl libc. The mapped file will be created at the temp directory of termux `(/data/data/com.termux/files/usr/tmp)` rather than tmpfs `(/dev/shm)`.
It provides the NDK <semaphore.h> header. So this commit will update the ndk-sysroot package and termux NDK toolchain. Hope that removing <semaphore.h> header from NDK will not cause the compilation failure of many packages.
See also: #8990

Add Package: libandroid-posix-semaphore

---

packages/python/build.sh
packages/python/multiprocessing.patch

Bionic libc doesn't support `sem_open`, `sem_close` and `sem_unlink`. This fix contains a port of posix named semaphore and shared memory from musl libc and is used for python multiprocessing module. Note that Android has no /dev/shm, so the mapped file will be created at the temp directory of termux.
Related issues: #570, #8938

Fix (python) : Add support for multiprocessing module

---

packages/mold/build.sh

TLDR mold is likely to be faster than lld at linking phase. Downside seems to be producing a bit larger binary (and missing LTO support, etc) at the moment. Currently use the latest main branch to allow working with clang. Note that I have no idea whether it works on ARM or not since others reported to upstream its not building for Linux ARM.
Fun fact: mold and lld are created by the same person.
Example of usage:
```
~/bin $ cat hello.c
#include <stdio.h>
int main(void) {
puts("Hello world!");
return 0;
}
~/bin $ time cc hello.c -o hello-lld
real    0m0.445s
user    0m0.164s
sys     0m0.280s
~/bin $ time cc hello.c -o hello-mold -fuse-ld=mold
real    0m0.420s
user    0m0.136s
sys     0m0.208s
~/bin $ readelf -p .comment hello-lld
String dump of section '.comment':
[     0]  Android …
```

new package: mold

---

packages/pathpicker/build.sh

v0.9.5 renamed it to `tests` from `__tests__`

pathpicker: fix tests directory path

---

packages/debianutils/build.sh

debianutils 5.5 now returns 404
Also seems like debianutils 5.7 only available in tar.gz
Also switch the source URL to https

debianutils: update to 5.7

---

packages/m4/build.sh
packages/m4/src-output.c.patch

Allocates *indefinite* amount of in-memory buffer.
Mitigates #9056.

m4: Mitigate temp file issue on 32-bit archs

---

packages/ffmpeg/build.sh
packages/ffmpeg/ffmpeg-5.0-vp9-dts-correction.patch

from https://github.com/FFmpeg/FFmpeg/commit/68595b46cb374658432fff998e82e5ff434557ac.
Closes #9115.

ffmpeg: Backport patch for VP9 DTS correction

---

packages/rsync/build.sh

and add `openssl` to `TERMUX_PKG_DEPENDS`.
Closes #9167.

rsync: Bump revision to rebuild

---

packages/mariadb/build.sh
packages/mariadb/mariadb-10.6.x-no-openssl-3.0.patch

mariadb: Build against openssl-1.1

---

packages/nodejs-lts/build.sh

nodejs-lts: Build against openssl-1.1

---

packages/nodejs-lts/build.sh

Should not be needed with NDK r23

Remove LDFLAGS hack for undefined symbols in libatomic

---

packages/stylua/build.sh

Enabling lua5.2 and lua [feature flags](https://github.com/JohnnyMorganz/StyLua#from-cratesio) in stylua
Without lua52 feature enabled stylua fails to parse lua 5.2 specific syntaxes . Also stylua releases are built with `--all-features`   https://github.com/JohnnyMorganz/StyLua/blob/49436232d9b3450ef818a0f434413dd7eba6e6d4/.github/workflows/release.yml#L54

stylua: enable lua52 & luau support

---

packages/ndk-sysroot/build.sh

The patch of function `wait3` has been removed from the standalone toolchain, a new version of `ndk-sysroot` should be bumped.

ndk-sysroot: bump version after ndk-patches is modified

---

packages/opencv/build.sh
packages/opencv/opencv-python.subpackage.sh

opencv: Build Python bindings

---

packages/nsis/build.sh

so that `command-not-found` can find it.
Closes https://github.com/termux/command-not-found/issues/10.

nsis: Create symlink to `makensis` from `bin/`

---

packages/gst-plugins-base/build.sh

gst-plugins-base: Remove `include/KHR` after install

---

packages/termux-gui-package/build.sh

I originally planned to make this PR when Termux:GUI is working on f-droid, but it seems that will take a while longer, so I can do it now.  
Is it okay to install a python package with pip in a postinstall hook?  
Is the maintainer field with @ + Github username right?

Add: termux-gui-package

---

packages/nodejs-lts/avoid-ficlone-ioctl.patch
packages/nodejs-lts/build.sh
packages/nodejs-lts/deps-uv-src-unix-core.c.patch
packages/nodejs-lts/deps-uv-src-unix-process.c.patch
packages/nodejs-lts/deps-uv-uv.gyp.patch
packages/nodejs-lts/deps-v8-src-flags-flag-definitions.h.patch
packages/nodejs-lts/deps-v8-src-logging-log.cc.patch
packages/nodejs-lts/deps-v8-src-trap-handler-trap-handler.h.patch
packages/nodejs-lts/fix_multiple_definitions.patch
packages/nodejs-lts/lib-child_process.js.patch
packages/nodejs-lts/lib-os.js.patch
packages/nodejs-lts/node.gyp.patch
packages/nodejs-lts/src-debug_utils.cc.patch
packages/nodejs-lts/src-node_internals.h.patch
packages/nodejs-lts/src-node_main.cc.patch
packages/nodejs-lts/tools-v8_gypfiles-toolchain.gypi.patch
packages/nodejs-lts/tools-v8_gypfiles-v8.gyp.patch

We missed v16.14.1, which seems to have some small changes, but since this is an LTS version, I'll make sure that this doesn't break anything by running the test suite as usual. Or else it could have been updated as is as done with nodejs. For context see d5704f5d531debeecf71345aef33be62d6495b42

nodejs-lts: update to v16.14.2

---

packages/vtm/build.sh

vtm: Depend on `libc++`

---

packages/lua-language-server/build.sh

* CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/lua-language-server/bin/lua-language-server": library "libandroid-spawn.so" not found: needed by main executable

lua-language-server: Depends on `libandroid-spawn`

---

packages/gnunet/build.sh
packages/libmicrohttpd/build.sh

* gnunet: Get rid of references to leaked builtins

libmicrohttpd: Rebuild with NDK r23b

---

packages/libevent/build.sh
packages/tmux/build.sh

* tmux: Get rid of references to leaked builtins

libevent: Rebuild with NDK r23b

---

packages/golang/build.sh
scripts/build/setup/termux_setup_golang.sh

We should take a bit extra care when merging this because it is known to break build of some packages: https://bugs.gentoo.org/835378.
It is true that `golang` is at most only a build dependency for every other package and therefore is not going to break existing binary packages. But I just want to avoid extra work to adapt other packages to Go 1.18 on my own. As Go 1.17.x is still being supported, I insist we wait at least one ~~month~~ week before merging Go 1.18.

golang: Update to 1.18

---

packages/findutils/build.sh

Since `findutils-4.9.0`, it starts to use a wrapper of `fclose` (`rpl_close`), which will `fflush` before closing it. But `fflush` from Bionic Libc doen't support flushing on an input stream. Set `gl_cv_func_fflush_stdin=no` to let it use a wrapper of `fflush` (`rpl_fflush`) which support these operations.
Closes #9506.
Tested on `Bluestacks` (x86_64).

findutils: use fflush wrapper

---

packages/libandroid-posix-semaphore/build.sh
packages/libandroid-posix-semaphore/semaphore.c

(1) Replace defined macro `PREFIX` with `_PATH_TMP` in `<paths.h>`, as `libandroid-shmem` does.
(2) Initialize the static variable `pthread_mutex_t lock` with `PTHREAD_MUTEX_INITIALIZER`.
(3) Fix a possible deadlock when the number of semaphores reaches `SEM_NSEMS_MAX`.
(4) Add parameter check. Now running `__import__("ctypes").CDLL("libandroid-posix-semaphore.so").sem_close(0)` will not cause a segmentation fault and will return `-1`.

libandroid-posix-semaphore: fix deadlock and add parameter check

---

packages/picolisp/build.sh

Tried to run `pil`, got the following error message:
```
(ins)~ $ pil
[/data/data/com.termux/files/usr/lib/picolisp/lib/net.l:3] !? (in (or "Alt" "@lib/sysdefs") (if (from (pack "^J[" "Sym" "]^J")) (while (and (skip) (<> "[" @)) (def (read) (read))) (quit "No sysdefs" "Sym")))
"@lib/sysdefs" -- Open error: No such file or directory
```
Ran `strace` on `pil`, saw that It look for `sysdefs` in `/data/data/com.termux/files/usr/lib/picolisp/lib/sysdefs` and not in `/data/data/com.termux/files/usr/lib/picolisp/sysdefs`
```
(ins)~ $ cat trace | rg sysdefs
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/picolisp/lib/sysdefs", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "\"@lib/sysdefs\" -- Open error: No"..., 56) = 56
```
Moved `sysdefs` into …

picolisp: Move sysdefs file.

---

packages/libandroid-shmem/build.sh

#9560 (do not close the issue until all revdeps are rebuilt.)

libandroid-shmem: Do not declare symbols defined in `libc.so`

---

packages/libandroid-sysv-semaphore/LICENSE
packages/libandroid-sysv-semaphore/build.sh
packages/libandroid-sysv-semaphore/sys_sem.c
packages/libandroid-sysv-semaphore/sys_sem.h

Used by `mercury`, `monetdb`, `uwsgi` and `qt5-qtbase`.

new package: libandroid-sysv-semaphore

---

scripts/updates/api/termux_github_api_get_tag.sh

- Revert "fix autoupdate for projects hosted on GitHub"
- fix(termux_github_api_get_tag): addition of '|000' when `extra_curl_opts[1]` was empty

auto update fix

---

packages/golang/build.sh
packages/golang/fix-hardcoded-etc-resolv-conf.diff
packages/golang/fix-hardcoded-etc-resolv-conf.sh
scripts/build/setup/termux_setup_golang.sh

referred to by comments in #9680 and #9683.

golang: Fix hardcoded `/etc/resolv.conf` and friends

---

scripts/build/termux_step_massage.sh

Building packages that use libtool for linking libraries has issues
with ndk-r23 (https://github.com/android/ndk/issues/1614).  This check
makes sure that the built libraries do not give an error like
CANNOT LINK EXECUTABLE "tesseract": cannot locate symbol "__extenddftf2" referenced by "/data/data/com.termux/files/usr/lib/libtesseract.so"...
once used on device.  In https://github.com/android/ndk/issues/1614 it
seemed like arm gave false positives and needed special consideration,
but when I tested it again today the same false positives do not occur
in built libraries, so no "if arm then .." workaround has been added
for now.

termux_step_massage: check built libs for undefined symbols

---

scripts/build/termux_step_massage.sh

termux_step_massage: Avoid using `CC`

---

packages/libcurl/build.sh

without which `dub` command (in `ldc` package) segfaults.

libcurl: Link with `-z nodelete`

---

packages/pulseaudio/build.sh

and do not depend on `libandroid-posix-semaphore` which is unnecessary.
Fixes #9934.

pulseaudio: Link against compiler-rt builtins

---

packages/openmpi/build.sh

openmpi: Link against libandroid-posix-semaphore

---

packages/ghc-libs/build.sh

This reverts commit 3f8aeb2fb27ea6593dd22576d4d0c4e769a11c59.
`lib/ghc-8.10.7/unix-2.7.2.2/libHSunix-2.7.2.2-ghc8.10.7.so` continues
referencing libc symbols, i.e. `sem_{open,close,unlink}`, regardless of
declarations in `<semaphore.h>`.
%ci:no-build

Revert "ghc-libs: depend on libandroid-posix-semaphore"

---

packages/ipfs/build.sh

- manually update `quic-go` library until
https://github.com/ipfs/go-ipfs/issues/8819 is resolved.
- remove already defined vars

chore(ipfs): update to 1.12.2

---

scripts/build/termux_step_massage.sh

defined in `libandroid-*`.
Closes #9944.

termux_step_massage: Check for unresolved symbols

---

packages/hash-slinger/build.sh
packages/unbound/build.sh
packages/unbound/pyunbound.subpackage.sh

and separate `pyunbound` as a subpackage.
Alternative to #9973.

unbound: Build without `pythonmodule`

---

packages/n-t-roff-sc/Makefile.patch
packages/n-t-roff-sc/build.sh

I'm proposing ~~switching sc's upstream~~ from the original 20 year old 7.16 source code on ibiblio.org to a maintained fork [n-t-roff/sc](https://github.com/n-t-roff/sc) on github.
I changed my proposal to adding this maintained fork as a separate package `n-t-roff-sc` alongside `sc`
~~This commit~~ bumps version number to 7.16_1.1.2 from n-t-roff's fork of sc that fixes sc compile-time errors ~~that were previously being patched by this repo~~ and has none of the run-time issues I've been experiencing with the currently packaged sc 7.16 that make it unusable for me, specifically:
* When opening sc, it hangs and does not redraw the TUI unless I resize the Termux window by changing device orientation or opening and closing the on screen keyboard.
* sc does not allow me to populate any …

New package: n-t-roff-sc, a maintained fork of sc 7.16

---

packages/vulkan-tools/build.sh

This package and vulkan-headers should be updated at same time since it
depends upon vulkan-headers of same version (obviously!).
Failing to comply so, they do not compile successfully.
re #10059
%ci:no-build

fix(vulkan-tools): depend on `vulkan-headers` of excatly same version

---

packages/libllvm/build.sh
packages/libllvm/clang.subpackage.sh
packages/ndk-multilib/build.sh

Looks like [a lot more patch releases of LLVM incoming](https://discourse.llvm.org/t/llvm-14-0-1-release/61700), we may need to change how we handle it.

libllvm: update from 14.0.0 to 14.0.1

---

scripts/bin/update-packages

- now a new issue (with output logs) for each failed package will be created and assigned to
$GITHUB_ACTOR.
- this will help us track and fix failed updates quickly
_This is just a proposal. Feel free to close this if you do not like this idea._

[Proposal] Create issue when auto update fails

---

scripts/bin/update-packages

- GitHub api only allows 65536 chars long body in one go.
- Now body beyond 65536 limit will be appended after a gap of 5 sec.
Appending (or patching) does not consider already present body, so we
can bypass this limit.

feat(auto-update): handle large logs while creating issues

---

packages/manpages/build.sh

* Also exclude entries for `<monetary.h>` and `pthread_cancel`
* Include intro entry for each section
Closes #10304.

manpages: Remove entries for aio facility

---

scripts/properties.sh
scripts/setup-android-sdk.sh

To make it a bit easier to try out different ndk versions.
setup-android-sdk and building packages seem to work, but need to think about if there are other scripts that have to be changed.

Keep ndk and sdk in versioned folders and use termux_download

---

x11-packages/webkit2gtk/build.sh

that seems to cause crashes.
Fixes #10080.

webkit2gtk: Disable OpenGL

---

packages/libarrow-cpp/build.sh
packages/libarrow-cpp/cpp-cmake_modules-FindPython3Alt.cmake.patch
packages/libarrow-cpp/libarrow-python.subpackage.sh

libarrow-cpp: Include libarrow-python as a subpackage

---

packages/yara/build.sh

fix(yara): depend on `libandroid-posix-semaphore`, update to 4.2.1

---

packages/htop/build.sh
packages/htop/root-actual-procstat-file.patch

There are some reports on which the user complains about static CPU usage in `htop` even if they're rooted. this PR should read `/proc/stat` inside the `LinuxProcessList.c` and not relying on the `PROCSTATFILE` macro which points to `$PREFIX/var/htop/stat`

htop: add checks if a user is rooted

---

packages/mpd/doc-mpdconf.example.patch

uncomment bind socket path in mpd.conf
closes #10395

fix(mpd): could not bind to socket

---

packages/ani-cli/build.sh

I intentionally separated this into 3 commits:
- throughout the lifetime of this package we never depended on git
- we prefer termux-tools over listing curl, grep, sed individually since we may expand our use of other coreutils. If this conflicts with policy, this can easily be reverted
- At least in my personal testing, ani-cli cannot find openssl if you just install openssl. We interact with the openssl commandline programm, so openssl-tool is required
Draft PR because we'll probably release 2.2 soon
Greetings from upstream

ani-cli dependency bugfix

---

packages/asciidoctor/build.sh
packages/frogcomposband/build.sh
packages/ghc-libs/build.sh
packages/lsof/build.sh
packages/netcat-openbsd/build.sh
packages/ovmf/build.sh
packages/snake/build.sh
packages/srelay/build.sh
x11-packages/libdrm/build.sh
x11-packages/xcb-util-keysyms/build.sh
x11-packages/xorg-fonts-100dpi/build.sh
x11-packages/xorg-fonts-75dpi/build.sh

in `termux_step_install_license()`.

packages: Fix hardcoded package name

---

packages/povray/build.sh
packages/povray/povray-data.subpackage.sh

* Compile with `-Ofast`
* Exclude HTML documents
* Separate platform-independent data as a subpackage

povray: Enable OpenEXR support

---

x11-packages/pulseeffects/build.sh
x11-packages/pulseeffects/meson.build.patch

EasyEffects version has build issue due to `<ranges>` missing from `libc++`. So PulseEffects version is packaged instead.
Closes #10417.

new package: pulseeffects

---

packages/n2n/Makefile.in.patch
packages/n2n/build.sh

In this package some commands (e.g. `edge`) are only usable with root privilege but others (e.g. `supernode`) are not. So I believe this should go to main repo rather than root repo, just like `softether-vpn` package.
Closes #10661.

new package: n2n

---

packages/ncurses/build.sh

when determining the current locale.
Fixes #10676.

ncurses: Do not rely on `nl_langinfo(CODESET)`

---

packages/mosh-git/build.sh
packages/mosh-git/mosh-server.cc.patch

It's been 5 years since the Mosh team have officially made a new
release. Meanwhile the master branch has seen many updates. Most notably
for me, 24 bit true colour.
There's been quite some discussion about cutting a new release. But see
here to start: https://github.com/mobile-shell/mosh/issues/1115

new package: mosh-git

---

x11-packages/ncspot-mpris/build.sh

- ncspot with mpris support requires x11, which eventually breaks
non-x11 setups.
- Therefore, seperate both into two different packages.
Closes #10772

enhance(main/ncspot): seperate ncspot-mpris to `x11-repo`

---

packages/tinyproxy/build.sh
packages/tinyproxy/pthread_flag.patch

- updated srm-m.patch and renamed to pthread_flag.patch
- removed adding permissions to files since there is no meaning of 'other'
and 'group' users in Termux.
Closes #10832

upgpkg(tinyproxy): update to 1.11.1

---

packages/crawl/Makefile.patch
packages/crawl/build.sh

Ages ago I made [this pull](https://github.com/termux/game-packages/pull/60) in the games repo, but after noticing some architecture-dependent build weirdness, I figured it shouldn't be merged until I figured that out.....then I kinda fell off the planet.
But I tried again recently, and managed to figure out how to get this to build on all architectures!
There was some Makefile weirdness, and I had to rpath the libraries so cross compiling wouldn't cause the linker to not know where to find its shared libraries, but we now have a working version of DCSS that can finally be added to the repos~ \^\^

Add package for Dungeon Crawl Stone Soup

---

packages/tome2/LICENSE
packages/tome2/build.sh

This PR adds the roguelike ToME 2, an open world band roguelike~
This also the game that [this issue](https://github.com/termux/termux-packages/issues/10904) was requesting, so this solves that too~

Add ToME 2

---

packages/lua-language-server/build.sh

Closes #10932
- add to `CFLAGS` `-Wno-unknown-warning-option` for `-Wno-maybe-uninitialized`

upgpkg(lua-language-server): update to 3.2.5

---

packages/zpaq/Makefile.patch
packages/zpaq/build.sh

Greetings, i need some advice here. The Makefile passes the LDFLAGS to g++ when compiling, however, it also passes the -static-openmp flag that is in the LDFLAGS, which g++ just, doesn't know what do with and fails the build. 
How can i specifically remove only that argument from the LDFLAGS instead of setting the whole thing manually like i ended up doing? Which just seems wrong

zpaq: new package

---

packages/angle-grinder/build.sh

* It was unable to find/link with `libgcc`.
* This must be due to shift of Android from `libgcc` to clang's
`libclang_rt.builtins` in ndk-r23.
Closes #10957

fix(main/angle-grinder): arm build

---

packages/apt/build.sh

- No x11-repo as a package exists for Pacman. It's subscribed to all
repos by default.
Closes #10951

fix(apt): do not suggest `x11-repo`

---

packages/cmake/build.sh

Recommend them instead. Closes #11057.

cmake: don't depend on clang and make

---

packages/neovim-nightly/build.sh

Side changes:
* rename cmake build directories in compliance with changes introduced
in https://github.com/neovim/neovim/pull/19120
Closes #11105

upgpkg(main/neovim-nightly): to 0.8.0-dev+513-g01fc5097d

---

packages/apt/9999-pkgTagSection-Key-visiable.patch
packages/apt/build.sh
packages/python-apt/build.sh

* python-apt: dependency issues in #10960.
* apt: update to 2.5.1
Continuation of https://github.com/termux/termux-packages/pull/10960.
Temporary fix for #11120.

apt, python-apt: update and fix

---

packages/binutils-is-llvm/build.sh

`llvm-as` is not a GNU as replacement. Actually, they are totally different. `llvm-as` will convert LLVM assembly file (`.ll`) to LLVM bitcode (`.bc`) and GNU `as` will convert assembly file (`.s/.asm`) to object file (`.o`). So I'd like to remove the symlink from `llvm-as` to `as` (which usually means GNU `as`).
See: https://github.com/termux/termux-packages/discussions/9376#discussioncomment-3113526, https://github.com/android/ndk/issues/1290#issuecomment-649083154.

binutils-is-llvm: remove symlink from llvm-as to as

---

scripts/get_hash_from_file.py

Fix `get_Packages_hash_from_Release`.
Currently, it works fine when the line containing `Packages` in the `Release` appears before the line containing `Packages.gz/bz2`, like what the `aptly` does. But if some `Release` files put the line containing `Packages.gz/bz2` before the line containing `Packages`, it will show the checksum of `Packages.gz/bz2` rather than `Packages`.

get_hash_from_file.py: ignore Packages.gz/bz2 in Release file

---

scripts/run-docker.sh

Mainly to fix issues like this:
```sh
[jylo@t430-2022-04-10 Projects]$ cd termux-packages/
[jylo@t430-2022-04-10 termux-packages]$ ./scripts/run-docker.sh 
Running container 'termux-package-builder' from image 'termux/package-builder'...
Creating new container...
18e47a1c3cf39a3237fd43506beb7dfb62dd01febeddf5ee7f4265abd2b1bc3a
builder@18e47a1c3cf3:~/termux-packages$ ls
ls: cannot open directory '.': Permission denied
builder@18e47a1c3cf3:~/termux-packages$ pwd
/home/builder/termux-packages
```
Should only affect newly created containers moving forward...

enhance(run-docker.sh): add support for Fedora

---

packages/kcptun/build.sh
packages/kcptun/kcptun-client.subpackage.sh
packages/kcptun/kcptun-server.subpackage.sh

Close #11254 .
* Why the main package (kcptun) has only one `LICENSE`?
Because when you install the main package (kcptun), the subpackage (main program) will be installed as a dependency.

add(main): new package kcptun

---

packages/samba/build.sh

Causes conflicts upon installation. showing these two outputs that `samba` has its own tdb tools while the standalone version also has it. separating them maybe a good idea
tdb-tools:
```console
~ $ apt-file list tdb-tools
tdb-tools: /data/data/com.termux/files/usr/bin/tdbbackup
tdb-tools: /data/data/com.termux/files/usr/bin/tdbdump
tdb-tools: /data/data/com.termux/files/usr/bin/tdbrestore
tdb-tools: /data/data/com.termux/files/usr/bin/tdbtool
tdb-tools: /data/data/com.termux/files/usr/share/man/man8/tdbbackup.8.gz
tdb-tools: /data/data/com.termux/files/usr/share/man/man8/tdbdump.8.gz
tdb-tools: /data/data/com.termux/files/usr/share/man/man8/tdbrestore.8.gz
tdb-tools: /data/data/com.termux/files/usr/share/man/man8/tdbtool.8.gz
```
samba:
```console
~ $ apt-file list samba | grep …
```

samba: remove tdb related utilities

---

packages/dialog/build.sh

The old link now returns error 410
```sh
termux - building dialog for arch arm...
Downloading https://fossies.org/linux/misc/dialog-1.3-20220117.tgz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0  2158    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 410
Failed to download https://fossies.org/linux/misc/dialog-1.3-20220117.tgz
Failed to build package 'bash' for arch 'arm'
[*] Building 'bash' exited with exit code 1
```

upgpkg(main/dialog): to 1.3-20220526

---

scripts/build/termux_step_start_build.sh

The pre-built binary cannot execute on device. Use the one from repo instead.
Related: https://github.com/termux-user-repository/tur-on-device/actions/runs/2769860859.

scripts: fix for building on device

---

scripts/build/termux_error_exit.sh
scripts/build/termux_step_massage.sh

By stripping, fixing shebangs and checking for undefined syms in parallel we can speed up build time by around 15 - 45 %, at least in my tests done when building on device.
For a package with many files like boost build time went from 89 minutes to 74 minutes, and for smaller library packages like libandroid-support and libcap build time went from around 1min40s to 1min0s

Decrease build times: simplify loop that checks for undefined symbols in massage step 

---

packages/emscripten/build.sh
packages/emscripten/emscripten-tests-third-party.subpackage.sh

Since https://github.com/emscripten-core/emscripten/commit/7d291a7660cbf678dac9988dda7b898570ba4ed0, `tests` has been renamed to `test` from upstream.
Closes #11418.

emscripten: update to 3.1.18

---

packages/libntl/build.sh

Adds [ntl](https://libntl.org), a library for doing Number Theory.

new package: libntl

---

packages/termux-keyring/build.sh

It's time to develop security in the pacman package manager.

termux-keyring: configured to work with pacman

---

packages/ngspice/build.sh
packages/ngspice/src-frontend-com_shell.c.patch
packages/ngspice/src-frontend-inp.c.patch
packages/ngspice/src-frontend-plotting-gnuplot.c.patch
packages/ngspice/src-include-ngspice-defines.h.patch
packages/ngspice/src-include-ngspice-ipctiein.h.patch
packages/ngspice/src-tclspice.c.patch

- Uses dumb term when gnuplot is ran. https://github.com/termux/termux-packages/issues/8143#issuecomment-1072758507
- Fixes loading of library (code model) with undefined symbols https://github.com/termux/termux-packages/pull/11001#issue-1274606719

ngspice: update to 37

---

packages/boinc/build.sh
packages/boinc/client-hostinfo_unix.cpp.patch

Needed for special case like `termux-docker`

fix(main/boinc): add fallback android version to 7.0

---

packages/magic-wormhole-rs/build.sh
packages/magic-wormhole-rs/remove-clipboard.patch

Adds a Rust client for [magic-wormhole](https://github.com/magic-wormhole).
The reference impl. is in Python. Installing a python tool requires python and pip. This single static binary client is better suited for those who don't want to install python dependencies.
Note that `wormhole-rs` still is not in feature-parity with Python's magic-wormhole, but it offers some [improvements](https://github.com/magic-wormhole/magic-wormhole.rs#comparison-with-the-python-implementation). Also it is a project from the same GitHub organization.
The dependency on `libxcb` is for handling clipboard in a graphical environment. It works in headless setups so this is not a X11 package.
Regarding the naming of the package: https://repology.org/project/magic-wormhole-rs/versions

new package: magic-wormhole-rs

---

packages/libgf2x/build.sh

Adds [gf2x](https://gitlab.inria.fr/gf2x/gf2x) library used for multiplying polynomials over the binary field.
This is a dependency of [NTL library](https://libntl.org/).

new package: libgf2x

---

packages/weechat-matrix-rs/build.sh

The plugin should have been installed in : `"$TERMUX_PREFIX/lib/weechat/plugins/"`.
Also fixed weechat plugin header locations.
update: Use header file directly instead of extracting its version.

weechat-matrix-rs: fix installation path of the plugin

---

packages/fclones/build.sh

Adds [fclones](https://github.com/pkolaczk/fclones), an efficient duplicate file finder.
For this functionality, fdupes is already present in Termux repos but fclones is [faster](https://github.com/pkolaczk/fclones#benchmarks) than fdupes and [jdupes](https://github.com/termux/termux-packages/pull/10915) (@Efreak).

new package: fclones

---

packages/libllvm/build.sh

Also, add the clang++-14 symlink asked for, fixes #11366.

rebuild(libllvm): bump to build against NDK 25

---

packages/libmesode/build.sh

libmesode has been archived by its maintainers. So I think there is no need to auto-update this package.

libmesode: disable auto-update

---

packages/zlib/build.sh
packages/zlib/zlib-1.2.12-fix-CVE-2022-37434.patch

https://security-tracker.debian.org/tracker/CVE-2022-37434
Note: This patch can be removed in the next version

fix(main/zlib): CVE-2022-37434

---

packages/libntl/build.sh

Adds libgf2x dependency for performance improvement.
Add a rule to tune for x86 archs (x86_64 and i686)
Covert spaces to tabs in `build.sh`

libntl: add libgf2x dep, add tune, fix formatting

---

.github/workflows/bootstrap_archives.yml
.github/workflows/package_updates.yml
.github/workflows/packages.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

packages/rust/build.sh

Fixes #11427 
To reproduce issue locally: `./scripts/run-docker.sh ./build-package.sh -I -a aarch64 liblzma rust`
To reproduce issue on CI: bump revision for liblzma and rust, https://github.com/truboxl/termux-packages/pull/59
Add `%ci:no-build` to prevent build and push since rust still have issue with NDK r25 (especially arm)

chore(main/rust): fix fresh build conflict with liblzma

---

packages/geographiclib/build.sh

Adds [geographiclib](https://geographiclib.sourceforge.io/). This package contains both library and utilities but it is named as geographiclib. Here is the list of utilities: 
`GeoConvert, CartConvert, RhumbSolve, TransverseMercatorProj, GeoidEval, GeodesicProj, ConicProj, Gravity, MagneticField, GeodSolve`

new package: geographiclib

---

packages/guile18/build.sh

To fix segmentation fault.  Archlinux are using a similar fix: https://github.com/archlinux/svntogit-packages/commit/777290ab1870f00a90905ef0bb57e8a77a6226df
Fixes termux/termux-packages#11080.

fix(main/guile18): do hostbuild with -O1

---

packages/libccd/build.sh

Adds [libccd](https://github.com/danfis/libccd), a library for collision detection, having applications in robotics.
I enabled double precision on 64bit ISAs since I think double-precision calculations would actually be faster on them (compared to 32-bit).

new package: libccd

---

packages/urdfdom-headers/build.sh

Adds https://github.com/ros/urdfdom_headers needed for urdfdom.

new package: urdfdom-headers

---

packages/rw/build.sh

The current version of `sponge(1)` from moreutils always write to `TMPDIR` for atomic write, even if we point it to stdout.
This will double the wearout of flash storage if target is stdout, e.g:
```sh
$ curl .... | sponge | sort | rev > filename.txt
```
the data will got written to flash storage in twice:
`$TMPDIR/spongeXXXX` and then sort/rev'd `filename.txt`.
Since on unrooted device `TMPDIR` is usually not a tmpfs, using sponge in similar cases will result in unnecessary wearout of flash storage when:
- invoke sponge w/o params, or target is stdout
- end of pipeline point to a file in a filesystem different than TMPDIR resides
In case of the length of input data is prior known or splited to a size smaller than available memory, we can use `rw` instead.

rw: add package 'rw', a Rust analogue of sponge(1)

---

x11-packages/the-powder-toy/build.sh

Elf-cleaning should be done in `termux_step_massage`. Fixes #11779.

the-powder-toy: do not use elf-cleaner

---

packages/clifm/build.sh

Termux support has been added with the latest release: https://github.com/leo-arch/clifm/wiki/Introduction#small_blue_diamond-c-termux

add(main): new package clifm

---

packages/sfeed/Makefile.patch
packages/sfeed/build.sh

*tldr*: this package consists of a shell scriptable feed aggregator, a RSS/Atom-to-TSV parser, and a curses-based feed entires reader.
Project is actively maintained and written in portable C and POSIX shell, listed on [suckless.org recommends](http://suckless.org/rocks).
------
`sfeed(1)` is a RSS/Atom feed parsing utility written in C that aimed to be used in a scriptable feed aggregating pipeline (or newsreading workflow, for a more generally speaking) on UNIX.
`sfeed_update(1)` is the POSIX shell script aimed to be placed in crontab for periodical updating of feeds, as the "aggregator".
**NOTE:** Crontab entries is not defined in `build.sh`.  On Termux things in crontab usually read/write to `$PREFIX/var`,
I'd leave this simple task to users for more flexibility (i.e. I may want to …

new package: sfeed -- a scriptable feed aggregator

---

packages/miniserve/build.sh

Add `postrm` hook to clear out shell completion functions

miniserve: add postrm hooks to remove shell completion helpers

---

packages/python-numpy/build.sh

This is a quick fix for #11870, but more investigation is needed to find the underlying cause of the wrong ext_suffix (expected `.cpython-310.so`, got `.cpython-310-$TERMUX_HOST_PLATFORM.so`).

python-numpy: fix ext_suffix

---

packages/pipebuffer/build.sh

a stdio-only, non-blocking `mbuffer(1)` (`-m`) analogue, that buffering stdin in given size then flush to stdout
(or like memory-only `sponge(1)` but flush to output on buffer exceeding)
NOTE: Some other implementation that provide similar functionality (afaict) does exist but is either unmaintained, require #8871, or use Perl/Python.

add(main): pipebuffer

---

packages/ani-cli/build.sh

Just a basic version bump.
Solves ani-cli's [#893](https://github.com/pystardust/ani-cli/issues/893)
We now use axel as our download accelerator.
Also fzf may become a required dependency in our next point release, but I'll make a seperate PR for that when it happensf

ani-cli: update to 3.4

---

.github/workflows/packages.yml

A lot of packages cannot be built since we switch our docker image to ubuntu-22.04, such as #11357, #11578 and #11518. Until now, `seccomp`'s version in `ubuntu-latest (ubuntu-20.04)`  is `2.5.1-1ubuntu1~20.04.2` and doesn't have `close_range` syscall. Until we drop the usage of docker image, we could use ubuntu-22.04 as ci's base system to avoid the errors related to `close_range` syscall.

ci: switch to 22.04

---

packages/libjxl/a2x-is-shell-script.patch

on environment where `a2x` is a shell script.
Closes #11595.

libjxl: Fix build

---

packages/mkvtoolnix/build.sh

Use internal version of fmt.
Closes #11176.

mkvtoolnix: Fix build

---

packages/groovy/build.sh
packages/libjansi/Makefile
packages/libjansi/build.sh
packages/maven/build.sh

To avoid bad interaction with `kotlin`.
Fixes #10851.

libjansi: Install so file in `$PREFIX/lib/jansi`

---

packages/k2pdfopt/build.sh

In accordance with Debian package.
Fixes #11162.

k2pdfopt: Depend on djvulibre and gsl

---

packages/tmux/build.sh
packages/tmux/tmux.h.patch

where f8e73d466068c8eb2b5c4e44a663a5c38374e1cf does not work well.
Fixes #11354.

tmux: Fix behavior with non-login shell

---

packages/libprotobuf/build.sh

Both version 3.21.5 and 3.21.6 have the same `SOVERSION` (`32`) and so revdep-rebuild should not be necessary. ~~I will implement a `SOVERSION` guard in the `build.sh` afterwards so that auto-update can be enabled.~~ Now `SOVERSION` guard is implemented.

libprotobuf: Bump to 3.21.6

---

packages/tcllib/build.sh
packages/tcllib/tcl-modules-path-fix.patch

standard library of tcl language
the patch to fix hardcoded path in `modules/**.tcl` has been slimmed down to as minimal as possible (i.e. docs, manpages, test all excluded for hardcoded path fix)

new package: tcllib

---

packages/python-cryptography/build.sh
packages/python-cryptography/openssl-libs.diff

As of now, installing `cryptography` through `pip` does not work without non-trivial workaround (#12083).

new package: python-cryptography

---

packages/python/build.sh
packages/python/configure.patch

First note that multiarch was actually disabled when built with NDK r23.
I would not expect any catastrophe brought by this change.
When multiarch is enabled, crossenv seems to use wrong `EXT_SUFFIX` when
building some extensions.
Fixes #11870.

python: Disable multiarch

---

packages/nginx/build.sh

PCRE (8.x) is now EOL. Packages are recommended to migrate to PCRE2 (10.x) as far as possible.

nginx: Migrate to using PCRE2

---

packages/libxfixes/build.sh

for backward compatibility.
Partially fixes #12139.

libxfixes: Create `lib/libXfixes.so.3` symlink

---

packages/neovim-nightly/build.sh
packages/neovim-nightly/revert-libvterm-0.3.patch

neovim-nightly: update to 0.8.0-dev-1202-g33dd917d7

---

packages/lowdown/build.sh

what: fork of hoedown from bsd.lv, has different underlying implementation, plus man(7)/latex output that hoedown does not have
regress check run w/o error in local build

add(main): new package lowdown

---

packages/emscripten/build.sh

Closes #12221
It seems like latest tip of tree has fixed the build issue so use that
Tip of tree is what usually emscripten uses for their emsdk "build from source" releases
The build was first broken in commit llvm/llvm-project@f35230ae0a69bbdd74a4faa3ae0b69a46796dc12
The last known working is commit llvm/llvm-project@46525fee812343b5e603a77893dfe2983768ca56
I have yet to determine which commit fix the build, ideally should use that instead

fix(main/emscripten): i686 build

---

packages/miniserve/build.sh

Add the [generated manpage](https://github.com/svenstaro/miniserve/pull/738) (`miniserve --print-manpage`) to build script.

miniserve: add manpage

---

CONTRIBUTING.md
scripts/bin/update-checksum
scripts/updates/utils/termux_pkg_upgrade_version.sh

Earlier convention:
upgpkg(<repo>/<package>): update to <ver>
Newer convention:
upgpkg(<repo>/<package>): <ver>
Similarly same for dwnpkg.
Thanks to @truboxl for the suggestion

chore(CONTRIBUTING.md): Remove unnecessary message for update and downgrade

---

x11-packages/telepathy-glib/build.sh

Actually 0.24.2 is newer than 0.99.11.
Closes #12223.

telepathy-glib: "Bump" to 0.24.2

---

packages/valgrind/aarch64_have_lse_atomics.patch

In compiler-rt, `__aarch64_have_lse_atomics` is initialized by `init_have_lse_atomics()` which calls `getauxval()` defined in libc. Let's always assume that the system does not have LSE atomics.
Closes #12224.

valgrind: Fix build for aarch64

---

packages/valgrind/android-memcpy.patch

as well as memcpy builtins (33e9cda847836c08808f4cc6af3bc40fae12852c).
Closes #12224.

valgrind: Avoid overriding memclr builtins

---

packages/rlwrap/build.sh
packages/rlwrap/disable-bracketed-paste.patch

Could cause regressions elsewhere though.
Fixes #12282.

rlwrap: Disable bracketed paste

---

scripts/build/termux_step_create_pacman_install_hook.sh

`postupg` - script that will run after the package is updated (`post_upgrade()` is responsible for this function in pacman).
`preupg` - script to be run before updating packages (`pre_upgrade()` is responsible for this function in pacman).
I don't know if there are similar functions in `apt`, but they will definitely be useful for `pacman`.

improve(termux_step_create_pacman_install_hook.sh): adding preupg and postupg function

---

packages/binutils/build.sh
packages/binutils/ldd
packages/ldd/build.sh

now that we have a separate package that provides one.
See https://github.com/termux/termux-packages/pull/12426#issuecomment-1283145628.

binutils: Remove `ldd` command

---

packages/nodejs-lts/build.sh
packages/nodejs-lts/configure.py.patch
packages/nodejs-lts/node.gyp.patch
scripts/build/setup/termux_setup_nodejs.sh

Let's get the LTS first, then will update nodejs to latest v18 too. Wont be updating it to v19 atleast till v18 is declared as LTS, then nodejs-lts will have v18 and nodejs will have v19

upgpkg(main/nodejs-lts): v16.18.0

---

x11-packages/gnome-font-viewer/build.sh
x11-packages/gnome-font-viewer/fix-build-against-gnome-desktop-42.0.patch

gnome-font-viewer: Adapt to gnome-desktop API change

---

x11-packages/tuxpaint/build.sh

to avoid potential build failure. Not yet reproducing in CI though.
Fixes #12458.

tuxpaint: Make `trans` directory in advance

---

packages/recoll/build.sh

This PR builds on #12299 to enable Python support in the recoll package. Hopefully also fixes https://github.com/koniu/recoll-webui/issues/86.

enhance(recoll): configure without --disable-python-module

---

scripts/build/setup/python-crossenv-PYTHONPATH.patch

in cross-python.
~~Not sure if really needed though.~~

termux_setup_python_crossenv: Fix `PYTHONPATH`

---

packages/xcb-proto/build.sh
packages/xcb-proto/python-xcbgen.subpackage.sh

and separate python-xcbgen as a subpackage.

xcb-proto: Bump to 1.15.2

---

packages/dnote/build.sh
packages/dnote/cli-build.sh.patch
packages/dnote/dnote-client.subpackage.sh
packages/dnote/dnote-server.subpackage.sh
packages/dnote/server-build.sh.patch

```bash
mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql
pg_ctl -D $PREFIX/var/lib/postgresql start
createdb dnote
DBHost=localhost DBPort=5432 DBName=dnote DBUser=postgres DBPassword="" DBSkipSSL=true WebURL=localhost:3000 dnote-server start
```
```bash
mkdir -p $HOME/.dnote
echo editor: "nano" > ~/.dnote/dnoterc
echo apiEndpoint: http://localhost:3000/api >> ~/.dnote/dnoterc
dnote login
```
```bash
~ $ DBHost=localhost DBPort=5432 DBName=dnote DBUser=postgres DBPassword="" DBSkipSSL=true WebURL=localhost:3000 dnote-server start
2022/10/29 11:31:21 Performed 0 migrations
2022/10/29 11:31:21 Started background tasks
2022/10/29 11:31:21 Dnote version 2.0.1 is running on port 3000
{"duration":"54ms","level":"info","method":"GET","msg":"incoming …
```

add(main): new package dnote

---

packages/z3/build.sh

z3: Do not use unnecessary _PYTHON_VERSION

---

packages/dnote/build.sh

Fixes #12784
I was missing `-tags fts5` for the build command.
And regarding the post installation script, I'm not sure why @2096779623 added it, I just kept it like that but now that I checked, there's no such command as `dnote completions` so I completely removed the shell completion stuff.

dnote: add tag fts5 and remove post installation script

---

packages/micro/build.sh

This ensures the runtime files are generated and properly embedded into the binary.
A user complained about syntax highlighting not working so I tried to look into what could be wrong and I found people discussing a similar issue in the arch linux packaging https://github.com/zyedidia/micro/issues/2521
v2.0.11 uses `go generate` to generate some files and those needs to be ran before the main build, the `build` target of the Makefile is essentially generate & quick-build

micro: use make build instead of quick-build

---

packages/diffstat/build.sh

once again.
invisible-mirror.net is not suitable for CI due to bad responsiveness.
%ci:no-build

diffstat: Use alternative source URL

---

packages/box86/CMakeLists.txt.patch
packages/box86/build.sh
packages/box86/src_dynarec_dynablock.c.patch
packages/libandroid-complex-math/LICENSE
packages/libandroid-complex-math/build.sh
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cacoshl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cacosl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/casinhl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/casinl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/catanhl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/catanl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/ccoshl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/ccosl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cephes_subrl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cephes_subrl.h
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cexpl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/clog.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/clogf.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/clogl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cpow.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cpowf.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cpowl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/csinhl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/csinl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/ctanhl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/ctanl.c

Closes #7672
Notes:
1. Unfortunately the box86 here is nothing more than a tech demo that allows running binaries created using `clang --target=i686-linux-android` on an arm(32) Android device. It is still not a replacement for qemu-i386 (and never will, I think, due to how box86 works). There's still other issues for a proot + box86 integration that I am not willing to dig for now.
2. If you are thinking running Steam with this, you will be disappointed. There's way too many missing global symbols issues in bionic libc to allow full fledged glibc programs to run in box86 way, which wraps calls on the fly, I think. Prepare to maintain a long list of wrapped calls for a lot of libs if you really want to improve this box86.
3. You are better off with a `proot + Linux distro (arm) + box86` …

addpkg(main): libandroid-complex-math, box86

---

packages/profanity/build.sh

against Python 3.11.
Fixes #12920.

profanity: Revbump and rebuild

---

packages/xorg-util-macros/build.sh
packages/xtrans/build.sh
packages/yajl/build.sh
x11-packages/xbitmaps/build.sh

after commit 3f1be51372b6f33762eac18c3096e3b240cb056a.
On-device `pkg-config` searches `$PREFIX/share/pkgconfig` by default.
%ci:no-build

*: Remove `share/pkgconfig` hack

---

packages/zellij/build.sh
packages/zellij/cargo-lock.patch
packages/zellij/etc-path.patch
packages/zellij/wasmer.patch

Resolves #11857.
This PR adds [Zellij](https://github.com/zellij-org/zellij) to the package registry. I have to include a relatively large patch for the `Cargo.lock` file thanks to the `wasmer` dependency version bump. The patches were generated using https://github.com/zellij-org/zellij/pull/1833. No patch would be needed after the PR merges, which is expected to happen before next release.

new package: zellij

---

packages/nim/build.sh

Updates Nim to [1.6.8](https://nim-lang.org/blog/2022/09/27/version-168-released.html)

nim: update to 1.6.8

---

packages/binutils-is-llvm/build.sh

as some packages (such as `ldc` #11062) really require GNU Binutils.

binutils-is-llvm: Stop providing binutils

---

packages/fakeroot/build.sh
packages/fakeroot/dont-wrap-while-environ-is-null.patch

and add workaround for
```
libfakeroot: FAKEROOTKEY not defined in environment
```
on some Android version. (#3148)
I have confirmed that this works on my Android 8.1.0 (API 27) environment. Does this work on other Android versions that are affected? (Not sure but I guess Android 9 (API 28) is affected too.)

fakeroot: Bump to 1.30.1

---

packages/ldc/build.sh

which contains bin/ld.bfd.
Fixes #11062.

ldc: Depend on binutils-bin

---

packages/calcurse/build.sh
packages/calcurse/threading.patch

Use of atomic flags does not work well when the loop involves long wait.

calcurse: Use alternative `pthread_cancel` workaround

---

packages/feroxbuster/build.sh

upgpkg(main/feroxbuster): 2.7.1 to 2.7.2

---

scripts/bin/revbump

Useful for bumping packages
Usage:
```
~$ ./scripts/bumper.py python
```
This will bump all the packages that have python in dependencies or in build dependencies

chore(scripts): improve revbump

---

packages/gnuplot/build.sh

as a workaround for build failure in some environment.
Closes #13420.

gnuplot: Configure host build without lua

---

packages/7zip/build.sh
packages/7zip/disable_hardware_acceleration_support_on_arm.patch
packages/7zip/guard_armv8_feature_from_old_architectures.patch
packages/7zip/remove_pthread.patch

Termux currently provides a quite up-to-date fork of the 7-Zip port p7zip (https://github.com/jinfeihan57/p7zip), since the original p7zip hasn't been updated since 2016.
Since 2021 there is however an official version of 7-Zip for Linux. This new version is slowly finding its way into some well-known distros:
- Alpine: https://pkgs.alpinelinux.org/packages?name=7zip
- Arch: https://aur.archlinux.org/packages/7-zip
- Debian: https://packages.debian.org/bullseye-backports/7zip
- OpenSUSE: https://software.opensuse.org/package/7zip
- Ubuntu: https://packages.ubuntu.com/jammy/7zip
Therefore, it would be nice to have this new, official version on Termux too :)
Most distros use "7zip" as the name of the package (as opposed to "7-Zip").
The build process generates an executable called "7zz", so …

New package: 7zip

---

root-packages/lvm2/build.sh

Otherwise we get errors like:
CANNOT LINK EXECUTABLE "cryptsetup": cannot find verneed/verdef for version index=32785 referenced by symbol "dm_bitset_parse_list" at "/data/data/com.termux/files/usr/lib/libdevmapper.so.1.02"
I mistakenly thought this issue was fixed in commit 650fcddc7ffe
("cryptsetup: bump after lvm2 update").
Fixes termux/termux-packages#13574

lvm2: configure --with-symvers=no

---

packages/proton-bridge/build.sh

Needs to be updaed soon because Protonmail is dropping support for version <2.3.0 in beginning of 2023

proton-bridge: bump to 2.3.0

---

packages/hstr/build.sh
packages/hstr/src-hstr_utils.c.patch

for return value of `fopen("/proc/sys/kernel/hostname", "r")`.
Fixes #13697.

hstr: Add NULL check

---

scripts/build/termux_step_get_dependencies.sh

In commit b9b5987319e6df8a9de1a15cf3a0d2c22befcb27, we want to ensure the build process of dependencies follow the parent whether `-f` is passed. But as `TERMUX_FORCE_BUILD` is always set to `false` in `termux_step_setup_variables`, it cannot work properly.
Closes #13702.

fix(scripts): bug in termux_step_get_dependencies

---

x11-packages/texworks/build.sh

Symbol `_ZN12QtConcurrent16ThreadEngineBase13startBlockingEv` is defined in Qt Concurrent 5.15.5 but not in 5.15.7.
Fixes #13756.

texworks: Rebuild aginast Qt Concurrent 5.15.7

---

scripts/build/get_source/termux_git_clone_src.sh

The origin one copies twice `checkout` folder and cannot detect whether package has updated.

chore(scripts): improve `termux_git_clone_src`

---

.github/workflows/packages.yml
scripts/properties.sh

As mentioned in termux/termux-packages#13804 package uploads will be disabled for maybe 2 h to allow for migration from fosshost to a new vps. 
This PR will be merged at 2022-12-10 09:00 UTC+0.

Disable package uploads

---

packages/php/build.sh
packages/php/ext-standard-php_fopen_wrapper.c.patch
packages/php/php-apache-ldap.subpackage.sh
packages/php/php-apache-opcache.subpackage.sh
packages/php/php-apache-pgsql.subpackage.sh
packages/php/php-apache-sodium.subpackage.sh
packages/php/php-apache.subpackage.sh

This is a "major" bump including <a href="https://www.php.net/manual/en/migration82.incompatible.php">backward-incompatible changes</a>. Tests requested.
~~Include a workaround tip for #13256 in postinst message of `php-apache`.~~
Extensions for PHP/Apache are packaged under the name of `php-apache-*` and are installed under the directory `$PREFIX/lib/php-apache/`.
(Extensions under `$PREFIX/lib/php/` will not work with PHP/Apache.)
Closes #13256.

php: Bump to 8.2.0

---

x11-packages/tint2/build.sh
x11-packages/tint2/src-battery-dummy.c.patch

tint2: Bump to 17.1.3

---

packages/libandroid-support/build.sh

It was added to fix a particular package dependency issue when libiconv was added (see termux/termux-packages#3762).  It is however not correct, libandroid-support does not (pre-)depend on dpkg and specifying that it does can lead to cyclic dependency issues.
Remove this workaround since it by now has been several years since the original issue was fixed.
Fixes termux/termux-packages#13913

enchance(main/libandroid-support): remove pre-depends on dpkg

---

x11-packages/gtk3/broadway-server.patch
x11-packages/gtk3/build.sh
x11-packages/gtk3/gdkbroadway-server.patch

Hello,
This PR enables building gtk3 with the broadway backend.    
This backend allows to display GTK applications in a browser using HTML. It thus allows launching GTK application from termux without relying on an X server and using a browser to use the application.  
Please have a look here for more information: https://docs.gtk.org/gtk3/broadway.html.    
I can successfully build gtk3 using docker, and launch gtk3-demo via broadway, but it probably needs a bit more testing.

enhance(x11/gtk3): add broadway backend

---

packages/libenet/build.sh

ENet's purpose is to provide a relatively thin, simple and robust network communication layer on top of UDP (User Datagram Protocol).The primary feature it provides is optional reliable, in-order delivery of packets.
ENet omits certain higher level networking features such as authentication, lobbying, server discovery, encryption, or other similar tasks that are particularly application specific so that the library remains flexible, portable, and easily embeddable.
As an example of enet's use: [love2d](https://love2d.org) (which is also available in termux) already comes with it to allow games using it to implement networking. This package allows more flexibility to users allowing them to e.g write servers in different languages while still being protocol compatible with love2d's client, …

enet: add package

---

packages/apksigner/build.sh
packages/d8/build.sh
scripts/properties.sh

Also stops ~~directly specifying `$TERMUX_ANDROID_BUILD_TOOLS_VERSION` in~~ using the `TERMUX_ANDROID_BUILD_TOOLS_VERSION` variable when specifying `TERMUX_PKG_VERSION`. Ref: #2486.

properties.sh: Bump build-tools to 33.0.1

---

scripts/build/configure/termux_step_configure_autotools.sh
scripts/build/configure/termux_step_configure_cmake.sh
scripts/build/configure/termux_step_configure_meson.sh

In response to commit ae454e2ef4faf9676974104328e1261f3aa97c70.

scripts: Provide hooks triggered by failure in configure

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh

Recent package updates related to `libuuid` have created errors when updating via pacman.
This is because package version comparison requires a revision at the end, otherwise pacman will only compare by version, ignoring the package revision.

fix version view in package info for pacman

---

packages/fastfetch/build.sh

`vulkan-headers` and `vulkan-loader-android` are build dependencies. They don't need to be installed when running fastfetch.

Fastfetch: upgrade to 1.8.0

---

packages/boinc/build.sh
packages/boinc/client-cpu_benchmark.h.patch
packages/boinc/client-dhrystone.cpp.patch
packages/boinc/client-whetstone.cpp.patch

My poor attempt on fixing this issue by slapping `volatile` in the code which actually works.
I dont understand why this does not happen on Fedora which supposedly turn on LTO everywhere...

fix(main/boinc): make benchmark LTO resistant

---

packages/rust/build.sh
packages/rust/dlopen.patch

`rust-analyzer` uses an [unsupported](https://github.com/termux/termux-packages/wiki/Common-porting-problems#dlopen-and-rtld_-flags) `dlopen` flag `RTLD_DEEPBIND`, causing many proc macros (e.g. `tokio::main`) to get errors and not expanded, resulting in an inferior Rust development experience on Termux - `rust-analyzer` doesn't even work on a `#[tokio::main]` hello-world application.
This PR fixes the issue by removing the flag for good.
Instead of patching `rust-analyzer`, I'm patching the `rust` package first, because the `rust` package ships a `rust-analyzer-proc-macro-srv` binary, which is used by `rust-analyzer` by default (RA falls back to using itself only when it cannot find the preinstalled srv binary), no matter how `rust-analyzer` itself is installed.
Tested on my phone, proc …

fix(rust): patch unsupported dlopen flag

---

packages/photon-rss/build.sh
packages/ratt/build.sh

as a follow-up of commit 3ec82277d7773e29aac53d525fdf519f74246bd4.
%ci:no-build

photon-rss, ratt: Restore `termux_step_post_get_source`

---

packages/newsboat/build.sh
packages/newsboat/rust-libnewsboat-src-utils.rs.patch

After it was (accidentally?) removed newsboat started having issues, see newsboat/newsboat#2299

newsboat: re-add iconv dependency

---

packages/moria/build.sh

Fixes #1401
I initially tried to change the current `postinst` into `termux_step_post_massage` and use `TERMUX_PKG_CONFFILES` for `game.sav` and `scores.dat` to let package manager to deal with cleaning and directory sharing between packages
But it is less ideal as everytime you upgrade will be greeted with:
```
Configuration file '/data/data/com.termux/files/usr/lib/games/moria/scores.dat'
==> File on system created by you or by a script.
==> File also in package provided by package maintainer.
What would you like to do about it ?  Your options are:
Y or I  : install the package maintainer's version
N or O  : keep your currently-installed version
D     : show the differences between the versions
Z     : start a shell to examine the situation
The default action is to keep your current …
```

moria: add prerm script

---

scripts/updates/utils/termux_pkg_upgrade_version.sh

to avoid warnings like
```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2:0.8.3 is an invalid version and will not be supported in a future release
```

auto-update: Exclude epoch in version comparison

---

packages/cmake/Modules-Platform-Android-GNU.cmake.patch
packages/cmake/build.sh

cmake: Fix C compiler ABI detection with GCC

---

x11-packages/qt-creator/build.sh

to get rid of unresolved symbols.
The same as commit 6337a0af3ba9fb618d99438050db4d4fcd9afb95.

qt-creator: Rebuild against newer Qt Concurrent

---

packages/snapcast-server/snapcast-0.26.0-boost-1.81.0.patch

snapcast-server: Fix build with Boost 1.81.0

---

packages/pacman/build.sh
packages/pacman/pacman.conf.in.patch

The `pacman` package manager now has a plain format domain with faster download speeds. The old links (`s3.amazonaws.com/termux-pacman.us/...`) will still work, but I recommend using the new ones.

bump(main/pacman): updating server links to repos and adding email to TERMUX_PKG_MAINTAINER

---

packages/2ping/build.sh
packages/python-apt/build.sh
packages/python-cryptography/build.sh

This happened because I didn't separate the packages correctly.
Close #14586

tree-wide: make python packages use termux_setup_python_pip (part 2)

---

packages/gforth/build.sh
scripts/build/termux_step_massage.sh

Also fixes logic of shebang fix in `termux_step_massage`.

gforth: Fix alignment of magic in `*.fi`

---

packages/guile/build.sh

so that `gen-scmconfig` produces correct config for target host.
Without this `SCM_SIZEOF_LONG` is defined as `8` on arm (32-bit) target which is obviously wrong.

guile: Fix `CC_FOR_BUILD`

---

packages/libdart/CMakeLists.txt.patch
packages/libdart/build.sh

https://github.com/termux/termux-packages/issues/14617

libdart: fix update to 6.13.0
