- packages/libjpeg-turbo/build.sh
> libjpeg-turbo: Add SOVERSION suffix

- packages/libjpeg-turbo/build.sh
> libjpeg-turbo: Check if SONAME is properly set

- packages/qemu-system-x86-64-headless/build.sh
- x11-packages/qemu-system-x86-64/build.sh
> qemu: Revbump to rebuild

- x11-packages/feh/build.sh
and recommend libjpeg-turbo-progs instead.
> feh: Remove libjpeg-turbo from dependency

- packages/libxml2/build.sh
> libxml2: Add SOVERSION suffix

- packages/libbluray/build.sh
> libbluray: Revbump to rebuild

- packages/libspatialite/build.sh
> libspatialite: Revbump to rebuild

- packages/ffmpeg/build.sh
> ffmpeg: Revbump to rebuild

- packages/graphicsmagick/build.sh
> graphicsmagick: Revbump to rebuild

- packages/libgnt/build.sh
> libgnt: Revbump to rebuild

- packages/libsoup/build.sh
> libsoup: Revbump to rebuild

- packages/libwv/build.sh
> libwv: Revbump to rebuild

- x11-packages/goffice/build.sh
> goffice: Revbump to rebuild

- x11-packages/gtksourceview3/build.sh
> gtksourceview3: Revbump to rebuild

- packages/emacs/build.sh
- x11-packages/emacs-x/build.sh
> emacs{,-x}: Revbump to rebuild

- packages/vlc/build.sh
- x11-packages/vlc-qt/build.sh
> vlc{,-qt}: Revbump to rebuild

- packages/imagemagick/build.sh
> imagemagick: Revbump to rebuild

- packages/php/build.sh
> php: Revbump to rebuild

- x11-packages/qt5-qtwebkit/build.sh
> qt5-qtwebkit: Revbump to rebuild

- packages/openscad/build.sh
> openscad: Revbump to rebuild

- x11-packages/handbrake/build.sh
> handbrake: Revbump to rebuild

- x11-packages/inkscape/build.sh
> inkscape: Revbump to rebuild

- x11-packages/epiphany/build.sh
> epiphany: Revbump to rebuild

- x11-packages/ardour/build.sh
> ardour: Revbump to rebuild

- packages/libxml2/build.sh
> libxml2: Revbump and unbreak the package

- packages/vtm/netxs-desktopio-input.hpp.patch
> vtm: fix build on 32-bit

- packages/nushell/build.sh
See https://www.nushell.sh/blog/2022-11-29-nushell-0.72.html.
> fix(main/nushell): use `--features=dataframe`

- packages/hunspell-hu/build.sh
Looks like it's been updated. If there's a system for picking a version other than date of pull request, I didn't figure it out and will amend.
> hunspell-hu: Update to latest version.

- packages/tesseract/build.sh
Closes termux/termux-packages#17407.
> bump(main/tesseract): 5.3.2

- packages/pypy/0007-termux-build.patch
- packages/pypy/build.sh
- packages/pypy3/0007-termux-build.patch
- packages/pypy3/build.sh
> pypy{,3}: fix rpath

- packages/ansifilter/build.sh
> new package: ansifilter

- packages/tere/0001-rustix-fix-libc-removing-unsafe-on-makedev.diff
- packages/tere/build.sh
> tere: bump to 1.5.0

- packages/topgrade/build.sh
> topgrade: bump to 12.0.1

- packages/mpv/build.sh
- x11-packages/mpv-x/build.sh
> mpv{,-x}: bump to 0.36.0

- packages/aapt/build.sh
- packages/googletest/build.sh
> googletest: bump to 1.14.0

- packages/kakoune/build.sh
- packages/kakoune/src-display_buffer.hh.patch
> kakoune: bump to 2023.07.29

- packages/boinc/build.sh
> bump(main/boinc): 7.24.0

- packages/dnote-server/build.sh
https://github.com/termux/termux-packages/actions/runs/5839365038/job/15837465242?pr=17590#step:6:539
> dnote-server: fix build

- packages/frp/build.sh
- packages/frp/upgrade-quic-go-to-0.37.4.patch
> fix(main/frp): upgrade quic-go to 0.37.4

- packages/opencl-vendor-driver/build.sh
- packages/opencl-vendor-driver/postinst.sh
Drop grep usage and simplify script
Add PowerVR support
> bump(main/opencl-vendor-driver): 0.2

- packages/libgit2/build.sh
> upgpkg(main/libgit2): 1.7.0

- packages/hilbish/build.sh
- packages/hilbish/fix-hardcoded-path.patch
> addpkg(main): hilbish

- packages/opencl-vendor-driver/build.sh
- packages/opencl-vendor-driver/postinst.sh
Fix minor bug for fail to install user override lib
> bump(main/opencl-vendor-driver): 0.3

- .github/workflows/docker_image.yml
- scripts/Dockerfile
- scripts/setup-cgct.sh
- scripts/setup-ubuntu.sh
I found a way to make `cgct` work in `package-builder` without changing the internal system.
> package-builder: adding the CGCT tool

- packages/vulkan-loader-generic/0002-properly-enable-extensions.patch
- packages/vulkan-loader-generic/build.sh
> vulkan-loader-generic: bump to 1.3.262

- packages/texlive-bin/build.sh
Fixes termux/termux-packages#17722
> texlive-bin: bump after zlib update

- build-package.sh
- scripts/build/termux_create_debian_subpackages.sh
- scripts/build/termux_create_pacman_subpackages.sh
- scripts/build/termux_download_deb_pac.sh
- scripts/build/termux_step_get_dependencies.sh
- scripts/build/termux_step_setup_cgct_environment.sh
- scripts/build/termux_step_setup_variables.sh
- scripts/get_hash_from_file.py
- scripts/utils/package/package.sh
- adding version check of dependencies in pacman format
- improving termux_step_setup_cgct_environment()
- adding a new `-w` flag
- fix creating static packages
> Improvement build-package.sh

- packages/wasmedge/build.sh
> fixup(main/wasmedge): fix typo

- packages/lsd/build.sh
> lsd: bump to 1.0.0

- packages/proxmark3/build.sh
Closes #17783 
Ping @s00se as the maintainer
> proxmark3: bump to 4.17140

- packages/ncurses/build.sh
> ncurses: symlink headers in `post_massage` step

- packages/findomain/build.sh
Fix https://github.com/termux/termux-packages/actions/runs/6189353019/job/16803268196
> fix(main/findomain): i686 build

- packages/emacs/Makefile.patch
- packages/emacs/build.sh
- packages/emacs/lisp-textmodes-ispell.el.patch.beforehostbuild
- packages/emacs/lisp.Makefile.in.patch
- packages/emacs/no-procent_n-android.patch
- packages/emacs/src-filelock.c.patch
- x11-packages/emacs-x/Makefile.patch
- x11-packages/emacs-x/build.sh
- x11-packages/emacs-x/lisp-textmodes-ispell.el.patch.beforehostbuild
- x11-packages/emacs-x/lisp.Makefile.in.patch
- x11-packages/emacs-x/no-procent_n-android.patch
- x11-packages/emacs-x/src-filelock.c.patch
Hello,
This is a proposal for updating Emacs to version 29.1.
I also enabled tree-sitter in both versions.
Let me know if you see improvements to be made on the updated files !
> emacs{,-x}: update to version 29.1

- packages/perl/build.sh
Fixes termux/termux-packages#17837
> perl: convert hardlinks to softlinks

- packages/fx/build.sh
> fx: bump to 30.0.2

- .github/workflows/package_updates.yml
> ci(package_updates.yml): always clean up for spaces

- packages/tinygo/build.sh
> fix(main/tinygo): rework custom auto update 2

- x11-packages/firefox/build.sh
Fix https://github.com/termux/termux-packages/actions/runs/6272327685/job/17033652646
> fix(x11/firefox): disable debuginfo for Arm

- packages/tinygo/build.sh
> chore(main/tinygo): rework checksum verification

- packages/libfcft/build.sh
- packages/libtllist/build.sh
- x11-packages/foot/0001-fix-wayland-scanner-path.patch
- x11-packages/foot/build.sh
> new package: libtllist, libfcft, foot

- x11-packages/quassel/0001-avoid-deduplication-of-users-CXXFLAGS.patch
- x11-packages/quassel/0002-recover-cxxflags-from-envvars-after-processing.patch
- x11-packages/quassel/build.sh
> new package: quassel

- packages/tinygo/build.sh
> bump(main/tinygo): 0.30.0

- packages/seafile-client/build.sh
> seafile-client: bump to 9.0.4

- packages/vulkan-utility-libraries/0001-do-not-build-for-android.patch
- packages/vulkan-utility-libraries/build.sh
> vulkan-utility-libraries: bump to 1.3.265

- packages/below/build.sh
> chore(main/below): switch to auto update newest-tag

- packages/libduckdb/build.sh
Missed this change in the last PR
> libduckdb: restore extensions

- packages/ffmpeg/build.sh
> enhance(main/ffmpeg): enable libsvtav1, libv4l2

- packages/rust/build.sh
- packages/rust/syncfs.c
> fix(main/rust): define syncfs for Android 8.x and older

- packages/parallel/build.sh
- packages/parallel/parallel.patch
Fix https://github.com/termux/termux-packages/discussions/17895
> fix(main/parallel): switch method to count CPUs

- x11-packages/lite-xl/build.sh
- x11-packages/lite-xl/meson.build.patch
> fix(x11/lite-xl): desktop shortcuts

- packages/ncurses/build.sh
See https://github.com/termux/termux-packages/issues/18094
> ncurses: Update kitty terminfo to 0.30.0

- .github/workflows/packages.yml
Let's see how much disk space it frees up and how well this works.
> Build large packages on the CI without Docker

- packages/procyon-decompiler/build.sh
- packages/procyon-decompiler/gradle-7.patch
- scripts/properties.sh
- scripts/setup-ubuntu.sh
Having the LTS JDK 17 seems to be enough.
This shaves away 600 MB from the docker image size.
> scripts(setup-ubuntu): Remove jdk 8 and 18

- .github/workflows/packages.yml
- packages/rust/build.sh
- packages/rust/config.toml
- packages/rust/rustc-dev.subpackage.sh
- scripts/build/setup/termux_setup_rust.sh
- scripts/lint-packages.sh
- scripts/setup-ubuntu.sh
> bump(main/rust): 1.73.0

- packages/glslang/build.sh
- packages/shaderc/build.sh
- packages/spirv-headers/build.sh
- packages/spirv-tools/build.sh
> addpkg(main): spirv-headers, spirv-tools, shaderc

- packages/maxima/build.sh
> maxima: fix to working

- packages/vulkan-tools/build.sh
> bump(main/vulkan-tools): 1.3.268

- packages/ncdu2/build.sh
> addpkg(main): ncdu2

- packages/fzf/bin-fzf-tmux.patch
- packages/fzf/build.sh
> upgpkg(main/fzf): 0.43.0

- x11-packages/spek/build.sh
> fix(x11/spek): add libandroid-stub to depends

- scripts/bin/update-packages
- scripts/updates/api/termux_repology_api_get_latest_version.sh
I'll merge it in the case if nobody minds in this 24 hours. Thank you.
> scripts(update-packages): add an option to opt-out updates

- packages/libprotobuf/0000-issue-18002.patch
- packages/libprotobuf/build.sh
> fix(main/libprotobuf): export missing symbol

- packages/bc-gh/build.sh
Please forgive me! I accidentally left in some debugging code that was not caught with tests since it was in a signal handler.
> bump(main/bc-gh): 6.7.2

- packages/btfs2/build.sh
- packages/btfs2/fix-hardcoded-etc-resolv-conf.diff
- packages/btfs2/fix-hardcoded-etc-resolv-conf.sh
> btfs2: bump to 2.3.3

- packages/flang/build.sh
- packages/flang/postinst.sh.in
- packages/flang/prerm.sh.in
> flang: enable modules

- packages/matplotlib/build.sh
> matplotlib: bump to 3.8.0

- packages/glib/build.sh
- scripts/build/termux_step_massage.sh
- scripts/build/termux_step_setup_variables.sh
> chore(main/glib-cross): exclude files from shebang fix

- packages/rust/build.sh
- packages/rust/config.toml
- packages/rust/rust-std-wasm32.subpackage.sh
- packages/wasi-libc/build.sh
> addpkg(main): wasi-libc, wasm32-wasi target for Rust

- packages/rust/build.sh
> fix(main/rust): link against libc++_shared.so

- root-packages/erofs-utils/build.sh
> add(root): new package erofs-utils

- packages/shiori/build.sh
> fix(main/shiori): 32bit bad syscall

- packages/cmocka/build.sh
a unit testing framework for C.
[homepage](https://cmocka.org)
> new package: cmocka

- packages/vulkan-tools/build.sh
- packages/vulkan-tools/no-android.patch
> upgpkg(main/vulkan-tools): 1.3.270

- packages/fakeroot/build.sh
- packages/fakeroot/doc-Makefile.am.patch
> upgpkg(main/fakeroot): 1.32.2

- packages/zellij/build.sh
> upgpkg(main/zellij): 0.39.0

- packages/rdiff-backup/build.sh
> rdiff-backup: install pyyaml in postinst

- packages/libicu/build.sh
- packages/music-file-organizer/build.sh
- x11-packages/gw/build.sh
> libicu: revbump revdeps (4)

- packages/libicu/build.sh
- x11-packages/firefox/build.sh
- x11-packages/firefox/icu-74.patch
> libicu: revbump revdeps (3)

- build-package.sh
- scripts/build/setup/termux_setup_xmake.sh
- x11-packages/mogan/build.sh
- x11-packages/mogan/plugins-shell-CMakeLists.txt.patch
- x11-packages/mogan/qmake.sh
- x11-packages/mogan/xmake.lua.patch
> bump(x11/mogan): 1.1.6, enhance(scripts): termux_setup_xmake

- packages/harfbuzz/build.sh
>  harfbuzz-icu: revbump to link against with libicu 74

- packages/libtbb/build.sh
> libtbb: bump to 2021.11.0

- packages/kak-lsp/build.sh
- packages/kak-lsp/src-text_edit.rs.patch
> upgpkg(main/kak-lsp): 15.0.0

- packages/libxml2/build.sh
Closes #18521 
I'll merge this PR if there is no more review next Monday. Thanks!
> libxml2: bump to 2.12.0

- packages/dpkg/build.sh
> dpkg: use `less` as pager

- packages/procps/w.c.patch
> procps: fix build on ndk r26

- x11-packages/firefox/build.sh
- x11-packages/firefox/firefox.patch
- x11-packages/firefox/fix-arm-build.patch
- x11-packages/firefox/rust.configure.patch
- x11-packages/firefox/shared_memory_posix.cc.patch
> bump(x11/firefox): 120.0

- packages/qemu-system-x86-64-headless/0007-fix-syscalls.patch
- packages/qemu-system-x86-64-headless/build.sh
https://github.com/termux/proot/discussions/291
> qemu-user: Don't pass flags to faccessat2()

- packages/aspell-fr/build.sh
> fix(main/aspell-fr): use word-list-compress

- packages/libplacebo/build.sh
- packages/mpv/build.sh
- x11-packages/mpv-x/build.sh
Gets merged in 3 days if no review.
> MPV update

- packages/socat/build.sh
- packages/socat/fix-format-specifiers-for-32-bit-archs.patch
Signed-off-by: Vasyl Gello <vasek.gello@gmail.com>
> bump(main/socat): 1.8.0

- packages/blink/blink-blink.c.patch
- packages/blink/blink-machine.h.patch
- packages/blink/build.sh
- packages/blink/fix-tmpdir.patch
* ignore QEMU -E and -U options, add compatibility with proot
* enable all the supported compiler flags
* enable bad syscalls (handled by proot)
> enhance(main/blink): various enhancements

- packages/ripgrep/build.sh
> ripgrep: bump to 14.0.3

- packages/tdl/build.sh
new package: tdl
📥 A Telegram downloader/tools written in Golang
https://github.com/iyear/tdl
> new package: tdl

- packages/libmediainfo/build.sh
Activated auto-update because the package is tracked by repology.
> upgpkg(main/libmediainfo): 23.11

- packages/trurl/build.sh
- packages/trurl/increment-version-0.8.patch
- scripts/build/termux_step_install_license.sh
- scripts/lint-packages.sh
close #18591 
upstream forgot to increment the version to 0.9, added a patch for that.
Also added the curl license and changed the license of curl to that.
> new package: trurl

- packages/djvulibre/0001-remove-register-keyword-for-cxx17.patch
- packages/djvulibre/build.sh
> djvulibre: revbump to rebuild with libjpeg

- .github/workflows/packages.yml
- packages/rust-analyzer/build.sh
- packages/rust/build.sh
- scripts/big-pkgs.list
- scripts/build/termux_create_debian_subpackages.sh
- scripts/build/termux_download.sh
The CI logs are now hard to load so separate them like they used to
> rust 1.74.1, rust-analyzer 20231204, CI and script adjustments

- packages/rust-analyzer/build.sh
> fix(main/rust-analyzer): custom auto update

- packages/libopenblas/blas-openblas.subpackage.sh
- packages/libopenblas/build.sh
> libopenblas: enable static libs and provide blas/cblas/lapack/lapacke

- packages/suitesparse/0001-android-complex-math.patch
- packages/suitesparse/build.sh
Add package suitesparse, the dependency of sundials and octave.
Part of #387
> new package: suitesparse

- packages/libsecret/build.sh
- packages/libsecret/gir/Secret-1.xml
> libsecret: bump to 0.21.2

- packages/termux-elf-cleaner/build.sh
- scripts/build/termux_step_start_build.sh
Now we can clean packages in multiple threads!
> bump(main/termux-elf-cleaner): update to 2.2.0

- packages/sundials/0001-fix-int-type.patch
- packages/sundials/build.sh
Add package sundials, the dependency of octave.
Part of #387
> new package: sundials

- packages/apt/build.sh
Simple bump. Needs some tests before merging.
> bump(main/apt): 2.7.7

- scripts/bin/update-packages
Close #18779 
Close #18767 
Close #18784 
Close #18769 
Close #18785 
Close #18772 
Close #18781 
Close #18765
Close #18780 
Close #18787 
Close #18771
Close #18783 
Close #18786
(all the issues are duplicated)
To prevent making duplicated issues over and over by auto updater
> fix(auto-updater): increase gh issue list limit to 10000

- packages/arpack-ng/build.sh
- packages/octave/0001-fix-hardcoded-paths.patch
- packages/octave/0002-append-rpath-flag-to-pkg-config-files.patch
- packages/octave/0003-undefine-the-macro-in-pwd.h.patch
- packages/octave/build.sh
- packages/qrupdate-ng/build.sh
- x11-packages/octave-x/0001-fix-hardcoded-paths.patch
- x11-packages/octave-x/0002-append-rpath-flag-to-pkg-config-files.patch
- x11-packages/octave-x/0003-undefine-the-macro-in-pwd.h.patch
- x11-packages/octave-x/build.sh
> new package: octave, octave-x

- packages/php/ext-libxml-libxml.c.patch
- packages/php/ext-soap-php_sdl.c.patch
> php: fix build with libxml 2.12

- x11-packages/audacity/build.sh
- x11-packages/audacity/lib-src-libnyquist-nyquist-cmt-midifile.c.patch
- x11-packages/audacity/lib-src-libnyquist-nyquist-nyqsrc-handlers.c.patch
> audacity: fix build with clang 17

- packages/mesa/0007-fix-build-for-lld-17.patch
- packages/mesa/0008-do-not-use-config-tool-when-searching-llvm.patch
- packages/mesa/build.sh
> mesa: bump to 23.3.1

- packages/erlang/build.sh
- packages/erlang/wrapper.py.in
> erlang: bump to 26.2

- packages/libgcrypt/build.sh
> libgcrypt: bump to 1.10.3

- packages/libmpdclient/build.sh
> libmpdclient: bump to 2.22

- x11-packages/firefox/build.sh
- x11-packages/firefox/firefox.patch
- x11-packages/firefox/rust.configure.patch
> bump(x11/firefox): 121.0

- packages/geth/build.sh
- packages/geth/geth-utils.subpackage.sh
Close #18744 
faucet has been removed in upstream https://github.com/ethereum/go-ethereum/pull/28586
> bump(main/geth): 1.13.6

- packages/starship/0001-Cargo.toml.patch
- packages/starship/build.sh
- packages/starship/gix-index-0.27.0-src-fs.rs.diff
> starship: bump to 1.17.0

- packages/ttyplot/build.sh
> ttyplot: bump to 1.6.0

- packages/opencv/build.sh
> upgpkg(main/opencv): 4.9.0

- packages/mesa-vulkan-icd-freedreno-dri3/build.sh
> mesa-vulkan-icd-freedreno-dri3: resolve file conflicts

- packages/broot/build.sh
- packages/broot/disable-trash.patch
> bump(main/broot): 1.32.0

- packages/libtsduck/Makefile.inc.patch
- packages/libtsduck/build.sh
- packages/libtsduck/src-libtsduck-Makefile.patch
- packages/libtsduck/src-libtsduck-base-system-tsForkPipe.cpp.patch
- packages/libtsduck/src-libtsduck-base-system-tsSysUtils.h.patch
- packages/libtsduck/src-libtsduck-config-Makefile.patch
- packages/libtsduck/src-libtsduck-config-tsduck.pc.patch
- packages/libtsduck/src-libtsduck-python-Makefile.patch
- packages/libtsduck/src-tsplugins-Makefile.patch
- packages/libtsduck/src-tstools-Makefile.patch
> bump(main/libtsduck): 3.36.3528

- packages/at-spi2-core/build.sh
- packages/at-spi2-core/gir/Atk-1.0.xml
- packages/at-spi2-core/gir/Atspi-2.0.xml
> at-spi2-core: bump to 2.50.1

- build-package.sh
- scripts/build/termux_step_get_dependencies.sh
This change will avoid cyclical attempts to install/compile the package. How this can happen: if two (or more) packages are updated and depend on each other due to other packages, the compiler will endlessly try to install/compile those packages.
~~@agnostic-apollo, could you check if this PR breaks the logic of the `-F` flag?~~
> termux_step_get_dependencies.sh: avoid getting into package dependency cycles

- x11-packages/praat/build.sh
> praat: bump to 6.4.04

- packages/cloudflared/build.sh
> cloudflared: bump to 2024.1.0

- packages/proton-bridge/build.sh
- packages/proton-bridge/disable-updater.patch
> proton-bridge: bump to 3.7.1

- packages/nushell/build.sh
> nushell: bump to 0.89.0

- packages/libdecor/build.sh
- x11-packages/sdl2/build.sh
- x11-packages/sdl2/src-video-wayland-SDL_waylandsym.h.patch
> addpkg(main): libdecor, enhance(x11/sdl2): enable opengles, vulkan, wayland

- packages/uftrace/build.sh
- packages/uftrace/check-deps-Makefile.patch
https://github.com/termux/termux-packages/actions/runs/7508992821/job/20447581563
> fix(main/uftrace): i686 build

- .github/workflows/bootstrap_archives.yml
> fix(ci): {up,down}load-artifact@v4 on generate bootstrap archive

- x11-packages/virglrenderer/build.sh
> virglrenderer: bump to 1.0.1

- packages/gmic/Makefile.patch
- packages/gmic/build.sh
> gmic: bump to 3.3.3

- packages/electrum/android.patch
- packages/electrum/build.sh
- packages/electrum/only-text-gui.patch
> electrum: bump to 4.5.0

- packages/glibc-repo/build.sh
> main/glibc-repo: new pkg

- packages/python-pillow/build.sh
- packages/python-pillow/setup.py.patch
> python-pillow: fix installation

- x11-packages/scrcpy/build.sh
> scrcpy: depends on android-tools

- x11-packages/thunderbird/0001-configure-treat-termux-as-linux.patch
- x11-packages/thunderbird/0002-configure-fix-arm-options.patch
- x11-packages/thunderbird/0003-configure-fix-rustflags.patch
- x11-packages/thunderbird/0004-configure-do-not-check-libstdcxx-headers.patch
- x11-packages/thunderbird/0005-configure-do-not-append-sysroot.patch
- x11-packages/thunderbird/0006-configure-do-not-enable-alsa.patch
- x11-packages/thunderbird/0007-configure-fix-autoconf-on-android.patch
- x11-packages/thunderbird/0008-fix-marcos.patch
- x11-packages/thunderbird/0009-impl-posix-shmem.patch
- x11-packages/thunderbird/0010-do-not-check-time_t-for-system-libevent.patch
- x11-packages/thunderbird/0011-use-UnderrunHandlerNoop.patch
- x11-packages/thunderbird/0012-do-not-use-adaptive-mutex.patch
- x11-packages/thunderbird/0013-fix-rust-compile.patch
- x11-packages/thunderbird/0014-unset-thread-priority-scheduling-macro.patch
- x11-packages/thunderbird/0015-skia-termux.patch
- x11-packages/thunderbird/0016-protobuf-no-android-log.patch
- x11-packages/thunderbird/0017-icu-74.patch
- x11-packages/thunderbird/0018-fix-include-dir-for-cpufeatures.patch
- x11-packages/thunderbird/0019-fix-sigbus.patch
- x11-packages/thunderbird/0020-fix-dlopen-library-name.patch
- x11-packages/thunderbird/build.sh
- x11-packages/thunderbird/mozconfig.cfg
- x11-packages/thunderbird/thunderbird.desktop
> new package: thunderbird

- packages/electrum/build.sh
> electrum: bump to 4.5.2

- packages/libjpeg-turbo/build.sh
> libjpeg-turbo: bump to 3.0.2

- packages/uftrace/build.sh
- packages/uftrace/check-deps-Makefile.patch
> uftrace: bump to 0.15.2

- packages/typst-lsp/build.sh
> new package: typst-lsp (#15975)

- packages/zlib/build.sh
* Use source tarball from GitHub.
* Enable auto update.
> bump(main/zlib): 1.3.1

- packages/libvpx/build.sh
> libvpx: Enable vp9 codec

- packages/emacs/build.sh
- x11-packages/emacs-x/build.sh
Hello,
This is a proposal to update Emacs to version 29.2.
Let me know if you see improvements to be made on the updated files !
> emacs{,-x}: update to version 29.2

- packages/logo-ls/build.sh
> logo-ls: migrate to maintained fork

- packages/osslsigncode/build.sh
> add package: osslsigncode

- packages/yazi/build.sh
- packages/yazi/pr-600.patch
> add package: yazi

- root-packages/ipset/build.sh
> bump(root/ipset): 7.20

- packages/neomutt/build.sh
- packages/neomutt/muttlib.c.patch
> upgpkg(main/neomutt): 20240201

- packages/mpd/build.sh
- packages/python-torch/build.sh
> fix(main/mpd,python-torch): conflict with fmt

- packages/python-pip/build.sh
> python-pip: fix build

- packages/teleport-tsh/build.sh
- packages/teleport-tsh/metadata_linux.go.patch
> upgpkg(main/teleport-tsh): 15.0.0

- packages/libarrow-cpp/build.sh
- packages/python-pyarrow/build.sh
> libarrow-cpp, python-pyarrow: Bump to 15.0.0

- packages/imlib2/0000-fix-mblen.patch
- packages/imlib2/0002-fix-hardcoded-paths.patch
- packages/imlib2/build.sh
> upgpkg(main/imlib2): 1.12.2

- packages/python-torchaudio/build.sh
> python-torchaudio: revbump to rebuild

- packages/nushell/build.sh
> nushell: bump to 0.90.1

- packages/mruby/build.sh
> fix(main/mruby): use repology update method

- packages/testssl.sh/build.sh
> fix(main/testssl.sh): use repology update method

- x11-packages/scite/build.sh
> bump(x11/scite): 5.4.1

- packages/libduckdb/build.sh
Fixes https://github.com/termux/termux-packages/issues/19239
> libduckdb: update to 0.10.0

- packages/vulkan-tools/build.sh
- packages/vulkan-tools/no-android.patch
> bump(main/vulkan-tools): 1.3.278

- packages/python-scipy/0001-pr-19909.patch
- packages/python-scipy/build.sh
- packages/python-scipy/wrapper.py.in
> python-scipy: bump to 1.12.0

- packages/miniupnpc/build.sh
> bump(main/miniupnpc): 2.2.6

- x11-packages/eww/build.sh
- x11-packages/eww/fix_tmp_hardcoded_path.patch
- x11-packages/gtk-layer-shell/build.sh
- x11-packages/gtk-layer-shell/protocol-meson-build.patch
> bump(x11/eww): 0.5.0

- packages/libcurl/build.sh
- packages/libnghttp3/build.sh
- packages/openssl/build.sh
> libcurl: enable HTTP/3

- packages/proxmark3/build.sh
Include resources, dictionaries, and various scripts
Remove debug
Disable gd
> proxmark3: update build.sh

- packages/rsgain/build.sh
closes:
- #19132
---
New package checklist:
> new package: rsgain

- packages/ovmf/build.sh
> bump(main/ovmf): 20231122-16.fc40

- packages/jfrog-cli/build.sh
> bump(main/jfrog-cli): 2.53.1

- packages/liblzma/build.sh
> bump(main/liblzma): 5.6.0

- packages/flang/build.sh
- packages/flang/postinst.sh.in
> flang: bump to 17.0.6

- root-packages/squashfuse/build.sh
> bump(root/squashfuse): 0.5.2

- x11-packages/ardour/build.sh
> bump(x11/ardour): 8.4

- packages/libarrow-cpp/build.sh
- packages/python-pyarrow/build.sh
- packages/python-pyarrow/upstream-15.0.1-Fix-except-clauses.patch
> bump(main/libarrow-cpp, python-pyarrow): 15.0.1

- packages/yazi/build.sh
> upgpkg(main/yazi): 0.2.4

- packages/typst/build.sh
> bump(main/typst): 0.11.0

- packages/typst-lsp/build.sh
Also enabled auto updates (follow up for #15975 and #19071)
> bump(main/typst-lsp): 0.13.0

- root-packages/nexttrace-enhanced/build.sh
> bump(root/nexttrace-enhanced): 1.2.9

- packages/wakatime-cli/build.sh
> bump(main/wakatime-cli): 1.90.0

- packages/glib/build.sh
- packages/glib/glib-gcharset.c.patch
> bump(main/glib): 2.80.0

- packages/libwolfssl/build.sh
Change SOVERSION check logic.
Fixes #19532
> bump(main/libwolfssl): 5.7.0

- packages/emacs/build.sh
- x11-packages/emacs-x/build.sh
Hello,
This is a proposal to update Emacs to version 29.3.
Let me know if you other updates to the modified files !
> emacs{,-x}: update to version 29.3

- build-package.sh
- scripts/build/termux_create_pacman_subpackages.sh
- scripts/build/termux_step_create_pacman_package.sh
Inspired by https://gitlab.archlinux.org/pacman/pacman/-/commit/d30878763ce1b5be453b563f2729d7333242e79b
> build-packages.sh: Set timestamp for all files in pacman package

- packages/tinygo/GNUmakefile.patch.beforehostbuild
- packages/tinygo/build.sh
> bump(main/tinygo): 0.31.2

- packages/atuin/build.sh
This removes the host build step and reduces total package build time.
/cc @laurentlbm
> chore(main/atuin): Generate shell completions at install time

- packages/vim-python/build.sh
- packages/vim-python/fix-writing-archive.patch
- packages/vim/build.sh
- packages/vim/fix-writing-archive.patch
- x11-packages/vim-gtk/build.sh
- x11-packages/vim-gtk/fix-writing-archive.patch
Added a patch to fix editing of zip and tar file contents
> vim{,-python,-gtk}: update to 9.1.0200

- packages/texlive-installer/build.sh
trying to implement this suggestion: https://github.com/termux/termux-packages/issues/19606#issuecomment-2028231680
this does not fix any issues
> feat(main/texlive-installer): add profile script for fish shell

- packages/zoxide/build.sh
Also fix man page directory. Previously, man pages were in an extra man1 subdirectory.
> chore(main/zoxide): Install shell completions

- x11-packages/nextcloud-client/CMakeLists.txt.patch
- x11-packages/nextcloud-client/FindInotify.cmake.patch
- x11-packages/nextcloud-client/build.sh
- x11-packages/nextcloud-client/ocsprofileconnector.cpp.patch
- x11-packages/nextcloud-client/theme.cpp.patch
- x11-packages/nextcloud-client/tokencredentials.cpp.patch
- x11-packages/qtkeychain/CMakeLists.txt.patch
- x11-packages/qtkeychain/ECMGeneratePriFile.cmake.patch
- x11-packages/qtkeychain/build.sh
> Adding `nextcloud-client` & `qtkeychain` packages

- packages/openjdk-17/build.sh
> chore(main/openjdk-17): adding libandroid-spawn to dependencies

- scripts/boot-set-up-pkgs.sh
- scripts/generate-bootstraps.sh
> scripts/generate-bootstraps.sh: improve pacman-based bootstrap creations

- packages/nushell/build.sh
> nushell: bump to 0.92.0

- packages/libarchive/build.sh
- packages/libarchive/tar-make-error-reporting-more-robust-and-use-correct-errno.patch
See libarchive/libarchive#1609 and libarchive/libarchive#2101
> libarchive: backport upstream fix

- packages/dateutils/build.sh
> addpkg(main/dateutils): 0.4.11

- scripts/buildorder.py
`TERMUX_PKG_ACCEPT_PKG_IN_DEP` - allows you to add an initial package as a dependency, if any requested package will have a dependency on it.
> scripts/buildorder.py: improving and adding new feature

- scripts/get_hash_from_file.py
Error - https://github.com/termux/glibc-packages/actions/runs/8673471012
> fix(scripts/get_hash_from_file.py): do not write old packages

- packages/glib/build.sh
- packages/glib/gir/GIRepository-3.0.xml
- packages/glib/gir/GLib-2.0.xml
- packages/glib/gir/GLibUnix-2.0.xml
- packages/glib/gir/GModule-2.0.xml
- packages/glib/gir/GObject-2.0.xml
- packages/glib/gir/Gio-2.0.xml
- packages/glib/gir/GioUnix-2.0.xml
- packages/glib/meson.build.patch
This is the 3rd and final step of glib and gobject-introspection bootstrapping.
> enhance(main/glib): Enable generating gobject introspection data and man pages

- packages/lighttpd/build.sh
> bump(main/lighttpd): 1.4.76

- packages/ninja/build.sh
- packages/ninja/src-util.cc.patch
> bump(main/ninja): 1.12.0

- packages/tinygo/build.sh
* move subpackages DEPENDS append to pre configure step
* make all dependencies hard
> chore(main/tinygo): clean up build script

- packages/rust/build.sh
* Enable custom auto update
* Bring back x86_64 host build to workaround issue from efc0a1cf291d6aa93ae4f07f42645df303ef932e
> bump(main/rust): 1.77.2

- packages/apt/0002-no-locales.patch
- packages/apt/build.sh
> bump(main/apt): 2.7.12

- packages/asm-lsp/build.sh
> asm-lsp: init at 0.6.0

- packages/dotconf/build.sh
> bump(main/dotconf): 1.4.1

- packages/pandoc/build.sh
See https://github.com/jgm/pandoc/releases/tag/3.1.13
> bump(main/pandoc): 3.1.13

- packages/libhangul/build.sh
- x11-packages/fcitx5-hangul/build.sh
> addpkg(x11/fcitx5-hangul): 5.1.2

- packages/libmediainfo/build.sh
- packages/mediainfo/build.sh
> libmediainfo,mediainfo: Use Custom termux_pkg_auto_update

- packages/libmediainfo/build.sh
- packages/mediainfo/build.sh
> fix(main/libmediainfo,mediainfo): unbound variable

- packages/libxmlrpc/build.sh
- packages/libxmlrpc/lib-expat-xmltok-Makefile.patch
- packages/libxmlrpc/src-xmlrpc_data.c.patch
- packages/rtorrent/build.sh
> enhance(main/rtorrent): Build with libxmlrpc

- packages/cppcheck/build.sh
> bump(main/cppcheck): 2.14.0

- scripts/build/setup/termux_setup_ninja.sh
> ninja: update to 1.12.0

- packages/hcloud/build.sh
hcloud failed to build in last cbc23b62b3cade28e710da44563d18348fa8ae0b commit.
> chore(main/hcloud): Install shell completion

- x11-packages/weston/build.sh
- x11-packages/weston/bump-neatvnc.patch
> bump(x11/weston): 13.0.1

- packages/mu/build.sh
- packages/mu/lib-mu-scanner.cc.patch
- packages/mu/mu4e-dont-bytecompile-meson.patch
> bump(main/mu): 1.12.4

- packages/yosys/Makefile.patch
- packages/yosys/build.sh
> bump(main/yosys): 0.40

- packages/dar/build.sh
- packages/dar/configure.patch
- packages/dar/no-tests.patch
> bump(main/dar): 2.7.14

- packages/syncthing/build.sh
> bump(main/syncthing): 1.27.6

- packages/gitea/build.sh
> bump(main/gitea): 1.21.11

- packages/rust/build.sh
Repology auto update does not work for rust
> chore(main/rust): switch auto update

- packages/ffmpegthumbnailer/build.sh
> addpkg(main/ffmpegthumbnailer): 2.2.2-p20240104

- packages/gitea/build.sh
> gitea: remove the workaround

- packages/swi-prolog/build.sh
Adds a auto update function for `swi-prolog` devel releases.
Largely written by: [erlanger](https://github.com/erlanger).
> enhance(main/swi-prolog): enable auto-updates

- x11-packages/freerdp/0001-mblen.patch
- x11-packages/freerdp/build.sh
> bump(main/freerdp): 2.11.7

- packages/webp-pixbuf-loader/build.sh
> addpkg(main/webp-pixbuf-loader): 0.2.7

- packages/nushell/build.sh
- packages/nushell/interprocess-socklen_t.diff
- packages/nushell/libmimalloc-sys-tls.diff
It fails to compile on arm/i686.
https://github.com/termux/termux-packages/actions/runs/8903503887/job/24451359307
> nushell: fix compile

- packages/perl/build.sh
> Fix undefined math symbols while building perl

- packages/lux/build.sh
> fix(main/lux): version embed

- packages/moreutils/build.sh
Couple housekeeping items in here as well.
- Updated the package homepage to the HTTPS variant
- Set a maintainer
- Tarball compression switched from Gzip to Xz in upstream
- Enabled auto updates
> bump(main/moreutils): 0.69

- x11-packages/atril/build.sh
- x11-packages/atril/gir/AtrilDocument-1.5.0.xml
- x11-packages/atril/gir/AtrilView-1.5.0.xml
Fixes #18957
In AArch64 termux and xfce4 :point_down:
> addpkg(x11/atril): 1.28.0

- packages/xmake/build.sh
```
$ xmake f --menu
error: ncurses not found, please install it first.
```
> xmake: support `xmake f --menu`

- packages/python-pip/build.sh
- scripts/updates/utils/termux_pkg_upgrade_version.sh
> chore(main/python-pip): do not recognize beta releases as stable

- packages/libarrow-cpp/build.sh
- packages/libarrow-cpp/cpp-src-arrow-util-io_util.cc.patch
- packages/python-pyarrow/build.sh
- packages/python-pyarrow/python-CMakeLists.txt.patch
> bump(main/python-pyarrow): 16.0.0

- packages/libsoldout/build.sh
> fix(main/libsoldout): drop libsoldout.so.1.gz

- x11-packages/mate-menus/build.sh
- x11-packages/mate-menus/gir/MateMenu-2.0.xml
Enable gobject instrospection data
> bump(x11/mate-menus): 1.28.0

- packages/zk/build.sh
> addpkg(main/zk): A plain text note-taking assistant

- packages/texinfo/build.sh
- packages/texinfo/update-info-dir.subpackage.sh
> fixup(main/texinfo): include files properly

- packages/libgrpc/build.sh
> libgrpc: fix auto updates

- packages/python-grpcio/build.sh
- packages/python-grpcio/setup.py.patch
> bump(main/python-grpcio): 1.63.0

- x11-packages/python-torch/build.sh
> revbump(x11/python-torch): abseil-cpp update

- packages/starship/0001-Cargo.toml.patch
- packages/starship/build.sh
> starship: bump to 1.19.0

- x11-packages/eww/build.sh
- x11-packages/eww/x11rb-protocol-path.diff
- x11-packages/eww/zbus-path.diff
> eww: fix hardcoded paths

- packages/sabnzbd/build.sh
> sabnzbd: skip sabctools

- packages/libgrpc/build.sh
- packages/libgrpc/src-core-lib-gpr-tmpfile_posix.cc.patch
> bump(main/libgrpc): 1.64.0

- packages/et/build.sh
> revbump(main/et): abseil-cpp update

- packages/pipewire/build.sh
- packages/pipewire/pthread_cancel.patch
> bump(main/pipewire): 1.1.81

- packages/pacman/build.sh
- packages/pacman/check.c.patch
fix https://github.com/termux-pacman/pacman-for-termux/issues/23
> main/pacman: packages checking fix

- x11-packages/firefox/0013-fix-rust-compile.patch
- x11-packages/firefox/build.sh
> firefox: bump to 126.0

- packages/matplotlib/build.sh
- packages/matplotlib/mplsetup.cfg.patch
> matplotlib: bump to 3.9.0

- packages/lgogdownloader/build.sh
> bump(main/lgogdownloader): 3.13

- packages/starship/build.sh
- packages/taplo/build.sh
TOML LSP and toolkit.
Todo list:
> addpkg(main/taplo): 0.9.1

- x11-packages/alacritty/0001-disable-clipboard.patch
- x11-packages/alacritty/build.sh
- x11-packages/alacritty/expat-sys.diff
- x11-packages/alacritty/freetype-sys.diff
- x11-packages/alacritty/glutin-treat-android-as-linux.diff
- x11-packages/alacritty/patch-root-Cargo.diff
- x11-packages/alacritty/rustix.diff
- x11-packages/alacritty/servo-fontconfig-sys.diff
- x11-packages/alacritty/winit-treat-android-as-linux.diff
- x11-packages/alacritty/x11rb-protocol.diff
closes #10148
Doesn't build yet, but I'm done working on it for now.
If anyone else wants to take a look,
the `android-activity` crate is causing the build failure.
And I'm not sure how to resolve it.
> addpkg(x11/alacritty): 0.13.2

- packages/mdbook-katex/build.sh
> bump(main/mdbook-katex): 0.9.0

- packages/boinc/build.sh
- packages/rust-analyzer/build.sh
- packages/spirv-headers/build.sh
- packages/spirv-tools/build.sh
- packages/vulkan-extension-layer/build.sh
- packages/vulkan-validation-layers/build.sh
- packages/yarn/build.sh
> bump(main/yarn): 1.22.22, chore(main): auto update use sort -V

- x11-packages/qt6-qtcharts/build.sh
- x11-packages/qt6-qtcharts/qt6-qtcharts-cross-tools.subpackage.sh
- x11-packages/qt6-qtdeclarative/build.sh
- x11-packages/qt6-qtdeclarative/qt6-qtdeclarative-cross-tools.subpackage.sh
- x11-packages/qt6-qtimageformats/build.sh
- x11-packages/qt6-qtimageformats/qt6-qtimageformats-cross-tools.subpackage.sh
- x11-packages/qt6-qtlanguageserver/build.sh
- x11-packages/qt6-qtlanguageserver/qt6-qtlanguageserver-cross-tools.subpackage.sh
- x11-packages/qt6-qttools/build.sh
- x11-packages/qt6-qttools/qt6-qttools-cross-tools.subpackage.sh
- x11-packages/qt6-qttranslations/build.sh
- x11-packages/qt6-qttranslations/qt6-qttranslations-cross-tools.subpackage.sh
> addpkg(x11/qt6-qtdeclarative): 6.7.1

- packages/weechat/build.sh
- packages/weechat/no-setuid.patch
- packages/weechat/src-core-core-config.c.patch
- packages/weechat/src-core-core-url.c.patch
- packages/weechat/src-core-hook-hook-url.c.patch
- packages/weechat/src-core-hook-hook-url.h.patch
https://github.com/weechat/weechat/blob/5cff9c0e46ad1d75c281fc17f4a2f8a978b053ea/UPGRADING.md?plain=1#L1557
https://github.com/weechat/weechat/commit/c588ee21bc8fd33678893d5c67616033281032e3
Close #20329
> bump(main/weechat): 4.3.0

- packages/coinor-cbc/build.sh
- packages/libcoinor-cgl/build.sh
> Add Coinor CBC and CGL 

- packages/ncspot/build.sh
- x11-packages/ncspot-mpris/build.sh
> ncspot{,-mpris}: bump to 1.1.1

- packages/openjdk-17/build.sh
- packages/openjdk-17/openjdk-17-x.subpackage.sh
> fix(main/openjdk-17): fix dependencies

- packages/librav1e/build.sh
Fix #20100 
Reproduce issue using `./scripts/run-docker.sh ./build-package.sh zlib librav1e`. Irrelevant to `glib` issue.
> fix(main/librav1e): zlib build conflict

- x11-packages/mogan/build.sh
> bump(x11/mogan): 1.2.5.5

- x11-packages/qt6-qtdeclarative/build.sh
> enhance(x11/qt6-qtdeclarative): Build all tools same as host cross tools packages

- packages/libmediainfo/build.sh
- packages/mediainfo/build.sh
> libmediainfo,mediainfo: remove termux_pkg_auto_update introduced by #19852

- x11-packages/qt6-qttools/build.sh
> enhance(x11/qt6-qttools): Build all tools same as host cross tools packages

- packages/ta-lib/LICENSE.patch
- packages/ta-lib/build.sh
Using the version and source used in AUR and YACP. 
I am not sure if it is safe repo or not, please, feel free to close this PR if it is not safe.
> bump(main/ta-lib): 0.5.0

- x11-packages/schismtracker/build.sh
> bump(x11/schismtracker): 20240523

- packages/neocmakelsp/build.sh
> addpkg(main/neocmakelsp): 0.7.1

- packages/ccache/build.sh
See https://github.com/ccache/ccache/blob/v4.10/doc/INSTALL.md
Close #20357
> bump(main/ccache): 4.10

- packages/ugrep/build.sh
- packages/ugrep/configure.ac.patch
> bump(main/ugrep): 6.1.0

- packages/lit/build.sh
- packages/luvi/build.sh
- packages/luvi/fix-lua-openssl-src.patch
- packages/luvi/luajit-c-bytecode.patch
- packages/luvit/build.sh
> new package: luvi, luvit, lit

- packages/php/build.sh
- packages/php/ext-gd-config.m4.patch
> bump(main/php): 8.3.8

- packages/helm-ls/build.sh
> new package: helm-ls

- x11-packages/lyx/build.sh
> bump(x11/lyx): 2.4.0

- packages/python-scipy/build.sh
- scripts/build/setup/termux_setup_meson.sh
> python-scipy: fix `from scipy import *`

- .github/workflows/package_updates.yml
- scripts/bin/update-packages
Refactor so that only termuxbot2 can create GH issue for auto update while others dont. Also set issue template colour to console instead of bash.
> scripts(auto-update): add CREATE_ISSUE switch

- packages/artalk/build.sh
try to fix #20471
I have no idea how to run auto-update script locally to test it.
@TomJo2000 please take a look
> fix(main/artalk): add auto-update script

- packages/graphicsmagick/build.sh
> revbump(main/graphicsmagick): after libxml2 update

- packages/rust/build.sh
- packages/rust/config.toml
- scripts/setup-ubuntu.sh
> bump(main/rust): 1.79.0

- packages/micro/build.sh
> chore(main/micro): fix auto-updates [no ci]

- x11-packages/qt6-qtbase/build.sh
- x11-packages/qt6-qtbase/src-corelib-configure.cmake.patch.beforehostbuild
- x11-packages/qt6-qtbase/src-corelib-ipc-qsharedmemory_posix.cpp.patch.beforehostbuild
> qt6-qtbase: use posix ipc

- packages/libwv/build.sh
> fix(main/libwv): Switch to working src url

- packages/libllvm/build.sh
Follow-up to #20593, broken out as a separate PR not triggering a CI build.
%ci:no-build
> chore(main/libllvm): Add comment and version guard about flang sync

- packages/neovim/build.sh
- packages/neovim/neovim-fix-latest-tree-sitter-vimdoc.patch
- packages/tree-sitter-lua/build.sh
- packages/tree-sitter-query/build.sh
- packages/tree-sitter-vimdoc/build.sh
> enhance(main/neovim): Add tree sitter parsers

- packages/python-pip/build.sh
- packages/python-pip/fix-hardcoded-paths.patch
> bump(main/python-pip): 24.1

- packages/artalk/build.sh
> bump(main/artalk): 2.8.7

- x11-packages/flameshot/build.sh
> addpkg(x11/flameshot): 12.1.0

- packages/emacs/build.sh
- x11-packages/emacs-x/build.sh
Hello,
This is a proposal to update Emacs to version 29.4 (an emergency bugfix release).
Let me know if you require other updates to the modified files !
> emacs{,-x}: update to version 29.4

- packages/openjdk-17/build.sh
- packages/openjdk-17/hooks/debian/postinst
- packages/openjdk-17/hooks/debian/prerm
- packages/openjdk-17/hooks/pacman/postinst
- packages/openjdk-17/hooks/pacman/prerm
close https://github.com/termux-pacman/termux-packages/issues/86
> fix(main/openjdk-17): add working `debscripts` for pacman

- packages/libllvm/build.sh
Ref: https://github.com/termux/termux-packages/actions/runs/9669472853/job/26676054177
> libllvm: fix build

- packages/svt-av1/build.sh
> bump(main/svt-av1): 2.1.1

- packages/grafana/build.sh
Bump grafana to 11.1.0. Since this builds smoothly I thought we could also enable auto update.
> bump(main/grafana): 11.1.0

- packages/python-scipy/build.sh
> python-scipy: bump to 1.14.0

- packages/ruff/build.sh
> bump(main/ruff): 0.5.0

- packages/algernon/build.sh
- packages/algernon/fix-hardcoded-paths.patch
> bump(main/algernon): 1.17.0

- packages/openssh/build.sh
- packages/openssh/sshd.c.patch
> fix(main/openssh): requires execution with an absolute path

- packages/cargo-c/build.sh
> bump(main/cargo-c): 0.10.2

- packages/asm-lsp/build.sh
- packages/asm-lsp/memmap2.diff
> bump(main/asm-lsp): 0.7.1

- packages/sops/build.sh
- packages/sops/go-sockaddr.diff
> bump(main/sops): 3.9.0

- x11-packages/xkeyboard-config/build.sh
> bump(x11/xkeyboard-config): 2.42

- packages/openssh/build.sh
- packages/openssh/sshd.c.patch
> fix(main/openssh): Privilege separation user sshd does not exist

- packages/nodejs-lts/build.sh
- packages/nodejs-lts/node.gyp.patch
I was planning to do 22.15.0 and now there is a security release. So
let's get this in ASAP.
> bump(main/nodejs-lts): 22.15.1

- packages/alist/build.sh
- scripts/bin/update-checksum
- x11-packages/opencv/build.sh
- x11-packages/virglrenderer-android/build.sh
> scripts(bin/update-checksum): support for array SHA-256

- x11-packages/kf6-kwindowsystem/build.sh
- x11-packages/kf6-kwindowsystem/src-platforms-wayland-shm.cpp.patch
> bump(x11/kf6-kwindowsystem): 6.4.0

- packages/neocmakelsp/build.sh
> bump(main/neocmakelsp): 0.7.8

- x11-packages/freerdp/build.sh
See https://gitlab.freedesktop.org/wayland/weston/-/blob/main/libweston/backend-rdp/meson.build#L7
Close #20777
> fix(x11/freerdp): Fixed freerdp version below 3

- packages/nerdfix/build.sh
> bump(main/nerdfix): 0.4.1

- packages/apache-orc/build.sh
- packages/libarrow-cpp/build.sh
> bump(main/libarrow-cpp): 16.1.0

- packages/aapt/build.sh
- packages/googletest/build.sh
> bump(main/googletest): 1.15.0

- packages/snowflake/build.sh
- packages/snowflake/snowflake-client.subpackage.sh
- packages/snowflake/snowflake-proxy.subpackage.sh
Close #20527 .
Can anyone test if it works properly?
> addpkg(main/snowflake): Pluggable Transport using WebRTC

- packages/borgbackup/build.sh
- packages/borgbackup/use-distutils.patch
Just rewriting the patch and bumping msgpack.
> Checklist
> - [x] Builds on CI
> - [x] Tested on device (Android 13, Aarch64, Fairphone 5)
also set a maintainer
> bump(main/borgbackup): 1.4.0

- packages/ffmpeg/build.sh
This started from discussion in Discord https://discord.com/channels/641256914684084234/641256914684084237/1263900347152470107
> enhance(main/ffmpeg): enable vmaf filter via libvmaf

- x11-packages/arc-gtk-theme/build.sh
> new package: arc-gtk-theme

- x11-packages/tuxpaint/Makefile.patch
- x11-packages/tuxpaint/build.sh
> bump(x11/tuxpaint): 0.9.33

- CODEOWNERS
- packages/helix/build.sh
> chore(main/helix): update maintainer and suggest fields

- packages/vulkan-validation-layers/build.sh
> bump(main/vulkan-validation-layers): 1.3.290

- packages/logo-ls/build.sh
Update logo-ls to latest commit
Update build command to reflect changes to project structure
> bump(main/logo-ls): 2024.07.17

- packages/tinygo/GNUmakefile.patch.beforehostbuild
- packages/tinygo/build.sh
> bump(main/tinygo): 0.32.0

- packages/emscripten/build.sh
- packages/emscripten/postinst.sh
- packages/emscripten/postrm.sh
- packages/emscripten/tests.sh
Part of #20533
Fix  https://github.com/termux/termux-packages/issues/20927#issuecomment-2242296763
> chore(main/emscripten): clean up

- scripts/setup-ubuntu.sh
Fix "lld : Depends: lld-19 (>= 19~) but it is not installable"
And simplify sudo condition
> scripts(setup-ubuntu): remove reference to llvm-toolchain-jammy

- packages/megacmd/build.sh
> megacmd: add libicu to deps

- CODEOWNERS
- packages/starship/0001-Cargo.toml.patch
- packages/starship/build.sh
- set maintainer
- add elvish completions
- clean up build script
> PR Checklist:
> - [x] builds locally
> - [x] builds on CI
> - [x] tested on device (Aarch64, Android 14, Fairphone 5)
> bump(main/starship): 1.20.1

- packages/mg/build.sh
meson fails with git describe command.
Fixes #20981
> bump(main/mg): 20240709

- packages/icecast/build.sh
> fix(main/icecast): explicitly include `libxml2`

- packages/aapt/build.sh
- packages/googletest/build.sh
> bump(main/googletest): 1.15.2

- packages/lexter/build.sh
> chore(main/lexter): update URL

- x11-packages/qt6ct/CMakeLists.txt.patch
- x11-packages/qt6ct/build.sh
- x11-packages/qt6ct/src-qt6ct-common-qt6ct.cpp.patch
> addpkg(x11/qt6ct): 0.9

- packages/yazi/0001-fix-android-building-error-caused-by-trash-crate-139.patch
- packages/yazi/build.sh
> bump(main/yazi): 0.3.0

- packages/pueue/build.sh
- packages/pueue/patches.patch
Closes #8599.
I tested the binaries that were built.
> addpkg(main/pueue): a command-line task management tool

- packages/yazi/build.sh
and ship nushell and elvish completions
fixes #21054
> enhance(main/yazi): Include `ya` CLI/IPC utility

- packages/poac/build.sh
> bump(main/poac): 0.10.0

- packages/ndk-sysroot/build.sh
> ndk-sysroot: remove `vk_video`

- packages/geth/build.sh
- packages/geth/geth-utils.subpackage.sh
> bump(main/geth): 1.14.8

- root-packages/fio/Makefile.patch
- root-packages/fio/build.sh
- root-packages/fio/configure.patch
- root-packages/fio/fix-hardcoded-path.patch
> addpkg(root/fio): Flexible I/O Tester

- clean.sh
- scripts/build/termux_step_setup_cgct_environment.sh
- scripts/build/termux_step_setup_variables.sh
- scripts/build/toolchain/termux_setup_toolchain_gnu.sh
- scripts/properties.sh
These changes are intended to make it easier to customize the compilation of glibc-based packages for other applications.
> scripts: improving work with cgct

- packages/weechat/build.sh
- packages/weechat/src-core-core-crypto.c.patch
> bump(main/weechat): 4.3.6

- packages/apt/0012-ndk-r27.patch
- packages/apt/build.sh
> apt: fix build on ndk r27

- packages/libucontext/build.sh
- root-packages/fio/build.sh
> fix(main/libucontext, root/fio): auto update

- scripts/bin/update-checksum
Also rename update-sha256 to update-checksum
> enhance(scripts/update-checksum): show URL download

- packages/pypy/0010-do-not-try-to-get-L2-cache-on-Android.patch
- packages/pypy/build.sh
> pypy: bump to 7.3.16

- packages/pup/build.sh
> pup: revbump to rebuild

- packages/v2ray/build.sh
> v2ray: fix auto-update

- packages/groonga/build.sh
- packages/groonga/cmake-FindGroongalz4.cmake.patch
- packages/groonga/lib-grn.h.patch
- packages/groonga/vendor-CMakeLists.txt.patch
- packages/onigmo/build.sh
- packages/pgroonga/build.sh
> Add pgroonga and dependencies

- packages/viddy/build.sh
Close #21206 .
https://github.com/sachaos/viddy?tab=readme-ov-file#viddy-v100-rc-is-available
> upgpkg(main/viddy): 1.0.0

- packages/mariadb/build.sh
> chore(main/mariadb): remove test files

- packages/micro/build.sh
> fix(main/micro): fix -version printing dev version

- packages/php/build.sh
- packages/php/php-gd.subpackage.sh
- packages/php/php-ldap.subpackage.sh
- packages/php/php-pgsql.subpackage.sh
- packages/php/php-sodium.subpackage.sh
> fix(main/php): Add config file for loading extensions

- packages/pypy/0005-fix-unavailable-functions.patch
- packages/pypy/build.sh
> pypy: bump to 7.3.17

- x11-packages/browsh/build.sh
Closes #16661 
I added it about 4 months ago in TUR. This tool may be useful for users that are searching for Text Browser.
> new package: browsh

- packages/vulkan-tools/build.sh
> bump(main/vulkan-tools): 1.3.295

- packages/python-onnxruntime/0001-use-system-abseil.patch
- packages/python-onnxruntime/0002-use-system-protobuf.patch
- packages/python-onnxruntime/build.sh
> new package: python-onnxruntime

- packages/v2ray/build.sh
> v2ray: fix auto-build

- root-packages/gptfdisk/build.sh
> gptfdisk: adjust dependencies

- scripts/build/termux_download.sh
Also set minimum download speed threshold
Close #20036
> scripts(termux_download): handle fail download midway and retry

- packages/v2ray/0001-fix-config-paths.patch
- packages/v2ray/build.sh
> v2ray: bump to 5.17.1

- packages/jpegoptim/build.sh
- packages/jpegoptim/disable-fdsan.patch
> fix(main/jpegoptim): Disable fdsan to fix running with multiple threads

- packages/plantuml/build.sh
> bump(main/plantuml): 1.2024.7

- packages/wasi-libc/build.sh
> bump(main/wasi-libc): 24

- packages/croc/build.sh
> bump(main/croc): 10.0.12

- packages/seanime/build.sh
closes: https://github.com/termux/termux-packages/issues/21331
> addpkg(main/seanime): 2.1.1

- packages/ipfs/build.sh
> bump(main/ipfs): 0.30.0

- packages/zstd/build-cmake-contrib-CMakeLists.txt.patch
- packages/zstd/build-meson-contrib-meson.build.patch
- packages/zstd/build.sh
Need .cmake files to find zstd in libtiledb
https://github.com/TileDB-Inc/TileDB/blob/2.26.0/cmake/Modules/FindZstd.cmake
> chore(main/zstd): Use CMake to build

- packages/libunibilium/build.sh
> bump(main/libunibilium): 2.1.2

- packages/tinygo/GNUmakefile.patch
- packages/tinygo/build.sh
> bump(main/tinygo): 0.33.0

- packages/z3/build.sh
> revbump(main/z3): fix build with NDK r27

- packages/util-linux/build.sh
- packages/util-linux/configure.patch
> fix(main/util-linux): Add back col

- x11-packages/thunderbird/0023-check-if-dlpi_name-is-nullptr-before-using.patch
- x11-packages/thunderbird/0024-configure-no-pack-relative-relocs.patch
- x11-packages/thunderbird/build.sh
> thunderbird: no pack-relative-relocs

- packages/ccache/build.sh
> revbump(main/ccache): After fmt 11 update

- packages/wasmedge/build.sh
> bump(main/wasmedge): 0.14.1

- packages/manim/build.sh
The latest version crashes on build
> bump(main/manim): downgrade av python package

- packages/vulkan-tools/build.sh
> bump(main/vulkan-tools): 1.3.296

- x11-packages/kitty/build.sh
- x11-packages/kitty/kitty-safe-wrappers.h.patch
- x11-packages/kitty/kitty-systemd.c.patch
- x11-packages/kitty/setup.py.patch
Depends on #21594, the `simde` package being added.
> bump(x11/kitty): 0.36.4

- packages/mono/build.sh
Upstream will be changing soon, refer https://github.com/mono/mono/issues/21796
%ci:no-build
> chore(main/mono): disable auto update

- packages/libtorrent/build.sh
> bump(main/libtorrent): 0.14.0

- packages/rtorrent/build.sh
> bump(main/rtorrent): 0.10.0

- packages/grafana/build.sh
> fix(main/grafana): Build with go 1.22 for now

- packages/neovim/build.sh
- packages/neovim/src-nvim-po-CMakeLists.txt.patch
> bump(main/neovim): 0.10.2

- packages/typst/build.sh
> chore(main/typst): do not update to release candidates

- packages/alist/build.sh
> alist: fix auto-update

- packages/vulkan-validation-layers/build.sh
> bump(main/vulkan-validation-layers): 1.3.297

- x11-packages/qt6-qtdeclarative/build.sh
> fix(x11/qt6-qtdeclarative): Add -flto to LDFLAGS

- x11-packages/firefox/build.sh
It builds fine on my local build container.
Not sure what cause the auto update build to fail.
closes #21741
> bump(x11/firefox): 131.0.2

- packages/vulkan-tools/build.sh
- scripts/build/setup/termux_setup_pkg_config_wrapper.sh
Caused by line swap in https://github.com/termux/termux-packages/commit/a338cd8a4f366a0eb4090ac3db915ef6d170527d
fixes #21777
@twaik does this look correct to you?
> fix accidental infinite recursion in `termux_setup_wayland_cross_pkg_config_wrapper`

- packages/vulkan-tools/build.sh
> bump(main/vulkan-tools): 1.3.298

- x11-packages/thunderbird/build.sh
Also cleanup Shellcheck's complaints.
> enhance(x11/thunderbird): enable updates to latest ESR release

- scripts/build/setup/termux_setup_xmake.sh
- x11-packages/mogan/build.sh
- x11-packages/mogan/qmake.sh
- x11-packages/mogan/xmake-beamer.lua.patch
- x11-packages/mogan/xmake-code.lua.patch
- x11-packages/mogan/xmake-draw.lua.patch
- x11-packages/mogan/xmake-packages-l-lolly.patch
- x11-packages/mogan/xmake-packages-s-s7.patch
- x11-packages/mogan/xmake-packages.lua.patch
> bump(x11/mogan): 1.2.9.5

- x11-packages/kvantum/build.sh
Moves kvantum to Qt6.
Fixes #19503
> bump(x11/kvantum): 1.1.2

- packages/sftpgo/0001-conf.patch
- packages/sftpgo/build.sh
> new package: sftpgo

- packages/nginx/build.sh
- packages/nginx/src-os-unix-ngx_setaffinity.h.patch
> nginx: enable http_v3 module

- packages/bionic-host/build.sh
> chore(main/bionic-host): fix downloading ubuntu packages, disable undefined symbols checking, disable `repo` SHA256 verification

- packages/ipfs/build.sh
- packages/ipfs/cmd-ipfs-Rules.mk.patch
> bump(main/ipfs): 0.31.0

- packages/bionic-host/build.sh
Follow up to #21825.
See also: https://github.com/termux/termux-packages/issues/21130#issuecomment-2419213816
CC: @twaik
> fix(main/bionic-host): fix build issues for local builds

- packages/dropbear/Makefile.in.patch
- packages/dropbear/build.sh
- packages/dropbear/common-session.c.patch
- packages/dropbear/compat.c.patch
- packages/dropbear/default_options.h.patch
- packages/dropbear/gensignkey.c.patch
- packages/dropbear/loginrec.c.patch
- packages/dropbear/sshpty.c.patch
- packages/dropbear/svr-agentfwd.c.patch
- packages/dropbear/svr-auth.c.patch
- packages/dropbear/svr-authpasswd.c.patch
- packages/dropbear/svr-chansession.c.patch
- packages/dropbear/svr-session.patch
- packages/dropbear/sysoptions.h.patch
I can start server and connect it from my PC, scp from PC to device also works.
I will merge it on Sunday if no one minds.
> bump(main/dropbear): 2024.85

- x11-packages/gtk2/build.sh
Fixes #20247
I'll merge it in 12 hours if nobody minds.
> fix(x11/gtk2): enable xi to let gimp enumerate input devices

- x11-packages/mousepad/build.sh
> enhance(x11/mousepad): Enable gspell plugin for spell checking

- packages/wireproxy/0001-drop-sandbox.patch
- packages/wireproxy/build.sh
> new package: wireproxy

- x11-packages/xwallpaper/build.sh
> addpkg(x11/xwallpaper): 0.7.5

- x11-packages/tuxpaint/build.sh
Fixes #21890
I will merge it in 72 hours if no one minds.
Or anyone else can merge it earlier.
> fix(x11/tuxpaint): add missing desktop entry

- x11-packages/xpdf/build.sh
> chore(x11/xpdf): Switch to Qt6

- packages/ncurses/build.sh
There's 3 main parts to this PR.
- 1.) Drop `termite`'s terminfo.
The `termite` project has been [archived for close to 3 and a half years](https://github.com/thestinger/termite).
We can probably stop shipping a terminfo file for it.
- 1.1) We *do* probably wanna start shipping terminfo files for `foot`, since we have it packaged and it is in very active development.
- 2.) Make "version realignment" for `alacritty`, `foot` and `kitty` easier.
Currently keeping version and checksum for these synced between their build scripts and `ncurses` is a pain in the ass.
Since what we need from them is the `TERMUX_PKG_{VERSION,SRCURL,SHA256}` values, let's just grab them from the respective build script.
This way they can also be "safely" auto-updated, without creating additional work to "realign" …
> enhance(main/ncurses): drop `termite`, add `foot` terminfo

- packages/xmlto/build.sh
Now it actually works on my phone
> fix(main/xmlto): Don't hardcode build-machine paths to tools

- packages/vulkan-extension-layer/build.sh
> bump(main/vulkan-extension-layer): 1.3.299

- x11-packages/filelight/build.sh
- x11-packages/kf6-kirigami-addons/build.sh
> addpkg(x11/filelight): 24.08.2

- packages/ncspot/build.sh
- x11-packages/ncspot-mpris/build.sh
Fixes #21827, fixes #21826
Not perfect, but works, will be glad to fix it after review.
Will be merged in 72 hours if nobody minds or when it gets 2+ approves.
> bump({main,x11}/ncspot{,-mpris}): 1.2.0

- packages/python-tflite-runtime/0001-no-android-log.patch
- packages/python-tflite-runtime/0002-include-neon2sse-for-xnnpack.patch
- packages/python-tflite-runtime/build.sh
> new package: python-tflite-runtime

- packages/await/build.sh
> bump(main/await): 1.0.7

- packages/libpluto/build.sh
- packages/libpluto/src-vendor-Soup-build_lib.php.patch
> bump(main/libpluto): 0.10.0

- scripts/updates/api/dump-repology-data
Fixes #22023
I will merge this in 12 hours if nobody minds or after it gets 2+ approves.
> scripts(dump-repology-metadata): fix API usage

- x11-packages/obconf-qt/build.sh
> bump(x11/obconf-qt): 0.16.5

- packages/util-linux/build.sh
> fix(main/util-linux): disable syscall statx

- packages/mariadb/build.sh
> fix(main/mariadb): Move vendored groonga docs to resolve file conflict with groonga

- packages/ncmpcpp/build.sh
- packages/ncmpcpp/settings.cpp.patch
On-device test was fine.
I will merge this in 72 hours if nobody minds or after it gets 2+ approves.
> bump(main/ncmpcpp): 0.10.1

- x11-packages/lxqt-qtplugin/build.sh
- x11-packages/lxqt-qtplugin/src-CMakeLists.txt.patch
> bump(x11/lxqt-qtplugin): 2.1.0

- x11-packages/lxqt-panel/autostart-CMakeLists.txt.patch
- x11-packages/lxqt-panel/build.sh
- x11-packages/lxqt-panel/panel-backends-wayland-wlroots-lxqttaskbarwlrwm.cpp.patch
> bump(x11/lxqt-panel): 2.1.0

- packages/fzf/bin-fzf-tmux.patch
- packages/fzf/build.sh
Closes #22136
I'll merge this after 72 hours if there is no more review.
> fzf: move tmux to suggests

- x11-packages/the-powder-toy/03-saves-dir-path.patch
- x11-packages/the-powder-toy/build.sh
This update adds missing desktop icon and allows users to save their progress in folders other than default one.
I will merge it in 72 houts if no objections or after it gets 2+ approves.
> bump(x11/the-powder-toy): 98.2.365

- packages/nala/build.sh
> enhance(main/nala): Add manpages and shell completions

- packages/libwayland/build.sh
- packages/libwayland/src-wayland-util.h.patch
* Fixes #22233 
* Fixes #22234
> fix(main/libwayland): Fix compiler error when STDC_VERSION is undefined

- packages/arturo/build.sh
- packages/libpluto/build.sh
- packages/luvi/build.sh
Update outdated maintainer's name.
> fix(main/{arturo,libpluto,luvi}): update maintainer's name

- packages/snowflake/build.sh
> snowflake: bump to 2.10.1

- packages/v2ray/0001-fix-config-paths.diff
- packages/v2ray/build.sh
> v2ray: bump to 5.22.0

- x11-packages/fcitx5-chinese-addons/build.sh
- x11-packages/libime/build.sh
> addpkg(x11/libime): 1.1.9

- packages/ffmpeg/build.sh
- packages/libvpx/abi-test.c
- packages/libvpx/build.sh
> libvpx: add ABI version check

- packages/mediamtx/build.sh
- packages/mediamtx/internal-core-core.go.patch
> addpkg(main/mediamtx): 1.9.3

- packages/swtpm/build.sh
- packages/swtpm/src-swtpm_setup-swtpm.c.patch
Remove unnecessary installed tests explicitly.
* Fixes #22273
> bump(main/swtpm): 0.10.0

- packages/rabbitmq-server/build.sh
Fulfills package request #10273 and seems to pass the criteria in the package request template
> Added rabbitmq-server package

- x11-packages/foot/0002-fix-hardcoded-paths.patch
- x11-packages/foot/build.sh
- x11-packages/foot/doc-meson.build.patch
> fix(x11/foot): Fix terminfo file conflict with ncurses

- packages/luvi/0002-disable-luajit-version-check.patch
- packages/luvi/0003-enable-shared-lpeg.patch
- packages/luvi/build.sh
Bump to fixed version, use shared lpeg, enable zlib, and fix luajit version symbol.
> fix,enhance,bump(main/luvi): bump to fixed version 2.15.0

- packages/libicu/build.sh
- packages/libicu/source-Makefile.in.patch
- x11-packages/firefox/0013-fix-rust-compile.patch
- x11-packages/firefox/0028-webextensions.storage.sync.kinto-true.patch
- x11-packages/firefox/build.sh
> libicu: revbump revdeps (9)

- packages/n-t-roff-sc/Makefile.patch
- packages/n-t-roff-sc/build.sh
> bump(main/n-t-roff-sc): 7.16-1.1.3

- packages/zsh/build.sh
This PR adopts Arch Linux's cherry-picks from upstream Zsh to update the `zsh/pcre` module to use `pcre2` instead of the now deprecated `pcre`[^1].
This change is already present in the upstream project's master branch, and is slated for inclusion in the 5.10 release of Zsh.
<sub>Which will presumably happen sometime prior to the heat death of the universe.</sub>
This PR also contains:
- Switching the source URL for Zsh to the official Zsh FTP site.
- Creating a symlink for `zsh-$version` in place of the `zsh-$version` hardlink provided by other packagings of Zsh
- And some minor build script cleanup.
[^1]: https://gitlab.archlinux.org/archlinux/packaging/packages/zsh/-/blob/main/0004-pcre2.patch
> enhance(main/zsh): Cherry-pick PCRE2 support for `zsh/pcre` module

- packages/enchant/build.sh
> chore(main/enchant): change upstream URL

- x11-packages/lite-xl/build.sh
- x11-packages/lite-xl/meson.build.patch
> bump(x11/lite-xl): 2.1.6

- packages/rust/build.sh
- packages/rust/config.toml
- scripts/setup-ubuntu.sh
> bump(main/rust): 1.83.0, host bump to LLVM 18

- packages/libpoco/build.sh
> bump(main/libpoco): 1.14.0

- packages/moar/build.sh
> addpkg(main/moar): 1.30.0

- packages/mbedtls/build.sh
- root-packages/pciutils/build.sh
%ci:no-build
Based on discussion https://github.com/termux/termux-packages/pull/21078#discussion_r1864922077
> chore(main,root): prefer '@U' over '^^'

- packages/taplo/build.sh
closes #22470
This is the same approach used for `ncdu`/`ncdu2` and `vim`/`vim-gtk`.
> chore(main/taplo): use a `ncdu`-style auto update function

- packages/rust/build.sh
> fix(main/rust): set and check RUNPATH

- packages/unshield/build.sh
Closes https://www.reddit.com/r/termux/comments/1h95k9l/
> unshield: link against openssl 3.x

- packages/pv/build.sh
> bump(main/pv): 1.9.15

- .github/workflows/packages.yml
Also move setting environment variables from run into env
Fixes https://github.com/termux/termux-packages/pull/22453#issuecomment-2520200478
> ci(packages): move upload-test to its own step

- scripts/setup-ubuntu.sh
- x11-packages/labwc/0001-fix-path.patch
- x11-packages/labwc/0002-fix-build.patch
- x11-packages/labwc/build.sh
- x11-packages/wlroots/0004-impl-termux-gui-backend.patch
- x11-packages/wlroots/build.sh
- x11-packages/wlroots/src/backend/termuxgui/allocator.c
- x11-packages/wlroots/src/backend/termuxgui/backend.c
- x11-packages/wlroots/src/backend/termuxgui/input.c
- x11-packages/wlroots/src/backend/termuxgui/meson.build
- x11-packages/wlroots/src/backend/termuxgui/output.c
- x11-packages/wlroots/src/include/backend/termuxgui.h
- x11-packages/wlroots/src/include/wlr/backend/termuxgui.h
Write a new backend for wlroots, which has basic display and keyboard and mouse input based on termux-gui. The vulkan renderer works on the freedreno turnip driver.
> Draft: new package: labwc

- x11-packages/firefox/0008-fix-marcos.patch
- x11-packages/firefox/0009-impl-posix-shmem.patch
- x11-packages/firefox/build.sh
> firefox: bump to 133.0

- packages/fselect/build.sh
- packages/fselect/libmimalloc-sys-tls.diff
> bump(main/fselect): 0.8.7

- x11-packages/firefox/build.sh
> bump(x11/firefox): 133.0.3

- packages/wasi-libc/build.sh
> bump(main/wasi-libc): 25

- packages/mono/build.sh
Switch upstream to gitlab.winehq.org/mono/mono
> bump(main/mono): 6.12.0.206

- packages/postgis/build.sh
> bump(main/postgis): 3.5.1

- x11-packages/xfce4-docklike-plugin/build.sh
- x11-packages/xfce4-docklike-plugin/src-Hotkeys.cpp.patch
> bump(x11/xfce4-docklike-plugin): 0.4.3

- packages/libjanet/Makefile.patch.beforehostbuild
- packages/libjanet/build.sh
- packages/libjanet/janet.subpackage.sh
> newpkg(main/janet): 1.37.1

- packages/tree-sitter/build.sh
> enhance(main/tree-sitter): ship shell completions

- packages/rbw/build.sh
Add --no-default-features option to disable clipboard. Otherwise, build failed with error.
https://github.com/doy/rbw/commit/5814122bc74770ea7ec50e0e0a32bd24c83ccd7b
* Fixes #22695
> bump(main/rbw): 1.13.1

- packages/ldc/build.sh
- packages/ldc/iwyu-cstdint.patch.beforehostbuild
> ldc: set `RUNPATH` rather than `RPATH`

- packages/php/build.sh
- packages/php/ext-pgsql-config.m4.patch
> fix(main/php): Fix pcre2 linking with php-pgsql extension

- packages/pueue/build.sh
- packages/pueue/patches.patch
> bump(main/pueue): 4.0.0-rc.1

- packages/weechat/build.sh
> bump(main/weechat): 4.5.1

- packages/nwipe/build.sh
- packages/nwipe/fix-hardcoded-paths.patch
> bump(main/nwipe): 0.38

- packages/weechat/build.sh
> fix(main/weechat): libdl.a is a stub --- use libdl.so instead

- packages/mediamtx/build.sh
Fix the following build error.
link: github.com/wlynxg/anet: invalid reference to net.zoneCache
* Fixes #22916
> bump(main/mediamtx): 1.11.1

- packages/vulkan-validation-layers/0004-setenv.patch
- packages/vulkan-validation-layers/build.sh
> bump(main/vulkan-validation-layers): 1.4.304

- packages/gitui/build.sh
> bump(main/gitui): 0.27.0

- packages/rsync/build.sh
> bump(main/rsync): 3.4.1

- packages/capstone/build.sh
- Implement check for non-stable versions marked as latest release by upstream.
%ci:no-build
> pkg(main/capstone): Fix auto-update

- packages/libgee/build.sh
* Enable auto update.
* Switch to new upstream source link.
> bump(main/libgee): 0.20.8

- packages/libgit2/build.sh
- **bump(main/libgit2): 1.9.0**
> bump(main/libgit2): 1.9.0

- packages/electrum/build.sh
> pkg(electrum): Add missing dependencies

- packages/scala/build.sh
> fix(main/scala): missing softlink and depends

- packages/cloudflared/0001-disable-install-service.patch
- packages/cloudflared/build.sh
> cloudflared: disable `install` command

- root-packages/authbind/Makefile.patch
- root-packages/authbind/build.sh
> bump(root/authbind): 2.2.0

- packages/sox/build.sh
> fix(main/sox): should depend on wget

- x11-packages/sdl2-compat/build.sh
- x11-packages/sdl3/build.sh
> addpkg(x11): sdl3, sdl2-compat

- packages/chezmoi/build.sh
> bump(main/chezmoi): 2.59.0

- x11-packages/hugin/build.sh
> bump(x11/hugin): 2024.0.1

- packages/libarrow-cpp/build.sh
> bump(main/libarrow-cpp): 19.0.0

- packages/libandroid-stub/build.sh
> libandroid-stub: ship `libmediandk.so`

- packages/nala/build.sh
> nala: properly install deps in `postinst`

- packages/cloudflared/build.sh
> bump(main/cloudflared): 2025.2.0

- packages/ollama/0001-cgo-flags.patch
- packages/ollama/build.sh
I'd like to move this package from TUR to main repo. It seems that the usage of this package is not low.
Closes #18902
> new package: ollama

- x11-packages/sdl2-image/build.sh
> chore(x11/sdl2-image): sdl2-compat co-exist

- x11-packages/mogan/build.sh
- x11-packages/mogan/s7.diff
- x11-packages/mogan/xmake-beamer.lua.patch
- x11-packages/mogan/xmake-code.lua.patch
- x11-packages/mogan/xmake-draw.lua.patch
- x11-packages/mogan/xmake-packages-l-lolly.patch
- x11-packages/mogan/xmake-packages-s-s7.patch
> bump(x11/mogan): 2.9.8

- packages/ffmpeg/build.sh
- packages/ffmpeg/postinst.sh.in
closes #23192
- Fixes an oversight from #23191
> fix(main/ffmpeg): fix postinst script's shebang

- packages/gopls/build.sh
> bump(main/gopls): 0.18.0

- x11-packages/putty/build.sh
> bump(x11/putty): 0.83

- packages/libduckdb/build.sh
- packages/libduckdb/tools-shell-shell.c.patch
> bump(main/libduckdb): 1.2.0

- packages/asm-lsp/build.sh
> bump(main/asm-lsp): 0.10.0

- x11-packages/texworks/build.sh
- x11-packages/texworks/src-CMakeLists.txt.patch
> bump(x11/texworks): 0.6.10

- packages/pypy/0005-fix-unavailable-functions.patch
- packages/pypy/0011-set-_FILE_OFFSET_BITS-to-64-on-arm.patch
- packages/pypy/build.sh
> pypy: bump to 7.3.18

- root-packages/runc/build.sh
- root-packages/runc/memfd.patch
Fixes https://github.com/termux/termux-packages/issues/23181. More details can be found at https://github.com/opencontainers/runc/issues/4640 and https://github.com/opencontainers/runc/pull/4641
> bug fix(root/runc): Do not use F_SEAL_FUTURE_WRITE

- packages/clvk/0001-Do-not-use-__builtin_elementwise_popcount-for-clc_po.patch.beforehostbuild
- packages/clvk/build.sh
> clvk: bump to 0.0.20250224.115625

- packages/neovim/build.sh
- packages/neovim/nvim-shim.sh
- packages/pass/build.sh
> Neovim/Pass, resolve environment variable conflict.

- packages/mtd-utils/build.sh
> bump(main/mtd-utils): 2.3.0

- packages/emscripten/build.sh
- packages/emscripten/llvm-project-clang-lib-Driver-ToolChains-Linux.cpp.diff
> emscripten: bump to 4.0.4

- packages/python-onnxruntime/0002-use-system-protobuf.patch
- packages/python-onnxruntime/0004-cmake-python-find-Development-before-Development.Module.patch
- packages/python-onnxruntime/build.sh
> python-onnxruntime: bump to 1.21.0

- x11-packages/shotcut/0001-lib-name.patch
- x11-packages/shotcut/build.sh
> bump(x11/shotcut): 25.01.25

- root-packages/zmap/build.sh
- root-packages/zmap/hostbuild.diff
- root-packages/zmap/use-yacc.patch
Starts fine on device, but I am not sure how to use it right.
> bump(root/zmap): 4.3.2

- build-package.sh
- scripts/build/setup/termux_setup_meson.sh
- scripts/build/setup/termux_setup_python_pip.sh
- scripts/build/toolchain/termux_setup_toolchain_gnu.sh
> scripts: fixing the path to the required python

- packages/imagemagick/build.sh
- document enable status for all compile options
- enable DJVu support
- enable GSlib support
- enable Graphviz support
- enable Liblqr support
- enable Libraqm support
> enhance(main/imagemagick): enable additional features

- packages/vulkan-validation-layers/0001-no-android.patch
- packages/vulkan-validation-layers/build.sh
> bump(main/vulkan-validation-layers): 1.4.310

- packages/zrok/build.sh
> bump(main/zrok): 1.0.0

- packages/megacmd/build.sh
- packages/megacmd/cryptopp-import-fix.patch
- packages/megacmd/no-android.patch
- packages/megacmd/src-megacmdcommonutils.h.patch
Fixes #23427
I'd like to merge it in 72 hours if nobody minds or after it gets 2+ approves.
> bump(main/megacmd): 2.0.0

- x11-packages/glslviewer/build.sh
- x11-packages/glslviewer/cast-getexposure-setuniform.patch
- x11-packages/glslviewer/disable-update-databases.patch
- x11-packages/glslviewer/pthread_cancel.patch
- x11-packages/glslviewer/rename-pipe-variable-to-avoid-unistd-collision.patch
- x11-packages/glslviewer/system-liblo.patch
- x11-packages/glslviewer/vera-find-glfw.patch
- Fixes https://github.com/termux/termux-packages/issues/23809
- Fixes https://github.com/patriciogonzalezvivo/glslViewer/issues/373
> addpkg(x11/glslviewer): 3.2.4

- packages/librsvg/build.sh
- packages/librsvg/gir/Rsvg-2.0.xml
- packages/librsvg/meson.build.patch
> bump(main/librsvg): 2.60.0

- packages/fontconfig/build.sh
- packages/fontconfig/fcatomic.c.patch
> bump(main/fontconfig): 2.16.1

- packages/pacman/build.sh
- packages/pacman/serverlist
> pacman: add Vietnamese mirror

- packages/imlib2/0001-link-modules-with-libImlib2.patch
- packages/imlib2/build.sh
This fixes loading images with feh, imlib2_view etc. programs.
* Fixes #23854
> fix(main/imlib2): Link modules with main imlib library

- packages/proton-bridge/build.sh
- packages/proton-bridge/disable-updater.patch
* Fixes #23909 
* Fixes #23435
> bump(main/proton-bridge): 3.18.0

- packages/dbus/build.sh
- packages/dbus/dbus-dbus-sysdeps-unix.c.patch
I am not sure about this socklen_t cast so I am not merging this without proper review.
> bump(main/dbus): 1.16.2

- root-packages/runc/build.sh
- root-packages/runc/memfd.patch
> bump(root/runc): 1.2.6

- packages/gnunet/build.sh
- packages/gnunet/no-curl-gnutls.patch
Also switching mirror https://ftpmirror.gnu.org since I get 504 Gateway timeout on upstream url.
Fixes #23886, fixes #23803.
> bump(main/gnunet): 0.24.0

- packages/vulkan-validation-layers/0001-no-android.patch
- packages/vulkan-validation-layers/build.sh
> bump(main/vulkan-validation-layers): 1.4.311

- packages/libsqlite/build.sh
> enhance(main/libsqlite): Enable fts4 and fts5 extensions

- x11-packages/lxde-icon-theme/build.sh
Move to new upstream repository.
* Fixes #23941
> bump(x11/lxde-icon-theme): 0.5.2

- packages/mesa/0011-lld-undefined-version.patch
- packages/mesa/build.sh
> mesa: bump to 25.0.2

- .github/workflows/packages.yml
- scripts/free-space.sh
- Fixed required packages being deleted:
php and ruby are required by setup-ubuntu.sh script.
- Also clear some more space
> ci(packages): Move space cleaning logic to separate script

- x11-packages/mousepad/build.sh
> bump(x11/mousepad): 0.6.4

- x11-packages/xfce4-terminal/build.sh
> bump(x11/xfce4-terminal): 1.1.5

- x11-packages/ristretto/build.sh
> bump(x11/ristretto): 0.13.4

- x11-packages/hangover-wine/9998-fix-winegcc-build-target.patch.beforehostbuild
- x11-packages/hangover-wine/build.sh
> hangover-wine: bump to 10.4

- packages/ffmpeg/build.sh
> enhance(main/ffmpeg): enable `libzmq` support

- .github/workflows/package_updates.yml
> ci(package_updates): Use external space cleaning script

- packages/php-imagick/build.sh
> chore(main/php-imagick): do not update to RC releases

- packages/taskwarrior/build.sh
> bump(main/taskwarrior): 3.4.1

- x11-packages/qt6-qttools/cmake-find-zstd-before-clang.patch.beforehostbuild
> fix(x11/qt6-qttools): Fix cmake error with zstd

- packages/e2fsprogs/build.sh
- packages/e2fsprogs/fix-libarchive-path.patch
> fix(main/e2fsprogs): enable libarchive support

- x11-packages/libcolord/0001-drop-deps-on-libudev.patch
- x11-packages/libcolord/0002-only-build-client-library.patch
- x11-packages/libcolord/build.sh
- x11-packages/libcolord/gir/Colord-1.0.xml
- x11-packages/libei/build.sh
- x11-packages/mutter/0001-fix-hardcoded-paths.patch
- x11-packages/mutter/0002-link-explicitly.patch
- x11-packages/mutter/0003-missing-guards.patch
- x11-packages/mutter/0004-fill-getrandom.patch
- x11-packages/mutter/0005-fill-memfd.patch
- x11-packages/mutter/0006-fix-anno-file.patch
- x11-packages/mutter/build.sh
- x11-packages/mutter/gir/Clutter-16.xml
- x11-packages/mutter/gir/Cogl-16.xml
- x11-packages/mutter/gir/Meta-16.xml
- x11-packages/mutter/gir/Mtk-16.xml
> new package: mutter

- build-package.sh
- packages/at-spi2-core/build.sh
- packages/gdk-pixbuf/build.sh
- packages/glib/build.sh
- packages/libcairo/build.sh
- packages/libsecret/build.sh
- packages/pango/build.sh
- scripts/build/setup/termux_setup_ldc.sh
- scripts/build/termux_step_make.sh
- x11-packages/gtk3/build.sh
- x11-packages/libvte/build.sh
- x11-packages/tilix/build.sh
- x11-packages/tilix/data-scripts-install-man-pages.sh.patch
- x11-packages/tilix/source-gx-tilix-terminal-terminal.d.patch
This PR introduces the LDC toolchain for dlang projects and adds `sideloader`, a frequently used tool to sideload apps for iOS as a reference dlang project
> addpkg(x11/tilix): 1.9.6

- packages/php-imagick/build.sh
> pkg(main/php-imagick): Fix auto-update filter regex

- scripts/build/setup/termux_setup_meson.sh
See https://mesonbuild.com/Release-notes-for-1-7-0.html
> bump(scripts/setup-meson): Update meson from 1.6.1 to 1.7.2

- scripts/build/get_source/termux_unpack_src_archive.sh
I will merge it in 12 hours if nobody minds.
> scripts(termux_unpack_src_archive): remove orphan variable

- x11-packages/xfce4-pulseaudio-plugin/build.sh
> bump(x11/xfce4-pulseaudio-plugin): 0.5.0

- packages/codon/build.sh
> Libxml2 rebuilds codon

- x11-packages/godot/build.sh
- x11-packages/godot/prepend-prefix-to-absolute-tmp-paths.patch
- Fixes https://github.com/termux/termux-packages/issues/24214
> fix(x11/godot): prepend `$TERMUX_PREFIX` to absolute `/tmp` paths

- packages/libtsduck/build.sh
- packages/libtsduck/scripts-make-config.sh.patch
- packages/libtsduck/scripts-make-config.sh.patch.beforehostbuild
- packages/libtsduck/src-libtscore-Makefile.patch
- packages/libtsduck/src-libtscore-config-tscore.pc.patch
- packages/libtsduck/src-libtscore-system-tsForkPipe.cpp.patch
- packages/libtsduck/src-libtscore-system-tsSysUtils.h.patch
- packages/libtsduck/src-libtsduck-Makefile.patch
- packages/libtsduck/src-libtsduck-config-tsduck.pc.patch
- packages/libtsduck/src-tsplugins-Makefile.patch
- packages/libtsduck/src-tstools-Makefile.patch
> bump(main/libtsduck): 3.40.4165

- packages/git-credential-manager/build.sh
- closes #10420
> [!NOTE]
> PR checklist.
> - [x] Builds in CI
> - [x] Tested on device (AArch64, Android 14, Fairphone 5)
> - [x] Links properly to libraries
> addpkg(main/git-credential-manager): 2.6.1

- packages/opentimelineio/build.sh
- x11-packages/kdenlive/build.sh
> fix(x11/kdenlive): Fix file conflicts with imath

- x11-packages/gedit/build.sh
- x11-packages/gedit/gir/Gedit-3.0.xml
> bump(x11/gedit): 48.2

- build-package.sh
- packages/gdk-pixbuf/build.sh
- packages/gdk-pixbuf/gdk-pixbuf-query-loaders.alpm.hook
- packages/glib/build.sh
- packages/glib/glib-compile-schemas.alpm.hook
- scripts/build/termux_step_install_pacman_hooks.sh
- x11-packages/desktop-file-utils/build.sh
- x11-packages/desktop-file-utils/hooks/postinst.in
- x11-packages/desktop-file-utils/hooks/postrm.in
- x11-packages/desktop-file-utils/update-desktop-database.alpm.hook
- x11-packages/gtk2/build.sh
- x11-packages/gtk2/gtk-query-immodules-2.0.alpm.hook
- x11-packages/gtk2/hooks/postrm.in
- x11-packages/gtk3/build.sh
- x11-packages/gtk3/gtk-query-immodules-3.0.alpm.hook
- x11-packages/gtk3/hooks/postrm.in
- x11-packages/shared-mime-info/build.sh
- x11-packages/shared-mime-info/postinst
- x11-packages/shared-mime-info/postrm
- x11-packages/shared-mime-info/update-mime-database.alpm.hook
- x11-packages/xorg-mkfontscale/build.sh
- x11-packages/xorg-mkfontscale/postinst
- x11-packages/xorg-mkfontscale/postrm
- x11-packages/xorg-mkfontscale/xorg-mkfontscale.alpm.hook
- x11-packages/xorg-mkfontscale/xorg-mkfontscale.alpm.script
> implementation of alpm-hooks configuration in pacman packages

- packages/emscripten/build.sh
> bump(main/emscripten): 4.0.7

- packages/dwarves/build.sh
- packages/dwarves/lib-bpf-src-linker.c.patch
> bump(main/dwarves): 1.30

- packages/timewarrior/build.sh
- packages/timewarrior/src-CMakeLists.txt.patch
> bump(main/timewarrior): 1.8.0

- x11-packages/meld/build.sh
> bump(x11/meld): 3.23.0

- packages/diffstat/build.sh
- packages/diffstat/diffstat.c.patch
> bump(main/diffstat): 1.68

- x11-packages/weston/build.sh
- x11-packages/weston/fix-neatvnc.patch
> bump(x11/weston): 14.0.2

- scripts/build/termux_step_massage.sh
This optimization is pretty much basic.
Shebang-fixer code optimization:
Instead of iterating all possible files in massage directory we explicitly search for text files having `#` symbol at the start of any line.
This optimization reduces shebang-fixing from ~1m 33s to ~80ms while building `kf6-breeze-icons` on my machine.
OpenMP symbols scanning:
Instead of iterating all possible files we explicitly search files having elf magic at the start of any line.
This optimization reduces openmp-scanning from ~6s 700 ms to ~290ms while building `kf6-breeze-icons` on my machine.
The whole time of building `kf6-breeze-icons` was reduced from ~2m 10s to ~35s.
I am pretty much sure other packages will have similar results.
CC @truboxl since you wrote the elf-openmp-scanning code.
> chore: massaging step optimization

- packages/spidermonkey/0001-configure-treat-termux-as-linux.patch
- packages/spidermonkey/0002-configure-fix-arm-options.patch
- packages/spidermonkey/0003-configure-fix-rustflags.patch
- packages/spidermonkey/0004-configure-do-not-check-libstdcxx-headers.patch
- packages/spidermonkey/0005-configure-do-not-append-sysroot.patch
- packages/spidermonkey/0006-configure-do-not-enable-alsa.patch
- packages/spidermonkey/0008-fix-marcos.patch
- packages/spidermonkey/0009-impl-posix-shmem.patch
- packages/spidermonkey/0010-do-not-check-time_t-for-system-libevent.patch
- packages/spidermonkey/0011-use-UnderrunHandlerNoop.patch
- packages/spidermonkey/0012-do-not-use-adaptive-mutex.patch
- packages/spidermonkey/0013-fix-rust-compile.patch
- packages/spidermonkey/0014-unset-thread-priority-scheduling-macro.patch
- packages/spidermonkey/0015-skia-termux.patch
- packages/spidermonkey/0016-protobuf-no-android-log.patch
- packages/spidermonkey/0017-icu-74.patch
- packages/spidermonkey/0018-fix-include-dir-for-cpufeatures.patch
- packages/spidermonkey/0019-fix-sigbus.patch
- packages/spidermonkey/0020-do-not-call-get-pci-status.patch
- packages/spidermonkey/0021-fix-missing-include-for-zlib-module.patch
- packages/spidermonkey/0022-configure-no-pack-relative-relocs.patch
- packages/spidermonkey/0023-check-if-dlpi_name-is-nullptr-before-using.patch
- packages/spidermonkey/0024-fix-missing-include-for-macro-MOZ_TRY-in-TimeZone.cpp.patch
- packages/spidermonkey/0025-disable-native-https-dns-resolve.patch
- packages/spidermonkey/0026-partially-disable-unified-builds.patch
- packages/spidermonkey/build.sh
- packages/spidermonkey/mozconfig.cfg
This is the dependency of `gjs` (GNOME JavaScript Bindings).
Closes #18495
> new package: spidermonkey

- x11-packages/fcitx5-chinese-addons/build.sh
- x11-packages/fcitx5-chinese-addons/im-pinyin-CMakeLists.txt.diff
- x11-packages/libime/build.sh
- x11-packages/libime/data-CMakeLists.txt.diff
- x11-packages/libime/libime-data.subpackage.sh
> enhance(x11/libime): Build dictionary files

- scripts/bin/update-packages
- scripts/updates/api/termux_repology_api_get_latest_version.sh
- scripts/updates/internal/termux_github_graphql.sh
Also in this commit auto-updater script marks some packages as already seen as soon as it makes sure they are up to date.
> ci: reenable accidentally disabled graphql and speed up auto-updater

- .github/workflows/package_updates.yml
Commit detection code was ported from packages.yml.
Removed the irrelevant code.
> ci(package_updates): fix commit range detection and cleanup

- scripts/build/termux_step_massage.sh
- Fixes https://github.com/termux/termux-packages/issues/24606
- Also moves the declaration of `file` to the top of the function
- Also renames `excluded_f` to `excluded_file` and `f_needed` to `needed_file`
> fix(scripts/build/termux_step_massage): rename remaining instances of `f` to `file`

- packages/vulkan-validation-layers/build.sh
> bump(main/vulkan-validation-layers): 1.4.314

- x11-packages/inkscape/build.sh
- Fixes https://github.com/termux/termux-packages/issues/24635
> fix(x11/inkscape): mark as depending on `libjasper`

- packages/gcab/build.sh
- packages/gcab/gir/GCab-1.0.xml
- packages/msitools/build.sh
- packages/msitools/gir/Libmsi-1.0.xml
* Fixes #24644 
* Fixes #24643
> Add gcab and msitools package

- scripts/big-pkgs.list
- x11-packages/electron-for-code-oss/9001-use-prebuilt-snapshot.patch
- x11-packages/electron-for-code-oss/9002-use-prebuilt-cross-tools.patch
- x11-packages/electron-for-code-oss/9003-v8-use-prebuilt-cross-tools.patch
- x11-packages/electron-for-code-oss/9004-use-prebuilt-pdfium.patch
- x11-packages/electron-for-code-oss/9005-use-prebuilt-js2c-binary.patch
- x11-packages/electron-for-code-oss/build.sh
- x11-packages/electron-for-code-oss/third_party_override/swiftshader/src/Vulkan/BUILD.gn
- x11-packages/electron-for-code-oss/third_party_override/swiftshader/src/Vulkan/vulkan.gni
- x11-packages/electron-for-code-oss/toolchain-template/host-toolchain.gn.in
- x11-packages/electron-for-code-oss/toolchain-template/v8-toolchain.gn.in
> new package: electron-for-code-oss

- packages/mop/build.sh
> addpkg(main/mop): Stock market tracker

- x11-packages/xfce4-dict/build.sh
> bump(x11/xfce4-dict): 0.8.9

- packages/screen/0001-logfile-reintroduce-lf_secreopen-to-fix-CVE-2025-233.patch
- packages/screen/0002-default-PTY-mode-apply-safe-default-mode-of-0620-to-.patch
- packages/screen/0003-attacher.c-fix-bad-strncpy-which-can-lead-to-a-buffe.patch
- packages/screen/0004-attacher.c-prevent-temporary-0666-mode-on-PTYs-to-fi.patch
- packages/screen/0005-Avoid-file-existence-test-information-leaks-to-fix-C.patch
- packages/screen/0006-socket.c-don-t-send-signals-with-root-privileges-to-.patch
- packages/screen/build.sh
The CVEs are: CVE-2025-23395, CVE-2025-46802, CVE-2025-46803, CVE-2025-46804 and CVE-2025-46805, see
https://www.openwall.com/lists/oss-security/2025/05/12/1 for details.
> fix(main/screen): add patches to fix a bunch of CVEs

- packages/mbedtls/build.sh
Update src and homepage urls too.
* Fixes #24710
> bump(main/mbedtls): 3.6.3.1

- x11-packages/code-oss/build.sh
> code-oss: bump to 1.100.0

- x11-packages/code-oss/0009-include-vcse-sign-modules.patch
- x11-packages/code-oss/build.sh
> code-oss: include vcse-sign modules

- packages/rust/0002-no-signal_handler.patch
- packages/rust/0005-define-fn-backtrace-getauxval.patch
- packages/rust/build.sh
> bump(main/rust): 1.87.0

- x11-packages/xfce4-mailwatch-plugin/build.sh
> bump(x11/xfce4-mailwatch-plugin): 1.4.0

- x11-packages/xfce4-places-plugin/build.sh
> bump(x11/xfce4-places-plugin): 1.9.0

- x11-packages/gigolo/build.sh
> bump(x11/gigolo): 0.6.0

- x11-packages/xfce4-panel-profiles/build.sh
> bump(x11/xfce4-panel-profiles): 1.1.1

- x11-packages/xfce4-screenshooter/build.sh
- x11-packages/xfce4-screenshooter/src-meson.build.patch
> bump(x11/xfce4-screenshooter): 1.11.2

- packages/optipng/build.sh
> bump(main/optipng): 7.9.1

- packages/amfora/0001-Add-replace-directive-for-cview-360.patch
- packages/amfora/build.sh
cview migrated the repository to codeberg:
https://codeberg.org/tslocum/cview/commit/242e7c1f1b61a4b3722a1afb45ca1165aefa9a59
Also update amfora source repository url.
* Fixes #24857
> fix(main/amfora): Fix building due to module repository change

- packages/pandoc/build.sh
- Enabled building on CI
- Updated to 3.7.0.1
- Assigned myself as maintainer
Closes #372
> pkg(main/pandoc): Enable self build

- packages/passage/build.sh
- packages/passage/src-password-store.sh.patch
https://github.com/FiloSottile/passage
A fork of password-store that uses age as backend
> new package: passage

- packages/carapace/build.sh
> addpkg(main/carapace): 1.3.2

- packages/carapace/build.sh
Also stop building other binaries since we are not shipping them
> fix(main/carapace): build package in release mode

- x11-packages/hangover-wine/build.sh
> hangover-wine: disable osmesa

- packages/libidn/build.sh
Add soverion check and enable auto update.
> bump(main/libidn): 1.43

- packages/libidn2/build.sh
Add soversion check and enable auto update.
> bump(main/libidn2): 2.3.8

- packages/tree-sitter-query/build.sh
> bump(main/tree-sitter-query): 0.6.1

- packages/apr/build.sh
* Add major version check and enable auto update.
* Switch source url to apache archive where tarballs are not removed.
> bump(main/apr): 1.7.6

- x11-packages/lite-xl/build.sh
- x11-packages/lite-xl/meson.build.patch
- x11-packages/lite-xl/src-meson.build.patch
lite-xl was ported to sdl3.
* Fixes #24996
> bump(x11/lite-xl): 2.1.8

- packages/libhangul/build.sh
> fix(main/libhangul): Fix version check for auto update

- packages/taplo/build.sh
and fix the auto-update regex...
> bump(main/taplo): 0.10.0

- packages/openlist/build.sh
> openlist: bump to 4.0.2

- packages/vtm/0002-no-libinput.patch
- packages/vtm/build.sh
> bump(main/vtm): 2025.06.18

- packages/openlist/build.sh
> openlist: bump to 4.0.3

- .github/workflows/codeql.yml
We then get reports with potential issues in the security tab.
> ci(codeql): add CodeQL action to scan the github action scripts

- packages/oxlint/32-bit-arm.patch
- packages/oxlint/build.sh
- packages/oxlint/oxc-language-server.subpackage.sh
- Fixes https://github.com/termux/termux-packages/issues/25122
- Based loosely on Arch Linux package: https://gitlab.archlinux.org/archlinux/packaging/packages/oxc/-/blob/c9feb24ebea521aa240b707d668b80fbaa5f74f6/PKGBUILD
> addpkg(main/oxlint): 1.2.0

- packages/vulkan-validation-layers/build.sh
> bump(main/vulkan-validation-layers): 1.4.319

- packages/rgbds/build.sh
> bump(main/rgbds): 0.9.3

- packages/openlist/build.sh
> openlist: bump to 4.0.7

- x11-packages/opencv/build.sh
> bump(x11/opencv): 4.12.0

- root-packages/docker-compose/build.sh
> bump(root/docker-compose): 2.38.1

- x11-packages/carbonyl-host-tools/5001-clang-19.patch
- x11-packages/carbonyl-host-tools/5002-quiche-size-typo.patch
- x11-packages/carbonyl-host-tools/5003-base-containers-id_map-typo.patch
- x11-packages/carbonyl-host-tools/build.sh
> carbonyl-host-tools: fix build

- x11-packages/lxqt-panel/build.sh
- x11-packages/lxqt-panel/upstream-pr-2305.patch
> bump(x11/lxqt-panel): 2.2.2

- packages/rizin/0001-workaround-name-conflict.patch
- packages/rizin/build.sh
* Fixes #24519 
* Closes #24963
> bump(main/rizin): 0.8.1

- packages/pybind11/build.sh
- x11-packages/openimageio/build.sh
- x11-packages/openimageio/prefix.patch
- x11-packages/openimageio/python.patch
- x11-packages/openvdb/build.sh
- Fixes https://github.com/termux/termux-packages/issues/25379
- This package is desired as a dependency for on-device building of a potential improved Blender package
> addpkg(x11/openimageio): 3.0.8.1

- packages/openxr/build.sh
- Fixes https://github.com/termux/termux-packages/issues/25381
> addpkg(main/openxr): 1.1.49

- packages/draco/build.sh
- Fixes https://github.com/termux/termux-packages/issues/25383
> addpkg(main/draco): 1.5.7

- packages/codon/0005-fdsan.patch
- packages/codon/build.sh
> codon: fix for fdsan

- packages/libgrpc/build.sh
> bump(main/libgrpc): 1.74.0

- packages/rust/bootstrap.toml
- packages/rust/build.sh
- packages/rust/tests/0002-issue-25360.sh
- scripts/build/setup/termux_setup_rust.sh
> fix(main/rust): build to stage 2 to fix rust-analyzer error

- packages/vulkan-tools/0001-no-android.patch
- packages/vulkan-tools/0002-do-not-search-KHR_display-automatically-on-Termux.patch
- packages/vulkan-tools/build.sh
> bump(main/vulkan-tools): 1.4.323

- x11-packages/firefox/0013-fix-rust-compile.patch
- x11-packages/firefox/build.sh
- Fixes https://github.com/termux/termux-packages/issues/25435
> bump(x11/firefox): 141.0

- packages/lux-cli/build.sh
- Fixes https://github.com/termux/termux-packages/issues/25439
- This project releases tags for multiple subprojects from one project, so filter them in a roughly similar, but not identical, way to how `openjdk-17` does.
> fix(main/lux-cli): implement custom `termux_pkg_auto_update()` function

- packages/python-llvmlite/build.sh
- packages/python-llvmlite/ffi-build.py.patch
- packages/python-llvmlite/llvm-include-llvm-ADT-SmallVector.h.patch
- packages/python-llvmlite/llvm-tools-llvm-rtdyld-llvm-rtdyld.cpp.patch
- packages/python-llvmlite/llvm-tools-llvm-shlib-CMakeLists.txt.patch
- packages/python-llvmlite/openmp.patch
> new package: python-llvmlite

- x11-packages/lxterminal/build.sh
- Fixes https://github.com/termux/termux-packages/issues/25473
> addpkg(x11/lxterminal): 0.4.1

- packages/wasi-libc/0001-move-clang-resource-dir.diff
- packages/wasi-libc/build.sh
> bump(main/wasi-libc): 27

- packages/emscripten/build.sh
- packages/emscripten/tests/0001-hello-world.sh
- packages/emscripten/tests/0002-emscripten-tests-third-party-core0.sh
> bump(main/emscripten): 4.0.12

- packages/git-extras/build.sh
> addpkg(main/git-extras): 7.4.0

- packages/wasmedge/build.sh
- packages/wasmedge/fix-for-arm.patch
> bump(main/wasmedge): 0.15.0

- x11-packages/dunst/build.sh
> bump(x11/dunst): 1.13.0

- x11-packages/firefox/build.sh
> firefox: bump to 141.0.2

- x11-packages/thunderbird/build.sh
- Like https://github.com/termux/termux-packages/pull/25617, but for `thunderbird` instead of `firefox`
%ci:no-build
> fix(x11/thunderbird): fix build with NDK r28c

- x11-packages/kf6-kfilemetadata/fix-32bit-build.patch
See the build error in https://github.com/termux/termux-packages/actions/runs/16843699199
> fix(x11/kf6-kfilemetadata): Fix building for 32 bit architectures

- x11-packages/qgit/build.sh
Part of the qt6 transition (#10854).
> chore(x11/qgit): Switch to qt6

- packages/lux-cli/build.sh
Failed CI jobs:
* https://github.com/termux/termux-packages/actions/runs/17107081220/job/48518692567
* https://github.com/termux/termux-packages/actions/runs/17085214072/job/48447919526
* https://github.com/termux/termux-packages/actions/runs/17056155108/job/48354132017
> fix(main/lux-cli): Fix building for i686 architecture

- x11-packages/thunderbird/0033-skip-check-checksums-of-vendored-sources.patch
- x11-packages/thunderbird/0034-fix-for-rust-1.89.patch
- x11-packages/thunderbird/build.sh
> thunderbird: bump to 142.0

- x11-packages/chromium/0002-cflags.patch
- x11-packages/chromium/0101-group-base.patch
- x11-packages/chromium/0104-v8.patch
- x11-packages/chromium/0106-blink-and-mojo.patch
- x11-packages/chromium/0113-protobuf.patch
- x11-packages/chromium/0114-absl-and-perfetto.patch
- x11-packages/chromium/0115-webrtc.patch
- x11-packages/chromium/build.sh
> chromium: reland more jumbo targets

- x11-packages/sdl2-ttf/build.sh
> chore(x11/sdl2-ttf): Prevent auto-updating to 3.x.x versions

- packages/cookcli/build.sh
* Fixes #25852 
_I'm cooking..._
> bump(main/cookcli): 0.15.1

- packages/zrok/build.sh
Fix https://github.com/termux/termux-packages/actions/runs/17285121277?pr=25674
> chore(main/zrok): use releases URL

- x11-packages/kf6-kstatusnotifieritem/build.sh
- x11-packages/kf6-prison/build.sh
- x11-packages/kpipewire/build.sh
- x11-packages/libva/build.sh
- x11-packages/spectacle/build.sh
This pull request adds the `spectacle` package to the Termux repository.
* Fixes #25838
> addpkg(x11/spectacle): 6.4.4

- packages/supercollider/CMakeLists.txt.patch
- packages/supercollider/boost-1.89.patch
- packages/supercollider/build.sh
- packages/supercollider/lang-CMakeLists.txt.patch
- packages/supercollider/lang-LangPrimSource-PyrPrimitive.cpp.patch
- packages/supercollider/lang-LangSource-Bison-lang11d.patch
- packages/supercollider/lang-LangSource-Bison-lang11d_tab.cpp.patch
Previous PR was here #25025, had to open new one.
Closes #25024.
Oh, the boost patch problem might not be necessary now? TomJo2000 might have fixed that in Termux's system boost since then. **EDIT:** Nope I don't see the patch in Termux's boost. No biggie.
> addpkg(main/supercollider): 3.14.0

- packages/zellij/0001-curl-sys-0.4.78-curl-8.11.0.patch
- packages/zellij/build.sh
> bump(main/zellij): 0.43.1

- packages/suitesparse/build.sh
Rebuild some packages to get 16 kb page size.
> chore(main/suitesparse): Rebuild

- packages/gotorrent/0001-Support-32bit-systems.patch
- packages/gotorrent/build.sh
Convenient TUI that helps you find torrents on tpb.
> addpkg(main/gotorrent): 0.1.2

- packages/p11-kit/0001-workaround-asn1Parser-for-cross-compile.diff
- packages/p11-kit/build.sh
* Port to meson from autotools.
* Use proot workaround for asn1Parser.
* Fixes #26523
> bump(main/p11-kit): 0.25.9

- x11-packages/orca/build.sh
- x11-packages/orca/meson.build.patch
> bump(x11/orca): 49.1

- root-packages/bubblewrap/build.sh
- root-packages/containerd/build.sh
- root-packages/dnsmasq/build.sh
Rebuild some packages to get 16 kb page size.
> chore(root/bubblewrap,containerd,dnsmasq): Rebuild

- x11-packages/mogan/build.sh
- x11-packages/mousepad/build.sh
- x11-packages/mpv-x/build.sh
Rebuild some packages to get 16 kb page size.
> chore(x11/mogan,mousepad,mpv-x): Rebuild

- x11-packages/xfce4-calculator-plugin/build.sh
- x11-packages/xfce4-clipman-plugin/build.sh
- x11-packages/xfce4-cpugraph-plugin/build.sh
- x11-packages/xfce4-datetime-plugin/build.sh
Rebuild some packages to get 16 kb page size.
> chore(x11/xfce4-calculator-plugin,xfce4-clipman-plugin,xfce4-cpugraph-plugin,xfce4-datetime-plugin): Rebuild

- packages/openlist/build.sh
> bump(main/openlist): 4.1.4

- x11-packages/gimp/build.sh
- x11-packages/gimp/gir/Gimp-3.0.xml
> bump(x11/gimp): 3.0.6
