termux/termux-packages

packages/ragel/build.sh

It is based on my https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-ragel/PKGBUILD but I didn't test if it works honestly, would be nice if someone else do as my PC screen just got break :)

Add ragel package

---

Dockerfile

Added php5-cli to Dockerfile for successful php compilation.

Added php5-cli to Dockerfile

---

disabled-packages/man-db/build.sh

Just updating the man-db package to 2.7.5. Not much else has changed; I don't really know how to go about hosting built packages.

man-db: Update from 2.7.4 to 2.7.5

---

packages/pwgen/build.sh

Termux looks great, so I tried to package some things today.  pwgen successfully builds and runs... Although Sourceforge is flakey just this minute, so that's hard to demonstrate.

pwgen: add new package

---

packages/pwgen/build.sh
packages/zile/build.sh

Two packages can't be that hard, right?  RIGHT!!??
I've mildly obfuscated my email address in the commit, in a futile attempt to reduce spam.
Besides my information showing up in apt show, you're obviously welcome to punt any bug reports my way.

(Naïvely) agree to maintain a couple packages

---

packages/kona/0.c.patch
packages/kona/Makefile.patch
packages/kona/build.sh
packages/kona/c.c.patch
packages/kona/getline.c.patch
packages/kona/getline.h.patch
packages/kona/getline_android.c.patch
packages/kona/kc.c.patch

I have created a package for kona (open source version of the K programming language). Let me know if you have any questions or suggestions (this is my first termux package).

initial version of kona package

---

packages/mathomatic/build.sh

Mathomatic, a simple computer algebra system and calculator. It builds cleanly.

initial mathomatic package

---

Dockerfile
packages/corkscrew/build.sh
ubuntu-setup.sh

add corkscrew

---

packages/tree/build.sh

Tree is a recursive directory listing command that produces a depth indented
listing of files, which is colorized ala dircolors if the LS_COLORS environment
variable is set and output is to tty.
http://mama.indstate.edu/users/ice/tree/

Add tree package

---

Dockerfile

flex fails to build in ubuntu 15.04, since 15.10 is the recommended version of Ubuntu, I edited Dockerfile to reflect that

fix build of flex by using correct ubuntu

---

packages/termux-tools/build.sh

Use the system ip command, since it's not available in a package.

Add ip command to termux-tools

---

packages/mosh/build.sh
packages/mosh/configure.ac.patch
packages/mosh/makefile.am.patch
packages/mosh/mosh.cc.patch
packages/mosh/pty.cc.patch
packages/mosh/shittypty.h.patch

Its the old android branch frontend. Named it mosh-cfront because i am not very creative. Test it i guess.... 
I could of edited the build.sh but im lazy.

Old android  branch mosh frontend

---

packages/calcurse/build.sh
packages/calcurse/io.c.patch
packages/calcurse/notify.c.patch
packages/calcurse/ui-calendar.c.patch

I added [calcurse](http://calcurse.org/) again with a single commit. I tested it in a Nexus 9 with Android 6.0.

Added calcurse package

---

packages/stunnel/build.sh

Upgrade stunnel to 5.33

---

packages/valgrind/build.sh
packages/valgrind/dont-redefine-elf32_nhdr.patch

Requested in #251.
Fairly straightforward build, works for me in the sdk emulator.  I'm not sure what other tests are appropriate before submitting.

Add valgrind package.

---

packages/fzf/build.sh

the scripts allow keybindings and integration with the rest of the system, including tmux

added fzf shell helper scripts to the package

---

packages/libotr/build.sh
packages/libotr/configure.patch
packages/libstrophe/build.sh
packages/libstrophe/configure.ac.patch
packages/profanity/build.sh
packages/profanity/ui-inputwin.c.patch

Add profanity package +libstrophe +libotr

---

packages/emacs/lisp-loadup.el-2.patch.beforehostbuild

Closes termux/termux-packages#423
I hope if someone knows what sort of issues this can cause, they'll find the record of my investigations and correct me properly, but so far, everything runs fine.

Patch for the load-history problem

---

packages/graphviz/add-libcommon-to-gc.patch
packages/graphviz/build.sh
packages/graphviz/fix-edgepaintmain-include.patch
packages/graphviz/fix-gdefs-include.patch
packages/graphviz/general-free.patch
packages/graphviz/no-configure-dot-plugins.patch
packages/graphviz/no-mkdefs.patch
packages/graphviz/sfdpgen-free.patch

I've created patches to compile Graphviz for Termux.

Add Graphviz

---

packages/libmosquitto/build.sh
packages/libmosquitto/config.patch
packages/libmosquitto/mosquitto.subpackage.sh

Pretty much what it says on the tin.  Note that we have to disable threading in libmosquitto due to missing pthread_cancel() in bionic.

Add libmosquitto and its CLI clients

---

packages/neofetch/build.sh

[neofetch](https://github.com/dylanaraps/neofetch)
>`neofetch` is a script that gathers information about your system and prints it to the terminal next to an image, a distro's logo or any ASCII art of your choice.

neofetch: new package

---

packages/mpc/build.sh

mpc is a command line client for the Music Player Daemon (MPD).
references termux/termux-packages/#536

Add mpc package

---

packages/libmpdclient/build.sh

references termux/termux-packages/#536

Add libmpdclient

---

packages/ffmpeg/build.sh
packages/libvpx/build.sh

https://trac.ffmpeg.org/wiki/Encode/VP8

ffmpeg enable libvpx (WebM encoder)

---

disabled-packages/screen/attacher.c.patch
disabled-packages/screen/build.sh
disabled-packages/screen/misc.c.patch
disabled-packages/screen/os.h.patch
disabled-packages/screen/osdef.h.in.patch
disabled-packages/screen/screen.h.patch
disabled-packages/screen/utmp.c.patch
disabled-packages/screen/window.c.patch

screen compiling and working mostly

---

packages/tor/build.sh

Tor is an anonymizing program. Also, known as The Onion Router.

add package tor

---

packages/ed/build.sh
packages/ed/configure.patch

Add ed package

---

packages/joe/build.sh
packages/joe/do_not_build_utils.patch
packages/joe/fix_errno.patch
packages/joe/no_getpwent.patch

joe is a simplistic editor.
Have fun with it,
Richard

Add a joe (editor) package

---

packages/liblzo/build.sh
packages/lzop/build.sh

Portable lossless data compression library
http://www.oberhumer.com/opensource/lzo

add packages liblzo and lzop

---

packages/tty-clock/Makefile.patch
packages/tty-clock/build.sh

As discussed it https://github.com/termux/termux-packages/pull/680

Refactor build of tty-clock

---

packages/lrzsz/build.sh
packages/minicom/build.sh
packages/minicom/dial.c.patch
packages/minicom/file.c.patch
packages/minicom/getdir.c.patch
packages/minicom/getdir.h.patch
packages/minicom/script.h.patch
packages/minicom/wkeys.c.patch

#220 wanted this. Added lrzsz for zmodem file transfers... not really needed but may as well.

minicom and lrzsz

---

packages/proot/build.sh

More information about what's been done here:
https://plus.google.com/+OliverSchmidhauser/posts/FVqBDPdNzUd

Update proot to the latest version

---

packages/krb5/build.sh
packages/krb5/dnsglue.h.patch
packages/krb5/getpass.patch
packages/krb5/netbsd_getpass.c
packages/krb5/sethostent.patch

This is the MIT Kerberos. Its required as a dependency for many others, and enables optional features in many others/

add package krb5

---

packages/perl/build.sh

fixes perl build config so cpan works.

fixes the config so cpan works on install.

---

packages/libdb/build.sh

I added Berkeley DB library:
> Berkeley DB is a family of embedded key-value database libraries providing scalable high-performance data management services to applications. The Berkeley DB products use simple function-call APIs for data access and management.
Some packages I want to add requires this lib.

Added libdb package

---

disabled-packages/alsa-lib/alsa-conf-dir.patch
disabled-packages/alsa-lib/build.sh
disabled-packages/alsa-lib/pcm_direct.c.patch
disabled-packages/alsa-lib/pcm_mmap.c.patch.old
disabled-packages/alsa-lib/versionsort.patch
disabled-packages/alsa-plugins/asound.conf
disabled-packages/alsa-plugins/build.sh
disabled-packages/alsa-utils/build.sh
disabled-packages/alsa-utils/configure.patch
disabled-packages/alsa-utils/volume_mapping.c.patch
packages/libpulseaudio/build.sh
packages/libpulseaudio/pulseaudio-discuss-iochannel-don-t-use-variable-length-array-in-union.patch
packages/libpulseaudio/pulseaudio.subpackage.sh
packages/libpulseaudio/tmpdir.patch
packages/libsndfile/build.sh

alsa-{lib,utils,plugins} and pulseaudio packages

---

packages/nginx/Android-crossfile.patch32
packages/nginx/Android-crossfile.patch64
packages/nginx/auto-threads.patch
packages/nginx/build.sh
packages/nginx/cross-compile-nginx.patch

I have not tested any kinds of CGI.

nginx: add package

---

disabled-packages/openvpn/build.sh
disabled-packages/squid/build.sh
packages/liblzo/build.sh
packages/net-tools/build.sh
packages/net-tools/ifconfig.c.patch
packages/net-tools/lib-inet.c.patch
packages/net-tools/lib-inet6.c.patch
packages/net-tools/lib-inet6_sr.c.patch
packages/net-tools/nameif.c.patch

I'm thinking about enabling squid.
openvpn is still broken

Updates for some disabled packages and add net-tools

---

packages/proot/build.sh

Fixes #898
Also revert to thumb mode as termux/proot#1 is fixed

proot: Upgrade to fix #898

---

packages/gettext/build.sh
packages/gettext/gnulib-libmakefile.am.patch
packages/gettext/msginit.c.patch

It compiles i guess it could be split into sub packages

Adds gettext software

---

packages/memcached/build.sh
packages/memcached/getsubopt.c
packages/memcached/getsubopt.h
packages/memcached/memcached.c.patch

One commit only like requested in #833

Add Memcached package

---

packages/texlive/build.sh
packages/texlive/termux-install-tl.sh

Fixes #913 and [termux-app/issues/305](https://github.com/termux/termux-app/issues/305).

texlive: fix installation issues and reported shebang issue

---

packages/patchelf/build.sh

Useful for dealing with android linker issues.

Android Patchelf utility

---

packages/tintin++/build.sh

mud client tintin++

---

packages/dialog/build.sh

Bump version or else the build fails.
Test result here: https://gitlab.com/Wetitpig/termux-packages/builds/15951458#

Bump dialog version to 20170509

---

packages/mpd/build.sh
packages/mpd/configure.ac.patch
packages/mpd/makefile.am.patch
packages/mpd/mpd-script.sh
packages/mpd/mpdconf.example.patch
packages/mpd/registry.cxx.patch

it works well with ncmpcpp ....

mpd only working with openal and no mixer still good

---

packages/cscope/build.sh
packages/cscope/errno.patch

For response to #267, added package cscope and tested on my aarch64 Android 7.1 device.

cscope: Add package

---

packages/linux-man-pages/build.sh

There seems to be racing issues as shown in the following tests:
https://gitlab.com/Wetitpig/termux-packages/builds/16937394
https://gitlab.com/Wetitpig/termux-packages/builds/16937395

1 build only for linux-man-pages

---

packages/ncmpcpp/settings.cpp.patch

this makes visualizer work as default

fifo default working

---

packages/proot/build.sh
packages/proot/termux-chroot

* Update to fix emulated ptrace() on ARM thumb
* Mount /vendor (fixes termux/proot#2)

proot: Update and mount /vendor

---

packages/mpd/slesoutputplugin.cxx.patch

small edit so pause works in sles output.

[mpd] pause now works for opensles

---

packages/gnuit/build.sh
packages/gnuit/system.c.patch

hasn't been updated since 2009 though....

gnuit initial commit

---

packages/php/build.sh
packages/php/php-apache.subpackage.sh
packages/php/sapi-apache2handler-config.m4.patch

php-apache: add package

---

packages/php/build.sh
packages/php/sapi-apache2handler-config.m4.patch

* fix other modules linking against apr
* fix php including httpd.conf

php: handle php-apache properly

---

packages/proot/build.sh

proot: Update to include --kill-on-exit support

---

.travis.yml
Gemfile
Rakefile
packages/ack-grep/build.sh
packages/diffutils/build.sh

#1108 
Probably still needs some work, but it's a start. Other file touches show functionality
Might be helpful to enable using travis `allow_failures` feature to allowed failed builds to start with

Travis pkg builds

---

disabled-packages/apt/build.sh
disabled-packages/apt/methods-connect.cc.patch

refix htc bug and fix dependences

---

packages/moria/build.sh
packages/moria/source-config.h.patch
packages/moria/source-death.c.patch
packages/moria/source-signals.c.patch
packages/moria/unix-Makefile.patch
packages/moria/unix-unix.c.patch

As requested in #533 (fixes #533).

Add moria package

---

packages/ncurses/build.sh

Previous one has been down for at least two days.

ncurses: change url to working one

---

packages/apr/build.sh

required for autoconf detection of apr
similar to #1181 
tagging #1169

add apr-1-config to apr-dev

---

packages/apr-util/build.sh

required for autoconf detection of apr-util
similar to #1180 
tagging #1169

add apu-1-config to apr-util-dev

---

packages/freetype/build.sh

include freetype-config in freetype-dev

---

packages/pcre/build.sh

add pcre-config to pcre-dev

---

packages/libpng/build.sh

include libpng-config in libpng-dev

---

packages/fdupes/build.sh

fdupes allows to easily find and remove duplicates

fdupes: New package

---

packages/libassuan/build.sh

include libassuan-config in libassuan-dev

---

packages/ldns/build.sh

include ldns-config in ldns-dev

---

packages/libcurl/build.sh

add curl-config to libcurl-dev

---

packages/gpgme/build.sh

add gpgme-config to gpgme-dev

---

packages/ncurses/build.sh

include ncursesw6-config to ncurses-dev

---

packages/iconv/build.sh
packages/xorriso/build.sh
packages/xorriso/pthread.patch

xorriso allows to create ISO files. This is very useful to prepare a bootable ISO for an emulator like qemu

New package: xorriso

---

packages/mtools/build.sh
packages/mtools/sysinc.patch

mtools allow to manipulate FAT images without root

mtools: New package

---

packages/hfsutils/build.sh
packages/hfsutils/lfs.patch
packages/hfsutils/replace_hardlink_with_symlink.patch

HFS utils allows to manipulate HFS images without root

hfsutils: New package.

---

packages/libcurl/curl.subpackage.sh

specify curl binaries in curl subpackage

---

packages/lftp/ptyshell.cc.patch

fixed sftp shell

---

packages/texlive-bin/build.sh

Also add texlive as recommended package to texlive-bin.

texlive: keep certain texmf-dist files in texlive-bin (texliveonfly)

---

packages/cmus/build.sh

thanks to @its-pointless for the advice
needed for #1169, should not affect current build process
not 100% sure if i need the `export`

disable OSS in cmus

---

packages/libxapian/build.sh
packages/libxapian/xapian-tools.subpackage.sh

include xapian-config in dev package

---

packages/dropbear/build.sh
packages/graphviz/build.sh
packages/man/build.sh
packages/mlocate/build.sh
packages/mpd/build.sh
packages/openssh/build.sh
packages/python/build.sh
packages/python2/build.sh
packages/texlive/build.sh
packages/zsh/build.sh

Needs shebang otherwise uses /system/bin/sh .... 
#1264

put shebang in deb scripts like postinst

---

packages/tcl/build.sh

update lisqlite src file location

---

packages/texlive-bin/build.sh

add build dependency to texlive

---

packages/apr/build.sh

need files for apr-util build

---

packages/libllvm/build.sh
packages/libllvm/clang.subpackage.sh

Fixes #414, tested with a C file calling OpenMP, definitely sped up.

clang: add OpenMP library, should now work

---

packages/proot/build.sh

proot: Update to fix vfork-execve brk handling

---

packages/transmission/build.sh

add libcurl to transmission dependencies

---

packages/dcraw/build.sh

add libjpeg-turbo to dcraw dependency list

---

packages/libcairo/build.sh

add libpng to libcairo dependencies

---

packages/git/build.sh

add openssl to git dependencies

---

packages/qalc/build.sh

add libgmp to qalc dependencies

---

packages/ledger/build.sh

add libgmp dependency to ledger

---

packages/fontconfig/build.sh

add libpng dependency to fontconfig

---

packages/libotr/build.sh

add libgpg-error dependency to libotr

---

packages/xmlsec/build.sh

add dependencies to xmlsec

---

packages/frobtads/build.sh

add libcurl to frobtads dependencies

---

packages/ddrescue/build.sh
packages/ddrescue/fix-configure.patch

add package ddrescue

---

packages/gnupg2/build.sh

add libgpg-error to gnupg2 dependencies

---

packages/gpgme/build.sh

add libgpg-error to gpgme dependencies

---

packages/pinentry/build.sh

add libgpg-error dependency to pinentry

---

packages/pango/build.sh

add dev dependencies to pango

---

packages/fontconfig/build.sh

add freetype-dev to fontconfig dev dependencies

---

packages/harfbuzz/build.sh

add libgraphite-dev to harfbuzz dev dependencies

---

packages/gdk-pixbuf/build.sh

add libpng-dev to gdk-pixbuf devpackage depends

---

packages/vorbis-tools/build.sh

add libogg to vorbis-tools dependency

---

packages/libvorbis/build.sh

add libogg-dev to libvorbis dev package depends

---

packages/gpgme/build.sh

add libgpg-error to gpgme dev package depends

---

packages/gegl/build.sh

add glib dependency to gegl depends

---

packages/mpd/build.sh

add dependencies to mpd depends

---

packages/tcl/build.sh

add private headers for tcl dev package

---

packages/libgcrypt/build.sh

add libgpg-error-dev to gcrypt devpackage depends

---

packages/libpulseaudio/build.sh

add libtool to libpulseaudio build depends

---

packages/poppler/build.sh

add dependencies to poppler

---

packages/ncdc/build.sh

add build dependencies for ncdc

---

packages/liblua/build.sh

#1169
deals with subpackage dependency

add readline build dependency to lua

---

packages/zbar/build.sh

add libjpeg-turbo to zbar depends

---

packages/libgcrypt/build.sh

libgcrypt version bump

---

packages/libgnutls/build.sh

add devpackage depends to gnutls

---

packages/graphviz/build.sh

add libtool to graphviz build depends

---

packages/tty-solitaire/build.sh

https://github.com/termux/termux-packages/issues/1536

Added tty-solitaire

---

packages/hashdeep/build.sh
packages/hashdeep/hash.patch

Add hashdeep and md5deep

---

packages/tsocks/build.sh
packages/tsocks/configure.patch

Thanks to @vishalbiswas in #1573

Fix building tsocks for 32 bit architectures

---

packages/python2/build.sh

Python 2.7.14 is the latest bug fix release in the Python 2.7.x series.
Full Changelog: https://raw.githubusercontent.com/python/cpython/84471935ed2f62b8c5758fd544c7d37076fe0fa5/Misc/NEWS

python2 update

---

packages/texlive-bin/build.sh
packages/texlive/build.sh

Solves https://github.com/termux/termux-packages/issues/1639

texlive-bin: enable extglob locally in preinst script

---

packages/vifm/build.sh
packages/vifm/cmd_completion.c.patch
packages/vifm/configure.ac.patch
packages/vifm/file_info.c.patch
packages/vifm/pthread.c.patch
packages/vifm/pthread.h.patch

vifm window manager with vim bindings

---

packages/libgc/os_dep.c.patch

Looks like this breaks arm as well but only w3m....

fixes w3m on arm android 7

---

packages/elinks/build.sh
packages/elinks/elinks-fix-paths.patch

This should fix #1682 and problem with validation of SSL cerificates.

elinks: update to latest git version

---

packages/rcs/build.sh

When i misspelled `cp` to `co` it told me to install the package `rcs`
for it. Not knowing what it was I called `apt show rcs`. But the
description didn't help me at all.
So I copied the description from Debian.

Provide a better description for the rcs package

---

packages/ffmpeg/build.sh
packages/ffmpeg/enable-glob.patch

Should fix https://github.com/termux/termux-app/issues/450

ffmpeg: enable globbing

---

packages/opusfile/build.sh

v0.9 not well distributed, github seems to be a better source

update opusfile with more consistent link

---

packages/tcpdump/build.sh

https://github.com/termux/termux-root-packages/pull/6

move tcpdump to termux-root-packages

---

packages/libmnl/build.sh

add libmnl

---

packages/texlive-bin/build.sh
packages/texlive-bin/texlive-poppler-0.59.patch

Solves https://github.com/termux/termux-packages/issues/1765
and partly solves https://github.com/termux/termux-packages/issues/1657.
https://github.com/termux/termux-packages/issues/1657 is more complicated than I hoped for, the bug doesn't seem to be reproducible on x86_64 (desktop) and my valgrind/gdb skills aren't good enough to find anything.
We might need to revert the poppler update (again) in the worst case scenario.

texlive-bin bug fixes

---

packages/php/build.sh
packages/php/ext-mysqli-config.m4.patch
packages/php/ext-pdo_mysql-config.m4.patch
packages/php/php-mysql.subpackage.sh

requested in #630 #1600 and loads of times in the gitter chat

php-mysql: add package

---

packages/tsu/build.sh

update tsu package #1789

---

packages/tsu/build.sh

https://github.com/cswl/tsu/commit/f0d3a5c6d179c34be18fb91b14f2f3da2100365a

Update tsu to v0.3, fixes su detection

---

packages/tsu/build.sh

magic to handle magisk..
https://github.com/cswl/tsu/commit/88a8cb09d6fea8e8ed47bd874b5df8ea647302c0

update tsu to version 0.4

---

packages/squid/build.sh

squid: update to 3.5.27 and --enable-delay-pools

---

packages/serf/build.sh

add apr to serf depends

---

packages/pngquant/build.sh
packages/pngquant/configure.patch

fixes #1887 
Please note that I have globally disabled SSE support (x86), because I don't know anything about SSE.

pngquant: add package

---

packages/qpdf/build.sh

qpdf: add package

---

packages/atomicparsley/build.sh
packages/atomicparsley/util.cpp.patch
packages/atomicparsley/util.h.patch

zip doesn't work with build-package.sh so a work around was used.

atomicparsley add

---

packages/gpgme/build.sh

update gpgme dev dependency name

---

packages/gstreamer/build.sh

add glib-dev to gstreamer devpackage depends

---

packages/fontconfig/build.sh

add libxml2-dev to fontconfig dev depends

---

packages/graphicsmagick/build.sh

graphicsmagick++-dev is missing significant amount of headers

version bump graphicsmagick

---

packages/libical/build.sh
packages/libical/stow.c.patch

libical: add package

---

packages/mariadb/build.sh
packages/mariadb/etc-my.cnf.patch

I didn't update the manual files but all the places where it is used in the sources should be here.

mariadb: /etc/my.cnf -> @TERMUX_PREFIX@/etc/my.cnf

---

packages/json-glib/build.sh

add glib to json-glib devpackage depends

---

packages/global/build.sh

Also move SRCURL to mirrors.kernel.org/gnu

Update global to 6.6.1

---

packages/taskwarrior/build.sh

taskwarrior: bump revision to fix segmentation fault (#1942).

---

packages/gegl/build.sh

remove glib from gegl dependencies

---

packages/wol/build.sh

remove dead links as well
closes #1998

update wol srcurl

---

packages/boost/build.sh
packages/boost/libboost-python.subpackage.sh

should be enough for people to build python modules that use boost.

boost add python3 lib

---

packages/ldc/build.sh

Mostly updating source packages, plus tweaked some compiler flags and removed a line from the config file.

ldc: Update from 1.6 to 1.7

---

packages/libpulseaudio/build.sh
packages/libpulseaudio/module-sles-sink.c

updated now with configurable output sample rate.

updated sles module

---

packages/gbt/build.sh

This PR is updating the `gbt` package to the latest version.

Version bump for GBT v1.1.7

---

packages/gbt/build.sh

One more release before today's [presentation](https://www.meetup.com/DevOps-Exchange-London/events/246447551/) ;o)

GBT version bump to v1.2.0

---

disabled-packages/cups/build.sh
disabled-packages/cups/cups-thread.c.patch
disabled-packages/cups/file.c.patch
disabled-packages/cups/lockf.cpp.patch
disabled-packages/cutter/build.sh
disabled-packages/dovecot/build.sh
disabled-packages/dovecot/configure.patch
disabled-packages/dovecot/src-lib-connection.h.patch
disabled-packages/libwebp/build.sh
disabled-packages/mono/build.sh
disabled-packages/mono/complex.h
disabled-packages/mono/math_private.h
disabled-packages/mono/tkill.patch
disabled-packages/qt5/build.sh
disabled-packages/qt5/execinfo.h
disabled-packages/qt5/mkspec.diff
disabled-packages/qt5/qsystemdetection.h.patch
disabled-packages/qt5/qthread_unix.cpp.patch
disabled-packages/qt5/qtlocation-src-plugins-geoservices-geoservices.pro.patch
disabled-packages/qt5/qtsensors-src-plugins-sensors-linux-linux.pro.patch
disabled-packages/qt5/qtserialport-src-serialport-qserialport_unix.cpp.patch
packages/pcre2/build.sh

I'm not able to spare time to continue work on these packages.
Maybe someone else will find something I couldn't.
@xeffyr You may want to use this qt5 in your gui repo.

add disabled-packages

---

packages/isync/build.sh
packages/isync/isync.patch

fix termux_step_pre_configure in build.sh

Isync 1.3.0

---

packages/alpine/build.sh

on a fresh install creates a passwordless master password so its less annoying for users on mobiles to reenter pass constantly.

alpine improvements

---

packages/qpdf/build.sh

qpdf: Update from 7.0.0 to 7.1.1

---

packages/tsu/build.sh

Fixes `-p` in x64. 
Thanks to @urain39

Update tsu to v1.2

---

build-package.sh

Repairs last commit which may give unbound variable problem.

fix unbound variable issue

---

packages/tsu/build.sh

Update tsu to v2.0.0

---

packages/libllvm/0001-Transforms-Add-missing-header-for-InstructionCombini.patch
packages/libllvm/build.sh
packages/libllvm/llvm-config.in

llvm-config edit allows me to build nightly rustc  using our llvm6....

llvm fixes using jit and calling getProcessTriple

---

packages/ncurses/build.sh

Reason of this PR is https://github.com/termux/termux-packages/issues/2289 and https://github.com/termux/termux-packages/issues/2279

create libcurses as a symlink

---

packages/libgit2/build.sh

this fixes arm issues with libgit2

fixes libgit2 for arm

---

packages/zsh/build.sh

zsh: enable pcre

---

packages/proot/build.sh

Update proot to make it work on Linux >= 4.8
termux/proot#13

proot: Update for Linux >= 4.8

---

packages/ldc/build.sh
packages/ldc/llvm-config.in

Updated versions, hashes, and flags and renamed a local variable in the build script.

ldc: Update from 1.8 to 1.9

---

packages/proot/build.sh

proot: Update with fix for termux/proot#14

---

packages/librhash/build.sh

for #2393 
should rhash be split?

librhash: build executable as well

---

packages/valac/build.sh

version change symlink didn't ...

valac symlink fix

---

packages/boost/build.sh

this enables coroutine and context to be built.

boost enables coroutine and context

---

packages/openssh/build.sh
packages/openssh/session.c.patch

openssh: keep TMPDIR and PS1

---

packages/libidn2/build.sh

https://github.com/termux/termux-packages/issues/2437

Add package idn2

---

packages/luarocks/build.sh
packages/luarocks/src-luarocks-cfg.lua.patch

luarocks: look for headers in $PREFIX

---

packages/proot/build.sh

Update with fix by @Hax4us at termux/proot#17

proot: Update with fix for chroot(".")

---

packages/tsocks/tsocks.patch

not work with `source tsocks off`, there is no `\?`

bad sed statement with tsocks

---

packages/yarn/build.sh

Let yarn depend on nodejs or nodejs-current

---

packages/rclone/build.sh

rclone: Update from 1.41 to 1.42

---

packages/diffutils/build.sh

Just a typo that confused me for a second...

diffutils: no cmd command, only cmp

---

packages/command-not-found/build.sh
packages/command-not-found/commands.h
packages/dropbear/build.sh
packages/rsync/build.sh

Lets make rsync available for users which use dropbear instead of openssh.

rsync: make rsync usable with dropbear

---

packages/parallel/build.sh
packages/parallel/parallel.patch
packages/parallel/sem.patch

Fix for https://github.com/termux/termux-packages/issues/2024

parallel: fix path to default shell

---

packages/postgresql/build.sh

This will let us use xml columns and related functions

Compile postgres with --with-libxml

---

packages/mpv/build.sh
packages/mpv/pulse-buffer.patch

Since pulseaudio is available now, it would be cool if all our media
players would support it.

Enable pulseaudio in mpv

---

packages/openssh/build.sh
packages/openssh/ssh-agent.c.patch

Fixes it for Android Pie, see #2714

Don't use setresgid or setgid in ssh-agent

---

packages/busybox/build.sh
packages/busybox/networking-ftpd.c.patch

Fix for https://github.com/termux/termux-packages/issues/2740.

busybox: fix segfault in 'ftpd'

---

packages/valgrind/aarch64-setjmp.S
packages/valgrind/build.sh
packages/valgrind/coregrindmake.am.patch
packages/valgrind/libcsetjmp.h.patch
packages/valgrind/memcheckmake.am.patch

Added the assembly files from aosp

valgrind clang aarch64 patch

---

packages/ecj4.6/build.sh
packages/ecj4.6/ecj
packages/ecj4.6/ecj-21

ecj4.6: add package for compatibility with android 5 and 6

---

scripts/setup-ubuntu.sh

add gawk for apr-util build

---

packages/kbfs/build.sh
packages/keybase/build.sh

Fixes #2133
Based on https://github.com/keybase/client/blob/master/packaging/linux/build_binaries.sh
```
./scripts/run-docker.sh ./build-package.sh kbfs
```

packages: add keybase and kbfs

---

packages/nnn/build.sh

New package: nnn

---

scripts/properties.sh

properties.sh: 'source'->'.'

---

packages/git/build.sh

So to have the `__git_ps1` function

git: added git-prompt

---

packages/nnn/build.sh

Fixes https://github.com/termux/termux-app/issues/934.

nnn: add 'findutils' to dependencies

---

packages/rust/config.toml

rust minor fix so it doesn't download toolchain everytime

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/package_request.md

I've shamelessly copied the ones from @xeffyr's [x11-packages](https://github.com/termux/x11-packages/tree/master/.github/ISSUE_TEMPLATE) with some minor changes.
Feedback&comments are welcome!

Add bug_report and package_request templates

---

packages/mpd/HybridDsdDecoderPlugin.cxx.patch
packages/mpd/build.sh

Also add missing dependency libogg

mpd: DSD decoder message but don't disable dsd

---

packages/caddy/build.sh

Fixes https://github.com/termux/termux-packages/issues/3219.

new package: caddy

---

packages/openssh/build.sh
packages/openssh/sftp-with-agent.sh

Requested in https://github.com/termux/termux-packages/issues/1978.

openssh: add script "sftpa"

---

packages/gnuplot/build.sh
packages/gnuplot/plot.c.patch

fix SYS_SECCOMP error on recent android versions.

---

packages/debianutils/build.sh

4.8.6 tar.xz has been removed from ftp

debianutils: bump to 4.8.6.1

---

packages/openssh/build.sh

Some things should be fixed after https://github.com/termux/termux-packages/pull/3328.

Fixes for https://github.com/termux/termux-packages/pull/3328

---

.gitlab-ci.yml
scripts/ci/gitlab.sh

Support for building packages on Gitlab CI.

add scripts for Gitlab CI

---

scripts/Dockerfile

Probably unnecessary to write so many `COPY` statements for `Dockerfile`.

3 COPY to 1

---

build-package.sh
scripts/get_hash_from_file.py

This makes it possible to download .debs from dl.bintray.com/xeffyr

build-package.sh: handle Release.gpg and get deb path from Package

---

build-package.sh

Tested for openjpeg and harfbuzz, seem to work as intended.

fast-build: download subpackages dependencies

---

scripts/run-docker.sh

Noticed that Travis CI fails: https://travis-ci.org/termux/termux-packages/jobs/497926796.

scripts/run-docker.sh: use sudo for privileged operations (when changing uid/gid)

---

build-package.sh
packages/libllvm/tools-clang-lib-Driver-ToolChains-Linux.cpp.patch
packages/ndk-sysroot/build.sh

fix arm and also not make not needed asm symlink

fix for arm

---

packages/ruby/build.sh

See https://github.com/termux/termux-packages/issues/3380.

ruby: fix segmentation fault

---

scripts/build/termux_step_start_build.sh

Look for a `${PKG}.subpackage.sh` file in packages/. If found then build parent package, else build package.

termux_step_start_build: handle failed subpackage downloads

---

packages/openssl/build.sh
packages/openssl/openssl-tool.subpackage.sh

Fixes https://github.com/termux/termux-packages/issues/3426.

openssl: put openssl.cnf to main package

---

packages/mariadb/build.sh

See https://github.com/termux/termux-packages/issues/3387

mariadb: create directory $PREFIX/etc/my.cnf.d to prevent error on installation

---

packages/openssl/build.sh
packages/openssl/openssl-tool.subpackage.sh

To not get errors on apt update && apt upgrade

openssl: declare that it breaks openssl-tool << 1.1.1b-1

---

packages/syncthing/build.sh

syncthing: update to 1.1.0

---

packages/unstable-repo/build.sh
packages/x11-repo/build.sh

API 21 and 24 repositories will be stored separately.

Change URLs for supplementary repositories (Unstable & X11)

---

packages/proot/build.sh

Including pull request termux/proot#55 by @lightful

Upgrade proot with emulated chroot(/) fix

---

packages/poppler/build.sh
scripts/buildorder.py

fast build fixes

---

packages/poppler/build.sh
scripts/buildorder.py

Currently used by some X11 packages.

[android-5] poppler: enable glib bindings

---

packages/nodejs/build.sh
packages/nodejs/deps-uv-src-unix-linux-syscalls.c.patch

See https://github.com/termux/termux-packages/issues/3608

nodejs: avoid using __NR_statx

---

packages/ndk-sysroot/build.sh
packages/ndk-sysroot/math-header.diff

math header refix

---

packages/php/build.sh
packages/php/iconv-config.m4.patch

php iconv fix

---

scripts/build/termux_create_subpackages.sh

Please bump revision and rebuild at least pulseaudio after merging this, thanks.

build-package: fix conffiles for subpackages

---

packages/graphicsmagick/build.sh

Fixes https://github.com/termux/termux-packages/issues/3496.

[android-5] graphicsmagick: add *-config files to devpackage

---

packages/irssi/build.sh

Fixes https://github.com/termux/termux-packages/issues/3732

irssi: depend on utf8proc

---

packages/proot/build.sh

proot: Update for nested chroot() support

---

packages/irssi/build.sh

Fixes https://github.com/termux/termux-packages/issues/3732

[android-5] irssi: depend on utf8proc

---

packages/gmic/CImg.h.patch
packages/gmic/build.sh
packages/gmic/makefile.patch
packages/ncurses/build.sh

Actually, this is from https://github.com/termux/termux-packages/pull/3452.

Fix gmic and gdb for ARM

---

packages/valgrind/vg_preloaded.c.patch

simple fix to get it working on x86_64 ...

this fixes x86_64 valgrind memcheck

---

packages/gmic/Makefile.patch
packages/gmic/build.sh
packages/gmic/gmic-gm.subpackage.sh

also building variant that does not make use of graphicsmagick

gmic: workaround libunwind.a linking issue with a better approach

---

packages/build-essential/build.sh

termux-packages: Add util-linux to build-essential

---

packages/perl/build.sh
packages/perl/cnf-configure_path.sh.patch

Makes it easier to install cpan modules

perl: fix default libpath

---

packages/perl/build.sh
packages/perl/cnf-configure_path.sh.patch

Makes it easier to install cpan modules

[android-5] fix default libpath

---

packages/termux-tools/termux-upgrade-repo

Not tested for real yet.
Checks for its-pointless repo in addition to the official ones

[WIP] termux-upgrade-repo: backup (known) custom repos

---

packages/libiconv/build.sh

[android-5] libiconv: enable extra encodings

---

packages/libpulseaudio/build.sh
packages/libpulseaudio/module-sles-source.c
packages/libpulseaudio/sles.patch

pulseaudio sles input

---

packages/ffmpeg/build.sh
packages/libass/build.sh

Requested in https://github.com/termux/termux-packages/issues/2399.

[android-5] ffmpeg: enable support for libass

---

packages/termux-tools/build.sh

Issues https://github.com/termux/termux-packages/issues/4002 shouldn't happen anymore.

[android-5] termux-tools: provide wrappers for mount and umount

---

packages/fcgi/build.sh
packages/fcgi/fcgi-2.4.0-Makefile.am-CPPFLAGS.patch
packages/fcgi/fcgi-2.4.0-configure.in.patch
packages/fcgi/fcgi-2.4.0-gcc44_fixes.patch
packages/fcgi/fcgi-2.4.0-poll.patch
packages/fcgi/fix-libs.patch
packages/fcgiwrap/build.sh
packages/fcgiwrap/fix-kill-parameters.patch

Requested in https://github.com/termux/termux-packages/issues/3422.

[android-5] new package: fcgi + fcgiwrap

---

packages/dbus-glib/build.sh
packages/dbus-glib/glib-genmarshal-fix.patch
packages/dbus/build.sh
packages/telepathy-glib/build.sh
packages/telepathy-glib/configure.patch
scripts/setup-ubuntu.sh

Updated docker image with `libdbus-1-dev` already pushed.

[android-5] copy some new packages from android-7 branch

---

packages/mc/build.sh

MC needs rebuild due to glib update.
Issue https://github.com/termux/termux-packages/issues/4027.

[android-5] mc: bump package

---

packages/busybox/build.sh
packages/coreutils/build.sh

See https://github.com/termux/termux-packages/issues/4070.

busybox: disable applet symlinks

---

.cirrus.yml
scripts/build/ci/cirrus-ci_dispatcher.sh

Faster way to get docker image updated.
**Note**: docker image will be rebuilt only if related scripts or dockerfile are changed on branch 'master'.

CI: add support for automatic docker image rebuilding

---

packages/libgmp/build.sh

enable libgmpcxx

---

packages/libdb/build.sh

It just needed atomic_init renamed.

libdb enabled libc++

---

.cirrus.yml

https://github.com/termux/termux-packages/issues/4116

CI: reduce resource usage

---

packages/asciidoc/build.sh
packages/docbook-xml/build.sh
packages/docbook-xsl/765567_non-recursive_string_subst.patch
packages/docbook-xsl/build.sh

asciidoc: add package

---

packages/starship/build.sh

[Starship](https://starship.rs/) is a fast and pretty shell prompt.

starship: add package

---

packages/emacs/build.sh
packages/emacs/lib-src-emacsclient.c.patch

emacs: make emacsclient look for socket in $PREFIX/var/run per default

---

packages/bitcoin/build.sh
packages/lnd/build.sh

* Don't add termux-services as dependency to bitcoin. 
* Mark run-scripts as conffiles.

Bitcoin lnd service scripts

---

packages/tmux/build.sh

Fixes https://github.com/termux/termux-packages/issues/4296

tmux: make sure $PREFIX/var/run exists

---

packages/libao/ao_private.h.patch
packages/libao/ao_pulse.c.patch
packages/libao/build.sh
packages/libao/configure.ac.patch
packages/pianobar/Makefile.patch
packages/pianobar/build.sh

Reopen: Add packages: pianobar, libao

---

packages/libgnutls/build.sh

- improve version from 3.6.9 to 3.6.10

Package libgnutls update

---

packages/ffmpeg/build.sh
packages/libdav1d/build.sh

Fixes https://github.com/termux/termux-packages/issues/4412.

ffmpeg: build with libdav1d

---

packages/cmake/Modules-CMakeDetermineSystem.cmake.patch
packages/cmake/Modules-Platform-Android-Clang.cmake.patch
packages/cmake/Modules-Platform-Android-Determine-Compiler.cmake.patch
packages/cmake/Modules-Platform-Android-Determine.cmake.patch
packages/cmake/Modules-Platform-Android-Initialize.cmake.patch
packages/cmake/Modules-Platform-Android.cmake.patch
packages/cmake/Source-cmStateSnapshot.cxx.patch
packages/cmake/build.sh

For consistency, backported my earlier pull #4222 to this branch too.

[android-5] CMake: switch CMAKE_HOST_SYSTEM_NAME to Android

---

packages/dte/build.sh

Hi. This is a new package for [dte](https://github.com/craigbarnes/dte) -- a small, configurable text editor. Tested on LineageOS 16.

new package: dte

---

packages/binutils/build.sh
packages/libllvm/ORCv2.rst.patch
packages/libllvm/build.sh
packages/lldb/build.sh
packages/rust/build.sh
packages/rust/config.toml

don't merge just yet it should probably be reviewed.

update to llvm9 and fix tools in rust

---

packages/rust/build.sh

wrong path fix

---

packages/bs1770gain/build.sh

Following discussion in https://github.com/termux/termux-packages/issues/4455 and https://wiki.termux.com/wiki/Dev:Development_Session_42

bs1770gain: Remove package

---

packages/bs1770gain/build.sh

Following discussion in https://github.com/termux/termux-packages/issues/4455 and https://wiki.termux.com/wiki/Dev:Development_Session_42

[android-5] bs1770gain: Remove package

---

packages/lldb/ProcessLauncherPosixFork.cpp.patch
packages/lldb/build.sh

fix lldb for later android versions

---

packages/tokei/build.sh

Tokei is a program that displays statistics about your code. Tokei will show number of files, total lines within those files and code, comments, and blanks grouped by language.
https://github.com/XAMPPRocky/tokei

New package: tokei

---

packages/hunspell-en-us/build.sh
packages/libcln/build.sh
packages/libcln/revert_configure_tests.patch
packages/ncompress/build.sh
packages/unifdef/build.sh

These gave problems during a `./build-all -a arm`.

[android-5] various fixes

---

packages/cmusfm/build.sh

Last.fm standalone scrobbler for the cmus music player
https://github.com/Arkq/cmusfm

Add package: cmusfm

---

packages/starship/build.sh

Currently fails because include file conflicts

fix starship build

---

README.md

I have made a few grammatical corrections in README.md file.

Grammatical correction.

---

packages/qemu-system-x86_64-headless/0000-android-config-support.patch
packages/qemu-system-x86_64-headless/0001-fix-hardcoded-paths.patch
packages/qemu-system-x86_64-headless/0002-fix-soundcard.h-location.patch
packages/qemu-system-x86_64-headless/0003-add-missing-arch_prctl.patch
packages/qemu-system-x86_64-headless/0004-fix-time_nsec-defs.patch
packages/qemu-system-x86_64-headless/0005-add-missing-telldir-seekdir.patch
packages/qemu-system-x86_64-headless/0006-add-missing-sigorset.patch
packages/qemu-system-x86_64-headless/0007-fix-sem.h-location.patch
packages/qemu-system-x86_64-headless/0008-fix-syscalls.patch
packages/qemu-system-x86_64-headless/0009-fix-struct-member-conflicts.patch
packages/qemu-system-x86_64-headless/0010-fix-mman.h-defs.patch
packages/qemu-system-x86_64-headless/0011-disable-glob.h-include.patch
packages/qemu-system-x86_64-headless/build.sh
packages/qemu-system-x86_64-headless/qemu-common.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-system-aarch64-headless.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-system-arm-headless.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-system-i386-headless.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-system-riscv32-headless.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-system-riscv64-headless.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-user-aarch64.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-user-arm.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-user-i386.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-user-riscv32.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-user-riscv64.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-user-x86_64.subpackage.sh
packages/qemu-system-x86_64-headless/qemu-utils.subpackage.sh

Update QEMU to v4.1.1 and move from unstable repo. It should work fine on all devices now.

Moving QEMU from unstable repo

---

packages/php/build.sh

re-enable libgd

---

packages/dart/build.sh
packages/dart/fix-shell-path.patch

Updated dart version to 2.7.0 and removed 2 no longer needed patches

dart: update to 2.7.0

---

packages/o/build.sh

The related package request is here: https://github.com/termux/termux-packages/issues/4882
This is my first contribution to Termux so I hope I am following the correct procedure. Thanks for reviewing.

new package: o

---

packages/zsh/build.sh

First time contributing, but I think this is a simple enough change.
Closes #4939

zsh: add zsh/zselect module

---

packages/dirb/build.sh
packages/dirb/src-dirb.c.patch

new package: dirb

---

packages/rgbds/Makefile.patch
packages/rgbds/build.sh

Fixes https://github.com/termux/termux-packages/issues/4962

rgbds: use our LDFLAGS, and clean up build.sh a bit

---

packages/jo/build.sh

new package: jo

---

packages/xmake/build.sh

Add new package: xmake  A cross-platform build utility based on Lua
* https://xmake.io/
* https://github.com/xmake-io/xmake.git

add new package: xmake

---

packages/task-spooler/build.sh

new package: task-spooler

---

packages/rinetd/Makefile.patch
packages/rinetd/build.sh
packages/rinetd/rinetd.c.patch

Requested in https://github.com/termux/termux-packages/issues/4761.

new package: rinetd

---

packages/proxmark3/build.sh

update version to latest master
add maintainer
change platform from rdv4 to generic pm3

proxmark3: version update

---

packages/bgrep/Makefile.patch
packages/bgrep/build.sh

new package: bgrep(#4992)

---

packages/git-delta/build.sh

Requested in https://github.com/termux/termux-packages/issues/4991.

new package: git-delta

---

.github/workflows/packages.yml
packages/rust/build.sh
packages/rust/config.toml

rust-1.41.1

---

packages/proot/build.sh

proot: Update to fix PEEKDATA error on statfs64

---

packages/game-repo/build.sh
packages/root-repo/build.sh
packages/science-repo/build.sh
packages/termux-tools/build.sh
packages/termux-tools/termux-change-repo
packages/unstable-repo/build.sh
packages/x11-repo/build.sh

Simplifies changing repositories to a mirror, hopefully helps some users if the main repository on Bintray is not available
@xeffyr, any comments?

termux-tools: add termux-change-repo script

---

packages/links/build.sh

Fixes https://github.com/termux/termux-packages/issues/5073

links: add zstd as dependency

---

packages/boinctui/add_locale_header.patch
packages/boinctui/build.sh
packages/boinctui/no-pthreads-lib.patch

Hi,guys,this is a new package boinctui ,which is a manager for boic
https://github.com/termux/termux-packages/tree/master/packages/boinc

new package : boinctui

---

packages/cicada/build.sh

Adding a new package: cicada - A simple bash-like Unix shell.

new package: cicada

---

packages/cfengine/build.sh
packages/cfengine/fixup-for-termux.patch
packages/cfengine/libpromises-patches-copy-not-link.patch
packages/cfengine/unix_iface.patch

Bootstrapping from a policy server (or self) doesn't work yet.
There may be other issues but the basics work and this is useful as a way to test out policy on-the-go.

Added CFEngine (core + masterfiles) package

---

packages/fselect/build.sh

Updated fselect to version 0.6.10

Updated fselect to version 0.6.10

---

packages/rush/build.sh

Homepage: https://github.com/shenwei356/rush/

Rush: A cross-platform command-line tool for executing jobs in parallel 

---

packages/keychain/build.sh
packages/sleuthkit/build.sh

New package: keychain

---

packages/pup/build.sh

Pup : Command line html parser

---

packages/gh/build.sh

This is beta version of GitHub cli,

gh: GitHub’s official command line tool 

---

packages/ffmpeg/build.sh

closes #5290
side note: opinions on splitting a libwebp-progs subpackage from libwebp?

ffmpeg: enable WebP support

---

packages/golang/build.sh
scripts/build/setup/termux_setup_golang.sh

Upgrade golang to version 1.14.3

Upgrade golang to version 1.14.3

---

packages/libllvm/build.sh

Update libllvm build.sh

---

packages/shfmt/build.sh

[A {bash, mksh, sh} script formatter](https://github.com/mvdan/sh#shfmt)

shfmt: Add package

---

packages/dpkg/build.sh

dpkg: up to 1.20.4

---

packages/xdelta3/build.sh

surprised we didn't have this already tbh
it's also available under gpl3 but apparently the author prefers we use apache2

new package: xdelta3

---

packages/php/build.sh

enable php ffi

---

packages/electric-fence/Makefile.patch
packages/electric-fence/build.sh
packages/electric-fence/ef.sh

apparently it works on Android now, unlike 3 years ago in #1725

new package: Electric Fence

---

packages/binutils/build.sh
packages/libllvm/build.sh
packages/rust/build.sh

Let's see if this builds on the CI.

libllvm: update from 10.0.0 to 10.0.1

---

packages/electric-fence/Makefile.patch
packages/electric-fence/build.sh
packages/electric-fence/ef.sh

electric-fence: fix cross-compilation

---

packages/rust/build.sh

curl build fails. test for a fix

rustc fails

---

packages/libraqm/build.sh

New package libraqm

---

packages/iwyu/build.sh
packages/libllvm/build.sh
packages/lldb/build.sh

closes #5382
currently just testing build

new package: iwyu (include-what-you-use)

---

packages/libllvm/build.sh
packages/lldb/build.sh

i should have done this in #5642, sorry
https://github.com/termux/termux-packages/runs/944846593#step:5:616

libllvm: don't rm clang-offload-wrapper

---

packages/squid/build.sh
packages/squid/no-priv-drop.patch
packages/squid/posix-shm-support.patch

* POSIX shared memory (shm_open, shm_unlink) support for https://github.com/termux/termux-packages/issues/5651.
* No attempts to swich user id: https://github.com/termux/termux-packages/issues/5669.

Squid fixes

---

packages/wren/build.sh
packages/wren/projects-make-wren_test.make.patch

Run a verbose build on the CI and see what's different.

wren: fix i686 build

---

packages/libzim/build.sh

New package: libzim

---

packages/links/build.sh

Checking to see if this works on the CI.

links: disable using OpenMP for now

---

packages/hors/build.sh

instant coding answers via the command line written in rust similar to howdoi

New package: hors

---

packages/frogcomposband/LICENSE
packages/frogcomposband/autoconf.h.in.patch
packages/frogcomposband/build.sh
packages/frogcomposband/h-config.h.patch
packages/frogcomposband/util.c.patch

So this was originally [a PR for the game-packages repo](https://github.com/termux/game-packages/pull/59), but because of Angband's [pre-GPL licensing](http://www.roguebasin.com/index.php?title=Angband#Licensing), this is now a pull request for the main repository!
The game itself is FrogComposband, an extremely content-rich roguelike in the Angband family with an overworld, a ridiculous amount of quests, unique classes, or just ways to play in general. It's also currently the most popular game played on [angband.live](https://angband.live).

FrogComposband

---

packages/libimobiledevice/build.sh
packages/libimobiledevice/configure.ac.patch
packages/libplist/build.sh
packages/libusbmuxd/build.sh
packages/usbmuxd/build.sh
packages/usbmuxd/configure.ac.patch

New pacakge: libimobiledevice, libplist, libusbmuxd and usbmuxd 

---

packages/golang/build.sh

Add misc directory in golang root which contains useful wrapper for wasm, android etc

golang: build.sh add misc directory

---

packages/texlive-bin/build.sh

Requested in https://github.com/termux/termux-packages/issues/5722

texlive-bin: enable dvisvgm

---

packages/swift/build.sh
packages/swift/swift-cmake.patch
packages/swift/swift-lib-ClangImporter-ImportType.cpp.patch
packages/swift/swift-static-stdlib.patch
packages/swift/swift-stdlib-public-runtime-Float16Support.cpp.patch
packages/swift/swift-utils-build-script-impl-flags.patch
packages/swift/swiftpm-Utilities-bootstrap
packages/swift/swiftpm-android-flags.json
packages/swift/swiftpm-rpath.patch

swift: enable arm build and add upstream patch that fixes linking statically against the corelibs

---

packages/php-redis/build.sh

Add php-redis package

---

packages/lsd/build.sh

Add new package: lsd

---

packages/texlive-bin/build.sh
packages/zziplib/build.sh

zziplib: add package

---

packages/microsocks/Makefile.patch
packages/microsocks/build.sh

Closes https://github.com/termux/termux-packages/issues/5828.

New Package:microsocks (#5828)

---

packages/lazygit/build.sh

Add: Lazygit

---

packages/check/build.sh

Closes https://github.com/termux/termux-packages/issues/5810

new package:check (#5810)

---

packages/starship/build.sh

Update Starship to latest version

starship: update to 0.45.2

---

packages/fselect/build.sh

Updated the package fselect to version 0.7.1

fselect: update to 0.7.1

---

packages/k9s/build.sh

Add new package k9s

---

packages/libmediainfo/build.sh
packages/mediainfo/build.sh

Updated the packages mediainfo and libmediainfo to version 20.09

mediainfo: update to 20.09

---

packages/hors/build.sh

Also fixed to work on arm devices.

Update hors to 0.7.2

---

packages/proton-bridge/build.sh
packages/proton-bridge/disable_secretservice.patch
packages/proton-bridge/ignore_not.patch
packages/proton-bridge/replace_imap-specialuse.patch
packages/proton-bridge/replace_intro.patch

This is my first Termux package, I would appreciate if somebody can review it. Especially `build.sh`.

Proton-bridge package

---

packages/restic/build.sh

Update restic to version 0.11.0

restic: update to 0.11.0

---

packages/brook/build.sh

add new pkg:brook

---

packages/whatprovides/build.sh

https://github.com/termux/whatprovides

Add: Whatprovides

---

packages/php/build.sh

Enable php-tidy while compiling php.

Compile php with php-tidy

---

packages/binaryen/build.sh

Add Binaryen as a single package. 
More PR are coming to add emscripten

package Binaryen

---

packages/sox/build.sh
scripts/build/termux_step_setup_toolchain.sh

stick with the old practice, for now (see #6145)

sox: build with omp again

---

packages/rust/build.sh
packages/rust/config.toml
packages/rust/os-tmpdir.patch
packages/rust/src-librustc_llvm-build.rs.patch

rust 1.48.0

---

packages/dbus/build.sh
packages/dbus/dbus-sysdeps-unix.c.patch

Needed by libbluetooth in termux-root-packages so needs to be in main repository

dbus: mv from x11-packages to termux-packages

---

packages/et/CMakeLists.txt.patch
packages/et/build.sh
packages/et/src-base-Headers.hpp.patch
packages/et/src-base-TcpSocketHandler.cpp.patch
packages/et/src-terminal-ParseConfigFile.hpp.patch
packages/et/temporaryDirectory.patch

Closes #3385 and MisterTea/EternalTerminal#327, but currently doesn't work. If more people want to help debug, the build artifacts from this pull can be installed and tried.

et: add package

---

packages/termux-tools/motd

Suuuper-small PR, but I figured I'd fix a typo in the new motd ("receive" -> "receives"), since that seems to be a pretty visible place for one.
I also slightly changed the wording to keep the length of the lines consistent. (Just in case the first line was the maximum length we wanted to have)

motd update

---

packages/postgresql/build.sh

Add the extension `postgres_fdw` to the postgres build

postgresql: build postgres_fdw

---

packages/tcl/build.sh

i forgot a crucial part of Arch's solution! oops!
i promise it'll work after this

tcl: update to 8.6.11 and fix

---

packages/logrotate/build.sh

new package: logrotate

---

packages/libvips/build.sh

Resolves: #6113
Signed-off-by: Thibault Meyer <meyer.thibault@gmail.com>

Add libvips

---

packages/mpg123/build.sh

Provides mpg123 cli  and library.

Add mpg123

---

packages/swift/build.sh
packages/swift/swift-corelibs-xctest-CMakeLists.txt.patch
packages/swift/swift-utils-build-script-impl-build.patch
packages/swift/swift-utils-build-script-impl-cross.patch

swift: update from 5.3.2 to 5.3.3

---

packages/teleport-tsh/build.sh

teleport-tsh: update to 5.1.2

---

packages/wget2/build.sh

new package: wget2

---

packages/libstrophe/build.sh

New package: libstrophe

---

packages/rust/build.sh
packages/rust/rustc-dev.subpackage.sh

making this a pr first just in case

rust: update to 1.50.0

---

packages/strace/5.11fix.patch
packages/strace/build.sh
packages/strace/bundled-linux-include-uapi-linux-fs.h.patch
packages/strace/sigreturn.c.patch
packages/strace/strace.c.patch
packages/strace/xlat-faccessat_flags.h.patch

making this a pr for now, since i can confirm it builds but can only test it on aarch64

strace: update to 5.11

---

packages/germanium/build.sh

Resolves #6505
First time adding a package, hopefully did not mess up anything.

Add package germanium

---

packages/squashfs-tools-ng/build.sh

Creating PR again, hopefully this should fix this mess
Addressing #6537

Add Package: squashfs-tools-ng

---

packages/gopass/build.sh

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

gopass: update to 1.12.5

---

packages/android-tools/build.sh
packages/android-tools/fix-ndk.patch

This package include `img2simg,append2simg,fastboot,adb,mke2fs.android,simg2img`

Add android-tools

---

packages/neomutt/build.sh

My take at closing #6612 
I did not test this in any way, as I'm new to contributing to this repo and am not sure how :laughing:

neomutt: Add notmuch as dependency

---

packages/jftui/build.sh

Built and tested deb locally, still works fine.

jftui: update to 0.5.1

---

packages/libllvm/build.sh
packages/libllvm/lldb-source-Plugins-Process-Linux-NativeProcessLinux.cpp.patch
packages/libllvm/lldb.subpackage.sh
packages/libllvm/llvm-config.in
packages/libllvm/llvm.subpackage.sh

First, running it through CI to see if it builds, then I'll test and modify it a bit before merging. Rust and Swift will also need to be bumped after this is in.

libllvm: update from 11.1.0 to 12.0.0

---

README.md

Hi everyone!
I just added a repo size badge, for users to quickly understand how much size is your repo
I also had a doubt whether this repo was 1GB ?

Add repo size badge

---

packages/gopass/build.sh

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

gopass: update to 1.12.6

---

packages/ghostscript/fapi_ft.patch

Bug: 6704
Test: run ./build-package.sh -a arm ghostscript

Description:[fix] ghostscript 9.53.2 build

---

scripts/build/termux_extract_dep_info.sh

Test building some packages has worked as before.

 termux_extract_dep_info: fix logic for subpackages 

---

packages/recode/build.sh

Added as per #6614 request, but used active fork https://github.com/rrthomas/recode

new package: recode (#6614)

---

scripts/setup-ubuntu.sh

This is required for termux/x11-packages#354

Changes to setup-ubuntu.sh

---

packages/golang/build.sh
scripts/build/setup/termux_setup_golang.sh

Bump golang

---

scripts/update-docker.ps1

A carbon copy of [update-docker.sh](https://github.com/termux/termux-packages/blob/master/scripts/update-docker.sh) but for Windows
Like [run-docker.ps1](https://github.com/termux/termux-packages/blob/master/scripts/run-docker.ps1) to [run-docker.sh](https://github.com/termux/termux-packages/blob/master/scripts/run-docker.sh)

Add update-docker.ps1

---

packages/libandroid-wordexp/build.sh
packages/libandroid-wordexp/wordexp.c
packages/libandroid-wordexp/wordexp.h
packages/proxmark3/build.sh

Closes termux/libandroid-support#8

Add package : libandroid-wordexp

---

packages/silicon/build.sh

Add package: `silicon`

---

.github/workflows/packages.yml

github actions: don't free disk space on CI unless needed for large builds

---

scripts/updates/github-projects.txt

helix : add to auto updated github projects

---

packages/flyctl/build.sh
packages/flyctl/getcpuinfo.patch

Add package: `flyctl`

---

packages/tmux/build.sh
packages/tmux/configure.ac.patch

tmux: Update from 3.2 to 3.2a

---

packages/git-sizer/build.sh

Git Sizer repository and source: https://github.com/github/git-sizer

Add package: git-sizer

---

README.md

this one is more saturated as someone suggested in https://github.com/termux/termux-app/pull/2198
will open another PR to use non-blurplified one in termux-app repo readme

also add discord badge link

---

packages/php/build.sh

Bump revision for php

---

packages/php-psr/build.sh
scripts/build/termux_step_install_license.sh

New package: php-psr
php-psr: PHP extension providing the accepted PSR interfaces

add package: php-psr

---

packages/re2c/build.sh

Add new package re2c.
re2c: Lexer generator for C, C++ and Go.

add package re2c

---

packages/php-zephir-parser/build.sh

New package: php-zephir-parser
php-zephir-parser: The Zephir Parser delivered as a C extension for the PHP language.

add package: php-zephir-parser

---

packages/exa/build.sh
packages/nnn/build.sh

Sorry, I messed up in my previous PRs.

fix location of bash completions

---

packages/alpine/build.sh

alpine: Bump to 2.24.2

---

packages/dotconf/build.sh
packages/speechd/build.sh
packages/speechd/i18n.c.patch
packages/speechd/index_strchr.patch
packages/speechd/speechd.h.patch
packages/speechd/speechd.patch
packages/speechd/tmpdir.patch

Works in simple testing with spd-say. 
speech-dispatcher daemon hangs if run in debug mode, and can only be killed with kill -9 though. I suspect there is some more pthread/mutex patching needed.

Add speechd and dependency dotconf

---

packages/php-apcu/build.sh

APCu - APC User Cache
http://php.net/apcu

add new package php-apcu

---

packages/php-imagick/build.sh

[imagick](https://github.com/Imagick/imagick): The Imagick PHP extension

add php-imagick

---

packages/binutils/build.sh
packages/binutils/ldd

making this a PR in case anyone has complaints about it breaking their scripts, although my commit ea367b1d398d6d795c1b503314be8f6d9238683f may have already done that

binutils: better ldd

---

packages/libmosquitto/build.sh
packages/libmosquitto/tmp-dir.patch

libmosquitto: fix unable to open tmpfile

---

packages/flyctl/build.sh
packages/flyctl/getcpuinfo.patch

`flyctl`: Bump to 0.0.233

---

packages/fish/build.sh

Fix yadm conflicting with fish

---

packages/cc65/Makefile.patch
packages/cc65/build.sh

Added package cc65 as requested in #7340

Add Package cc65

---

packages/openssh/build.sh
packages/openssh/serverloop.c.patch

removing privsep from streamlocal, enabling gpg-agent forwarding

---

packages/jump/build.sh

This is my first PR for Termux. I've read CONTRIBUTING.md and I believe this is compliant. 
NAME
jump - navigate faster by learning your habits
SYNOPSIS
j [term ...]
DESCRIPTION
Jump  integrates  with  the  shell and learns about your navigational habits by keeping track of the directories you visit. It
strives to give you the best directory for the shortest search term.

Add "Jump" Package to Termux

---

packages/libslirp/build.sh

New package: libslirp

---

scripts/build/termux_create_pacman_subpackages.sh
scripts/build/termux_step_create_pacman_package.sh

[Discussion](https://github.com/termux/termux-packages/pull/7440#issuecomment-912798569)  
If the look of the values ​​remains strange in PKGINFO, show them.

Bug fix from #7460.

---

packages/pulseaudio/module-aaudio-sink.c
packages/pulseaudio/module-sles-sink.c

An attempt to fix #7389, in case my call of making use of `u->sink->request_rewind` is wrong. Please test before merging if interested. Not sure if it will actually help or make things worse. @Yonle

pulseaudio: process rewind in the realtime loop

---

packages/libelf/build.sh
packages/libelf/elfutils.subpackage.sh
packages/libelf/libdw.subpackage.sh

- ah...I forgot to move few  build time dependencies  to runtime in #7431

libelf: move few build dependencies to runtime

---

packages/ruby/build.sh

- Remove `--with-coroutine=copy`
- Do not use `__builtin_setjmp`

Ruby: modify configure args

---

packages/openssh/build.sh
packages/openssh/scp-with-agent.sh
packages/openssh/ssh-with-agent.sh

Create scpa script
Install scpa script
Quote args for ssha script

openssh: add scpa wrapper

---

packages/nodejs/build.sh
packages/nodejs/tools-v8_gypfiles-toolchain.gypi.patch

nodejs: Fix android log

---

packages/neovim/build.sh
packages/neovim/src-nvim-eval-funcs.c.patch
packages/vim/build.sh
packages/vim/src-evalfunc.c.patch

Make has(android/termux) return true in neovim/vim

---

packages/stylua/build.sh

It's a code formatter for lua.

Add package stylua

---

scripts/updates/github-projects.txt

Add auto update for
- php-apcu
- php-zephir-parser

add auto update

---

scripts/updates/check-updates.sh

fix auto update invalid version detection.

fix auto update invalid version detection

---

packages/enchant/build.sh

enchant: Depend on aspell and hunspell

---

packages/dtach/build.sh

Hi team,
I would like to add `dtach` package. Hope it is helpful for everyone.
Thanks!

Add package dtach-0.9

---

packages/reptyr/build.sh

I would like to add `reptyr` package with the latest version. Thanks!

packages: add reptyr-0.8.0

---

packages/pacman/build.sh
packages/pacman/pacman.conf.in.patch

Thank, @Yisus7u7 for the promotion.

Update pacman.conf (adding x11 packages)

---

packages/cpufetch/Makefile.patch
packages/cpufetch/build.sh

add package: cpufetch

---

packages/binutils/build.sh
packages/binutils/fix-empty-manpages.patch

binutils: Fix empty manpages

---

packages/ffmpeg/build.sh

ffmpeg: Add libxml2 dependency

---

packages/zsh/build.sh

zsh: Enable cap

---

packages/perl/build.sh

perl: Use thread support

---

packages/php/build.sh
packages/php/php-sodium.subpackage.sh

php: Enable sodium module

---

packages/recutils/build.sh

recutils: Install elisp files

---

packages/php/build.sh

php: Install `php.ini` examples

---

ndk-patches/dirent.h.patch
scripts/build/termux_step_start_build.sh

ndk-patches: Add IFTODT and DTTOIF to dirent.h

---

packages/apache2/build.sh
packages/apache2/libdummy.patch

apache2: Fix DT_NEEDED and DT_RUNPATH for modules

---

packages/avahi/build.sh
packages/avahi/configure.ac.patch
packages/libdaemon/build.sh

new package: avahi

---

packages/libgnutls/build.sh
packages/unbound/build.sh
packages/unbound/libunbound-libunbound.c.patch
packages/unbound/smallapp-unbound-host.c.patch

libgnutls: Enable libdane

---

packages/kubelogin/build.sh

https://github.com/int128/kubelogin

add package: kubelogin

---

packages/php/build.sh

php: Explicitly link against compiler-rt builtins

---

packages/mailutils/build.sh
packages/mailutils/lib-mailcap.c.patch
packages/mailutils/lib-manlock.c.patch
packages/mailutils/libmailutils-diag-bt.c.patch
packages/mailutils/mail-send.c.patch
packages/mailutils/mh-send.c.patch
packages/mailutils/mh-show.c.patch
packages/mailutils/paths.patch

mailutils: Fix hardcoded paths

---

packages/zsh/build.sh
packages/zsh/compinit.patch

zsh: compinit: unsetopt nocaseglob

---

packages/slashem-extended/build.sh
packages/slashem-extended/include-unixconf.h.patch
packages/slashem-extended/src-files.c.patch
packages/slashem-extended/sys-unix-GNUmakefile.patch
packages/slashem-extended/sys-unix-unixunix.c.patch

new package: slashem-extended

---

packages/avahi/avahi-autoipd-main.c.patch
packages/avahi/avahi-daemon-main.c.patch
packages/avahi/build.sh

avahi: Enable non-root user to launch daemon

---

packages/alpine/build.sh

alpine: Depend on coreutils

---

packages/apkeep/build.sh

new package: apkeep

---

packages/qemu-system-x86-64-headless/build.sh
packages/qemu-system-x86-64-headless/qemu-system-m68k-headless.subpackage.sh
packages/qemu-system-x86-64-headless/qemu-user-m68k.subpackage.sh

qemu: Include m68k targets

---

packages/dwarves/CMakeLists.txt.patch
packages/dwarves/build.sh
packages/dwarves/dutil.h.patch
packages/dwarves/elfcreator.h.patch
packages/dwarves/lib-bpf-include-linux-compiler.h.patch
packages/dwarves/lib-bpf-include-linux-types.h.patch
packages/dwarves/obstack.h

new package: dwarves

---

packages/iproute2/IN6_IS_ADDR_UNSPECIFIED.patch
packages/iproute2/Makefile.patch
packages/iproute2/build.sh
packages/iproute2/in_addr_t.patch
packages/iproute2/misc-arpd.c.patch
packages/iproute2/rindex.patch
packages/iproute2/sethostent.patch
packages/iproute2/strdupa.patch

new package: iproute2

---

packages/libresolv-wrapper/build.sh
packages/libresolv-wrapper/resolv_private.patch
packages/libresolv-wrapper/src-resolv_wrapper.c.patch
packages/php/build.sh

php: Use libresolv-wrapper

---

packages/erlang/build.sh

erlang: Configure with `erl_xcomp_sysroot`

---

packages/slashem-extended/build.sh

slashem-extended: Fix postinst

---

packages/libc-client/1006_openssl1.1_autoverify.patch
packages/libc-client/Makefile.patch
packages/libc-client/build.sh
packages/libc-client/src-c-client-c-client.h.patch
packages/libc-client/src-osdep-unix-Makefile.patch
packages/libc-client/src-osdep-unix-ckp_psx.c.patch
packages/libc-client/src-osdep-unix-env_unix.c.patch
packages/libc-client/src-osdep-unix-os_slx.c.patch
packages/mailsync/build.sh

new package: mailsync

---

packages/nim/build.sh

nim: Install tools

---

packages/stone/build.sh

new package: stone

---

packages/uwsgi/build.sh
packages/uwsgi/core-lock.c.patch
packages/uwsgi/core-spooler.c.patch
packages/uwsgi/core-utils.c.patch
packages/uwsgi/core-uwsgi.c.patch
packages/uwsgi/plugins-corerouter-corerouter.c.patch
packages/uwsgi/plugins-router_basicauth-router_basicauth.c.patch
packages/uwsgi/sys_sem.c
packages/uwsgi/sys_time.c
packages/uwsgi/use-Py_CompileString.patch
packages/uwsgi/uwsgi.h.patch
packages/uwsgi/uwsgiconfig.py.patch

new package: uwsgi

---

packages/traceroute/build.sh
packages/traceroute/traceroute-flowlabel.h.patch

new package: traceroute

---

packages/libtorrent-rasterbar/build.sh

new package: libtorrent-rasterbar

---

packages/megacmd/build.sh
packages/megacmd/configure.ac.patch
packages/megacmd/src-comunicationsmanagerfilesockets.cpp.patch
packages/megacmd/src-megacmdshell-megacmdshellcommunications.cpp.patch

new package: megacmd

---

packages/stuntman/build.sh
packages/stuntman/common-commonincludes.hpp.patch
packages/stuntman/testcode-Makefile.patch

new package: stuntman

---

packages/wget/build.sh
packages/wget/gnulib.patch

Fix bug #8223

---

packages/glib/build.sh
packages/glib/glib-gtimezone.patch

May fix termux/x11-packages#526.

glib: Fix bug in glib-gtimezone.patch

---

packages/nodejs-lts/build.sh

nodejs-lts: add TERMUX_PKG_PROVIDES for dependencies to work properly (for pacman)

---

packages/apktool/aapt-wrapper.patch
packages/apktool/build.sh

new package: apktool

---

packages/nim/build.sh

nim: Install dochack

---

packages/pulseaudio/build.sh
packages/pulseaudio/module-aaudio-sink.c

pulseaudio: changing the wrong directory

---

packages/diffstat/build.sh
packages/diffstat/diffstat.c.patch
packages/quilt/build.sh
packages/quilt/quilt-scripts-utilfns.patch
packages/quilt/quilt-setup.in.patch

new package: quilt

---

packages/dialog/build.sh
packages/libnewt/build.sh
packages/libnewt/whiptail.subpackage.sh

and add one from <a href="https://pagure.io/newt">Newt</a>.
Closes #2623.

dialog: Remove `whiptail` symlink

---

packages/krb5/build.sh
packages/krb5/lib-krb5-os-dnsglue.c.patch
packages/libresolv-wrapper/build.sh

krb5: Use libresolv-wrapper

---

packages/mruby/build.sh
packages/mruby/build_config.patch
packages/mruby/tasks-toolchains-android.rake.patch

new package: mruby

---

packages/pari/build.sh
packages/pari/config-Makefile.SH.patch
packages/pari/config-get_cc.patch
packages/pari/config-get_double_format.patch
packages/pari/config-get_gmp.patch
packages/pari/config-get_readline.patch
packages/pari/config-paricfg.h.SH.patch
packages/pari/src-language-es.c.patch
packages/pari/src-language-gplib.c.patch

new package: pari

---

packages/mympd/build.sh
packages/mympd/dist-src-libmpdclient-include-config.h.patch
packages/mympd/src-lib-http_client.c.patch
packages/mympd/src-mpd_client-mpd_client_autoconf.c.patch
packages/mympd/src-mpd_shared.c.patch
packages/mympd/src-mympd_api-mympd_api_utility.c.patch

new package: mympd

---

packages/tsmuxer/build.sh
packages/tsmuxer/tsMuxer-osdep-textSubtitlesRenderFT.cpp.patch

new package: tsmuxer

---

scripts/build/termux_step_setup_toolchain.sh
scripts/build/termux_step_start_build.sh

toolchain: Link libandroid-support with `--no-as-needed`

---

packages/wdiff/build.sh

Take 2. This pull request should not contain any previous unnecessary commits.

Add wdiff package

---

packages/squeezelite/build.sh
packages/squeezelite/squeezelite.h.patch

new package: squeezelite

---

packages/libbcprov-java/build.sh
packages/libcommons-lang3-java/build.sh
packages/pdftk/ASN1OutputStream-ctor.patch
packages/pdftk/build.sh
packages/pdftk/pdftk.patch

new package: pdftk

---

packages/bk/build.sh

Closes https://github.com/termux/termux-packages/issues/7489.

[Add package] bk 0.5.3

---

packages/geth/build.sh
packages/geth/usb.patch

Looks like auto-update is not working

geth: update to 1.10.13

---

packages/snapcast-server/CMakeLists.txt.patch
packages/snapcast-server/build.sh
packages/snapcast-server/common-CMakeLists.txt.patch
packages/snapcast-server/server-config.cpp.patch
packages/snapcast-server/server-control_session_http.cpp.patch
packages/snapcast-server/server-etc-snapserver.conf.patch
packages/snapcast-server/server-server_settings.hpp.patch
packages/snapcast-server/server-snapserver.1.patch
packages/snapcast-server/server-snapserver.cpp.patch
packages/snapcast-server/server-streamreader-airplay_stream.cpp.patch
packages/snapcast-server/test-test_main.cpp.patch

new package: snapcast-server

---

packages/liblog4c/build.sh
packages/liblog4c/src-sd-malloc.h.patch
packages/liblog4c/src-sd-stack.h.patch
packages/libmad/build.sh
packages/tizonia/build.sh
packages/tizonia/cast-libtizcastclient-src-tizcastclient_c.cc.patch
packages/tizonia/clients-chromecast-libtizchromecast-src-tizchromecast.cpp.patch
packages/tizonia/exe_wrapper
packages/tizonia/libtizplatform-src-tizrc.c.patch
packages/tizonia/meson.build.patch
packages/tizonia/player-src-tizgraphmgr.cpp.patch
packages/tizonia/player-src-tizplayapp.cpp.patch
packages/tizonia/player-src-tizprogramopts.cpp.patch
packages/tizonia/plugins-http_renderer-src-httprsrv.c.patch
packages/tizonia/plugins-meson.build.patch
packages/tizonia/rm-libtizrmproxy-src-tizrmproxy_c.cc.patch

new package: tizonia

---

packages/lnav/Makefile.am.patch
packages/lnav/build.sh
packages/lnav/src-ghc-filesystem.hpp.patch
packages/lnav/src-grep_proc.cc.patch
packages/lnav/src-line_buffer.cc.patch
packages/lnav/src-lnav.cc.patch

new package: lnav

---

packages/ckermit/build.sh
packages/ckermit/ckcdeb.h.patch
packages/ckermit/ckcftp.c.patch
packages/ckermit/ckcmai.c.patch
packages/ckermit/ckcnet.h.patch
packages/ckermit/ckucmd.c.patch
packages/ckermit/ckufio.c.patch
packages/ckermit/ckupty.c.patch
packages/ckermit/ckutio.c.patch
packages/ckermit/ckuus4.c.patch
packages/ckermit/ckuus5.c.patch
packages/ckermit/ckuusx.c.patch
packages/ckermit/makefile.patch

new package: ckermit

---

packages/gauche/build.sh
packages/gauche/src-gauche-priv-atomicP.h.patch
packages/gauche/src-libsys.c.patch

gauche: Update to 0.9.11 / Disable arm build

---

packages/stoken/build.sh
packages/stoken/src-cli.c.patch

new package: stoken

---

packages/libvbisam/build.sh
packages/libvbisam/efgcvt-dbl-macros.h
packages/libvbisam/efgcvt_r-template.c
packages/libvbisam/libvbisam-Makefile.am.patch
packages/libvbisam/vbisam.h.patch

new package: libvbisam

---

packages/tsu/build.sh

tsu: Update to 8.6.0

---

packages/pdf2djvu/build.sh

new package: pdf2djvu

---

packages/dnstop/build.sh

new package: dnstop

---

packages/broot/build.sh

new package: broot

---

packages/ncspot/Cargo.toml.patch
packages/ncspot/build.sh

new package: ncspot

---

packages/libduckdb/build.sh
packages/libduckdb/duckdb.subpackage.sh
packages/libduckdb/tools-shell-shell.c.patch

new package: duckdb

---

packages/libiodbc/build.sh
packages/libiodbc/include-sqlext.h.patch
packages/libiodbc/iodbcinst-SQLInstallDriver.c.patch
packages/libiodbc/iodbcinst-SQLInstallDriverEx.c.patch
packages/mdbtools/build.sh

new package: mdbtools

---

packages/xpup/build.sh

new package: xpup

---

packages/libpoco/Foundation-src-NamedEvent_UNIX.cpp.patch
packages/libpoco/Foundation-src-NamedMutex_UNIX.cpp.patch
packages/libpoco/Foundation-src-Path_UNIX.cpp.patch
packages/libpoco/Foundation-src-SharedMemory_POSIX.cpp.patch
packages/libpoco/build.sh

Closes #1249.
Supersedes #1408.

new package: libpoco

---

packages/zssh/Makefile.in.patch
packages/zssh/build.sh
packages/zssh/escape.c.patch
packages/zssh/misc.c.patch
packages/zssh/openpty.c.patch
packages/zssh/quote_removal.c.patch
packages/zssh/zmodem_act.c.patch

new package: zssh

---

packages/opencv/build.sh

new package: opencv

---

packages/libnfc/build.sh
packages/mfcuk/build.sh

new package: mfcuk

---

packages/gdal/build.sh

gdal: Missing compiler-rt builtins

---

packages/libuchardet/build.sh
packages/libuchardet/uchardet.subpackage.sh

new package: libuchardet

---

packages/cuetools/build.sh

new package: cuetools

---

packages/shntool/build.sh

new package: shntool

---

packages/gnustep-make/build.sh
packages/libgnustep-base/Source-NSPathUtilities.m.patch
packages/libgnustep-base/Tools-gdomap.c.patch
packages/libgnustep-base/build.sh
packages/libobjc2/build.sh
packages/libobjc2/libobjc2-2.1-eh_trampoline.patch

new package: libgnustep-base

---

packages/gnucobol/build.sh
packages/gnucobol/libcob-common.c.patch

new package: gnucobol

---

packages/plantuml/build.sh
packages/plantuml/build.xml.patch
packages/plantuml/plantuml.patch

new package: plantuml

---

packages/apr/build.sh

It has been revealed that this fixes #2027, though not originally meant to.

apr: Add configure args for cross compilation

---

packages/tizonia/build.sh
packages/tizonia/libtizplatform-src-tizthread.c.patch

tizonia: Override `PTHREAD_STACK_MIN`

---

packages/libjansi/Makefile
packages/libjansi/build.sh
packages/libjansi/src-main-native-jansi_structs.c.patch
packages/maven/build.sh

maven: Depend on libjansi

---

packages/coinor-clp/build.sh
packages/libcoinor-osi/build.sh
packages/libcoinor-utils/build.sh

new package: coinor-clp

---

packages/mercury/build.sh
packages/mercury/compiler-libs.md4.c.patch.beforehostbuild
packages/mercury/compiler-make.build.c.patch
packages/mercury/compiler-make.build.m.patch
packages/mercury/sys_sem.c

new package: mercury

---

packages/polyml/Makefile.in.patch.beforehostbuild
packages/polyml/build.sh
packages/polyml/libpolyml-basicio.cpp.patch
packages/polyml/libpolyml-osmemunix.cpp.patch
packages/polyml/libpolyml-process_env.cpp.patch
packages/polyml/modules-IntInfAsInt-Makefile.in.patch.beforehostbuild

new package: polyml

---

packages/libwavpack/build.sh
packages/libwavpack/wavpack.subpackage.sh

new package: libwavpack

---

packages/libcddb/build.sh
packages/libcddb/lib-cddb_net.c.patch

new package: libcddb

---

packages/libmusicbrainz/build.sh
packages/libmusicbrainz/libmusicbrainz-5.1.0-wildcards.patch.beforehostbuild

new package: libmusicbrainz

---

packages/unar/Makefile.linux.patch
packages/unar/XADPlatformLinux.m.patch
packages/unar/XADString.m.patch
packages/unar/build.sh
packages/unar/sys_time.c

new package: unar

---

packages/rp-pppoe/build.sh
packages/rp-pppoe/src-Makefile.in.patch

new package: rp-pppoe

---

packages/no-more-secrets/Makefile.patch
packages/no-more-secrets/build.sh

no-more-secrets: Build both with and without ncurses

---

packages/asymptote/build.sh
packages/asymptote/configure.patch
packages/libtirpc/build.sh
packages/libtirpc/types.patch

new package: asymptote

---

packages/id3lib/build.sh
packages/id3lib/configure.in.patch
packages/id3v2/Makefile.patch
packages/id3v2/build.sh

new package: id3v2

---

packages/exiftool/build.sh

exiftool: Update to 12.38

---

packages/crowbook/build.sh

new package: crowbook

---

packages/influxdb/build.sh

new package: influxdb

---

packages/monetdb/CMakeLists.txt.patch
packages/monetdb/build.sh
packages/monetdb/clients-mapiclient-mclient.c.patch
packages/monetdb/clients-mapiclient-msqldump.c.patch
packages/monetdb/gdk-CMakeLists.txt.patch
packages/monetdb/gdk-gdk_interprocess.c.patch
packages/monetdb/sys_sem.c
packages/monetdb/tools-mserver-mserver5.c.patch

new package: monetdb

---

packages/prover9/build.sh

new package: prover9

---

packages/scheme48/Makefile.in.patch
packages/scheme48/build.sh

new package: scheme48

---

packages/txikijs/CMakeLists.txt.patch.beforehostbuild
packages/txikijs/build.sh
packages/txikijs/deps-libuv-src-unix-core.c.patch
packages/txikijs/deps-libuv-src-unix-internal.h.patch
packages/txikijs/deps-wasm3-source-m3_api_wasi.c.patch
packages/txikijs/src-js-CMakeLists.txt.patch

new package: txikijs

---

packages/suite3270/Common-codepage.c.patch
packages/suite3270/Common-config.sub.patch
packages/suite3270/Common-pr3287-codepage.c.patch
packages/suite3270/b3270-Makefile.obj.in.patch
packages/suite3270/build.sh
packages/suite3270/c3270-Makefile.obj.in.patch
packages/suite3270/lib-3270-Makefile.obj.in.patch
packages/suite3270/s3270-Makefile.obj.in.patch

new package: suite3270

---

packages/posixvala/build.sh

new package: posixvala

---

packages/liblightning/build.sh

new package: liblightning

---

packages/dgsh/build.sh
packages/dgsh/core-tools-src-dgsh-tee.c.patch
packages/dgsh/core-tools-src-dgsh-w.c.patch
packages/dgsh/s_cpow.c

new package: dgsh

---

packages/libvmaf/build.sh

new package: libvmaf

---

packages/gpac/build.sh
packages/gpac/src-filters-in_dvb4linux.c.patch
packages/gpac/src-jsmods-core.c.patch
packages/gpac/src-utils-os_config_init.c.patch
packages/gpac/src-utils-os_divers.c.patch

new package: gpac

---

packages/libcec/build.sh
packages/libcec/cec-client.subpackage.sh
packages/libp8-platform/build.sh

new package: libcec

---

packages/tectonic/build.sh

new package: tectonic

---

packages/mcfly/build.sh

new package: mcfly

---

packages/peaclock/CMakeLists.txt.patch
packages/peaclock/build.sh

new package: peaclock

---

packages/choose/build.sh

new package: choose

---

packages/sd/build.sh

new package: sd

---

packages/curlie/build.sh

new package: curlie

---

packages/tealdeer/build.sh
packages/tealdeer/src-types.rs.patch

new package: tealdeer

---

packages/grex/build.sh

new package: grex

---

packages/scc/build.sh

new package: scc

---

packages/libdevil/build.sh
packages/libdevil/libdevil-1.8.0-jasper.patch

new package: libdevil

---

packages/ravencoin/build.sh
packages/ravencoin/src-leveldb-util-env_posix.cc.patch

new package: ravencoin

---

packages/monero/build.sh
packages/monero/translations-CMakeLists.txt.patch
scripts/build/setup/termux_setup_protobuf.sh

new package: monero

---

packages/texlab/build.sh

new package: texlab

---

packages/xh/build.sh

new package: xh

---

packages/mdbook-toc/build.sh

new package: mdbook-toc

---

packages/mdbook-linkcheck/build.sh

new package: mdbook-linkcheck

---

packages/mdbook-mermaid/build.sh

new package: mdbook-mermaid

---

packages/mdbook-plantuml/build.sh

new package: mdbook-plantuml

---

packages/mdbook-open-on-gh/build.sh

new package: mdbook-open-on-gh

---

packages/await/build.sh

new package: await

---

packages/desed/build.sh

new package: desed

---

packages/llama/build.sh

new package: llama

---

packages/viddy/build.sh

new package: viddy

---

packages/lipl/build.sh

new package: lipl

---

packages/up/build.sh

new package: up

---

packages/odin/build.sh

new package: odin

---

packages/miller/build.sh

new package: miller

---

packages/rip/build.sh

new package: rip

---

packages/fcp/build.sh

new package: fcp

---

packages/btfs2/build.sh
packages/btfs2/karalabe-usb-pthread_barrier.patch.diff

new package: btfs2

---

packages/cmus/build.sh

as a follow-up of ffmpeg version bump.

cmus: Bump revision to rebuild

---

packages/gst-libav/build.sh
packages/gst-libav/gst-libav-1.19.3-ffmpeg-5.0.patch

as a follow-up of ffmpeg version bump.

gst-libav: Fix build with ffmpeg 5.0

---

packages/deno/build.sh
packages/deno/ext-ffi-Cargo.toml.patch
packages/deno/runtime-ops-signal.rs.patch

new package: deno

---

packages/groff/build.sh

groff: Install files for font/devpdf

---

packages/procs/build.sh
packages/procs/procs-0.12.0-0001-Try-android-support.patch
packages/procs/procs-0.12.0-0002-Add-dependencies-for-android-223.patch
packages/procs/procs-0.12.0-0003-Add-android-to-all-cfg-223.patch
packages/procs/procs-0.12.0-0004-Fix-policy-for-android-223.patch

Closes #8567.
Supersedes #8572.

new package: procs

---

packages/mupdf/Makefile.patch
packages/mupdf/Makerules.patch
packages/mupdf/build.sh

mupdf: Build static libs

---

packages/softether-vpn/CMakeLists.txt.patch
packages/softether-vpn/build.sh
packages/softether-vpn/src-CMakeLists.txt.patch
packages/softether-vpn/src-Cedar-CMakeLists.txt.patch
packages/softether-vpn/src-Cedar-Cedar.c.patch
packages/softether-vpn/src-Mayaqua-FileIO.c.orig.patch
packages/softether-vpn/src-Mayaqua-Mayaqua.c.orig.patch
packages/softether-vpn/src-Mayaqua-Network.c.orig.patch
packages/softether-vpn/src-Mayaqua-Unix.c.orig.patch

new package: softether-vpn

---

packages/deno/build.sh

deno: Update to 1.17.3p20220119

---

packages/mono/build.sh
packages/mono/mono-utils-mono-threads-posix.c.patch

new package: mono

---

packages/grafana/bingo-Variables.mk.patch
packages/grafana/build.sh

new package: grafana

---

packages/fdm/LICENSE
packages/fdm/LICENSE.BSD
packages/fdm/build.sh
packages/fdm/configure.patch
packages/libtdb/build.sh
packages/libtdb/cross-answers.txt
packages/libtdb/tdb-tools.subpackage.sh

new package: fdm

---

packages/2048-c/build.sh

new package: 2048-c

---

packages/2048-c/build.sh

2048-c: add to group games

---

packages/cicada/build.sh

cicada: Fix build for x86_64

---

packages/mp3gain/build.sh

new package: mp3gain

---

packages/simh/LICENSE
packages/simh/build.sh
packages/simh/slirp-slirp.c.patch

new package: simh

---

packages/ngspice/build.sh
packages/ngspice/src-frontend-com_shell.c.patch
packages/ngspice/src-frontend-inp.c.patch
packages/ngspice/src-frontend-parser-complete.c.patch
packages/ngspice/src-include-ngspice-defines.h.patch

new package: ngspice

---

build-package.sh
packages/zig/build.sh
packages/zig/cmake-Findllvm.cmake.patch
scripts/build/setup/termux_setup_zig.sh
scripts/setup-offline-bundle.sh

Closes #4760.
Supersedes #7990.

add package: zig

---

packages/libfinalcut/build.sh
packages/libfinalcut/examples-Makefile.am.patch
packages/libfinalcut/examples-string-operations.cpp.patch
packages/libfinalcut/final-font-unicodemap.h.patch
packages/libfinalcut/final-output-tty-fterm.cpp.patch
packages/libfinalcut/final-output-tty-ftermlinux.h.patch
packages/libfinalcut/final-util-fstring.h.patch
packages/libfinalcut/final-util-fsystemimpl.h.patch

new package: libfinalcut

---

packages/ncpamixer/build.sh
packages/ncpamixer/src-ui-tab.cpp.patch

new package: ncpamixer

---

packages/crypto-monitor/SetPath.cmake.patch
packages/crypto-monitor/build.sh

new package: crypto-monitor

---

packages/rubiks-cube/Makefile.patch
packages/rubiks-cube/build.sh

new package: rubiks-cube

---

packages/outfieldr/build.sh
packages/outfieldr/build.zig.patch

new package: outfieldr

---

packages/libxlsxwriter/build.sh

new package: libxlsxwriter

---

packages/libxls/build.sh
packages/libxls/xls2csv.subpackage.sh

new package: libxls

---

packages/cliaoke/build.sh

new package: cliaoke

---

packages/gforth/Makefile.in.patch
packages/gforth/Makefile.in.patch.beforehostbuild
packages/gforth/arch-arm-machine.h.patch
packages/gforth/build.sh
packages/gforth/config.sub.patch
packages/gforth/preforth.in.patch
packages/gforth/prim.patch

new package: gforth

---

packages/xh/build.sh

xh: Update to 0.15.0

---

packages/rust/build.sh
packages/rust/config.toml
packages/rust/os-tmpdir.patch
scripts/setup-ubuntu.sh

rust: Update to 1.58.1

---

packages/mdbook-katex/build.sh

new package: mdbook-katex

---

packages/libunqlite/build.sh
packages/libunqlite/src-jx9_vfs.c.patch
packages/libunqlite/unqlite.c.patch

new package: libunqlite

---

packages/dynomite/build.sh
packages/dynomite/configure.ac.patch
packages/dynomite/contrib-Makefile.am.patch
packages/dynomite/src-Makefile.am.patch

new package: dynomite

---

packages/ssdb/Makefile.patch
packages/ssdb/build.sh
packages/ssdb/build.sh.patch
packages/ssdb/src-ssdb-options.cpp.patch
packages/ssdb/src-ssdb-options.h.patch
packages/ssdb/src-ssdb-server.cpp.patch
packages/ssdb/src-ssdb-ssdb_impl.cpp.patch

new package: ssdb

---

packages/libglog/CMakeLists.txt.patch
packages/libglog/build.sh
packages/librocksdb/build.sh
packages/librocksdb/env-fs_posix.cc.patch
packages/librocksdb/toku_time.h.patch
packages/librocksdb/tools-db_bench_tool.cc.patch
packages/librocksdb/tools-rdb-unit_test.js.patch
packages/pika/Makefile.patch
packages/pika/build.sh
packages/pika/include-pika_statistic.h.patch
packages/pika/src-pika_admin.cc.patch
packages/pika/src-pika_repl_client_conn.cc.patch
packages/pika/third-blackwidow-Makefile.patch
packages/pika/third-blackwidow-src-coding.h.patch
packages/pika/third-blackwidow-src-db_checkpoint.cc.patch
packages/pika/third-pink-pink-Makefile.patch
packages/pika/third-pink-pink-src-http_conn.cc.patch
packages/pika/third-slash-slash-Makefile.patch
packages/pika/third-slash-slash-src-env.cc.patch
packages/pika/third-slash-slash-src-posix.cc.patch

`pika` depends on `librocksdb`, thus two packages in one PR.
Closes #8789, closes #8791.

new package: librocksdb, pika

---

packages/libupscaledb/build.sh
packages/libupscaledb/tools-ups_bench-datasource_string.h.patch
packages/libupscaledb/upscaledb-tools.subpackage.sh

new package: libupscaledb

---

packages/nsis/build.sh

new package: nsis

---

packages/snapcast-server/build.sh
packages/snapcast-server/client-CMakeLists.txt.patch
packages/snapcast-server/client-snapclient.cpp.patch
packages/snapcast-server/snapcast-client.subpackage.sh

snapcast-server: Add subpackage snapcast-client

---

packages/libinih/build.sh
packages/pomodoro-curses/Makefile.patch
packages/pomodoro-curses/build.sh

new package: pomodoro-curses

---

packages/blade/CMakeLists.txt.patch
packages/blade/build.sh
packages/blade/src-blade_file.c.patch
packages/blade/src-standard-io.c.patch

new package: blade

---

packages/hcl/build.sh

new package: hcl

---

packages/yosys/Makefile.patch
packages/yosys/build.sh
packages/yosys/passes-sat-qbfsat.cc.patch
packages/yosys/techlibs-easic-synth_easic.cc.patch

new package: yosys

---

packages/net-snmp/agent-mibgroup-host-data_access-swinst_apt.c.patch
packages/net-snmp/agent-mibgroup-host-data_access-swinst_pkginfo.c.patch
packages/net-snmp/agent-mibgroup-host-hr_filesys.c.patch
packages/net-snmp/agent-mibgroup-host-hr_swinst.c.patch
packages/net-snmp/agent-mibgroup-host-hrh_filesys.c.patch
packages/net-snmp/agent-mibgroup-if-mib-data_access-interface_linux.c.patch
packages/net-snmp/agent-mibgroup-ip-mib-data_access-ipaddress_linux.c.patch
packages/net-snmp/apps-encode_keychange.c.patch
packages/net-snmp/apps-snmpnetstat-main.c.patch
packages/net-snmp/build.sh
packages/net-snmp/config.sub.patch
packages/net-snmp/include-net-snmp-library-types.h.patch
packages/net-snmp/include-net-snmp-session_api.h.patch
packages/snmptt/build.sh
packages/snmptt/snmptt.ini.patch

new package: net-snmp, snmptt

---

packages/libgnustep-base/build.sh
packages/libgnustep-base/configure.patch

libgnustep-base: Fix build for x86_64

---

packages/aapt/aapt2.subpackage.sh
packages/aapt/build.sh
packages/apktool/build.sh

aapt: Include aapt2

---

packages/libt3config/build.sh
packages/libt3highlight/build.sh
packages/libt3key/Makefile.in.patch
packages/libt3key/build.sh
packages/libt3widget/build.sh
packages/libt3widget/src-widgets-menu.cc.patch
packages/libt3window/build.sh
packages/libtranscript/build.sh
packages/tilde/build.sh
packages/tilde/src-main.cc.patch

new package: tilde

---

packages/oorexx/Makefile.in.patch
packages/oorexx/build.sh
packages/oorexx/common-platform-unix-SysLibrary.cpp.patch
packages/oorexx/configure.patch.beforehostbuild
packages/oorexx/extensions-platform-unix-rxunixsys-rxunixsys.cpp.patch
packages/oorexx/extensions-rexxutil-platform-unix-rexxutil.cpp.patch.beforehostbuild
packages/oorexx/interpreter-api-InterpreterAPI.cpp.patch.beforehostbuild
packages/oorexx/interpreter-api-ThreadContextStubs.cpp.patch.beforehostbuild
packages/oorexx/interpreter-platform-unix-ErrorMessages.cpp.patch.beforehostbuild
packages/oorexx/interpreter-platform-unix-ExternalFunctions.cpp.patch
packages/oorexx/interpreter-platform-unix-SystemCommands.cpp.patch

new package: oorexx

---

packages/libtvision/build.sh
packages/libtvision/include-tvision-compat-malloc-malloc.h.patch
packages/libtvision/source-CMakeLists.txt.patch

new package: libtvision

---

packages/liblua51/Makefile.patch
packages/liblua51/build.sh
packages/liblua51/lua-5.1.5-CVE-2014-5461.patch
packages/liblua51/lua.pc.in
packages/liblua51/lua51.subpackage.sh
packages/liblua51/src-Makefile.patch
packages/liblua51/src-luaconf.h.patch

new package: liblua51

---

packages/clipp/build.sh
packages/libspdlog/build.sh

clipp, libspdlog: Revbump to rebuild

---

packages/zzuf/build.sh
packages/zzuf/src-zzat.c.patch
packages/zzuf/src-zzuf.c.patch

new package: zzuf

---

packages/6tunnel/build.sh

new package: 6tunnel

---

packages/robotfindskitten/build.sh

new package: robotfindskitten

---

packages/astra-sm/build.sh
packages/astra-sm/src-astra-core-spawn.c.patch

new package: astra-sm

---

packages/libduktape/build.sh
scripts/Dockerfile
scripts/setup-ubuntu.sh

leaving as a PR for now due to limited testing

update docker image to Ubuntu 21.04

---

packages/cliaoke/build.sh
packages/cliaoke/karaoke-play_linux.go.patch

cliaoke: Fix for working with fluidsynth

---

packages/libmdbx/build.sh
packages/libmdbx/src-osal.c.patch

new package: libmdbx

---

packages/libsophia/build.sh
packages/libsophia/makefile.patch
packages/libsophia/sophia-std-ss_stdvfs.c.patch

new package: libsophia

---

build-package.sh
clean.sh
scripts/build/setup/termux_setup_cmake.sh
scripts/build/setup/termux_setup_ghc.sh
scripts/build/setup/termux_setup_gn.sh
scripts/build/setup/termux_setup_golang.sh
scripts/build/setup/termux_setup_ninja.sh
scripts/build/setup/termux_setup_rust.sh
scripts/build/termux_download_deb_pac.sh
scripts/build/termux_step_get_dependencies.sh
scripts/build/termux_step_setup_build_folders.sh
scripts/build/termux_step_setup_variables.sh
scripts/build/termux_step_start_build.sh

Change list:
1. The value of `TERMUX_PACKAGE_FORMAT` will have the same value as `TERMUX_MAIN_PACKAGE_FORMAT` if it exists.
2. Changed the logic definition of the package manager to a more stable one.
3. Bug fix #8523.

build-packages.sh: improvement and bug fixes

---

packages/libsled/bindings-sled-native-Cargo.toml.diff
packages/libsled/build.sh

new package: libsled

---

packages/libtsduck/Makefile.inc.patch
packages/libtsduck/build.sh
packages/libtsduck/src-libtsduck-Makefile.patch
packages/libtsduck/src-libtsduck-base-system-tsForkPipe.cpp.patch
packages/libtsduck/src-libtsduck-base-system-tsThread.cpp.patch
packages/libtsduck/src-libtsduck-base-types-tsPlatform.h.patch
packages/libtsduck/src-libtsduck-python-Makefile.patch
packages/libtsduck/src-tsplugins-Makefile.patch
packages/libtsduck/src-tstools-Makefile.patch
packages/libtsduck/tsduck-java.subpackage.sh
packages/libtsduck/tsduck-plugins.subpackage.sh
packages/libtsduck/tsduck-python.subpackage.sh
packages/libtsduck/tsduck-tools.subpackage.sh

new package: libtsduck

---

packages/postgresql/build.sh

postgresql: Update to 14.2

---

packages/libimtui/build.sh
packages/libimtui/hnterm.subpackage.sh

new package: libimtui

---

packages/locustdb/build.sh
packages/locustdb/nix-0.5.1-errno.diff
packages/locustdb/nix-0.5.1-sched.diff
packages/locustdb/nix-0.5.1-termios.diff
packages/locustdb/rustyline-1.0.0-ioctl.diff

new package: locustdb

---

packages/v2ray/build.sh
packages/v2ray/common-platform-others.go.patch

new package: v2ray

---

packages/wasmedge/build.sh
packages/wasmedge/cmake-Helper.cmake.patch
packages/wasmedge/getsockopt-socklen_t.patch
packages/wasmedge/lib-host-wasi-linux.h.patch

new package: wasmedge

---

packages/ipv6toolkit/GNUmakefile.patch
packages/ipv6toolkit/build.sh
packages/ipv6toolkit/tools-libipv6.h.patch
packages/ipv6toolkit/tools-scan6.c.patch
packages/ipv6toolkit/tools-script6.patch

new package: ipv6toolkit

---

packages/bsd-games/Config.mk.in.patch
packages/bsd-games/build.sh
packages/bsd-games/common-util.c.patch
packages/bsd-games/config.h.in.patch

new package: bsd-games

---

packages/gitui/build.sh

gitui: Add package

---

packages/proxmark3/build.sh

license update to gpl-3.0 for when the version is automatically bumped

proxmark3: update license

---

packages/wiz/Makefile.patch
packages/wiz/build.sh

new package: wiz

---

packages/nushell/Cargo.toml.patch
packages/nushell/build.sh

nushell: Enable x86_64 build

---

packages/go-findimagedupes/build.sh

go-findimagedupes: Bump revision to rebuild

---

packages/fte/Makefile.patch
packages/fte/build.sh
packages/fte/install.patch
packages/fte/src-cfte.cpp.patch
packages/fte/src-e_cvslog.cpp.patch
packages/fte/src-e_svnlog.cpp.patch
packages/fte/src-e_unix.cpp.patch
packages/fte/src-fte-unix.mak.patch
packages/fte/src-fte.cpp.patch

new package: fte

---

packages/groovy/AnsiRenderWriter.java
packages/groovy/bin-startGroovy.patch
packages/groovy/build.sh
packages/groovy/jline2.patch

groovy: Fix libjansi issue

---

packages/make-guile/build.sh
packages/make-guile/src-job.c.patch
packages/make-guile/src-output.c.patch

new package: make-guile

---

packages/rust/build.sh

rust: update to 1.59.0

---

packages/littlecms/build.sh

littlecms: Create symlink with soversion suffix

---

packages/gitea/build.sh

as a follow-up of commit c31ee772c293a2b0a6f458972e9fb3e14e8858d2.

gitea: Disable autoupdate

---

build-package.sh
packages/gitea/build.sh
scripts/build/setup/termux_setup_nodejs.sh

Fixes https://github.com/termux/termux-packages/issues/9226

Add termux_setup_nodejs function and enable autoupdates of gitea again

---

build-package.sh
packages/borgbackup/build.sh
packages/borgbackup/setup.py-prefixes.patch
scripts/build/setup/termux_setup_python_crossenv.sh
scripts/setup-offline-bundle.sh
scripts/setup-ubuntu.sh

borgbackup: Fix `ImportError` described in #9207

---

packages/asciidoc/build.sh

Depends on #9242 (python crossenv).

asciidoc: Update to 10.1.3

---

packages/lesspipe/build.sh
packages/lesspipe/lesspipe.sh.patch

lesspipe: Do not try to invoke `locale` command

---

scripts/build/termux_download_deb_pac.sh

termux_download_deb_pac.sh: Handle 'all' arch properly

---

packages/unpaper/build.sh

new package: unpaper

---

packages/aalib/build.sh
packages/aalib/config.sub.patch
packages/aalib/ltconfig.patch
packages/aalib/src-aalinuxkbd.c.patch
packages/aview/build.sh

new package: aview

---

packages/rig/Makefile.patch
packages/rig/build.sh

new package: rig

---

packages/gopher/Makefile.config.in.patch
packages/gopher/build.sh
packages/gopher/conf.h.patch
packages/gopher/gopher-download.c.patch
packages/gopher/gopher-gopher.c.patch

new package: gopher

---

packages/paruz/build.sh
packages/paruz/paruz.patch

new package: paruz

---

packages/tenki-php/build.sh
packages/tenki-php/tenki-php.conf

new package: tenki-php

---

packages/mplayer/build.sh
packages/mplayer/command.c.patch
packages/mplayer/configure.patch
packages/mplayer/libmpcodecs-vf_fixpts.c.patch
packages/mplayer/mplayer-1.4-CVE-2016-4352.patch

new package: mplayer

---

packages/cloudflared/build.sh

new package: cloudflared

---

packages/ndk-multilib/build.sh

ndk-multilib: add libcompiler-rt files for cross-compile

---

packages/dvdauthor/build.sh
packages/dvdauthor/src-conffile.c.patch
packages/libdvdread/build.sh

new package: dvdauthor

---

packages/rdrview/add-seccomp-rules.patch
packages/rdrview/build.sh

Patch proposed upstream: https://github.com/eafer/rdrview/pull/28
Closes #8328.

rdrview: Add seccomp rules

---

packages/aview/asciiview.patch
packages/aview/build.sh

aview: Fix hardcoded paths

---

.github/workflows/packages.yml
packages/aapt/build.sh
scripts/setup-android-sdk.sh

aapt: Use 'platforms;android-32'

---

packages/pkgfile/build.sh
packages/pkgfile/meson.build.patch
packages/pkgfile/meson_options.txt.patch
packages/pkgfile/src-update.c.patch
packages/pkgfile/src-update.h.patch

new package: pkgfile

---

packages/subtitleripper/Makefile.patch
packages/subtitleripper/build.sh

new package: subtitleripper

---

packages/jbig2enc/build.sh
packages/jbig2enc/configure.ac.patch
packages/jbig2enc/src-Makefile.am.patch

new package: jbig2enc

---

packages/sendxmpp/build.sh

new package: sendxmpp

---

packages/socat/build.sh
packages/socat/fix-format-specifiers-for-32-bit-archs.patch

* Re-enable 32-bit builds
Closes #9378.

socat: Update to 1.7.4.3

---

packages/mcfly/build.sh
packages/mcfly/src-settings.rs.patch

mcfly: Disable broken Bash support

---

packages/python-apt/build.sh
packages/python-apt/setuptools-44.1.1-no-bdist_wininst.diff

new package: python-apt

---

packages/matplotlib/Pillow-setup.py.patch
packages/matplotlib/build.sh
packages/matplotlib/mplsetup.cfg.patch
packages/matplotlib/setup.py.patch
packages/matplotlib/setuptools-44.1.1-no-bdist_wininst.diff

new package: matplotlib

---

packages/yq/build.sh

new package: yq

---

packages/pypy/aarch64-cc.sh
packages/pypy/added.patch
packages/pypy/arm-cc.sh
packages/pypy/build.sh
packages/pypy/fix-hardcoded-pathes.patch
packages/pypy/fix-loaded-libs.patch
packages/pypy/fix-not-available-functions.patch
packages/pypy/package-zip.patch
packages/pypy/pypy-tkinter.subpackage.sh
packages/pypy/termux-build.patch
scripts/setup-ubuntu.sh

Closes #1265.
Continuation of #9302.

new package: pypy

---

packages/libwavpack/build.sh
packages/libwavpack/wavpack-5.4.0-sanitize-DSD-file-types.patch
packages/libwavpack/wavpack.subpackage.sh

from https://github.com/dbry/WavPack/commit/773f9d0803c6888ae7d5391878d7337f24216f4a.

libwavpack: Add security patch

---

packages/pngcrush/build.sh

new package: pngcrush

---

packages/ipv6calc/build.sh
packages/ipv6calc/lib-Makefile.in.patch
packages/ipv6calc/tools-ipv6calc-create-update-ipset.sh.patch
packages/ipv6calc/tools-ipv6calc-db-update.sh.in.patch

new package: ipv6calc
