termux/termux-packages

packages/pypy3/aarch64-cc.sh
packages/pypy3/added.patch
packages/pypy3/arm-cc.sh
packages/pypy3/build.sh
packages/pypy3/fix-hardcoded-pathes.patch
packages/pypy3/fix-loaded-libs.patch
packages/pypy3/fix-not-available-functions.patch
packages/pypy3/package-zip.patch
packages/pypy3/pypy3-tkinter.subpackage.sh
packages/pypy3/termux-build.patch

new package: pypy3

---

packages/fluidsynth/build.sh

https://github.com/FluidSynth/fluidsynth/releases/tag/v2.2.6

fluidsynth: update to 2.2.6

---

packages/transcode/build.sh
packages/transcode/configure.in.patch
packages/transcode/export-ffmpeg_cfg.c.patch.txt
packages/transcode/filter-filter_compare.c.patch
packages/transcode/filter-filter_text.c.patch
packages/transcode/filter-parse_csv.awk.in.patch
packages/transcode/filter-preview-filter_pv.c.patch
packages/transcode/import-clone.c.patch
packages/transcode/import-dvd_reader.c.patch
packages/transcode/import-import_mplayer.c.patch
packages/transcode/import-import_vnc.c.patch
packages/transcode/pvm3-tcpvmexportd.c.patch
packages/transcode/src-tc_defaults.h.patch
packages/transcode/src-transcode.c.patch
packages/transcode/tools-avisync.c.patch

new package: transcode

---

packages/mplayer/build.sh

mplayer: Depend on libdvdread

---

packages/inetutils/build.sh
packages/whois/build.sh

new package: whois

---

packages/libsndfile/build.sh

Disable MP3 support to avoid cyclic dependency.

libsndfile: Update to 1.1.0

---

packages/dmtx-utils/build.sh
packages/libdmtx/build.sh

new package: dmtx-utils

---

packages/waypipe/build.sh
packages/waypipe/meson.build.patch
packages/waypipe/src-meson.build.patch
packages/waypipe/src-platform.c.patch
packages/waypipe/src-util.c.patch
packages/waypipe/src-waypipe.c.patch

new package: waypipe

---

packages/picocom/build.sh

new package: picocom

---

packages/anacron/Makefile.patch
packages/anacron/anacron.8.patch
packages/anacron/anacrontab.5.patch
packages/anacron/build.sh
packages/anacron/global.h.patch
packages/anacron/gregor.c.patch
packages/anacron/obstack.h
packages/anacron/readtab.c.patch
packages/anacron/runjob.c.patch

new package: anacron

---

packages/profanity/build.sh
packages/profanity/cmd_funcs.c.patch
packages/profanity/configure.ac.patch

fix(profanity): update to 0.12.0 and add `libstrophe` to depends

---

packages/ani-cli/build.sh

new package: ani-cli

---

packages/awesomeshot/build.sh

new package: awesomeshot

---

packages/photon-rss/build.sh

new package: photon-rss

---

packages/ratt/build.sh

new package: ratt

---

packages/lsix/build.sh

new package: lsix

---

packages/matterbridge/build.sh

new package: matterbridge

---

packages/hut/Makefile.patch
packages/hut/build.sh

new package: hut

---

packages/senpai/build.sh

new package: senpai

---

packages/pingme/build.sh

new package: pingme

---

packages/ytfzf/Makefile.patch
packages/ytfzf/build.sh
packages/ytfzf/ytfzf.patch

new package: ytfzf

---

packages/2ping/build.sh

new package: 2ping

---

packages/libnats-c/CMakeLists.txt.patch
packages/libnats-c/build.sh
packages/libnats-c/src-libnats.pc.in.patch

new package: libnats-c

---

packages/gomuks/build.sh
packages/libolm/build.sh
packages/libolm/olm.pc.in.patch

new package: gomuks

---

packages/amfora/build.sh

new package: amfora

---

packages/hello/build.sh

new package: hello

---

packages/libretls/LICENSE
packages/libretls/build.sh

Signed-off-by: Yonle <yonle@duck.com>

New Package: libretls

---

packages/bitlbee/bitlbee.conf.patch
packages/bitlbee/build.sh
packages/bitlbee/configure.patch
packages/bitlbee/ipc.c.patch
packages/bitlbee/otr.c.patch
packages/bitlbee/protocols-purple-ft-direct.c.patch
packages/bitlbee/protocols-purple-ft.c.patch
packages/bitlbee/utils-bitlbeed.c.patch

new package: bitlbee

---

packages/rdircd/build.sh

new package: rdircd

---

CODEOWNERS
packages/rxfetch-termux/build.sh

rxfetch-termux: Add package

---

packages/miniflux/Makefile.patch
packages/miniflux/build.sh

new package: miniflux

---

packages/pounce/bounce.h.patch
packages/pounce/build.sh
packages/pounce/pounce.1.patch
packages/pounce/xdg.c.patch

new package: pounce

---

packages/mautrix-whatsapp/build.sh

new package: mautrix-whatsapp

---

packages/catgirl/build.sh
packages/catgirl/catgirl.1.patch
packages/catgirl/chat.h.patch
packages/catgirl/command.c.patch
packages/catgirl/xdg.c.patch

new package: catgirl

---

packages/catimg/build.sh

new package: catimg

---

packages/biboumi/CMakeLists.txt.patch
packages/biboumi/build.sh
packages/biboumi/cmake-Modules-FindGCRYPT.cmake.patch

new package: biboumi

---

CODEOWNERS
packages/rxfetch/build.sh

Termux support merged upstream: https://github.com/Mangeshrex/rxfetch/pull/45

Package original rxfetch

---

packages/openexr2/build.sh

new package: openexr2

---

packages/liba52/a52dec.subpackage.sh
packages/liba52/build.sh

new package: liba52

---

packages/libtwolame/build.sh
packages/libtwolame/twolame.subpackage.sh

new package: libtwolame

---

packages/libbluray/build.sh
packages/libbluray/libbluray-utils.subpackage.sh
packages/libudfread/build.sh

new package: libbluray

---

packages/udftools/build.sh
packages/udftools/pktsetup-pktsetup.c.patch

new package: udftools

---

packages/libxv/build.sh

new package: libxv

---

packages/gluelang/build.sh
packages/gluelang/src-Makefile.patch
packages/gluelang/src-main.cc.patch

new package: gluelang

---

packages/make-guile/build.sh

make-guile: fix conflict with make when installing base-devel

---

packages/slashtime/build.sh
packages/slashtime/slashtime.pl.patch

new package: slashtime

---

packages/zipios/build.sh

new package: zipios

---

packages/cccc/build.sh

new package: cccc

---

packages/1oom/build.sh
packages/1oom/src-os-unix-os.c.patch

new package: 1oom

---

packages/z-push/build.sh
packages/z-push/config-apache2-z-push-autodiscover.conf.patch
packages/z-push/config-apache2-z-push.conf.patch
packages/z-push/src-autodiscover-config.php.patch
packages/z-push/src-backend-imap-config.php.patch
packages/z-push/src-backend-imap-imap.php.patch
packages/z-push/src-backend-kopano-checkshares.php.patch
packages/z-push/src-backend-kopano-config.php.patch
packages/z-push/src-backend-kopano-listfolders.php.patch
packages/z-push/src-backend-vcarddir-config.php.patch
packages/z-push/src-config.php.patch

new package: z-push

---

packages/yuma123/build.sh
packages/yuma123/netconf-man-netconf-subsystem.1.patch
packages/yuma123/netconf-man-netconfd.1.patch
packages/yuma123/netconf-man-yangcli.1.patch
packages/yuma123/netconf-man-yangdiff.1.patch
packages/yuma123/netconf-man-yangdump.1.patch
packages/yuma123/netconf-src-agt-agt.h.patch
packages/yuma123/netconf-src-agt-agt_ncxserver.h.patch
packages/yuma123/netconf-src-mgr-mgr_ses.c.patch
packages/yuma123/netconf-src-ncx-ncxconst.h.patch
packages/yuma123/netconf-src-ncx-ncxmod.c.patch
packages/yuma123/netconf-src-ncx-ncxmod.h.patch
packages/yuma123/netconf-src-ncx-val.c.patch
packages/yuma123/netconf-src-subsys-netconf-subsystem.c.patch
packages/yuma123/netconf-src-yangcli-yangcli.h.patch
packages/yuma123/netconf-src-yangdiff-yangdiff.h.patch
packages/yuma123/netconf-src-yangrpc-example-yangrpc-example.c.patch
packages/yuma123/netconf-src-yangrpc-example-yangrpc-parse-example.c.patch
packages/yuma123/netconf-src-ydump-yangdump.h.patch

new package: yuma123

---

packages/fact++/build.sh
packages/fact++/src-CMakeLists.txt.patch
packages/fact++/src-FaCT++-CMakeLists.txt.patch
packages/fact++/src-FaCT++.C-CMakeLists.txt.patch
packages/fact++/src-Kernel-AtomicDecomposer.cpp.patch

new package: fact++

---

packages/ldc/build.sh

ldc: Set `DT_RUNPATH` for dub (and other tools)

---

packages/vlc/build.sh
packages/vlc/configure.ac.patch
packages/vlc/modules-audio_output-Makefile.am.patch
packages/vlc/modules-codec-Makefile.am.patch
packages/vlc/modules-demux-Makefile.am.patch
packages/vlc/modules-keystore-Makefile.am.patch
packages/vlc/modules-keystore-file_crypt.h.patch
packages/vlc/modules-video_output-Makefile.am.patch
packages/vlc/src-Makefile.am.patch
packages/vlc/src-network-getaddrinfo.c.patch
packages/vlc/src-posix-filesystem.c.patch
packages/vlc/vlc-3.0.17.3-dav1d-1.0.patch

new package: vlc

---

packages/glib-networking/build.sh
packages/glib-networking/tls-meson.build.patch

new package: glib-networking

---

packages/vlc/build.sh
packages/vlc/configure.ac.patch
scripts/setup-ubuntu.sh

vlc: Enable Lua support

---

packages/hash-slinger/build.sh
packages/hash-slinger/openpgpkey.patch
packages/hash-slinger/tlsa.patch

new package: hash-slinger

---

packages/ccextractor/build.sh
packages/ccextractor/src-CMakeLists.txt.patch
packages/ccextractor/src-lib_ccx-CMakeLists.txt.patch
packages/ccextractor/src-lib_ccx-ccx_sub_entry_message.pb-c.h.patch
packages/ccextractor/src-lib_ccx-params.c.patch

new package: ccextractor

---

packages/libdvbpsi/build.sh
packages/vlc/build.sh

vlc: Depend on libdvbpsi

---

packages/polyml/build.sh

polyml: Link against compiler-rt builtins

---

packages/autoconf-archive/autoconf-archive-2022.02.11-python-3.10.patch
packages/autoconf-archive/build.sh

new package: autoconf-archive

---

packages/syncthing/build.sh

syncthing: Prefix `v` to version string

---

packages/game-music-emu/build.sh
packages/game-music-emu/player-CMakeLists.txt.patch

new package: game-music-emu

---

packages/below/below-config-src-lib.rs.patch
packages/below/build.sh
packages/below/libbpf-sys-0.6.0-1-libbpf-include-linux-compiler.h.diff
packages/below/libbpf-sys-0.6.0-1-libbpf-include-linux-types.h.diff
packages/below/nix-0.22.0-src-sys-statfs.rs.diff
packages/below/nix-0.23.1-src-sys-statfs.rs.diff
scripts/setup-ubuntu.sh

new package: below

---

packages/ssdeep/Makefile.am.patch
packages/ssdeep/build.sh

new package: ssdeep

---

packages/libimagequant/build.sh
packages/pngquant/build.sh

* pngquant: Update to 2.17.0 and depend on libimagequant
Closes #9969.

new package: libimagequant

---

packages/chibicc/build.sh
packages/chibicc/main.c.patch

new package: chibicc

---

packages/panda3d/build.sh
packages/panda3d/dtool-src-dtoolutil-filename.cxx.patch
packages/panda3d/makepanda-installpanda.py.patch
packages/panda3d/panda3d-samples.subpackage.sh

new package: panda3d

---

packages/lilv/build.sh
packages/lilv/src-filesystem.c.patch
packages/lilv/wscript.patch
packages/lv2/build.sh
packages/serd/build.sh
packages/sord/build.sh
packages/sratom/build.sh

new package: lilv

---

scripts/build/termux_step_override_config_scripts.sh

build-package: Apply `$PREFIX/bin/sh` hack appropriately

---

packages/suil/build.sh

new package: suil

---

packages/rust/build.sh

rust: update to 1.60.0

---

packages/bdsup2sub/build.sh
packages/bdsup2sub/src-Manifest.txt
packages/srt2vobsub/build.sh
packages/srt2vobsub/defaults.conf.patch
packages/srt2vobsub/srt2vobsub.py.patch

new package: srt2vobsub

---

packages/binutils-is-llvm/LICENSE
packages/binutils-is-llvm/build.sh

Mostly for user's convenience. Partially addresses #8191 and #9715.

new package: binutils-is-llvm

---

packages/vobsub2srt/CMakeLists.txt.patch
packages/vobsub2srt/build.sh

new package: vobsub2srt

---

packages/tex-gyre/build.sh

new package: tex-gyre

---

packages/neovim/build.sh

fix(nvim): error: failed to initialize builtin lua modules

---

packages/hunspell-hu/build.sh
packages/hunspell-nl/build.sh

new package: hunspell-{hu,nl}

---

packages/starship/Cargo.toml.patch
packages/starship/build.sh

chore(starship): update to 1.6.2

---

packages/lilypond/build.sh
scripts/setup-ubuntu.sh

new package: lilypond

---

packages/youtubedr/build.sh

feat(youtubedr): add shell completions

---

packages/xdelta3/build.sh

xdelta3: Define `_FILE_OFFSET_BITS` before `#include`s

---

packages/speedtest-go/build.sh

new package: speedtest-go

---

x11-packages/xpdf/build.sh

xpdf: Remove files conflicting with poppler

---

packages/go-findimagedupes/build.sh

go-findimagedupes: Update to 2022.02.23

---

x11-packages/vlc-qt/build.sh
x11-packages/vlc-qt/configure.ac.patch
x11-packages/vlc-qt/modules-audio_output-Makefile.am.patch
x11-packages/vlc-qt/modules-codec-Makefile.am.patch
x11-packages/vlc-qt/modules-demux-Makefile.am.patch
x11-packages/vlc-qt/modules-keystore-Makefile.am.patch
x11-packages/vlc-qt/modules-keystore-file_crypt.h.patch
x11-packages/vlc-qt/modules-video_output-Makefile.am.patch
x11-packages/vlc-qt/src-Makefile.am.patch
x11-packages/vlc-qt/src-network-getaddrinfo.c.patch
x11-packages/vlc-qt/src-posix-filesystem.c.patch
x11-packages/vlc-qt/vlc-3.0.17.3-dav1d-1.0.patch

Closes #10121. Supersedes #10243.

new package: vlc-qt

---

x11-packages/sdl-pango/build.sh

new package: sdl-pango

---

x11-packages/sdl-gfx/build.sh

new package: sdl-gfx

---

x11-packages/glfw/build.sh
x11-packages/glfw/src-x11_init.c.patch

new package: glfw

---

x11-packages/sfml/build.sh
x11-packages/sfml/cmake-Config.cmake.patch
x11-packages/sfml/src-SFML-Window-CMakeLists.txt.patch

new package: sfml

---

x11-packages/gtk3-nocsd/build.sh
x11-packages/gtk3-nocsd/gtk3-nocsd.in.patch

new package: gtk3-nocsd

---

x11-packages/gtksourceview4/build.sh

new package: gtksourceview4

---

x11-packages/mousepad/build.sh

new package: mousepad

---

x11-packages/xwayland/build.sh

xwayland: Remove files conflicting with xorg-server

---

packages/zoxide/build.sh

copy manpages recursively
fix #10306

fix(zoxide): add `-r` options to `cp`, update to 0.8.1

---

x11-packages/lxqt-panel/build.sh

fix(lxqt-panel): add `libxtst` to depends, update to 1.1.0

---

x11-packages/st/build.sh
x11-packages/st/x.c-xsettitle-check-return-value.patch

by checking return value of `Xutf8TextListToTextProperty()`.
Fixes #10124.

st: Fix invalid `free()` in `xsettitle()`

---

packages/zstd/build.sh
packages/zstd/pzstd.subpackage.sh

zstd: Include pzstd

---

packages/libarrow-cpp/build.sh
packages/libarrow-cpp/cpp-src-arrow-util-io_util.cc.patch

new package: libarrow-cpp

---

x11-packages/dunst/build.sh
x11-packages/dunst/prefix.patch

Still don't know if it works...

New package:dunst

---

packages/fluidsynth/build.sh

https://github.com/FluidSynth/fluidsynth/releases/tag/v2.2.7

Fluidsynth: Update to 2.2.7

---

x11-packages/scite/build.sh
x11-packages/scite/lexilla-src-makefile.patch
x11-packages/scite/scintilla-gtk-makefile.patch
x11-packages/scite/scite-gtk-makefile.patch

new package: scite

---

scripts/bin/update-packages

- Now auto update will be disable until issue is closed.
- Assign to GITHUB_ACTOR. Myself if GITHUB_ACTOR is Termux bot.

refactor(auto-update): do not append same log again

---

scripts/generate-bootstraps.sh

#10256
So far only done for `generate-bootstraps.sh`.  Already tested everything, it works fine.  I'll work on improving `build-bootstraps.sh` later.

generate-bootstraps.sh: adding a way to generate bootstrap based on pacman

---

x11-packages/glfw/build.sh
x11-packages/glfw/src-wl_init.c.patch
x11-packages/glfw/src-wl_platform.h.patch
x11-packages/glfw/src-x11_init.c.patch
x11-packages/glfw/src-x11_window.c.patch
x11-packages/sfml/build.sh
x11-packages/sfml/include-SFML-Config.hpp.patch
x11-packages/sfml/src-SFML-System-Unix-ThreadImpl.cpp.patch

glfw, sfml: Fix unresolved symbols issue

---

x11-packages/xboard/build.sh
x11-packages/xboard/menus.c.patch
x11-packages/xboard/xaw-xboard.c.patch

new package: xboard

---

x11-packages/raylib/build.sh

new package: raylib

---

packages/libmp3lame/build.sh
x11-packages/audacity/CMakeLists.txt.patch
x11-packages/audacity/build.sh
x11-packages/audacity/cmake-proxies-portaudio-v19-CMakeLists.txt.patch
x11-packages/audacity/cmake-proxies-portmidi-CMakeLists.txt.patch
x11-packages/audacity/cmake-proxies-wxWidgets-CMakeLists.txt.patch
x11-packages/audacity/lib-src-libnyquist-nyquist-cmt-midifns.c.patch
x11-packages/audacity/src-AudacityApp.cpp.patch
x11-packages/audacity/src-AudioIOBase.cpp.patch
x11-packages/audacity/src-CMakeLists.txt.patch
x11-packages/audacity/src-MixerBoard.cpp.patch

new package: audacity

---

scripts/bin/check-auto-update

- add checks for 'newest-tag' as fallback, if 'latest-release-tag' is not found
- adhere to DRY principle

feat(scripts/check-auto-update): improve script, minor clean up

---

packages/ghostscript/build.sh

ghostscript: Update to 9.56.1

---

x11-packages/abiword/abiword-3.0.4-enchant-2.patch
x11-packages/abiword/build.sh
x11-packages/abiword/configure.ac.patch
x11-packages/abiword/plugins-command-xp-AbiCommand.cpp.patch
x11-packages/abiword/src-wp-ap-gtk-ap_UnixApp.cpp.patch

new package: abiword

---

x11-packages/gnumeric/build.sh
x11-packages/gnumeric/configure.patch

new package: gnumeric

---

x11-packages/bluefish/build.sh

new package: bluefish

---

x11-packages/pong2/build.sh
x11-packages/pong2/configure.ac.patch

new package: pong2

---

packages/ani-cli/build.sh

Updated ani-cli to 2.1
edited only build.sh
added ffmpeg as new dependency, according to the readme for 2.1

ani-cli: update to 2.1

---

x11-packages/xournalpp/build.sh
x11-packages/xournalpp/no-execinfo.patch

new package: xournalpp

---

x11-packages/lenmus/CMakeLists.txt.patch
x11-packages/lenmus/build.sh
x11-packages/lenmus/use-pulseaudio.patch
x11-packages/lenmus/wx-3.1.patch

new package: lenmus

---

scripts/setup-ubuntu.sh
x11-packages/gimp/build.sh
x11-packages/gimp/gimp-data.subpackage.sh

new package: gimp

---

x11-packages/texstudio/build.sh
x11-packages/texstudio/texstudio-data.subpackage.sh

new package: texstudio

---

x11-packages/ocs-url/build.sh
x11-packages/ocs-url/scripts-prepare.patch

new package: ocs-url

---

x11-packages/kid3/build.sh
x11-packages/kid3/src-core-model-kid3application.cpp.patch
x11-packages/kid3/src-plugins-acoustidimport-ffmpegfingerprintdecoder.cpp.patch

new package: kid3

---

x11-packages/tuxpaint/Makefile.patch
x11-packages/tuxpaint/build.sh
x11-packages/tuxpaint/src-tuxpaint-import.sh.patch
x11-packages/tuxpaint/src-tuxpaint.conf.patch
x11-packages/tuxpaint/tuxpaint-data.subpackage.sh

new package: tuxpaint

---

packages/git/build.sh
packages/git/config.mak.uname.patch

git: update to 2.36.0

---

packages/libandroid-execinfo/LICENSE
packages/libandroid-execinfo/build.sh
packages/libandroid-execinfo/execinfo.c
packages/libandroid-execinfo/execinfo.h

new package: libandroid-execinfo

---

root-packages/docker/build.sh

docker: update to 20.10.14

---

x11-packages/tuxpaint/Makefile.patch
x11-packages/tuxpaint/build.sh
x11-packages/tuxpaint/static-inline.patch

tuxpaint: Fix unresolved symbols in plugins

---

x11-packages/xfce4-dev-tools/Makefile.am.patch
x11-packages/xfce4-dev-tools/build.sh
x11-packages/xfce4-dev-tools/scripts-xdt-autogen.in.patch

new package: xfce4-dev-tools

---

x11-packages/olivia/build.sh

new package: olivia

---

x11-packages/pyqt5/build.sh
x11-packages/pyqt5/cxx-wrapper
x11-packages/pyqt5/pylupdate5.in
x11-packages/pyqt5/pyrcc5.in
x11-packages/pyqt5/pyuic5.in

new package: pyqt5

---

x11-packages/azpainter/build.sh
x11-packages/azpainter/no-librt.patch

update to official azpainter v3.0.5

---

packages/libcairomm-1.16/build.sh
packages/libglibmm-2.68/build.sh
packages/libpangomm-2.48/build.sh
packages/libsigc++-3.0/build.sh
x11-packages/gtkmm4/build.sh

new package: gtkmm4

---

packages/zsh/build.sh

zsh: Remove compdef pkg not suitable for Termux

---

packages/gh/build.sh

gh: add shell completions

---

packages/qemu-system-x86-64-headless/build.sh
packages/qemu-system-x86-64-headless/qemu-common.subpackage.sh
x11-packages/qemu-system-x86-64/build.sh

Allows host-guest communication such as time synchronization, filesystem thaw/freeze and better serial console access

qemu: enable guest agent

---

x11-packages/polyphone/build.sh
x11-packages/polyphone/sources-context-audiodevice.cpp.patch
x11-packages/polyphone/sources-polyphone.pro.patch

new package: polyphone

---

x11-packages/2bwm/LICENSE.2bwm
x11-packages/2bwm/LICENSE.hidden
x11-packages/2bwm/Makefile.patch
x11-packages/2bwm/build.sh

new package: 2bwm

---

packages/libx264/build.sh
packages/libx264/x264.subpackage.sh

libx264: add completion

---

packages/nginx/build.sh

--with-stream enables the TCP and UDP proxy functionality.
close: #10541

feat(nginx): enable stream and stream-ssl support

---

packages/ovmf/build.sh

https://github.com/termux-pacman/termux-packages/actions/runs/2284379213

ovmf: fix download source

---

packages/taskwarrior/build.sh

taskwarrior: Install shell compdefs

---

packages/texinfo/build.sh
packages/update-info-dir/build.sh
packages/update-info-dir/update-info-dir.8.patch
packages/update-info-dir/update-info-dir.patch

* texinfo: Recommend update-info-dir
Closes #10064.

new package: update-info-dir

---

packages/libopencore-amr/build.sh

I create this package for adding amr codec support to ffmpeg.
I built this package in docker environment and successfully tested in an Android device.

new package: libopencore-amr

---

scripts/setup-ubuntu.sh
x11-packages/libhandy-0.0/build.sh
x11-packages/news-flash-gtk/build.sh

new package: news-flash-gtk

---

packages/helix/build.sh
packages/lua-language-server/build.sh

- install to $PREFIX/share instead of $PREFIX/lib
- this seems more compliant to unix fhs

fix: file system hierarchy

---

x11-packages/libadwaita/build.sh

new package: libadwaita

---

packages/psutils/build.sh

- feat: add new package libpaper-rrthomas
- chore(psutils): update to 2.09

Fix auto update failing for psutils

---

packages/php7/build.sh

php7: Fix linking against openssl

---

x11-packages/kitty/build.sh
x11-packages/kitty/kitty-cross-platform-random.h.patch
x11-packages/kitty/kitty-safe-wrappers.h.patch
x11-packages/kitty/posix-shm.c.in
x11-packages/kitty/setup.py.patch

Merge should be after `mesa` update (#10597).
Closes #10126.

new package: kitty

---

packages/git-delta/build.sh

git-delta: Update to 0.13.0

---

packages/bore/build.sh

feat: add new package bore

---

x11-packages/fontforge-gtk/build.sh
x11-packages/fontforge-gtk/fontforge-cvundoes.c.patch
x11-packages/fontforge-gtk/fontforgeexe-displayfonts.c.patch
x11-packages/fontforge-gtk/fontforgeexe-lookupui.c.patch
x11-packages/fontforge-gtk/fontforgeexe-prefs.c.patch
x11-packages/fontforge-gtk/gutils-fsys.c.patch

new package: fontforge-gtk

---

packages/neovim-nightly/build.sh

fix(neovim-nightly): update version extraction regex

---

x11-packages/epiphany/build.sh
x11-packages/epiphany/getrandom.patch
x11-packages/epiphany/meson.build.patch
x11-packages/libdazzle/build.sh
x11-packages/libdazzle/meson.build.patch
x11-packages/libdazzle/src-util-dzl-counter.c.patch

new package: epiphany

---

x11-packages/polybar/build.sh

~~Still not sure is it work or not...~~
It work! Devs can merge now...

polybar:enable i3 support

---

disabled-packages/bytepath/build.sh
disabled-packages/bytepath/main.lua.patch

Disabled due to unclear license.
Closes #10084.

new disabled package: bytepath

---

x11-packages/gnome-desktop3/build.sh
x11-packages/gnome-desktop3/libgnome-desktop-meson.build.patch
x11-packages/gnome-font-viewer/build.sh
x11-packages/gnome-font-viewer/fix-build-with-meson-0.60.0.patch
x11-packages/gnome-font-viewer/meson.build.patch

new package: gnome-font-viewer

---

packages/libzxing-cpp/build.sh

new package: libzxing-cpp

---

x11-packages/gtk4/avoid-using-opengl-renderer.patch
x11-packages/gtk4/build.sh

gtk4: Avoid using OpenGL renderer

---

x11-packages/pulseeffects/build.sh
x11-packages/pulseeffects/fix-type-of-local-variables.patch

pulseeffects: Fix type of local variables

---

packages/lv2/build.sh

lv2: Fix package dependencies

---

packages/nodejs/avoid-ficlone-ioctl.patch
packages/nodejs/build.sh
packages/nodejs/deps-uv-src-unix-core.c.patch
packages/nodejs/deps-uv-src-unix-process.c.patch
packages/nodejs/deps-uv-uv.gyp.patch
packages/nodejs/deps-v8-src-flags-flag-definitions.h.patch
packages/nodejs/deps-v8-src-logging-log.cc.patch
packages/nodejs/deps-v8-src-trap-handler-trap-handler.h.patch
packages/nodejs/fix_multiple_definitions.patch
packages/nodejs/lib-child_process.js.patch
packages/nodejs/lib-internal-test_runner-test.js.patch
packages/nodejs/lib-os.js.patch
packages/nodejs/node.gyp.patch
packages/nodejs/src-debug_utils.cc.patch
packages/nodejs/src-getaddrinfo.patch
packages/nodejs/src-node_internals.h.patch
packages/nodejs/src-node_main.cc.patch
packages/nodejs/src-node_os.cc.patch
packages/nodejs/tools-v8_gypfiles-toolchain.gypi.patch
packages/nodejs/tools-v8_gypfiles-v8.gyp.patch

Do not expect to get this merged soon. Will need to test this and maybe also fix builds

upgpkg(main/nodejs): update to v18.2.0

---

packages/wasmer/build.sh
packages/wasmer/lib_vm_src_trap_traphandlers.rs.patch

Took way too long to figure things out

wasmer: update to 2.2.1

---

packages/starship/build.sh
packages/starship/getloadavg.diff

upgpkg(starship): update to 1.7.1

---

packages/terraform/build.sh

add(main): new package terraform

---

packages/fd/build.sh
packages/hyperfine/build.sh

- enhance(main/fd): add shell auto-completions
- enhance(main/hyperfine): add shell auto-completions
Closes #10586

Add fd and hyperfine shell completions

---

packages/termux-tools/build.sh
packages/termux-tools/notify-send

This PR adds a wrapper script over `termux-notification` to mimic freedesktop's `notify-send`
https://github.com/termux/termux-packages/issues/9923

notify-send: add a wrapper script over termux-notification

---

packages/pipewire/build.sh
packages/pipewire/pthread_cancel.patch
packages/pipewire/reallocarray.c
packages/pipewire/reallocarray.diff
packages/pipewire/runtime_dir.patch
scripts/build/setup/meson_libintl.patch
scripts/build/setup/termux_setup_meson.sh

add(main): new package pipewire

---

packages/chicken/Makefile.android.patch
packages/chicken/build.sh
packages/chicken/runtime.c.patch

add(main): new package chicken

---

packages/tmux/build.sh
packages/tmux/configure.ac.patch

- update `configure.ac.patch`
- configure to set `screen-256color` as default TERM
Closes #10872

upgpkg(tmux): update to 3.3

---

packages/tergent/build.sh

Also remove v0.X / v1.X incompatbility warning and add support for debug builds
Tested on aarch64 and arm.

tergent: add support for arm and i686

---

packages/nodejs/build.sh
packages/nodejs/node.gyp.patch
packages/nodejs/src-node_report.cc.patch
packages/nodejs/test-parallel-test-blob-buffer-too-large.js.patch
packages/nodejs/test-parallel-test-child-process-exec-env.js.patch
packages/nodejs/test-parallel-test-child-process-spawnsync-shell.js.patch
packages/nodejs/test-parallel-test-child-process-stdio-overlapped.js.patch
packages/nodejs/test-parallel-test-dgram-bind-fd.js.patch
packages/nodejs/test-parallel-test-dgram-membership.js.patch
packages/nodejs/test-parallel-test-dgram-socket-buffer-size.js.patch
packages/nodejs/test-parallel-test-gc-http-client-connaborted.js.patch
packages/nodejs/test-sequential-test-gc-http-client-onerror.js.patch
packages/nodejs/test-sequential-test-gc-http-client.js.patch

Need to run the tests as usual before merging

upgpkg(main/nodejs): update to v18.3.0

---

packages/ipfs/build.sh

upgpkg(ipfs): update to 0.13.0

---

packages/ciso/Makefile.patch
packages/ciso/build.sh

Hopefully I've done this corrrectly.

Add package ciso

---

packages/alist/build.sh

add(main): new package alist

---

packages/glab-cli/build.sh

add(main): new package glab-cli

---

packages/fish/build.sh
packages/fish/src-path.cpp.patch

upgpkg(main/fish): update to 3.5.0

---

packages/git/build.sh
packages/git/disable-fdsan.patch

git: disable fdsan

---

packages/cookcli/Sources-CookCLI-CookCLI.swift.patch
packages/cookcli/build.sh
packages/cookcli/cook-dependencies.diff
scripts/build/setup/termux_setup_swift.sh
scripts/build/termux_step_massage.sh

Finally got this working, though it won't work for aarch64 unless built natively in the Termux app, because the upstream Swift 5.6 compiler for linux still doesn't have my memory-tagging fix, while our native Termux compiler does. The upcoming 5.7 will fix that, but getting this in in the meantime.

addpkg(main/cookcli): command-line tool written in Swift to help manage cooking and shopping for food

---

packages/neovim-nightly/build.sh
packages/neovim-nightly/src-nvim-os-stdpaths.c.patch

* updated `src-nvim-os-stdpaths.patch`
Closes #11121

upgpkg(main/neovim-nightly): to `0.8.0-dev+538-ga9de89894`

---

packages/matterircd/build.sh
packages/peco/build.sh
packages/pet/build.sh

add(main): new package pet, peco and matterircd

---

packages/vale/build.sh

add(main): new package vale

---

packages/mu/mu4e-dont-bytecompile-meson.patch

* byte-compilation has not been made optional. I wrongly interpreted the
commit message. Thanks to @m4lvin for pointing out.
Also see: https://github.com/termux/termux-packages/commit/6b61e2ee2790c5550cc4fea51b52a63af720697b#commitcomment-77681259
Sorry @m4lvin.

fixup! upgpkg(main/mu): to 1.8.3

---

packages/mu/build.sh
packages/mu/mu4e-dont-bytecompile-meson.patch

upgpkg(main/mu): to 1.8.5

---

packages/binutils-is-llvm/build.sh

binutils-is-llvm: add some arch-prefixed symlinks

---

packages/fzf/build.sh

fix(main/fzf): add dependencies

---

packages/valgrind/build.sh

valgrind: fix TLS segment

---

packages/pipewire/build.sh
packages/pipewire/runtime_dir.patch

pipewire: update to 0.3.55

---

packages/google-drive-upload/build.sh

updpkg(main/google-drive-upload): update to 4.3

---

packages/pandoc/build.sh

Resulting package works fine on my device.

updpkg(main/pandoc): from 2.16.1 to 2.18

---

packages/neovim-nightly/build.sh

neovim-nightly: update package version

---

packages/corgi/build.sh

https://github.com/termux/termux-packages/issues/11198#issuecomment-1190912556

fix(main/corgi): broken shell

---

packages/alist/build.sh

fix(main/alist): alist-web build failed

---

packages/ipfs/build.sh

ipfs: update to 0.14.0 and switch LICENSE

---

scripts/Dockerfile
scripts/setup-ubuntu.sh

Ubuntu 21.10 reached its end of life. That means `sudo apt` will not work. It's time to use Ubuntu 22.04 as base Docker image.
```
builder@2ac39d8d2aba:~/termux-packages$ sudo apt update
Ign:1 http://archive.ubuntu.com/ubuntu impish InRelease
Ign:2 http://archive.ubuntu.com/ubuntu impish-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu impish-backports InRelease
Ign:4 http://security.ubuntu.com/ubuntu impish-security InRelease
Err:5 http://archive.ubuntu.com/ubuntu impish Release
404  Not Found [IP: 185.125.190.39 80]
Err:6 http://archive.ubuntu.com/ubuntu impish-updates Release
404  Not Found [IP: 185.125.190.39 80]
Err:7 http://security.ubuntu.com/ubuntu impish-security Release
404  Not Found [IP: 91.189.91.38 80]
Err:8 http://archive.ubuntu.com/ubuntu impish-backports Release …
```

enhance(scripts/Dockerfile): upgrade ubuntu version

---

packages/difftastic/build.sh

Add package [difftastic](https://difftastic.wilfred.me.uk/introduction.html), a syntax-aware diff tool

new package: difftastic

---

packages/neovim-nightly/build.sh

Fixes https://github.com/termux/termux-packages/pull/11290#commitcomment-79308560.

neovim-nightly: fix termux_pkg_auto_update

---

packages/restish/build.sh

Adds [restish](https://rest.sh/)

new package: restish

---

packages/atool/build.sh

Adding [atool](https://repology.org/project/atool/versions) which provides various tools to handle many archive formats.

new package: atool

---

packages/apktool/build.sh
packages/termux-elf-cleaner/build.sh
packages/valgrind/build.sh
scripts/build/termux_step_massage.sh
scripts/build/termux_step_start_build.sh

And download and use pre-compiled tool for cleaning built packages

Update termux-elf-cleaner to 2.1.1

---

packages/libhiredis/build.sh

add(main): new package libhiredis

---

packages/mazter/build.sh

Adds [Mazter](https://dystroy.org/mazter/) game.

new package: mazter

---

packages/rsync/build.sh

rsync: enable ipv6

---

packages/weechat-matrix-rs/build.sh

Adds a [plugin](https://github.com/poljar/weechat-matrix-rs) for supporting Matrix protocol in Weechat.

new package: weechat-matrix-rs

---

packages/rush/build.sh

upgpkg(main/rush): update to 0.5.0

---

packages/libmuparser/build.sh

Adds [muparser](https://beltoforion.de/en/muparser/) library for parsing math expressions.

new package: libmuparser

---

packages/libasio/build.sh

Adding [asio](https://think-async.com/Asio/)

new package: libasio

---

packages/graphviz/CMakeLists.txt.patch
packages/graphviz/build.sh
packages/graphviz/dl_iterate_phdr.patch

Let's see if this fixes #11503.

graphviz: link libgvc against libandroid-glob

---

x11-packages/polybar/build.sh
x11-packages/polybar/termux-prefix.patch

Signed-off-by: 2096779623 <admin@utermux.dev>

upgpkg(x11/polybar): update to 3.6.3

---

packages/psmisc/build.sh
packages/psmisc/src-killall.c.patch

psmisc(killall): disable fdsan

---

root-packages/bubblewrap/build.sh
root-packages/bubblewrap/swap-getcwd-func.patch

Attempt at building [bubblewrap](https://github.com/containers/bubblewrap)...

new package: bubblewrap

---

packages/wasmedge/build.sh
packages/wasmedge/cmake-Helper.cmake.patch
packages/wasmedge/getsockopt-socklen_t.patch
packages/wasmedge/lib-host-wasi-linux.h.patch

upgpkg(main/wasmedge): to 0.10.1

---

packages/findomain/build.sh

It builds successfully on my PC, so just test it.
Closes #11610

findomain: update to 8.2.0

---

packages/dex2jar/build.sh

add(main): new package dex2jar

---

packages/ldc/build.sh

ldc: bump to rebuild with ndk-r25

---

packages/algernon/build.sh
packages/algernon/fix-hardcoded-paths.patch

upgpkg(main/algernon): update to 1.14.0

---

packages/imath/build.sh

add(main): new package Imath

---

packages/alembic/build.sh

add(main): new package alembic

---

packages/pystring/build.sh
packages/pystring/makefile.patch

add(main): new package pystring

---

packages/discordo/build.sh

I mistakenly deleted the discordo's commit on my master. 
Closes #11607

add(main): new package discordo

---

packages/gum/build.sh

Adds [gum](https://github.com/charmbracelet/gum/)

new package: gum

---

packages/qhull/build.sh

Adds [qhull](http://www.qhull.org) used for calculating convex hulls.

new package: qhull

---

packages/libosl/build.sh

Adds [openscop](http://icps.u-strasbg.fr/people/bastoul/public_html/development/openscop/) needed for [cloog](http://www.bastoul.net/cloog/).

new package: libosl

---

packages/libcloog/build.sh

Adds [cloog library](http://www.bastoul.net/cloog/index.php) (generates loops for scanning polyhedra).
Depends on https://github.com/termux/termux-packages/pull/11428 .

new package: libcloog

---

packages/libfann/build.sh

Adds [libfann](http://leenissen.dk/fann/wp/), a fast artificial NN library

new package: libfann

---

packages/libceres-solver/build.sh

Adds [ceres-solver](http://ceres-solver.org/index.html) used for optimization problems.

new package: libceres-solver

---

packages/libnova/build.sh

Adds [libnova](http://libnova.sourceforge.net/)

new package: libnova

---

packages/simulavr/build.sh
packages/simulavr/hardcode_version_and_comment_docs.patch

Adds [simulavr](https://www.nongnu.org/simulavr/).
I wasn't able to guide cmake to install the docs though (manpages, etc). Commented out `docs` dir.

new package: simulavr

---

packages/nelua/Makefile.patch
packages/nelua/build.sh

add(main): new package nelua

---

packages/libexpat/build.sh

fix https://github.com/termux/termux-packages/pull/11712#issuecomment-1225947147

fix(main/libexpat): fix cmake library file path

---

packages/nzbget/build.sh

Tested on my device and service control using `sv` works

nzbget: add service

---

packages/octomap/build.sh

Adds [octomap](http://octomap.github.io/)

new package: octomap

---

packages/simuwaerm/build.sh

Adds a [heat simulator](https://github.com/file-acomplaint/simuwaerm).

new package: simuwaerm

---

packages/aapt/build.sh

Rebuild aapt/aapt2 for libprotobuf 2:3.21.5

---

packages/vbindiff/build.sh

new package: vbindiff

---

scripts/setup-android-sdk.sh

Should be one step closer dropping Docker usage in Github Actions...

scripts: improve setup-android-sdk.sh support in Github Actions

---

packages/chafa/build.sh

https://github.com/hpjansson/chafa/releases/tag/1.12.3

chafa: Update to 1.12.3

---

packages/nushell/build.sh
packages/nushell/crates-pwd-for-android.diff
packages/nushell/user_home_dir.patch

nushell: update to 0.68.0

---

x11-packages/phantomjs/build.sh

new package: phantomjs

---

x11-packages/xfce4-genmon-plugin/build.sh

add(x11): new package xfce4-genmon-plugin

---

packages/ptex/build.sh

add(main): new package ptex

---

packages/rage/build.sh

add(main): new package: rage

---

packages/mingw-w64-crt/build.sh

new package: mingw-w64-crt

---

packages/mingw-w64-gcc-libs/build.sh

new package: mingw-w64-gcc-libs

---

packages/mingw-w64/build.sh

new package: mingw-w64

---

packages/coreutils/build.sh
packages/coreutils/lib-fflush.c.patch

coreutils: Mitigate write() error on 32-bit archs

---

packages/ttyc/build.sh

ttyc: fix build

---

packages/telegram-bot-api/build.sh

telegram-bot-api: Fix build

---

packages/gnunet/no-git.patch

gnunet: Fix build

---

x11-packages/audacious-plugins/configure-pkg-config.patch

audacious-plugins: Fix build

---

x11-packages/mate-terminal/build.sh

mate-terminal: Depend on mate-desktop

---

packages/terraform/build.sh

terraform: Fix build

---

x11-packages/libwayland/build.sh
x11-packages/libwayland/libwayland-cross-scanner.subpackage.sh
x11-packages/xwayland/build.sh

{lib,x}wayland: Fix build

---

packages/racket/collects-compiler-private-xform.rkt.patch.beforehostbuild

racket: Fix build

---

packages/at-spi2-core/build.sh
x11-packages/at-spi2-atk/at-spi2-core.wrap.patch
x11-packages/at-spi2-atk/build.sh

new package: at-spi2-core

---

x11-packages/gimp/build.sh

gimp: Fix build

---

packages/cloneit/build.sh

Signed-off-by: Kevin Williams <admin@utermux.dev>
Close #11923 .

add(main): new package cloneit

---

packages/rust/build.sh

The build system somehow tried to link binaries against a wrong libc, leading to build failures for arm (#11640) and runtime errors for others (#11658).
Closes #11640. Fixes #11658.

rust: Fix build

---

packages/sed/build.sh
packages/sed/fix-locale.patch

Fixes https://github.com/termux/termux-packages/issues/11719.

sed: Fix locale handling

---

packages/rust/build.sh
scripts/build/setup/termux_setup_rust.sh

rust: Update to 1.63.0

---

packages/libllvm/build.sh
packages/libllvm/clang-lib-Driver-ToolChain.cpp.patch
packages/libllvm/clang-lib-Driver-ToolChains-Linux.cpp.patch
packages/libllvm/clang.subpackage.sh
packages/libllvm/flang.patch
packages/libllvm/llvm-include-llvm-ADT-SmallVector.h.patch
packages/libllvm/mlir-lib-ExecutionEngine-CRunnerUtils.cpp.patch
packages/libllvm/mlir.subpackage.sh

upgpkg(libllvm): 14.0.6 to 15.0.0

---

packages/lychee/build.sh
packages/lychee/trust-dns-resolver.diff

lychee: Fix hardcoded `/etc/resolv.conf`

---

packages/k2pdfopt/build.sh
packages/k2pdfopt/fix-mupdf.patch

k2pdfopt: Enable MuPDF support

---

packages/rust/build.sh
packages/rust/rust-1.63.0-llvm-wrapper.patch

rust: Revbump to rebuild against libllvm 15

---

packages/fluidsynth/build.sh

https://github.com/FluidSynth/fluidsynth/releases/tag/v2.3.0

fluidsynth: Update to 2.3.0

---

packages/miniserve/0001-upstream-fix-libc-removing-unsafe-on-makedev.diff
packages/miniserve/build.sh

miniserve: update to 0.22.0

---

packages/flang/0001-find-native-mlir-tablegen.patch
packages/flang/0002-remove-some-macros-that-breaks-building.patch
packages/flang/0003-don_t-try-to-run-the-newly-built-flang-new-when-cross-compiling.patch
packages/flang/0004-add-support-for-pic.patch
packages/flang/build.sh

Continuation of #6568, #7910 and #9043.
Please keep this PR a draft until #11863 is merged.

new package: flang

---

packages/oidn/0001-dummy-pthread-affinity.patch
packages/oidn/0002-fix-ambiguous-user.patch
packages/oidn/build.sh

add(main): new package oidn

---

x11-packages/eww/build.sh
x11-packages/eww/fix_tmp_hardcoded_path.patch

add(x11): new package eww

---

packages/gnucobol/build.sh
packages/libgnustep-base/build.sh
packages/libraptor2/build.sh
packages/librasqal/build.sh
packages/libtsduck/build.sh

which can be handled in `termux_step_configure_autotools`.

*/build.sh: Remove individual `*-config` hack

---

packages/alist/build.sh

upgpkg(main/alist): update to 3.0.1

---

packages/zsh/build.sh
packages/zsh/man-path.patch

[zsh]: Fix hardcoded man path

---

x11-packages/audacity/audacity-ffmpeg.subpackage.sh
x11-packages/audacity/build.sh
x11-packages/audacity/ffmpeg-configure.patch
x11-packages/audacity/src-FFmpeg.h.patch

audacity: Enable FFmpeg support

---

packages/console-bridge/build.sh
packages/libtinyxml/Makefile.patch
packages/libtinyxml/build.sh
packages/libtinyxml/tinyxml-2.6.1-entity.patch
packages/libtinyxml/tinyxml-2.6.2-defineSTL.patch
packages/urdfdom/build.sh

Adds https://github.com/ros/urdfdom.
Depends on https://github.com/termux/termux-packages/pull/11483

new package: urdfdom

---

scripts/setup-ubuntu.sh
x11-packages/ghex/build.sh

new package: ghex

---

packages/less/build.sh

less: Bump to 608

---

packages/python-bcrypt/build.sh

new package: python-bcrypt

---

packages/opencolorio/build.sh

add(main): new package opencolorio

---

packages/libxcfun/build.sh

Adds [xcfun](https://xcfun.readthedocs.io/en/latest/index.html)

new package: libxcfun

---

packages/libxdrfile/build.sh

Adds [xdrfile](https://userguide.mdanalysis.org/stable/formats/reference/xtc.html)

new package: libxdrfile

---

scripts/build/termux_step_check_prefix.sh

adds -print option, prevents -prune option from printing -path values

Fix new_files including ignored paths name

---

packages/glm/6059c5767.patch
packages/glm/build.sh

I'm participant of the [hacktoberfest](https://hacktoberfest.com/), please add the label `hacktoberfest-accepted` to this PR when merging.

glm: new package

---

packages/samurai/Makefile.patch
packages/samurai/build.sh

Adds `samurai` (like `ninja` but written in C)

new package: samurai

---

x11-packages/azpainter/build.sh

azpainter: fix build

---

packages/k9s/build.sh

upgpkg(main/k9s): update to 0.26.6

---

packages/flyctl/build.sh

upgpkg(main/flyctl): update to 0.0.402

---

packages/rgbds/build.sh

upgpkg(main/rgbds): update to 0.6.0

---

packages/procs/0001-rustix-upstream-fix-libc-removing-unsafe-on-makedev.diff
packages/procs/build.sh

procs: update to 0.13.2

---

packages/wasmedge/build.sh
packages/wasmedge/fix-for-arm.patch
packages/wasmedge/getsockopt-socklen_t.patch

wasmedge: update to 0.11.1 and enable arm

---

packages/guile/build.sh
packages/guile/malloc.h
packages/lilypond/build.sh
packages/make-guile/build.sh
scripts/setup-ubuntu.sh

Continuation of #11263.
Closes #11269.

guile: update to 3.0.8

---

packages/libfcl/build.sh

https://github.com/termux/termux-packages/issues/12219

fix(main/libfcl): depend on octomap-static

---

packages/robin-map/build.sh

add(main): new package robin-map

---

packages/readline/build.sh

readline: update to 8.2.1

---

packages/barcode/build.sh

barcode: compilation fix

---

packages/mdbtools/build.sh

mdbtools: compilation fix, adding libiodbc dependencies

---

packages/indent/build.sh
packages/indent/src-Makefile.in.patch

indent: compilation fix

---

x11-packages/bdftopcf/build.sh

add(x11): new package bdftopcf

---

scripts/updates/utils/termux_pkg_upgrade_version.sh

In commit https://github.com/termux/termux-packages/commit/400826006e23b7740a3e6b5732e3297b858e1b5c, I have tried to fix this error. But it seems to work only when the package exists in `packages` folder.
See also #10748, #12321
Closes #12337, termux-user-repository/tur#121

fix(scripts): building failure when auto-updating

---

packages/silicon/build.sh
packages/silicon/src-hb_wrapper.rs.patch

upgpkg(main/silicon): 0.5.1

---

packages/starship/0001-Cargo.toml.patch
packages/starship/build.sh
packages/starship/rust-git-config-path.diff

upgpkg(main/starship): 1.11.0

---

packages/marisa/build.sh

fix(main/marisa): rebuild for arm

---

packages/ne/build.sh

ne: Set TERMUX_MAKE_PROCESSES to 1

---

packages/root-repo/build.sh
packages/x11-repo/build.sh

This greatly reduces installation time (for most users) .

feat(main/{x11,root}-repo): auto select mirror

---

disabled-packages/vlang/build.sh

vlang: Add comment about known issues

---

root-packages/zmap/build.sh
root-packages/zmap/default-blocklist-path.patch
root-packages/zmap/use-yacc.patch
root-packages/zmap/util-setaffinity.patch

add(root): new package zmap

---

packages/python-apsw/build.sh
packages/python-apsw/setup.cfg

new package: python-apsw

---

packages/rsync/build.sh
packages/rsync/rsync-3.2.6-bug-with-relative-rules.patch

from https://github.com/WayneD/rsync/commit/464555ea923b32f3504678d05bc7de9205e5c8da.
Fixes #12419.

rsync: Backport patch

---

packages/picolisp/build.sh

picolisp: Fix build

---

packages/ldd/build.sh
packages/ldd/ldd.in

A (fake) `ldd` that shows the entire dependency tree (not only the direct dependencies) is needed by `gobject-introspection` that I am currently working on.

new package: ldd

---

x11-packages/gjots2/bin-gjots2.patch
x11-packages/gjots2/build.sh

new package: gjots2

---

disabled-packages/midori/build.sh
scripts/build/setup/termux_setup_gir.sh
x11-packages/midori/build.sh

Not working correctly. Unmaintained upstream.
Closes #10222.

new disabled package: midori

---

x11-packages/xdotool/build.sh
x11-packages/xdotool/platform.sh.patch

new package: xdotool

---

packages/recoll/build.sh

New package: recoll

---

packages/ceu-lang/Makefile.patch
packages/ceu-lang/build.sh

Adds [ceu language.](http://www.ceu-lang.org/)

new package: ceu-lang

---

packages/libdart/CMakeLists.patch
packages/libdart/build.sh

Adds [dart](https://github.com/dartsim/dart).

new package: libdart

---

x11-packages/libnotify/build.sh
x11-packages/libnotify/gir/0.8.1/Notify-0.7.xml

libnotify: Bump to 0.8.1

---

x11-packages/libvte/build.sh
x11-packages/libvte/gir/0.62.3/Vte-2.91.xml

libvte: Bump to 0.62.3

---

packages/libgsf/build.sh
packages/libgsf/gir/1.14.50/Gsf-1.xml

libgsf: Bump to 1.14.50

---

x11-packages/goffice/build.sh
x11-packages/goffice/gir/0.10.53/GOffice-0.10.xml

goffice: Bump to 0.10.53

---

packages/poppler/build.sh
packages/poppler/gir/22.04.0/Poppler-0.18.xml
scripts/build/setup/termux_setup_gir.sh
x11-packages/poppler-qt/build.sh

* poppler: Build introspection data

poppler-qt: Remove files that are also in poppler

---

x11-packages/extra-cmake-modules/build.sh

extra-cmake-modules: package update and compilation fix

---

x11-packages/libmatekbd/build.sh

libmatekbd: Explicitly disable gir

---

x11-packages/libunique/build.sh
x11-packages/libunique/gir/1.1.6/Unique-1.0.xml

libunique: Build introspection data

---

x11-packages/mate-desktop/build.sh

mate-desktop: Explicitly disable gir

---

scripts/build/setup/termux_setup_gir.sh
x11-packages/caja/build.sh
x11-packages/libxfce4ui/build.sh
x11-packages/libxfce4util/build.sh
x11-packages/mate-menus/build.sh
x11-packages/thunar/build.sh
x11-packages/xfce4-panel/build.sh
x11-packages/xfconf/build.sh

* caja: Adapt to termux_setup_gir
* libxfce4ui: Adapt to termux_setup_gir
* libxfce4util: Adapt to termux_setup_gir
* thunar: Adapt to termux_setup_gir
* xfce4-panel: Adapt to termux_setup_gir
* xfconf: Adapt to termux_setup_gir
* mate-menus: Adapt to termux_setup_gir

*: Adapt to termux_setup_gir

---

x11-packages/libxfce4ui/build.sh
x11-packages/libxfce4ui/gir/4.17.2/Libxfce4ui-2.0.xml
x11-packages/libxfce4util/build.sh
x11-packages/libxfce4util/gir/4.17.1/Libxfce4util-1.0.xml
x11-packages/xfce4-panel-profiles/build.sh

* libxfce4ui: Build introspection data
* libxfce4util: Build introspection data

xfce4-panel-profiles: Depend on pygobject

---

packages/samba/0002-Remove-setuid-etc.patch
packages/samba/build.sh
packages/samba/findsmb.patch
packages/samba/more-pw_gecos-removal.patch
packages/samba/openwrt-fix-host-tools-checks.patch

<a href="https://wiki.samba.org/index.php/Samba_4.14_Features_added/changed">"Samba 4.14 is Discontinued (End of Life)."</a>

samba: Bump to 4.15.11

---

x11-packages/gimp3/build.sh
x11-packages/gimp3/gimp-2.99.12-libheif-1.13.patch
x11-packages/gimp3/gir/2.99.12/Gimp-3.0.xml
x11-packages/gimp3/gir/2.99.12/GimpUi-3.0.xml
x11-packages/gimp3/meson.build.patch
x11-packages/gimp3/plug-ins-python-meson.build.patch

A development version, should be disabled for now.

[DISABLED] new package: gimp3

---

packages/2ping/build.sh
packages/asciinema/build.sh
packages/electrum/build.sh
packages/matplotlib/build.sh
packages/nala/build.sh
packages/python-apsw/build.sh
packages/python-bcrypt/build.sh
packages/python-cryptography/build.sh
packages/python-tldp/build.sh

*/build.sh: Remove unneeded TERMUX_PKG_RM_AFTER_INSTALL

---

packages/abootimg/0001-fixed-silly-warnings-due-to-Wall.patch
packages/abootimg/0002-renamed-un-pack-initrd-to-abootimg-un-pack-initrd.patch
packages/abootimg/0003-Fix-man-page-typos.patch
packages/abootimg/Makefile.patch
packages/abootimg/build.sh

Requested in termux/termux-packages#12567.

newpkg(main/abootimg)

---

packages/recoll/Makefile.in.patch
packages/recoll/build.sh
packages/recoll/python-recoll-setup.py.in.diff
packages/recoll/recoll-python.subpackage.sh

recoll: Separate recoll-python as a subpackage

---

packages/micro/build.sh

Updates micro to [2.0.11](https://github.com/zyedidia/micro/releases/tag/v2.0.11)

micro: update to 2.0.11

---

packages/texlive-bin/fix-path-to-md5.h.patch

when `libmd` package is installed.

texlive-bin: Fix build

---

packages/nodejs/build.sh

nodejs: Revbump to rebuild

---

packages/nodejs-lts/build.sh

nodejs-lts: Revbump to rebuild

---

x11-packages/polybar/build.sh

polybar: Adjust dependency

---

x11-packages/xcb-util/build.sh

xcb-util: Remove no longer necessary symlink

---

packages/aubio/waflib-ConfigSet.py.patch
packages/aubio/waflib-Context.py.patch

aubio: Fix build

---

x11-packages/xcb-util-image/build.sh

Merge should come after #12690.

xcb-util-image: Remove no longer necessary symlink

---

packages/libvips/build.sh

libvips: Explicitly disable gir

---

packages/imagemagick/build.sh

imagemagick: Bump to 7.1.0.51

---

packages/opencv/build.sh
packages/opencv/calib3d_use_OCV_LAPACK_FUNC.patch
packages/opencv/opencv-python.subpackage.sh

And the version in file was 1.23.3 but in repo was 1.23.4

enhance(opencv-python):  depend on python-numpy

---

x11-packages/thunar-archive-plugin/build.sh
x11-packages/xfdesktop/build.sh

* thunar-archive-plugin: Bump to 0.5.0
* xfdesktop: Bump to  4.17.1

Thunar revdeps bump

---

x11-packages/glu/build.sh

glu: Remove unneeded dependencies

---

packages/fd/build.sh

upgpkg(main/fd): 8.5.0

---

packages/unicorn/build.sh
packages/unicorn/fix-endian.h.patch

upgpkg(main/unicorn): 2.0.1

---

packages/tvheadend/build.sh
packages/tvheadend/tvheadend-data.subpackage.sh

tvheadend: Subpackage platform-independent data

---

x11-packages/kvantum/build.sh

kvantum: Bump to 1.0.6

---

x11-packages/galculator/build.sh
x11-packages/gpg-crypter/build.sh
x11-packages/obconf/build.sh
x11-packages/pcmanfm/build.sh
x11-packages/pinentry-gtk/build.sh
x11-packages/putty/build.sh
x11-packages/pypanel/build.sh
x11-packages/uget/build.sh

*: Remove unneeded libandroid-shmem dependency

---

packages/samba/build.sh

samba: Depend on libandroid-execinfo

---

packages/buf/build.sh

Fix https://github.com/termux/termux-packages/issues/12900

Add buf package

---

packages/crowbook/build.sh

crowbook: Use Rust 1.63.0 to build

---

packages/doctest/build.sh

addpkg(main/doctest): a C++ single header testing framework

---

packages/libdvdnav/build.sh
packages/libspeex/build.sh
packages/libspeex/speex-utils.subpackage.sh
packages/libzimg/build.sh

* new package: libdvdnav
* new package: libspeex
* new package: libzimg

Add new packages for handbrake dependency

---

x11-packages/handbrake/build.sh
x11-packages/handbrake/gtk-module.defs.patch
x11-packages/handbrake/libhb-handbrake-common.h.patch
x11-packages/handbrake/make-configure.py.patch

new package: handbrake

---

packages/mpv/build.sh

and add guard from automagic dependency.

mpv: Modify dependency

---

x11-packages/firefox/build.sh

firefox: Disable jemalloc

---

packages/mariadb/build.sh
packages/mariadb/i686-no-asm-goto.patch
packages/mariadb/plugin-disks-information_schema_disks.cc.patch

mariadb: Bump to 10.9.4

---

packages/libnss/build.sh
x11-packages/firefox/build.sh
x11-packages/firefox/system-libevent.patch

firefox: Use system libs as far as possible

---

packages/fakeroot/build.sh
packages/fakeroot/communicate.c.patch

fix(fakeroot): removed hangup when executing commands

---

packages/beanshell/build.sh

beanshell: Use `d8`

---

packages/android-tools/CVE-2022-20128.patch
packages/android-tools/CVE-2022-3168.patch
packages/android-tools/build.sh

CVE-2022-3168 and CVE-2022-20128.

android-tools: Backport fixes for CVEs

---

packages/mold/build.sh

upgpkg(main/mold): 1.6.0 to 1.7.0

---

x11-packages/xfce4-docklike-plugin/build.sh
x11-packages/xfce4-docklike-plugin/src-Hotkeys.cpp.patch

new package: xfce4-docklike-plugin

---

packages/notcurses/CMakeLists.txt.patch
packages/notcurses/build.sh
packages/notcurses/include-notcurses-ncport.h.patch
packages/notcurses/notcurses-data.subpackage.sh
packages/notcurses/notcurses-tools.subpackage.sh
packages/notcurses/pkgconfig.patch
packages/notcurses/pthread_cancel.patch
packages/notcurses/src-lib-termdesc.h.patch

new package: notcurses

---

packages/onefetch/build.sh

fix(main/onefetch): shell completions

---

packages/libgit2/build.sh

libgit2: Adapt to change in directory structure

---

packages/git-delta/build.sh

of newer libgit2.
%ci:no-build

git-delta: Adapt to change in directory structure

---

packages/nushell/build.sh

of newer libgit2.
%ci:no-build

nushell: Remove no longer needed getloadavg workaround

---

packages/pipes.sh/build.sh

Actually not essentially bumped. Just the version string is changed.

pipes.sh: Bump to 2018.04.22

---

packages/topgrade/build.sh

The original maintainer has stopped development and a new team has taken over the project to continue it.

upgpkg(main/topgrade): v10.2.0

---

packages/weechat/build.sh
packages/weechat/cmake-FindGCRYPT.cmake.patch

in some environment.
Fixes #13493.

weechat: Fix build

---

x11-packages/aterm/aterm-1.0.1_src_rxvt.h.patch

aterm: Fix line endings in patch

---

packages/argp/argp-fmtstream.h.patch
packages/argp/argp-standalone-1.5.0-shared.patch
packages/argp/build.sh
packages/argp/fix-segfault.patch
packages/dwarves/build.sh
packages/libelf/build.sh
packages/libelf/elfutils.subpackage.sh
packages/libelf/libdw.subpackage.sh

argp: Bump to 1.5.0

---

packages/boinc/build.sh
packages/boinc/client-hostinfo_unix.cpp.patch
packages/boinctui/build.sh
packages/box86/build.sh
packages/clvk/build.sh
packages/emscripten/build.sh
x11-packages/gl4es/build.sh

* move to weekly push since daily commit upgrades are really minor and may not even be code changes
* test enabling LTO or ThinLTO
* some other cosmetic changes to build.sh

Maintenance for boinc, boinctui, box86, clvk, emscripten, gl4es

---

packages/mdbook-graphviz/build.sh

new package: mdbook-graphviz

---

packages/mdbook-epub/build.sh
packages/mdbook-epub/mdbook-src-renderer-html_handlebars-helpers-navigation.rs.diff

new package: mdbook-epub

---

packages/mdbook-presentation-preprocessor/build.sh

new package: mdbook-presentation-preprocessor

---

packages/mdbook-tera/build.sh
packages/mdbook-tera/mdbook-src-renderer-html_handlebars-helpers-navigation.rs.diff

new package: mdbook-tera

---

packages/mdbook-svgbob/build.sh

new package: mdbook-svgbob

---

packages/mdbook-svgbob2/build.sh

new package: mdbook-svgbob2

---

packages/mdbook-cat-prep/build.sh
packages/mdbook-cat-prep/mdbook-src-renderer-html_handlebars-helpers-navigation.rs.diff

new package: mdbook-cat-prep

---

packages/mdbook-auto-gen-summary/build.sh
packages/mdbook-auto-gen-summary/filetime-src-unix-utimes.rs.diff

new package: mdbook-auto-gen-summary

---

x11-packages/mgba/build.sh

new package: mgba

---

x11-packages/clutter-gst/build.sh
x11-packages/clutter-gst/gir/3.0.27/ClutterGst-3.0.xml
x11-packages/clutter-gtk/build.sh
x11-packages/clutter-gtk/gir/1.8.4/GtkClutter-1.0.xml
x11-packages/clutter/build.sh
x11-packages/clutter/clutter-Makefile.in.patch
x11-packages/clutter/gir/1.26.4/Cally-1.0.xml
x11-packages/clutter/gir/1.26.4/Clutter-1.0.xml
x11-packages/clutter/gir/1.26.4/ClutterGdk-1.0.xml
x11-packages/clutter/gir/1.26.4/ClutterX11-1.0.xml
x11-packages/cogl/build.sh
x11-packages/cogl/gir/1.22.8/Cogl-1.0.xml
x11-packages/cogl/gir/1.22.8/Cogl-2.0.xml
x11-packages/cogl/gir/1.22.8/CoglPango-1.0.xml
x11-packages/cogl/gir/1.22.8/CoglPango-2.0.xml
x11-packages/komorebi/CMakeLists.txt.patch
x11-packages/komorebi/build.sh
x11-packages/komorebi/extra-wallpaper-creator-OnScreen-InitialPage.vala.patch
x11-packages/komorebi/komorebi-data.subpackage.sh
x11-packages/komorebi/src-Utilities.vala.patch

new package: komorebi

---

packages/libc++utilities/build.sh
packages/libc++utilities/no-android.patch
x11-packages/qtutilities/build.sh
x11-packages/qtutilities/no-android.patch
x11-packages/tageditor/build.sh
x11-packages/tagparser/build.sh

new package: tageditor

---

packages/liblqr/build.sh
x11-packages/gimp-lqr-plugin/build.sh

new package: gimp-lqr-plugin

---

x11-packages/vala-panel-appmenu/build.sh
x11-packages/vala-panel-appmenu/meson.build.patch
x11-packages/vala-panel-appmenu/xfce4-appmenu-plugin.subpackage.sh

new package: xfce4-appmenu-plugin

---

packages/logo-ls/build.sh

add(main): new package logo-ls

---

x11-packages/i3-gaps/build.sh

new package: i3-gaps

---

packages/ass2bdnxml/CMakeLists.txt.patch
packages/ass2bdnxml/avs2bdnxml.c.patch
packages/ass2bdnxml/build.sh

new package: ass2bdnxml

---

x11-packages/xvkbd/build.sh

new package: xvkbd

---

packages/fm/build.sh

new package: fm

---

packages/storj-uplink/build.sh

new package: storj-uplink

---

packages/hexer/build.sh

new package: hexer

---

x11-packages/schismtracker/build.sh

new package: schismtracker

---

packages/plutolang/Makefile.patch
packages/plutolang/build.sh
packages/plutolang/src-Makefile.patch
packages/plutolang/src-loslib.cpp.patch
packages/plutolang/src-luaconf.h.patch

new package: plutolang

---

packages/libtpms/build.sh
packages/swtpm/build.sh
packages/swtpm/configure.ac.patch
packages/swtpm/src-swtpm_setup-swtpm.c.patch

new package: swtpm

---

x11-packages/fcitx5/build.sh
x11-packages/fcitx5/cmake-FindDL.cmake.patch
x11-packages/fcitx5/cmake-FindPthread.cmake.patch
x11-packages/fcitx5/fcitx5-data.subpackage.sh
x11-packages/fcitx5/fix-hardcoded-paths.patch
x11-packages/fcitx5/src-modules-spell-CMakeLists.txt.patch
x11-packages/xcb-imdkit/build.sh

new package: fcitx5

---

packages/lcal/COPYRIGHT.moonphase
packages/lcal/build.sh
packages/pcal/COPYRIGHT.moonphase
packages/pcal/build.sh

new package: pcal, lcal

---

packages/procyon-decompiler/build.sh
packages/procyon-decompiler/procyon-decompiler.patch

new package: procyon-decompiler

---

packages/nwipe/build.sh
packages/nwipe/configure.ac.patch
packages/nwipe/fix-hardcoded-paths.patch
packages/nwipe/pthread_cancel.patch
packages/nwipe/src-nwipe.c.patch

new package: nwipe

---

packages/esbuild/build.sh

new package: esbuild

---

packages/mp3wrap/build.sh
packages/mp3wrap/wrap.c.patch

new package: mp3wrap

---

packages/minimodem/build.sh

new package: minimodem

---

packages/kainjow-mustache/build.sh
packages/kiwix-tools/build.sh
packages/libkiwix/build.sh
packages/libkiwix/kiwix.pc.in.patch
packages/libkiwix/src-tools-pathTools.cpp.patch
packages/libpugixml/build.sh

new package: kiwix-tools

---

packages/hstr/build.sh

new package: hstr

---

packages/bsd-finger/build.sh
packages/bsd-finger/configure.patch
packages/bsd-finger/finger-Makefile.patch
packages/bsd-finger/finger-finger.c.patch
packages/bsd-finger/finger-util.c.patch
packages/bsd-finger/fingerd-Makefile.patch
packages/bsd-finger/fingerd-fingerd.c.patch
packages/bsd-finger/fingerd-pathnames.h.patch

new package: bsd-finger

---

x11-packages/deadbeef/build.sh
x11-packages/deadbeef/deadbeef-1.9.2-drop-Werror.patch
x11-packages/deadbeef/fix-underlinking.patch
x11-packages/deadbeef/junklib.c.patch
x11-packages/deadbeef/threading_pthread.c.patch

new package: deadbeef

---

packages/ncftp/build.sh
packages/ncftp/fix-hardcoded-paths.patch

new package: ncftp

---

packages/tut/build.sh

new package: tut

---

x11-packages/fritzing/build.sh
x11-packages/fritzing/fritzing-0.9.6-quazip1.patch
x11-packages/fritzing/fritzing-data.subpackage.sh
x11-packages/fritzing/phoenix.pro.patch

new package: fritzing

---

x11-packages/simulide/build.sh
x11-packages/simulide/simulide-data.subpackage.sh
x11-packages/simulide/src-gpsim-protocol.cc.patch

new package: simulide

---

root-packages/gocryptfs/build.sh

new package: gocryptfs

---

packages/libnl/build.sh
packages/libnl/include-linux-private-linux-in.h.patch
packages/libnl/libnl-cli-static.subpackage.sh
packages/libnl/libnl-cli.subpackage.sh

and subpackage them as libnl-cli.

libnl: Build CLI utils

---

packages/rdfind/build.sh

new package: rdfind

---

x11-packages/love/build.sh
x11-packages/love/src-common-config.h.patch
x11-packages/love/src-libraries-physfs-physfs_platform_unix.c.patch
x11-packages/love/src-modules-sound-lullaby-GmeDecoder.h.patch

new package: love

---

packages/autojump/bin-autojump.sh.patch
packages/autojump/build.sh
packages/autojump/install.py.patch

new package: autojump

---

packages/scrcpy/build.sh

new package: scrcpy

---

packages/nmon/build.sh
packages/nmon/lmon16n.c.patch

new package: nmon

---

packages/wasmtime/build.sh

new package: wasmtime

---

packages/libv4l/build.sh
packages/libv4l/lib-libv4l2-Makefile.in.patch
packages/libv4l/lib-libv4lconvert-control-libv4lcontrol.c.patch

new package: libv4l

---

packages/neovim-nightly/build.sh
packages/neovim-nightly/src-nvim-po-CMakeLists.txt.patch

The neovim-nightly package hasn't been updated in a while. This should fix build issue. Is there anything else need to be done to enable auto-update again?

fix: neovim-nightly build

---

x11-packages/spotify-qt/CMakeLists.txt.patch
x11-packages/spotify-qt/build.sh
x11-packages/spotify-qt/fix-hardcoded-paths.patch

Closes #10928.
Supersedes #13535.

new package: spotify-qt

---

root-packages/vlan/build.sh
root-packages/vlan/debian-network-if-pre-up.d-vlan.patch
root-packages/vlan/vconfig.patch

new package: vlan

---

x11-packages/ardour/ardour-data.subpackage.sh
x11-packages/ardour/atomic.patch
x11-packages/ardour/build.sh
x11-packages/ardour/dynamic_pointer_cast.patch
x11-packages/ardour/fix-hardcoded-paths.patch
x11-packages/ardour/fix-platform.patch
x11-packages/ardour/gtk2_ardour-ardour.sh.in.patch
x11-packages/ardour/libs-ardour-port_manager.cc.patch
x11-packages/ardour/no-alsa.patch
x11-packages/ardour/pthread_attr_setinheritsched.patch
x11-packages/ardour/pthread_cancel.patch
x11-packages/ardour/wscript.patch

new package: ardour

---

packages/ca-certificates/build.sh
packages/ca-certificates/ca-certificates-java.subpackage.sh

ca-certificates: Remove TrustCor root certificates

---

packages/vgmstream/build.sh
packages/vgmstream/cli-CMakeLists.txt.patch

new package: vgmstream

---

x11-packages/opensubdiv/build.sh
x11-packages/opensubdiv/opensubdiv-3.5.0-tbb-2021.patch
x11-packages/opensubdiv/opensubdiv-osd-CMakeLists.txt.patch

new package: opensubdiv

---

scripts/setup-ubuntu.sh
x11-packages/motif/Makefile.in.patch
x11-packages/motif/build.sh
x11-packages/motif/fix-hardcoded-paths.patch
x11-packages/motif/lib-Xm-Makefile.in.patch
x11-packages/motif/lib-Xm-XpmI.h.patch
x11-packages/motif/tools-wml-Makefile.in.patch

Closes #11155.
Supersedes #11558.

new package: motif

---

packages/vgmtools/build.sh

new package: vgmtools

---

x11-packages/dosbox-x/build.sh
x11-packages/dosbox-x/dosbox-x-data.subpackage.sh
x11-packages/dosbox-x/fix-hardcoded-paths.patch
x11-packages/dosbox-x/src-libs-porttalk-porttalk.cpp.patch

new package: dosbox-x

---

packages/libarchive/build.sh

Upstream: https://github.com/libarchive/libarchive/issues/1766

libarchive: Fix pkgconfig file

---

packages/delve/build.sh
packages/delve/debugger_unix.go.patch

upgpkg(main/delve): v1.20.0

---

packages/trzsz-go/build.sh

new package: trzsz-go

---

root-packages/libfuse2/build.sh
root-packages/libfuse2/lib-fuse.c.patch
root-packages/libfuse2/lib-fuse_loop_mt.c.patch

libfuse2: Use negative logic for pthread cancelation

---

packages/neomutt/build.sh

Fixes https://github.com/termux/termux-packages/issues/13890.

neomutt: Link against libandroid-support

---

packages/sysprop/build.sh
packages/sysprop/include-android-base-unique_fd.h.patch
packages/sysprop/sources.sh

new package: sysprop

---

x11-packages/tageditor/build.sh
x11-packages/tageditor/cli-helper.cpp.patch

tageditor: Fix FieldId::fromTagDenotation

---

packages/qemu-system-x86-64-headless/0001-fix-hardcoded-paths.patch
packages/qemu-system-x86-64-headless/0016-disable-signalfd.patch
packages/qemu-system-x86-64-headless/build.sh
packages/qemu-system-x86-64-headless/qemu-7.2.0-linux-user-syscall.c.patch
packages/qemu-system-x86-64-headless/setjmp-aarch64/private-bionic_asm.h
packages/qemu-system-x86-64-headless/setjmp-aarch64/private-bionic_asm_arm64.h
packages/qemu-system-x86-64-headless/setjmp-aarch64/private-bionic_constants.h
packages/qemu-system-x86-64-headless/setjmp-aarch64/setjmp.S
x11-packages/qemu-system-x86-64/0001-fix-hardcoded-paths.patch
x11-packages/qemu-system-x86-64/0016-disable-signalfd.patch
x11-packages/qemu-system-x86-64/build.sh
x11-packages/qemu-system-x86-64/qemu-7.2.0-linux-user-syscall.c.patch
x11-packages/qemu-system-x86-64/setjmp-aarch64/private-bionic_asm.h
x11-packages/qemu-system-x86-64/setjmp-aarch64/private-bionic_asm_arm64.h
x11-packages/qemu-system-x86-64/setjmp-aarch64/private-bionic_constants.h
x11-packages/qemu-system-x86-64/setjmp-aarch64/setjmp.S

Include workaround for #12261.
Closes #12261.

qemu: Bump to 7.2.0

---

packages/proxmark3/build.sh

administrative update for package maintainer address

proxmark3: admin update

---

packages/mesa/build.sh
packages/mesa/mesa-22.2.0-llvm-15.patch
packages/mesa/osmesa.subpackage.sh

* Separate osmesa as a subpackage
CC: @kawanakaiku (in case if interested)

mesa: Bump to 22.3.1

---

x11-packages/libxklavier/build.sh

libxklavier: Specify xkb-bin-base

---

packages/leptonica/build.sh

leptonica: Add SOVERSION guard

---

x11-packages/xorg-setxkbmap/build.sh

new package: xorg-setxkbmap

---

packages/ffmpeg/build.sh

ffmpeg: Enable libzimg

---

packages/gitoxide/build.sh

gitoxide: Fix auto-update

---

packages/megacmd/build.sh
packages/megacmd/sdk-src-posix-fs.cpp.patch

megacmd: Fix hardcoded paths

---

packages/boost/boost-1.80.0-python-3.11.patch
packages/boost/build.sh

boost: Backport patch to fix error with Python 3.11

---

root-packages/zmap/build.sh

The libraries are runtime dependencies.

zmap: fix dependencies

---

packages/exa/build.sh

as a revdep of libgit2. Just in case.

exa: Revbump to rebuild

---

packages/libduckdb/CMakeLists.txt.patch
packages/libduckdb/build.sh

libduckdb: bump to 0.6.1

---

packages/hstr/build.sh
packages/hstr/no-TIOCSTI.patch

hstr: Do not use `TIOCSTI`

---

root-packages/gptfdisk/build.sh

gptfdisk: Adjust dependency

---

packages/libxt/build.sh

and fix overlinking against libuuid in the previous binary package.

libxt: Adjust dependency

---

packages/cups-pdf/0000-cups-pdf-3.0.1-ghostscript-gpl-9.54-compat.patch
packages/cups-pdf/0001-fix-hardcoded-paths.patch
packages/cups-pdf/build.sh
packages/cups/build.sh
packages/cups/cups-scheduler-Makefile.patch
packages/cups/no-sbindir.patch

* new package: cups-pdf
Closes #14119.

cups: Bump to 2.4.2 / new package: cups-pdf

---

packages/neovim/build.sh

neovim: Fix auto-update

---

packages/vim-python/build.sh
packages/vim/build.sh
x11-packages/vim-gtk/build.sh

vim{,-python,-gtk}: Add version guard

---

packages/libfixposix/build.sh
packages/libfixposix/src-lib-stdlib.c.patch
packages/libfixposix/src-lib-strerror.c.patch

new package: libfixposix

---

packages/libknot/build.sh
packages/libknot/fix-hardcoded-paths.patch
packages/libknot/knot-utils.subpackage.sh
packages/libknot/pthread_cancel.patch

new package: libknot / knot-utils

---

packages/rirc/Makefile.patch
packages/rirc/build.sh
packages/rirc/fix-hardcoded-paths.patch
packages/rirc/struct_user.patch

add(main): new package rirc

---

packages/recode/build.sh

recode: Bump to 3.7.13

---

packages/cgif/build.sh

Add package [`cgif`](https://github.com/dloebl/cgif) (GIF encoding library). Required by #14346.

new package: cgif

---

packages/gomp/build.sh
packages/gomp/fix_hardcoded_path.patch

add(main): new package gomp

---

packages/libxlsxwriter/build.sh

libxlsxwriter: Enable auto-update

---

packages/markdown-flashcards/build.sh

new package: markdown-flashcards

---

packages/ncurses/build.sh

ncurses: Add terminfo for gnome

---

packages/fish/build.sh
packages/fish/src-path.cpp.patch

fish: Bump to 3.6.0

---

scripts/setup-ubuntu.sh
x11-packages/codeblocks/backport-r11938.diff
x11-packages/codeblocks/backport-r11991.diff
x11-packages/codeblocks/backport-r12190.diff
x11-packages/codeblocks/backport-r12281.diff
x11-packages/codeblocks/backport-r12305.diff
x11-packages/codeblocks/backport-r12312.diff
x11-packages/codeblocks/backport-r12511.diff
x11-packages/codeblocks/backport-r12532.diff
x11-packages/codeblocks/backport-r12578.diff
x11-packages/codeblocks/backport-r12579.diff
x11-packages/codeblocks/backport-r12580.diff
x11-packages/codeblocks/backport-r12592.diff
x11-packages/codeblocks/backport-r12707.diff
x11-packages/codeblocks/backport-r12841.diff
x11-packages/codeblocks/backport-r12842.diff
x11-packages/codeblocks/build.sh
x11-packages/codeblocks/codeblocks-data.subpackage.sh
x11-packages/codeblocks/r12190.diff.diff
x11-packages/codeblocks/src-mime-Makefile.am.patch
x11-packages/codeblocks/src-sdk-scripting-bindings-sc_wxtypes.cpp.patch

~~Supersedes~~ Continuation from #11529.
Closes #11151.

new package: codeblocks

---

x11-packages/mogan/CMakeLists.txt.patch
x11-packages/mogan/build.sh
x11-packages/mogan/mogan-data.subpackage.sh
x11-packages/mogan/plugins-shell-CMakeLists.txt.patch

new package: mogan

---

packages/pandoc/build.sh

pandoc: update to 2.19.2 & add bash completion

---

packages/csh/Makefile.patch
packages/csh/build.sh

csh: Fix DT_RUNPATH

---

x11-packages/qt5-qtwebengine/build.sh

qt5-qtwebengine: fix conflicts of cmake files

---

scripts/lint-packages.sh

Currently invalid package names such as `a` or `+a` are not rejected.
Source: https://www.debian.org/doc/debian-policy/ch-controlfields.html#source

lint_package: Check package / subpackage name

---

packages/python-cryptography/build.sh

fix(main/python-cryptography): removing --no-binary flag in pip

---

packages/speechd/build.sh

speechd: Rebuild to fix overlinking

---

packages/gnupg/build.sh
packages/gnupg/g10-keylist.c.patch

Which is not allowed on android.

gnupg: prevent attempt to print with %n format

---

packages/mesa/build.sh

Files with the same inode number become separate files after massage and make the binary package unnecessarily larger.

mesa: Avoid hard links in `$PREFIX/lib/dri/`

---

packages/tut/build.sh

upgpkg(main/tut): 2.0.0

---

packages/helix/build.sh
packages/helix/helix-grammars.subpackage.sh

helix: Separate grammar-related files as subpackages

---

root-packages/nexttrace-enhanced/build.sh

nexttrace-enhanced: Explicitly specify output binary name

---

packages/alist/build.sh

fix(main/alist): source being non-deterministic

---

root-packages/v4l-utils/build.sh
root-packages/v4l-utils/getsubopt.c
root-packages/v4l-utils/getsubopt.h
root-packages/v4l-utils/getsubopt.patch
root-packages/v4l-utils/no-android.patch
root-packages/v4l-utils/no-udev.patch
root-packages/v4l-utils/pthread_cancel.patch

Inspired by #12996 but written from scratch.
Closes #5019.

new package: v4l-utils

---

root-packages/keyutils/Makefile.patch
root-packages/keyutils/build.sh
root-packages/nfs-utils/build.sh
root-packages/nfs-utils/nfs-utils-2.5.2-no-werror.patch
root-packages/nfs-utils/strverscmp.c
root-packages/nfs-utils/support-export-export.c.patch
root-packages/nfs-utils/support-nfs-conffile.c.patch
root-packages/nfs-utils/support-nfs-rpcmisc.c.patch
root-packages/nfs-utils/support-nfs-svc_socket.c.patch
root-packages/nfs-utils/support-nfsidmap-libnfsidmap.c.patch
root-packages/nfs-utils/tools-nfsrahead-Makefile.am.patch
root-packages/nfs-utils/utils-mount-nfsumount.c.patch
root-packages/nfs-utils/versionsort.c

new package: nfs-utils

---

packages/golang/build.sh
packages/golang/fix-hardcoded-etc-resolv-conf.diff
scripts/build/setup/termux_setup_golang.sh

golang: Bump to 1.20

---

packages/websocat/build.sh

add(main): new package websocat

---

packages/v2ray/build.sh
packages/v2ray/upstream-upgrade-quic-go-to-0.32.0.patch

https://github.com/termux/termux-packages/actions/runs/4086737351
part of #14915 .

fix(main/v2ray): upgrade quic-go to 0.32.0

---

x11-packages/tigervnc/build.sh
x11-packages/xorg-server-xvfb/build.sh
x11-packages/xorg-server/build.sh

* tigervnc: Bump xserver to 21.1.7

xorg-server{,-xvfb}: Bump to 21.1.7

---

packages/libprotobuf/build.sh
packages/libprotobuf/protobuf-dev.subpackage.sh
packages/protobuf-static/build.sh
packages/protobuf-static/remove-android-logging.patch
scripts/build/setup/termux_setup_protobuf.sh

new package: protobuf-static

---

packages/poke/build.sh

poke: Fix build when libandroid-glob is installed

---

packages/python/build.sh

python: Recommend python-ensurepip-wheels

---

packages/ffmpeg/build.sh

for `libav{util,codec,format}`. Firefox expects that for `libavcodec`.

ffmpeg: Provide SOVERSION-suffixed shlib symlinks

---

root-packages/docker/build.sh
root-packages/docker/config.go.patch
root-packages/docker/generate-man.sh.patch
root-packages/docker/md2man-all.sh.patch

Major bump. I cannot test this by myself. Not for merge until a week later from now, unless tested and approved by others.

docker: Bump to 23.0.0

---

CODEOWNERS
packages/ldd/build.sh
packages/ldd/ldd.in
scripts/build/setup/termux_setup_gir.sh

* Include `libaaudio.so` in list of system libs
* Name myself as the maintainer
* CODEOWNERS: Assign some more GIR stuff to myself

ldd: Depend on binutils-bin

---

x11-packages/mtpaint/build.sh
x11-packages/mtpaint/fix-hardcoded-paths.patch

and correctly bump to 3.50.09.

mtpaint: Migrate to GTK+3

---

packages/libwslay/build.sh

new package: libwslay

---

packages/geth/build.sh
packages/geth/geth-utils.subpackage.sh

bump(main/geth): 1.11.0

---

packages/libffi/build.sh

libffi: Add SOVERSION guard

---

x11-packages/x11vnc/build.sh

x11vnc: Remove `bin/Xdummy`

---

packages/abseil-cpp/build.sh

new package: abseil-cpp

---

build-package.sh
packages/librav1e/build.sh
scripts/build/setup/termux_setup_cargo_c.sh
scripts/setup-offline-bundle.sh

* librav1e: Use `termux_setup_cargo_c`

scripts: Add `termux_setup_cargo_c`

---

packages/ghc-libs/always-use-pic-on-android-for-dynexec.patch
packages/ghc-libs/always_link_m.patch
packages/ghc-libs/build.sh
packages/ghc-libs/correct-host-triplet.patch
packages/ghc-libs/ghc.subpackage.sh
packages/ghc-libs/set-default-prefix.patch
packages/ghc-libs/undefined_symbols.patch
scripts/build/setup/termux_setup_cabal.sh
scripts/build/setup/termux_setup_ghc_cross_compiler.sh

haskell: update to 9.2.5

---

x11-packages/tigervnc/build.sh
x11-packages/xorg-server-xvfb/build.sh
x11-packages/xorg-server-xvfb/use_ashmem.patch
x11-packages/xorg-server/build.sh
x11-packages/xorg-server/use_ashmem.patch
x11-packages/xwayland/build.sh
x11-packages/xwayland/fix-required-libgl-version.patch
x11-packages/xwayland/use_ashmem.patch

Fixes https://github.com/termux/termux-packages/issues/15239

xorg-server, xorg-server-xvfb, xwayland: fix for using /dev/ashmem

---

packages/dufs/build.sh

new package: dufs

---

packages/gogs/build.sh

gogs: update to 0.13.0

---

packages/picolisp/build.sh
packages/picolisp/fix-bash-completion.patch

picolisp: add bash completion

---

packages/git-delta/build.sh

git-delta: Use system libgit2

---

x11-packages/firefox/build.sh
x11-packages/firefox/ffmpeg60.patch

firefox: Add support for FFmpeg 6.0

---

packages/mesa/build.sh
packages/mesa/fix-for-anon-file.patch
packages/mesa/fix-for-getprogname.patch
packages/mesa/mesa-vulkan-icd-swrast.subpackage.sh
packages/mesa/wsi-no-pthread_cancel.patch

mesa: enable swrast vulkan driver

---

packages/libx11/build.sh

libx11: Fix locale support

---

x11-packages/qb64/build.sh
x11-packages/qb64/no-no-pie.patch
x11-packages/qb64/setup_lnx.sh.patch

new package: qb64

---

x11-packages/scrot/build.sh
x11-packages/scrot/getsubopt.c
x11-packages/scrot/getsubopt.h
x11-packages/scrot/getsubopt.patch

scrot: Migrate to maintained fork

---

x11-packages/godot/build.sh
x11-packages/godot/crypto_core.cpp.patch
x11-packages/godot/crypto_mbedtls.cpp.patch
x11-packages/godot/detect.py.patch
x11-packages/godot/main.cpp.patch
x11-packages/godot/platform_utils.hpp.patch
x11-packages/godot/primitive_attr.cpp.patch
x11-packages/godot/remove-android-log.patch
x11-packages/godot/set_dir.patch
x11-packages/godot/set_handle_dlopen.patch
x11-packages/godot/thread.cpp.patch
x11-packages/godot/tls_context_mbedtls.h.patch
x11-packages/godot/upnp.cpp.patch
x11-packages/godot/upnp.h.patch
x11-packages/godot/upnp_device.cpp.patch

https://github.com/godotengine/godot/issues/73233

add(main): new package godot

---

packages/ol/build.sh

Purely functional [dialect](https://github.com/yuriy-chumak/ol) of Lisp.

new package: ol

---

packages/tinygo/Makefile.patch.beforehostbuild
packages/tinygo/build.sh
packages/tinygo/tinygo-common.subpackage.sh

new package: tinygo

---

x11-packages/ffplay/build.sh
x11-packages/ffplay/configure.patch

Not a subpackage of `ffmpeg` due to dependency on `sdl2` etc.

new package: ffplay

---

packages/bombadillo/build.sh

new package: bombadillo

---

packages/clidle/build.sh

new package: clidle

---

packages/ttyper/build.sh

new package: ttyper

---

packages/step-cli/build.sh

new package: step-cli

---

packages/grv/build.sh
packages/grv/git2go.v27.patch

new package: grv

---

packages/wtfutil/build.sh

new package: wtfutil

---

packages/ytui-music/build.sh
packages/ytui-music/front-end-src-ui-event.rs.patch

new package: ytui-music

---

packages/distant/build.sh
packages/distant/service-manager-0.2.0.diff
packages/distant/src-paths.rs.patch
packages/distant/termios-0.2.2.diff

new package: distant

---

packages/vulkan-tools/build.sh

bump(main/vulkan-tools): 1.3.243

---

x11-packages/abiword/build.sh
x11-packages/abiword/configure.ac.patch
x11-packages/abiword/gir/3.0.5/Abi-3.0.xml
x11-packages/abiword/plugin-configure.m4.patch
x11-packages/abiword/src-af-xap-xp-xap_Dialog.cpp.patch

* Fix underlinking against libgmodule
* Fix bashism in (patch for) configure
* Fix build failure

abiword: Fix underlinking (and others)

---

packages/sing-box/build.sh

https://github.com/termux/termux-packages/pull/15467#pullrequestreview-1325291047

fix(main/sing-box): add command completions

---

packages/coreutils/build.sh
packages/coreutils/src-copy.c.patch

coreutils: Fix FICLONE failure handling

---

packages/vulkan-tools/build.sh

bump(main/vulkan-tools): 1.3.245

---

packages/ndk-multilib/build.sh

ndk-multilib: Fix installation

---

x11-packages/qemu-system-x86-64/1001-find-gdbus-codegen.patch
x11-packages/qemu-system-x86-64/build.sh

qemu-system-x86-64: Enable virglrenderer

---

packages/redis/build.sh

redis: Add workaround for unaligned access on arm

---

packages/gawk/build.sh
packages/gawk/configure.patch

gawk: Fix `configure` for detecting readline

---

packages/libgcrypt/build.sh
packages/libgcrypt/libgcrypt-1.10.1-configure-clang16.patch

libgcrypt: Fix `configure` for detecting asm support

---

packages/libffi/build.sh
packages/libffi/libffi-3.4.4-open_temp_exec_file.patch

libffi: Fix build with strict C99

---

packages/m4/tests-strerror_r.c.patch

m4: Fix build with strict C99

---

packages/libgsf/configure.patch

libgsf: Fix `configure` for detecting libbz2

---

packages/gegl/build.sh
packages/gegl/bzero.patch

gegl: Fix build with strict C99

---

packages/python/build.sh
packages/python/disable-parallel-build.patch

python: Disable parallel build

---

packages/gettext/build.sh

gettext: Assume `tparm` to be available

---

packages/p11-kit/build.sh
packages/p11-kit/p11-kit-0.24.1-fix-configure-thread-local.patch

p11-kit: Fix `configure` for thread local

---

packages/zziplib/build.sh
packages/zziplib/zziplib-0.13.72-fix-int-conversion.patch

zziplib: Fix int conversion

---

packages/texlive-bin/utils-m-tx-mtx-src-prepmx.c.patch

texlive-bin: Fix implicit int

---

x11-packages/libcanberra/build.sh

declared in system `<malloc.h>`.

libcanberra: Fix implicit declaration of function

---

packages/emacs/build.sh
x11-packages/emacs-x/build.sh

emacs{,-x}: Assume `sigaltstack` to be available

---

packages/hfsutils/build.sh

hfsutils: Do `autoreconf`

---

packages/corkscrew/configure.patch

corkscrew: Fix build with strict C99

---

packages/librasqal/rasqal-0.9.33-configure-clang16.patch

librasqal: Fix `configure` for `__FUNCTION__`

---

packages/typst/build.sh

```bash
~ $ cat a.typ 
#set page(width: 10cm, height: auto)
#set heading(numbering: "1.")
= Fibonacci sequence
The Fibonacci sequence is defined through the
recurrence relation $F_n = F_(n-1) + F_(n-2)$.
It can also be expressed in _closed form:_
$ F_n = round(1 / sqrt(5) phi.alt^n), quad
phi.alt = (1 + sqrt(5)) / 2 $
#let count = 8
#let nums = range(1, count + 1)
#let fib(n) = (
if n <= 2 { 1 }
else { fib(n - 1) + fib(n - 2) }
)
The first #count numbers of the sequence are:
#align(center, table(
columns: count,
..nums.map(n => $F_#n$),
..nums.map(n => str(fib(n))),
))
~ $ typst -V
typst 0.1.0 (b3faef4b)
~ $ typst compile a.typ 
~ $ 
```
Close #15971 .

add(main): new package typst

---

packages/cmus/build.sh
packages/cmus/configure-clang16.patch

cmus: Fix `configure` for strict C99

---

x11-packages/telepathy-glib/build.sh
x11-packages/telepathy-glib/gir/0.24.2/TelepathyGLib-0.12.xml
x11-packages/telepathy-glib/telepathy-glib-protocol.c.patch

telepathy-glib: Fix incompatible function pointer types

---

packages/libncnn/build.sh

main/libncnn: fix conflicts

---

packages/bat/build.sh

bat: Fix build with strict C99

---

packages/gitui/build.sh

gitui: Fix build with strict C99

---

x11-packages/firefox/build.sh
x11-packages/firefox/fix-sigbus.patch

firefox: fix SIGBUS on Arm

---

x11-packages/fvwm/build.sh
x11-packages/fvwm/fvwm-2.7.0-clang16-0001.patch
x11-packages/fvwm/fvwm-2.7.0-clang16-0002.patch

fvwm: Fix `configure` for strict C99

---

packages/python-torchaudio/0001-do-not-try-to-import-torch-when-cross-compiling.patch
packages/python-torchaudio/0002-fix-cross-compiling.patch
packages/python-torchaudio/0003-fix-patch-for-sox.patch
packages/python-torchaudio/0004-fix-patch-for-vorbis.patch
packages/python-torchaudio/build.sh

new package: python-torchaudio

---

packages/openjdk-17/build.sh
packages/openjdk-17/strerror_r.patch

openjdk-17: Fix for `strerror_r`

---

packages/screen/build.sh
packages/screen/screen-4.9.0-configure-implicit-function-decls.patch

screen: Fix `configure` for strict C99

---

packages/ncftp/build.sh
packages/ncftp/ncftp-3.2.6-configure-clang16.patch

ncftp: Fix configure for strict C99

---

packages/tsocks/build.sh
packages/tsocks/configure-clang16.patch

tsocks: Fix implicit int in `configure`

---

packages/links/build.sh
packages/links/configure-clang16.patch

links: Fix `configure` for strict C99

---

packages/lynx/build.sh
packages/lynx/configure-clang16.patch

lynx: Fix `configure` for strict C99

---

packages/gopher/build.sh
packages/gopher/configure-clang16.patch

gopher: Fix implicit int in `configure`

---

packages/nginx/auto-unix.patch
packages/nginx/build.sh

nginx: Fix `configure` for detecting `crypt()`

---

packages/openldap/build.sh
packages/openldap/openldap-2.6.4-configure-clang16.patch

openldap: Fix `configure` for strict C99

---

x11-packages/audacity/build.sh
x11-packages/audacity/lib-src-libnyquist-nyquist-xlisp-security.c.patch

audacity: Fix missing `getcwd` declaration

---

packages/tizonia/build.sh
packages/tizonia/libtizcore-src-tizcore.c.patch
packages/tizonia/plugins-chromecast_renderer-src-cc_prc.c.patch

tizonia: Fix missing `bzero` declaration

---

x11-packages/mogan/build.sh
x11-packages/mogan/src-Scheme-S7-s7.c.patch

mogan: Fix missing declaration of `clog` and `cpow`

---

packages/android-tools/build.sh
packages/android-tools/vendor_CMakeLists.fastboot.txt.patch

android-tools: Fix for `reallocarray`

---

packages/lowdown/build.sh
packages/lowdown/compats.c.patch

lowdown: Fix incompatible function pointer types

---

packages/speechd/build.sh
packages/speechd/pthread_cancel.patch

speechd: Fix missing `memset` declaration

---

packages/libwv/build.sh
packages/libwv/wvConfig.c.patch
packages/libwv/wvSummary.c.patch
packages/libwv/wvparse.c.patch

libwv: Fix build for Clang 16

---

x11-packages/freeglut/build.sh
x11-packages/freeglut/src-x11-fg_main_x11.c.patch

freeglut: Fix missing `clock_gettime` declaration

---

x11-packages/gtk2-engines-murrine/build.sh
x11-packages/gtk2-engines-murrine/gtk2-engines-murrine-0.98.2-implicit-functions.patch

gtk2-engines-murrine: Fix implicit function declaration

---

packages/arj/build.sh
packages/arj/waitpid-decl.patch

arj: Fix missing `waitpid` declaration

---

packages/cpulimit/build.sh

cpulimit: Fix for `basename`

---

packages/gcal/build.sh
packages/gcal/gcal-4.1-configure-clang16.patch
packages/gcal/lib-strerror_r.c.patch

gcal: Fix `configure` and build for Clang 16

---

packages/frogcomposband/build.sh
packages/frogcomposband/h-system.h.patch

frogcomposband: Fix implicit function declaration

---

packages/vorbis-tools/build.sh
packages/vorbis-tools/vorbis-tools-1.4.2-clang16.patch

vorbis-tools: Fix build with strict C99

---

packages/vitetris/build.sh
packages/vitetris/src-menu-netplay.c.patch

vitetris: Fix implicit int

---

packages/recutils/build.sh
packages/recutils/rec-sex-parser.c.patch
packages/recutils/rec-sex-tab.c.patch

recutils: Fix implicit function declaration

---

packages/timidity++/build.sh
packages/timidity++/timidity++-2.15.0-clang-16-configure.patch

timidity++: Fix `configure` and build for Clang 16

---

packages/inetutils/build.sh
packages/inetutils/telnet-sys_bsd.c.patch

inetutils: Fix implicit function declaration

---

packages/cvs/build.sh
packages/cvs/src-login.c.patch

cvs: Fix implicit function declaration

---

packages/dictd/build.sh
packages/dictd/dictd-1.13.0-lex.patch

dictd: Fix implicit function declaration

---

packages/gatling/build.sh
packages/gatling/http.c.patch

gatling: Fix missing `crypt` declaration

---

packages/libisoburn/build.sh
packages/libisoburn/xorriso-parse_exec.c.patch

libisoburn: Fix for `wait3`

---

packages/shellinabox/build.sh
packages/shellinabox/shellinabox_launcher.c.patch

shellinabox: Fix missing `login_tty` declaration

---

packages/html-xml-utils/build.sh

html-xml-utils: Fix implicit function declaration

---

packages/tinyfugue/build.sh
packages/tinyfugue/src-tfio.h.patch

tinyfugue: Fix implicit function declaration

---

packages/xmlstarlet/build.sh
packages/xmlstarlet/src-xml_elem.c.patch

xmlstarlet: Fix incompatible function pointer types

---

packages/torsocks/05_deadlock_in_initializer.patch
packages/torsocks/build.sh
packages/torsocks/torsocks-2.4.0-clang16.patch

torsocks: Fix implicit function declaration

---

packages/softether-vpn/build.sh
packages/softether-vpn/src-Mayaqua-Unix.c.orig.patch

softether-vpn: Fix incompatible function pointer types

---

packages/alpine/alpine-imap.c.patch
packages/alpine/build.sh
packages/alpine/configure.ac.patch
packages/alpine/os_lnx.c.patch
packages/alpine/os_lnx.h.patch

alpine: Fix implicit function declaration

---

packages/finch/build.sh
packages/finch/sasl_callback-proc.patch
x11-packages/pidgin/build.sh
x11-packages/pidgin/sasl_callback-proc.patch

finch, pidgin: Fix incompatible function pointer types

---

packages/expect/build.sh
packages/expect/expect-5.45-headers.patch
packages/expect/expect-5.45.4-configure-clang16.patch

expect: Fix `configure` and build for Clang 16

---

x11-packages/mate-settings-daemon/build.sh
x11-packages/mate-settings-daemon/plugins-a11y-keyboard-msd-a11y-keyboard-atspi.c.patch

mate-settings-daemon: Fix incompatible function pointer types

---

x11-packages/obconf/build.sh
x11-packages/obconf/obconf-2.0.4-clang16.patch

obconf: Fix implicit function declaration

---

packages/samba/build.sh
packages/samba/getgrouplist.patch
packages/samba/samba-4.16.10-configure-clang16.patch

samba: Fix build with strict C99

---

x11-packages/motif/build.sh
x11-packages/motif/clients-mwm-WmError.h.patch
x11-packages/motif/lib-Xm-Xpmcreate.c.patch
x11-packages/motif/lib-Xm-Xpmparse.c.patch
x11-packages/motif/tools-wml-wmlparse.y.patch

motif: Fix build for Clang 16

---

packages/mplayer/build.sh
packages/mplayer/libmpcodecs-put_image.patch
packages/mplayer/libmpcodecs-ve_lavc.c.patch

mplayer: Fix incompatible function pointer types

---

packages/libandroid-complex-math/build.sh
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cacoshl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/cacosl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/casinhl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/casinl.c
packages/libandroid-complex-math/upstream-netbsd/lib/libm/complex/catanhl.c

libandroid-complex-math: Fix implicit function declaration

---

packages/freeimage/Source-LibJXR-image-decode-segdec.c.patch
packages/freeimage/Source-LibJXR-jxrgluelib-JXRGlueJxr.c.patch
packages/freeimage/Source-ZLib-gzguts.h.patch
packages/freeimage/build.sh

freeimage: Fix implicit function declaration

---

packages/zile/build.sh
packages/zile/zile-2.6.2-incompatible-function-pointer-types.patch

zile: Fix incompatible function pointer types

---

x11-packages/loqui/build.sh
x11-packages/loqui/loqui-0.7.0-clang16.patch

loqui: Fix build for Clang 16

---

root-packages/bindfs/getpwent.patch

bindfs: Fix build for Clang 16

---

root-packages/nfs-utils/build.sh

nfs-utils: Fix missing `unshare` declaration

---

root-packages/v4l-utils/no-posix-shm.patch

v4l-utils: Fix build for Clang 16

---

root-packages/hwinfo/src-hd-mdt.c.patch
root-packages/hwinfo/src-hd-sys.c.patch
root-packages/hwinfo/src-hd-wlan.c.patch
root-packages/hwinfo/src-isdn-isa-probe.c.patch

hwinfo: Fix build for Clang 16

---

packages/perl/build.sh
packages/perl/cnf-clang16.patch

perl: Fix `configure` for Clang 16

---

packages/ravencoin/src-algo-sha2.c.patch

ravencoin: Fix implicit function declaration

---

scripts/build/termux_get_repo_files.sh

see https://github.com/termux/termux-packages/issues/16222#issuecomment-1510382933

build system: retry repo/Release.gpg

---

packages/emscripten/build.sh

emscripten: Fix `DT_RUNPATH` in emscripten-binaryen

---

x11-packages/tigervnc/build.sh
x11-packages/tigervnc/tigervnc-1.10.1-boolparam-0.patch
x11-packages/tigervnc/vncserver

tigervnc: Backport fix for `-BoolParam 0`

---

packages/librime/build.sh

enhance(main/librime): add configuration files

---

build-package.sh
scripts/setup-termux.sh

Improve script interaction with pacman

---

packages/dua/build.sh

new package: dua

---

packages/smalltalk/Makefile.am.patch
packages/smalltalk/build.sh
packages/smalltalk/expat.c.patch
packages/smalltalk/isinfl.patch
packages/smalltalk/no_hardlink.patch

smalltalk: Fix build

---

packages/perl/build.sh
packages/perl/no-sudo.patch

perl: Do not use sudo in cpan

---

packages/silicon/build.sh

https://t.me/termux24x7/1/82279
Looks like upstream fixed builds on arm devices.

enhance(main/silicon): enable arm support

---

packages/redis/build.sh
packages/redis/redis-7.0.11-alignment.patch

redis: Backport alignment fix

---

packages/debianutils/Makefile.in.patch
packages/debianutils/build.sh
packages/which/build.sh
x11-packages/xdg-utils/build.sh

* debianutils: Remove `bin/which`
Closes #15863

new package: which

---

x11-packages/mesa-demos/build.sh
x11-packages/mesa-demos/eglinfo-system.subpackage.sh

after commit 46c5cd3d7458adb980919a7ab4e75f6cec05af2f.

mesa-demos: Fix `eglinfo-system`

---

packages/python-greenlet/build.sh
packages/python-greenlet/setup.py.patch

Reference: #15911 
Reference: #16598

new package: python-greenlet

---

packages/cfengine/build.sh

cfengine: Bump to 3.21.1

---

packages/chafa/build.sh

https://github.com/hpjansson/chafa/releases/tag/1.12.5

Chafa: Upgrade to 1.12.5

---

packages/geth/build.sh
packages/geth/geth-utils.subpackage.sh

Fixes https://github.com/termux/termux-packages/issues/16764

bump(main/geth): 1.12.0

---

packages/wakatime-cli/build.sh

add(main): new package wakatime-cli

---

packages/rbw/build.sh

add(main): new package rbw

---

packages/agate/build.sh

add(main): new package agate

---

packages/vulkan-tools/build.sh

bump(main/vulkan-tools): 1.3.251

---

packages/git-delta/build.sh

upgpkg(main/git-delta): 0.16.5

---

packages/algernon/build.sh
packages/algernon/fix-hardcoded-paths.patch

upgpkg(main/algernon): 1.15.2

---

packages/iwyu/build.sh

hopefully this fixes the assertion errors i'm getting

iwyu: revbump

---

packages/pacman/build.sh
packages/pacman/pacman.conf.in.patch

pacman: moving service references to a separate file

---

packages/ruff/build.sh

upgpkg(main/ruff): 0.0.271

---

packages/python/build.sh
packages/python/no-xattr.patch

python: Do not use xattr

---

packages/php/build.sh

php: Bump to 8.2.7

---

packages/emscripten/build.sh
packages/emscripten/fix-rpath.py
packages/emscripten/tests.sh

fix(main/emscripten): various fixes

---

packages/fclones/build.sh

fclones: bump to 0.32.1

---

packages/imath/build.sh
packages/openexr/build.sh

openexr: Bump to 3.1.8

---

packages/vulkan-extension-layer/build.sh
packages/vulkan-tools/build.sh

bump(main/vulkan-tools): 1.3.254

---

scripts/updates/utils/termux_pkg_upgrade_version.sh

auto-update: clean before each successive build

---

packages/python-numpy/build.sh

python-numpy: bump to 1.25.0

---

packages/libarrow-cpp/build.sh
packages/libgrpc/build.sh
packages/libre2/build.sh

Do not merge until https://github.com/termux/termux-packages/issues/17012#issuecomment-1595763536 is resolved.

libre2: Bump to 2023.06.02

---

packages/json-c/build.sh

json-c: Disable `-Werror`

---

packages/lua-language-server/bee.lua-bee-net-endpoint.patch

lua-language-server: fix build on 32-bit arches

---

packages/sccache/build.sh

add(main): new package sccache

---

packages/uftrace/build.sh
packages/uftrace/cmds-live.c.patch
packages/uftrace/cmds-record.c.patch
packages/uftrace/configure_out_of_source.patch
packages/uftrace/utils-shmem.c.patch

uftrace: bump to 0.14
